### PR TITLE
[RayCluster controller] [Bug] Unconditionally reconcile RayCluster every 60s instead of only upon change

### LINKED ISSUE #845: [Bug] Sample `RayJob` YAML from documentation hangs at "Initializing"
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

After starting a KinD cluster:

```
kind create cluster
```

Starting the KubeRay operator with Helm:

```
helm install kuberay-operator kuberay/kuberay-operator --version 0.4.0
```

Starting a RayJob according to the docs at https://ray-project.github.io/kuberay/guidance/rayjob/:

```
kubectl apply -f https://raw.githubusercontent.com/ray-project/kuberay/master/ray-operator/config/samples/ray_v1alpha1_rayjob.yaml
```

The Ray cluster successfully starts (get the pod name from `kubectl get pod`):
```bash
kubectl logs rayjob-sample-raycluster-cdhg7-worker-small-group-swxs4
```
```
2022-12-20 16:01:56,939	INFO scripts.py:877 -- Local node IP: 10.244.0.9
2022-12-20 16:01:59,326	SUCC scripts.py:889 -- --------------------
2022-12-20 16:01:59,326	SUCC scripts.py:890 -- Ray runtime started.
2022-12-20 16:01:59,326	SUCC scripts.py:891 -- --------------------
2022-12-20 16:01:59,326	INFO scripts.py:893 -- To terminate the Ray runtime, run
2022-12-20 16:01:59,327	INFO scripts.py:894 --   ray stop
2022-12-20 16:01:59,327	INFO scripts.py:899 -- --block
2022-12-20 16:01:59,327	INFO scripts.py:901 -- This command will now block forever until terminated by a signal.
2022-12-20 16:01:59,327	INFO scripts.py:904 -- Running subprocesses are monitored and a message will be printed if any of them terminate unexpectedly. Subprocesses exit with SIGTERM will be treated as graceful, thus NOT reported.
 ```
 But the Job is stuck in Initializing:
 
 ```
 kubectl describe rayjobs rayjob-sample
 ```
 
 ```
 [...]
 Status:
  Dashboard URL:          rayjob-sample-raycluster-cdhg7-head-svc.default.svc.cluster.local:8265
  Job Deployment Status:  Initializing
  Job Id:                 rayjob-sample-fbtxd
  Ray Cluster Name:       rayjob-sample-raycluster-cdhg7
  Ray Cluster Status:
    Head:
Events:
  Type    Reason   Age   From               Message
  ----    ------   ----  ----               -------
  Normal  Created  11m   rayjob-controller  Created cluster rayjob-sample-raycluster-cdhg7
  ```
 

### Reproduction script

See above

### Anything else

It's not clear yet if this is a problem with the sample YAML or a deeper issue.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by architkulkarni**
Signed-off-by: Archit Kulkarni <architkulkarni@users.noreply.github.com>

## Why are these changes needed?
This PR fixes an issue where RayJobs would never be submitted even if the Ray Cluster was up and running. Debugged this with @brucez-anyscale .

The root cause is the following:

The cluster status is only marked "Ready" if all pods are RUNNING.  The cluster state only gets updated when a reconcile happens.

However, the Cluster reconcile doesn't get requeued if all the pods are in [RUNNING, PENDING] state. 

In particular, when the head pod becomes PENDING, the cluster never gets reconciled again. 

So the cluster is stuck in a state where it's status is not "Ready". Since the RayJob reconciler waits for the cluster status to be "Ready" before submission, the job hangs and is never submitted.

The fix in this PR is to ~requeue the cluster reconcile in the case where the cluster pods are not all running yet. This PR introduces a new cluster state "Pending" for this case.~ always requeue the cluster reconciliation (every 300s, for now.)

As for why the head node state change PENDING -> RUNNING didn't trigger a cluster reconcile before, we think it might be due to an event filter https://github.com/ray-project/kuberay/blob/633ff6375099b2737db4c74a51c31028d2e54bc3/ray-operator/controllers/ray/raycluster_controller.go#L803
which only does the reconcile when there's a config, label or annotation change. However we can't remove this filter because it's necessary to prevent reconciling in a tight loop, because `instance.Status.LastUpdateTime` is updated at each reconcile.

Conclusion after discussion on this PR: Fixing the event filters is a separate but related bug and will be addressed in a followup PR, the issue will be tracked here: https://github.com/ray-project/kuberay/issues/872. Once that is fixed, we could possibly consider a patch 0.4.1 release.  After this PR, there may be an up to 60s unnecessary delay between when the cluster is ready and when the Job is submitted, which is not ideal.

## Related issue number
Closes #845 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests

```
      # This script is used to rebuild the KubeRay operator image and load it into the Kind cluster. 
# Step 0: Delete the existing Kind cluster
kind delete cluster 

# Step 1: Create a Kind cluster
kind create cluster --image=kindest/node:v1.24.0

# Step 2: Modify KubeRay source code
# For example, add a log "Hello KubeRay" in the function `Reconcile` in `raycluster_controller.go`.

# Step 3: Build a Docker image
#         This command will copy the source code directory into the image, and build it.
# Command: IMG={IMG_REPO}:{IMG_TAG} make docker-build
IMG=kuberay/operator:nightly make docker-build

# Step 4: Load the custom KubeRay image into the Kind cluster.
# Command: kind load docker-image {IMG_REPO}:{IMG_TAG}
kind load docker-image kuberay/operator:nightly

# Step 5: Keep consistency
# If you update RBAC or CRD, you need to synchronize them.
# See the section "Consistency check" for more information.

# Step 6: Install KubeRay operator with the custom image via local Helm chart
# (Path: helm-chart/kuberay-operator)
# Command: helm install kuberay-operator --set image.repository={IMG_REPO} --set image.tag={IMG_TAG} .
helm install kuberay-operator --set image.repository=kuberay/operator --set image.tag=nightly ~/kuberay/helm-chart/kuberay-operator

# Step 7: Submit a RayJob
kubectl apply -f config/samples/ray_v1alpha1_rayjob.yaml   

# Step 8: Check the status of the pods
watch kubectl get pods

# When the pods are ready, check `kubectl logs` to see that the job has status SUCCEEDED
```
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by architkulkarni** [comment]
Would appreciate any hints on how to add a unit test for this, or whether this is the right approach!

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -233,6 +233,9 @@ func (r *RayClusterReconciler) rayClusterReconcile(request ctrl.Request, instanc
 			r.Log.Error(err, "Update status error", "cluster name", request.Name)
 		}
 	}
+	if instance.Status.State == rayiov1alpha1.Pending {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller.go:236]: In my understanding, the string member (i.e. `instance.Status.State`) in a struct (i.e. `instance`) will be deep copied by default [1]. Hence, `instance.Status.State = rayiov1alpha1.Pending` in the function `updateStatus` will not take effect here. That is, currently, this condition (`instance.Status.State == rayiov1alpha1.Pending`) will be fulfilled in the next reconciliation rather than this reconciliation if `r.Status().Update(...)` succeeds. On the other hand, if `r.Status().Update(...)` in the function `updateStatus` fails, it seems that the event will not be requeued again.

I did not run the code manually, so correct me if I miss any details. Thanks!

[1] https://echorand.me/posts/go-values-references-etc/#elements-in-maps-and-struct-types

**Comment by kevin85421** [comment]
> Would appreciate any hints on how to add a unit test for this, or whether this is the right approach!

Maybe we can refer to the existing tests in [1][2] and write tests to ensure `instance.Status.State` update correctly.  

[1] https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/raycluster_controller_fake_test.go
[2] https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/raycluster_controller_test.go

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go:236]: Good catch, I will double check this. It's possible my manual test passed because the reconciliation was called twice for unrelated reasons, which would have hidden this bug.

Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go:236]: Hi @kevin85421, in this case, `instance` is being passed as a pointer in `updateStatus`, so I think it's okay.  The blog post seems to agree with this.  What do you think?

Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go:236]: @kevin85421 Here `instance` is being passed to `updateStatus` as a pointer, so I think it should be okay. Is my understanding correct?

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 2]
```diff
@@ -233,6 +233,9 @@ func (r *RayClusterReconciler) rayClusterReconcile(request ctrl.Request, instanc
...
+		return ctrl.Result{RequeueAfter: DefaultRequeueDuration}, nil
+	}
 
 	return ctrl.Result{}, nil
```
Comment (DmitriGekhtman) [inline ray-operator/controllers/ray/raycluster_controller.go:240]: We should always requeue. I didn't realize we didn't do that. That's very bad. Reconciliation for any controller should happen periodically even if there's isn't a trigger that demands it.

The correct fix for this issue is to change the "successful return" from 
```
return ctrl.Result{}, nil
```
to 
```
return ctrl.Result{RequeueAfter: DefaultRequeueDuration}, nil
```

Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go:240]: Oh thanks, that's very good to know. Let me update the PR

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 3]
```diff
@@ -858,6 +861,8 @@ func (r *RayClusterReconciler) updateStatus(instance *rayiov1alpha1.RayCluster)
 	} else {
 		if utils.CheckAllPodsRunnning(runtimePods) {
 			instance.Status.State = rayiov1alpha1.Ready
+		} else {
+			instance.Status.State = rayiov1alpha1.Pending
```
Comment (DmitriGekhtman) [inline ray-operator/controllers/ray/raycluster_controller.go:865]: It's normal for a Ray cluster to gain pods that are in Pending state, particularly if autoscaling is enabled. With this change, the cluster could switch back and forth between Running and Pending. That seems undesirable. (The current reporting of state is not great either.)

**Review by DmitriGekhtman — CHANGES_REQUESTED** [review]
I'd leave the state reporting alone for now (maybe track the issue of making it more sensible).

We should change things so that we always requeue, i.e. do
`return ctrl.Result{RequeueAfter: DefaultRequeueDuration}, nil`

**Comment by DmitriGekhtman** [comment]
> As for why the head node state change PENDING -> RUNNING didn't trigger a cluster reconcile before, we think it might be due to an event filter

I am fuzzy on how these filters work, but the way things should work is that 
a RayCluster.status change doesn't trigger a reconcile
but
a Pod.status change does trigger a reconcile for a pod in the cluster.

Currently, it might be that neither event triggers a reconcile.

**Comment by architkulkarni** [comment]
@DmitriGekhtman Updated to always requeue the RayCluster reconciler.  After this, it seems the RayJob reconciler also gets called every few seconds even after the job has succeeded. I'm not exactly sure what is causing the RayJob reconciler to get requeued, but it sounds like this is what we want anyway.

There's ~10 other instances of `ctrl.Result{}, nil` in the codebase but I'll leave those alone for now.

**Comment by DmitriGekhtman** [comment]
> I'm not exactly sure what is causing the RayJob reconciler to get requeued, but it sounds like this is what we want anyway.

Probably the RayCluster status update is causing that.

**Comment by DmitriGekhtman** [comment]
We could say testing for the fix falls under the umbrella of e2e testing for Ray Jobs which is tracked in https://github.com/ray-project/kuberay/issues/763.

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
I guess by default it triggers once every 10 hrs
https://stackoverflow.com/questions/72033429/how-often-is-reconciliation-loop-run-in-kubebuilder
which seems to me way too long for any use-case.

I'm not sure if once every 2 seconds is too frequent to requeue by default, but I think this should work fine for now.

In a follow-up, we should fix the event filters to ensure that pod changes trigger immediate reconciliation.

**Comment by Jeffwan** [comment]
one thing I like to confirm is 

> In particular, when the head pod becomes PENDING, the cluster never gets reconciled again.

in this case, is it meaningful to submit the job? 


if head is running and partical workers are pending. I think move forward job submission makes sense.  We also need to be careful that we have to honor gang setting as well

**Comment by Jeffwan** [comment]
the latest change actually will reconcile an object which reaches the end state and it's meaningless. I would say it brings side effect especially when there're lots of CRs in the cluster. I think there're better ways to solve the problem?

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 2 above)
Comment (brucez-anyscale) [reply ray-operator/controllers/ray/raycluster_controller.go]: This is a good point.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go]: I missed that it is passed as a pointer. So, this `if` condition will be fulfilled in the same reconciliation no matter `r.Status().Update(...)` succeeds or not. Thank you for pointing this out!

**Comment by DmitriGekhtman** [comment]
> the latest change actually will reconcile an object which reaches the end state and it's meaningless. I would say it brings side effect especially when there're lots of CRs in the cluster. I think there're better ways to solve the problem(make the changes specific to job instead of clusters globally)? 

I think we messed up the event filters in a previous PR -- we should fix the filters so that changes to RayCluster status are ignored but changes to status of other watched resources are not ignored.

About periodically re-triggering reconciliation --
There isn't an end-state for a Ray cluster. There is a goal state.
If you don't periodically trigger reconciliation, state can get desynchronized due to
missed events (unlikely)
or
bugs in the operator code (more likely).
For that reason, it's a standard behavior of controllers to occasionally reconcile without an event trigger. By default controllers written using kubebuilder will do this once every 10 hours, which seems too infrequent to me for our needs. Once every two seconds is probably too frequent. We can consider using something in between, maybe in a different PR.

**Review by kevin85421 — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
So, again, given the above discussion -- my current opinion is that we should try to solve the issue by fixing the event filter so that pod status changes trigger reconcile.

Separately, we can consider if we want to always requeue after 30 seconds or a minute.

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 4]
```diff
@@ -234,7 +234,7 @@ func (r *RayClusterReconciler) rayClusterReconcile(request ctrl.Request, instanc
 		}
 	}
 
-	return ctrl.Result{}, nil
+	return ctrl.Result{RequeueAfter: DefaultRequeueDuration}, nil
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller.go:237]: What will happen in the following example?

(1) **t = 0**: `ctrl.Result{RequeueAfter: DefaultRequeueDuration}`
(2) **t = DefaultRequeueDuration / 2**: Delete RayCluster CR.
(3) **t = DefaultRequeueDuration**: Will the Pods be created again?

**Comment by kevin85421** [comment]
> Reconcile on pod status change but not RayCluster status change

Hi @DmitriGekhtman, I am not sure whether the Pod status change is enough or not. For example, if a ClusterIP service for a head Pod is deleted accidently and the head Pod's status does not change, the service may not be created again.

**Comment by DmitriGekhtman** [comment]
> > Reconcile on pod status change but not RayCluster status change
> 
> Hi @DmitriGekhtman, I am not sure whether the Pod status change is enough or not. For example, if a ClusterIP service for a head Pod is deleted accidently and the head Pod's status does not change, the service may not be created again.

Yes, right. I'm saying **do not filter our pod status changes** (it seems we currently do).

**Comment by architkulkarni** [comment]
Created https://github.com/ray-project/kuberay/issues/872 to track the filter issue.

Once this PR is merged I will open an issue to track increasing 2 seconds to 30 or 60 seconds.  We should do it after https://github.com/ray-project/kuberay/issues/872 is fixed, otherwise it will introduce a 30 or 60 second delay at the start of each RayJob.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 4 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go:237]: @kevin85421 what's the desired behavior here? Is it something that should be addressed by this PR?

**Comment by architkulkarni** [comment]
> > Reconcile on pod status change but not RayCluster status change
> 
> Hi @DmitriGekhtman, I am not sure whether the Pod status change is enough or not. For example, if a ClusterIP service for a head Pod is deleted accidently and the head Pod's status does not change, the service may not be created again.

I guess with the 2 or 30-60 second automatic reconcile, the service would be created again--does this resolve the concern? So we would have both this automatic reconciling as well as the reconciling upon Pod status change.

**Comment by DmitriGekhtman** [comment]
> > > Reconcile on pod status change but not RayCluster status change
> 
> > 
> 
> > Hi @DmitriGekhtman, I am not sure whether the Pod status change is enough or not. For example, if a ClusterIP service for a head Pod is deleted accidently and the head Pod's status does not change, the service may not be created again.
> 
> 
> 
> I guess with the 2 or 30-60 second automatic reconcile, the service would be created again--does this resolve the concern? So we would have both this automatic reconciling as well as the reconciling upon Pod status change.

Right, I'd recommend both fixing the pod status trigger and requeueing after a minute after successful reconcile.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 4 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:237]: The expected behavior is all related Kubernetes resources (e.g. Ray head Pod, Ray worker Pods, Ray head service, ... etc) should be removed and not be created again.

**Review by DmitriGekhtman — CHANGES_REQUESTED** [review]
Sry, "Requesting changes" again to indicate my intent -- @Jeffwan had a good point that unconditionally triggering reconcile every two seconds is overkill.

Instead we should
- Unconditionally trigger reconcile once a minute. (Modify the 2 seconds in the currently altered line to 60 seconds.)
- Make sure pod status changes trigger reconcile, by fixing the event filter.

Once this is fixed, we could possibly consider a patch 0.4.1 release to fix Ray Jobs.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 4 above)
Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:237]: > (2) **t = DefaultRequeueDuration / 2**: Delete RayCluster CR.
> (3) **t = DefaultRequeueDuration**: Will the Pods be created again?

I doubt this will happen (if it did we would have seen it by now).
I imagine we have a clause somewhere that skips reconciliation if the CR is marked for deletion?

Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:237]: We should probably take a closer look at the internal KubeBuilder and controller-runtime.

Comment (brucez-anyscale) [reply ray-operator/controllers/ray/raycluster_controller.go:237]: So in the controller, we need to first check if the CR exists, if (2) deletes the CR, then (3) knows the CR is deleted and then does not create pods again.

Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:237]: I'd be surprised if this check is not already there somewhere.
We also need to check if `metadata.deletionTimestamp` is set on the CR and skip reconcile if it is (but again I'd be surprised if we don't do that already)

Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go]: I found a check here that skips reconcile if the deletion timestamp is set: https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/raycluster_controller.go#L175-L178

I'm not sure where to look for the other check (the check if the CR exists), but I will manually test the scenario where the RayCluster CR is deleted.

Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go]: Verified manually by waiting for a RayJob to finish, then running `kubectl delete raycluster rayjob-sample-raycluster-d7k5v` and watching `kubectl get pods`. The pods get removed and no new pods get started, which is what we wanted.

**Comment by architkulkarni** [comment]
Manually tested so @DmitriGekhtman I think this is ready to be merged.  I think it makes sense to fix the filter issue https://github.com/ray-project/kuberay/issues/872 in a second PR instead of this PR because they're conceptually separate changes, but I don't feel strongly either way.

**Comment by DmitriGekhtman** [comment]
> Manually tested so @DmitriGekhtman I think this is ready to be merged. I think it makes sense to fix the filter issue #872 in a second PR instead of this PR because they're conceptually separate changes, but I don't feel strongly either way.

Makes sense to leave filter fix for later. For posterity, could you update the PR title and description to explain the changes?

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 4 above)
Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go]: Suuper, thanks!

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 3 above)
Comment (gvspraveen) [reply ray-operator/controllers/ray/raycluster_controller.go]: @DmitriGekhtman 
How do we differentiate between Pods are that are Pending due to autoscaler vs Pods being Pending during initial cluster setup?

Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go]: By the following funky logic:
The only cluster `State` transition in the current logic is `""` -> `Ready`.
If, after the initial cluster setup, we have a `Pending` pod due to scale change or failure, the `State` will not return to `""`.

**Comment by architkulkarni** [comment]
@DmitriGekhtman Ah thanks for the reminder--should be good to go now.

**Comment by akanso** [comment]
> 

For customers that are using KubeRay and managing 100's or thousands of clusters, a 60 reconciliation loop would have a big impact on the operator itself, and on the traffic to the k8s Api-server.

I think this should be a configurable attribute, we can default it to 5 minutes, for example we can pass an Env var to the operator that can specify a different frequency instead of hardcoding it.

**Comment by architkulkarni** [comment]
@akanso That makes sense to me, so something like this?  (cc @DmitriGekhtman)

```go
var requeueAfterSeconds int
requeueAfterSeconds, err := strconv.Atoi(os.Getenv("RAYCLUSTER_DEFAULT_RECONCILE_LOOP_S"))
if err != nil {
    requeueAfterSeconds = 5 * 60
}
return ctrl.Result{RequeueAfter: time.Duration(requeueAfterSeconds) * time.Second}, nil
```

And how would an environment variable typically be passed to the operator?

**Comment by akanso** [comment]
> @akanso That makes sense to me, so something like this? (cc @DmitriGekhtman)
> 
> ```go
> var requeueAfterSeconds int
> requeueAfterSeconds, err := strconv.Atoi(os.Getenv("RAYCLUSTER_DEFAULT_RECONCILE_LOOP_S"))
> if err != nil {
>     requeueAfterSeconds = 5 * 60
> }
> return ctrl.Result{RequeueAfter: time.Duration(requeueAfterSeconds) * time.Second}, nil
> ```
> 
> And how would an environment variable typically be passed to the operator?

We can simply pass it in the k8s Yaml manifest of the operator pod. if it is missing we default to 5 minutes.
we would want to the code snippet a log message as well.

**Comment by DmitriGekhtman** [comment]
5 minutes sounds good 
(anything on the order of "eventually" is fine, 10 hrs is no good)

**Comment by DmitriGekhtman** [comment]
> For customers that are using KubeRay and managing 100's or thousands of clusters, a 60 reconciliation loop would have a big impact on the operator itself, and on the traffic to the k8s Api-server.

Doesn't reconcile trigger on any pod spec change, though?

**Comment by architkulkarni** [comment]
Successfully tested manually with the latest change.

**Comment by akanso** [comment]
> Doesn't reconcile trigger on any pod spec change, though?

it does. But imaging kuberay is down or restarting, then it will an event, such such the creation/modification/deletion of a new raycluster, this reconcile logic will make sure missed event are processed. The events already processed will be ignored since the desired state is already satisfied.

**Comment by DmitriGekhtman** [comment]
I meant that the logic for 5 min vs. 1 min for performance reasons in a large cluster might not make sense, given that a large cluster has many pod changes happening -- these pod changes trigger many reconciles anyway.
(But 5 min sgtm.)

**Comment by architkulkarni** [comment]
@DmitriGekhtman "Go-build-and-test / Compatibility Test - Nightly (pull_request)" is failing, but I think this is known to be flaky.  Maybe we can bypass the test and merge this PR anyway?

**Review by DmitriGekhtman — APPROVED** [review]

**Comment by DmitriGekhtman** [comment]
Failing test is known to be flakey.
