### PR TITLE
[Bug] RayService restarts repeatedly with Autoscaler 

### LINKED ISSUE #1030: [Bug] RayService restarts repeatedly with Autoscaler
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

## Case 1 (bug): Trigger Autoscaler scale-up when the RayCluster is pending.

* Gist: [RayService YAML file](https://gist.github.com/kevin85421/0de4627d4eef6f62b23ec72ad68621a5)
* Reproduction script:
  ```sh
  helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0
  kubectl apply -f rayservice-autoscaler.yaml
  
  # The RayService will crash repeatedly
  ```

We have 5 Ray serve deployments in the [gist](https://gist.github.com/kevin85421/0de4627d4eef6f62b23ec72ad68621a5#file-rayservice-autoscaler-yaml-L16-L43). The MangoStand deployment requires 1 CPU and the other 4 deployments require 0.1 CPU. Hence, we need 1.4 CPUs for all serve deployments.

For head, we set `rayStartParams: {"num-cpus": "0"}` to avoid tasks/actors scheduling on the head Pod. In addition, we have [one worker Pod](https://gist.github.com/kevin85421/0de4627d4eef6f62b23ec72ad68621a5#file-rayservice-autoscaler-yaml-L85) by default which has 1 CPU. Hence, the autoscaler needs to create the other one worker Pod with 1 CPU to accommodate the 5 deployments.

In RayService, the new RayCluster is a `pendingRayCluster` for the RayService, and becomes a `activeRayCluster` when it becomes ready and healthy ([code](https://github.com/ray-project/kuberay/blob/dfc197f74889ee468c9cbaa29d5f3f0f458fb164/ray-operator/controllers/ray/rayservice_controller.go#L874-L877)).

However, if there is any change for the `pendingRayCluster`, the function `createRayClusterInstance` will delete the `pendingRayCluster` and create a new one. Because the autoscaler will update the `replicas` field in the RayCluster spec, the following `if` statement will be fulfilled.

https://github.com/ray-project/kuberay/blob/dfc197f74889ee468c9cbaa29d5f3f0f458fb164/ray-operator/controllers/ray/rayservice_controller.go#L417-L425

## Case 2 (expected behavior): Trigger Autoscaler scale-up when the RayCluster is active.
* [rayservice-autoscaler-2.yaml](https://gist.github.com/kevin85421/eb40036fc9a88201bdb5981213eae318#file-rayservice-autoscaler-2-yaml): 5 Ray Serve deployments require 0.5 CPU. By default, we have 1 worker Pod with 1 CPU. Hence, the autoscaler will not be triggered.

```sh
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0
kubectl apply -f rayservice-autoscaler-2.yaml

# Wait until the RayCluster becomes the RayService's active RayCluster

# Trigger the autoscaler manually. The cluster has already had 1 worker Pod with 1 CPU, so the autoscaler needs to create two new worker Pods so that the cluster has 3 CPUs in total.
export HEAD_POD=$(kubectl get pods --selector=ray.io/node-type=head -o custom-columns=POD:metadata.name --no-headers)
kubectl exec $HEAD_POD -it -c ray-head -- python -c "import ray;ray.init();ray.autoscaler.sdk.request_resources(num_cpus=3)"

# The worker Pods will not crash.
```

We can check whether the RayCluster is active or not by `kubectl describe rayservice rayservice-sample`. The "Active Service Status" of RayService should look like this:

Screen Shot 2023-04-17 at 1 27 26 PM

### Reproduction script

See above.

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?
 
PR #655 avoids the creation of a new RayCluster when an active RayCluster triggers Ray autoscaling. However, it is possible for a pending RayCluster to trigger Ray autoscaling. See the section "Case 1 (bug): Trigger Autoscaler scale-up when the RayCluster is pending" in #1030 as an example.

## What's the difference between #655 and this PR?

For #655,

* When a RayService creates a RayCluster, it will add an annotation `ray.io/cluster-hash` with the hash value of the "whole" `RayService.Spec.RayClusterSpec`. 
* Active RayCluster: Compare the hash value of `RayService.Spec.RayClusterSpec` and the value of the annotation `ray.io/cluster-hash` from the active RayCluster. Create a new RayCluster if they are not equal.
  * Ray autoscaler updates only the `RayCluster` spec and not the `RayService.Spec.RayClusterSpec`. Therefore, the creation of a new RayCluster will not be triggered when an active one triggers Ray autoscaling."

* Pending RayCluster: Compare the `pendingRayCluster.Spec` and `RayService.Spec.RayClusterSpec` by the function `CompareJsonStruct`. Hence, when the `pendingRayCluster.Spec` is updated by Ray autoscaling, the new pending RayCluster creation will be triggered.

For #1037 (this PR),

* When a RayService creates a RayCluster, it will add an annotation `ray.io/cluster-hash` with the hash value of "some parts" of `RayService.Spec.RayClusterSpec`. 
* Active RayCluster: Compare the hash values of `RayService.Spec.RayClusterSpec` and the value of the annotation `ray.io/cluster-hash` from the active RayCluster.
* Pending RayCluster: Compare the hash values of `pendingRayCluster.Spec` and `RayService.Spec.RayClusterSpec`.

## The generation of hash is different between #655 and #1037.

PR #655 generates a hash value based on the whole RayClusterSpec. On the other hand, in PR #1037, some fields are set to nil before generating the hash.

In #655, every update in `RayService.Spec.RayClusterSpec` will trigger a new cluster preparation. However, we should categorize updates for `RayService.Spec.RayClusterSpec` into 3 categories. 

* Case 1. RayService should ignore this update and does nothing. (e.g. WorkersToDelete)
* Case 2. RayService should not create a new RayCluster, but should update RayCluster (e.g. Replicas)
* Case 3. RayService should trigger a new RayCluster creation (e.g. update the RayCluster's Docker image)

This PR is capable of identifying whether an update falls under Case 3 or not, but it does not have the ability to differentiate between Case 1 and Case 2. In this PR, if an update does not belong to Case 3, we will ignore the update.

For example, the update of `WorkersToDelete` for `RayService.Spec.RayClusterSpec` will be ignored. See the change of the test "should update a rayservice object and switch to new Ray Cluster" in [rayservice_controller_test.go](https://github.com/ray-project/kuberay/pull/1037/files#diff-6db0d72814d5196ad71e09a7e728648c0a7630e24ff3b6c71cbba2ecab8fe560) for more details.

In the follow-up PRs, we need to provide a clear definition to differentiate between Case 1 and Case 2.

## Related issue number
Closes #1030 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### Reproduce bug with v0.5.0
```sh
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0
# path: ray-operator/config/samples/
# New RayCluster will be restarted by RayService repeatedly.
kubectl apply -f ray-service.autoscaler.yaml
```

### Test this PR
```sh
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0 --set image.repository=controller,image.tag=latest
# path: ray-operator/config/samples/
# New RayCluster preparation will not be triggered.
kubectl apply -f ray-service.autoscaler.yaml

# Update workerGroupSpecs[0].replicas from 1 to 3. (New cluster preparation should not happen.)
kubectl apply -f ray-service.autoscaler.yaml

# Update rayClusterConfig.rayVersion from '2.4.0' to '2.100.0'. (New cluster preparation should be triggered.)
kubectl apply -f ray-service.autoscaler.yaml
```

### CODE REVIEW

**Review by sihanwang41 — APPROVED** [review]
nice catch for this issue.

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 1]
```diff
@@ -926,3 +927,31 @@ func (r *RayServiceReconciler) labelHealthyServePods(ctx context.Context, rayClu
 
 	return nil
 }
+
+func (r *RayServiceReconciler) generateRayClusterJsonHash(rayClusterSpec rayv1alpha1.RayClusterSpec) (string, error) {
```
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/rayservice_controller.go]: Thank you for the suggestion! I have added a new unit test suite https://github.com/ray-project/kuberay/pull/1037/commits/dc7dd3e9c56cbd98b73b3327598d796185ab4c50.

File: ray-operator/config/samples/ray-service.autoscaler.yaml [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+        numReplicas: 1
+        rayActorOptions:
+          numCpus: 0.1
+      - name: DAGDriver
+        numReplicas: 1
+        routePrefix: "/"
+        rayActorOptions:
+          numCpus: 0.1
+  rayClusterConfig:
+    rayVersion: '2.100.0' # should match the Ray version in the image of the containers
```
Comment (shrekris-anyscale) [inline ray-operator/config/samples/ray-service.autoscaler.yaml:45]: It looks like [the Ray images](https://github.com/ray-project/kuberay/pull/1037/files#diff-977cfa49bfd741168136aa416c0b8c400c93aa3fb9d8aaddef58d7bac0459e35R65) in this spec use Ray 2.4, but the Ray version here is set to `2.100.0` (which I assume is Ray 2.1).

Could we either change the Ray version or change the comments saying that the version should match the package in the images?

File: ray-operator/controllers/ray/rayservice_controller_test.go [hunk 3]
```diff
@@ -319,6 +315,53 @@ var _ = Context("Inside the default namespace", func() {
 				time.Second*3, time.Millisecond*500).Should(BeNil(), "My myRayCluster  = %v", myRayCluster.Name)
 		})
 
+		It("Autoscaler updates RayCluster and should not switch to a new RayCluster", func() {
```
Comment (shrekris-anyscale) [inline ray-operator/controllers/ray/rayservice_controller_test.go:318]: Could you add a unit test that checks that the pending RayService doesn't start a new cluster if it autoscales? I believe the current unit tests are checking only that the active RayService doesn't start a new cluster.

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 4]
```diff
@@ -926,3 +931,29 @@ func (r *RayServiceReconciler) labelHealthyServePods(ctx context.Context, rayClu
 
 	return nil
 }
+
+func generateRayClusterJsonHash(rayClusterSpec rayv1alpha1.RayClusterSpec) (string, error) {
+	// Mute all fields that will not trigger new RayCluster preparation. For example,
+	// Autoscaler will update `Replicas` and `WorkersToDelete` when scaling up/down.
+	updatedRayClusterSpec := rayClusterSpec.DeepCopy()
+	for i := 0; i < len(updatedRayClusterSpec.WorkerGroupSpecs); i++ {
+		updatedRayClusterSpec.WorkerGroupSpecs[i].Replicas = nil
```
Comment (shrekris-anyscale) [inline ray-operator/controllers/ray/rayservice_controller.go:940]: Nice! Is there any way to guard against new fields that we should also ignore? Right now, we're specifically muting `Replicas` and `ScaleStrategy.WorkersToDelete`. My concern is that we add a new field to `RayClusterSpec` that we should also, but we forget to mute it here.

This is a minor suggestion, so if you feels it's not worth the refactoring, please feel free to ignore!

**Review by shrekris-anyscale — COMMENTED** [review]
Great work so far! Thanks for the detailed summary in the PR description. I left a few suggestions.

File: ray-operator/controllers/ray/rayservice_controller.go (hunk 4 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayservice_controller.go:940]: Good question, not sure whether a blacklist or whitelist approach is better here and I don't think there's a clear winner.  Tentatively I'd say the blacklist approach (current approach) is better because we expect that a typical new field should trigger a restart.

**Review by architkulkarni — APPROVED** [review]
Looks good to me pending Shreyas's comments.

In the bug, what's the field that gets updated that triggers the restart? (Is it `Replicas` or `WorkersTodelete`, or both?)

File: ray-operator/config/samples/ray-service.autoscaler.yaml (hunk 2 above)
Comment (kevin85421) [reply ray-operator/config/samples/ray-service.autoscaler.yaml]: Thanks! I have updated `rayVersion` to `2.4.0` https://github.com/ray-project/kuberay/pull/1037/commits/cc93f97bfc8071a7f14976c52d30221d2904c381. The behavior is the same as before. All values of `rayVersion` 2.X.Y have the same behavior.

File: ray-operator/controllers/ray/rayservice_controller_test.go (hunk 3 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayservice_controller_test.go]: Good idea! I missed the test. I have added a test "Autoscaler updates the pending RayCluster and should not switch to a new RayCluster".

File: ray-operator/controllers/ray/rayservice_controller.go (hunk 4 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayservice_controller.go:940]: I vote for the blacklist approach (current approach). The blacklist includes both Case 1 and Case 2. Case 1 fields should include those that are fully managed by Ray (`WorkersToDelete` seems to be the only one I can come up with at this moment.). For Case 2 fields, we should ensure that they are supported by the RayCluster rolling update. Currently, only the `Replicas` field for workers can be updated after the RayCluster is created.

Hence, most new fields will not belong to Case 1 and Case 2, so the blacklist can keep short.

> Case 1. RayService should ignore this update and does nothing. (e.g. WorkersToDelete)
Case 2. RayService should not create a new RayCluster, but should update RayCluster (e.g. update RayCluster's labels)
Case 3. RayService should trigger a new RayCluster creation (e.g. update the RayCluster's Docker image)

Comment (shrekris-anyscale) [reply ray-operator/controllers/ray/rayservice_controller.go:940]: That sounds good, I'll resolve this comment.

**Review by shrekris-anyscale — APPROVED** [review]
Nice job! Thanks for addressing all my comments!

**Comment by kevin85421** [comment]
> In the bug, what's the field that gets updated that triggers the restart? (Is it `Replicas` or `WorkersTodelete`, or both?)

To explain this, we need to know that `RayService.Spec.RayClusterSpec`, `pendingRayCluster.Spec`, and `activeRayCluster.Spec` are different.

[Without this PR]
If the pending RayCluster triggers autoscaling and updates `Replicas` (scale up/down) or `WorkersToDelete` (scale down), the function `utils.CompareJsonStruct(pendingRayCluster.Spec, rayServiceInstance.Spec.RayClusterSpec)` will return false and trigger a new RayCluster preparation to replace the original pending RayCluster.

In `ray-service.autoscaler.yaml`, we have 5 serve deployments which require 1.4 CPUs in total, but we only have 1 head (0 CPU) and 1 worker (1 CPU). Hence, the autoscaler will be triggered to update `Replicas` and KubeRay will create a new worker Pod. At this moment, `utils.CompareJsonStruct(pendingRayCluster.Spec, rayServiceInstance.Spec.RayClusterSpec)` will return false.
