### PR TITLE
Fixes to shorten generated Route name with consideration for namespace

### LINKED ISSUE #1882: [Bug] Long Route names and namespaces auto-generate invalid host
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When a Route is generated by the Ray Operator in OpenShift, it is populated with the Route `{metadata.name }`as provided by the ray-operator to be `<providedname>-head-route`, where `<providedname>-head-route` is ultimately checked for size maximums and reduced to 50 characters. The difficulty lies in that the `spec.host` value is not provided to the Route object, so when a `spec.host` is auto-generated it is created as the Route's: `{metadata.name}-{metadata.namespace}`. If the namespace is longer than 12 characters, then the generated `spec.host` value for the route's first DNS label is >63 characters, which is invalid per RFC 1035.

Example:
`my-task-does-not-have-too-long-a-name-raycluster-abcde-head-route` <- initial Route name
`t-have-too-long-a-name-raycluster-abcde-head-route` <- truncated name to 50 chars
`t-have-too-long-a-name-raycluster-abcde-head-route-my-namespace-here.mycluster.com` <- namespace appended to first portion of DNS by OpenShift is now 68 characters and will fail to create a route every time

### Reproduction script

Route that will fail to create in OpenShift that could be vaildly generated by Ray operator:

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: t-have-too-long-a-name-raycluster-abcde-head-route
  namespace: more-than-twelve-chars
spec:
  to:
    kind: Service
    name: t-have-too-long-a-name-raycluster-abcde-head-route
    weight: 100
  port:
    targetPort: 8265
  wildcardPolicy: None
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by neilisaur**
## Why are these changes needed?

OpenShift Routes `spec.host` values are a concatenation of Route `metadata.name` and `metadata.namespace`, which can expand beyond 63 characters without care, causing a failure to create the Route.

## Related issue number

Closes #1882

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @astefanutti would you mind reviewing this PR? Thanks!

File: ray-operator/controllers/ray/utils/util.go [hunk 1]
```diff
@@ -68,6 +68,24 @@ func IsRunningAndReady(pod *corev1.Pod) bool {
...
+	// 63 - (max(8,6) + 5 ) - length of namespace name + 1 => 49 - namespace name
+	// 6 to 8 char are consumed at the end with "-head-" or -worker- + 5 generated.
+	// Namespace name will be appended to form: {name}-{namespace} for first host
+	//   segment within route
+	maxLength := 49 - len(n)
+
+	if len(s) > maxLength {
+		// shorten the name
+		offset := int(math.Abs(float64(maxLength) - float64(len(s))))
+		fmt.Printf("route name is too long: len = %v, we will shorten it by offset = %v\n", len(s), offset)
```
Comment (astefanutti) [inline ray-operator/controllers/ray/utils/util.go:81]: The RayCluster controller logger should be used instead.

File: ray-operator/controllers/ray/utils/util.go [hunk 2]
```diff
@@ -68,6 +68,24 @@ func IsRunningAndReady(pod *corev1.Pod) bool {
 	return false
 }
 
+func CheckRouteName(s string, n string) string {
+	// 63 - (max(8,6) + 5 ) - length of namespace name + 1 => 49 - namespace name
+	// 6 to 8 char are consumed at the end with "-head-" or -worker- + 5 generated.
```
Comment (astefanutti) [inline ray-operator/controllers/ray/utils/util.go:73]: Routes are not generated for worker nodes, are they?

File: ray-operator/controllers/ray/utils/util.go [hunk 3]
```diff
@@ -68,6 +68,24 @@ func IsRunningAndReady(pod *corev1.Pod) bool {
...
+	// Namespace name will be appended to form: {name}-{namespace} for first host
+	//   segment within route
+	maxLength := 49 - len(n)
+
+	if len(s) > maxLength {
+		// shorten the name
+		offset := int(math.Abs(float64(maxLength) - float64(len(s))))
+		fmt.Printf("route name is too long: len = %v, we will shorten it by offset = %v\n", len(s), offset)
+		s = s[offset:]
```
[the remark this answers is not in the document]
Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util.go:82]: I'd suggest leaving it as trailing. The portion that the user specifies comes at the beginning and if a user is submitting multiple instances of similar work they'd likely use something like `my-work-a`, `my-work-b`, etc. If you truncate from the end of the supplied name, you'd lose that differentiator first and have conflicting route/pod/etc. names.

File: ray-operator/controllers/ray/utils/util.go (hunk 2 above)
Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util.go]: True; updated!

File: ray-operator/controllers/ray/utils/util.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util.go:82]: Though thinking further, the randomized 5-char addition should resolve that, so I'm either way

[the remark this answers is not in the document]
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/utils/util.go:82]: Yeah, the related Kubernetes (k8s) code that generates the random 5-character string is here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/storage/names/generate.go#L51. It truncates the end.

File: ray-operator/controllers/ray/utils/util.go (hunk 1 above)
Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util.go]: Updated to use the controller logger

File: ray-operator/controllers/ray/utils/util.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util.go:84]: Either way you'd end up preferring is fine here, but right now it's consistent with the existing CheckName function and I'm loathe to diverge them. Keep original way of truncating beginning or truncate from end?

[the remark this answers is not in the document]
Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util.go]: Fair enough; updated!

File: ray-operator/controllers/ray/utils/util_test.go [hunk 4]
```diff
@@ -95,13 +95,13 @@ func TestCheckRouteName(t *testing.T) {
 	str := "72fbcc7e-a661-4b18e-ca41-e903-fc3ae634b18e-lazer090scholar-director-s"
```
Comment (astefanutti) [inline ray-operator/controllers/ray/utils/util_test.go:95]: nit: Can we try using an example closer to a real case?

Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util_test.go]: Absolutely; updated!

File: ray-operator/controllers/ray/utils/util.go [hunk 5]
```diff
@@ -68,6 +68,27 @@ func IsRunningAndReady(pod *corev1.Pod) bool {
...
+	// Namespace name will be appended to form: {name}-{namespace} for first host
+	//   segment within route
+	// 63 - (6 + 5) - (length of namespace name + 1)
+	// => 52 - (length of namespace name + 1)
+	// => 51 - (length of namespace name)
+	maxLength := 51 - len(n)
+
+	if len(s) > maxLength {
+		// shorten the name
+		log.Info(fmt.Sprintf("route name is too long: len = %v, we will shorten it to = %v\n", len(s), maxLength))
```
Comment (astefanutti) [inline ray-operator/controllers/ray/utils/util.go:84]: the return carriage can be removed as it's formatted by the logger.

File: ray-operator/controllers/ray/utils/util_test.go [hunk 6]
```diff
@@ -90,6 +90,29 @@ func TestCheckName(t *testing.T) {
 	}
 }
 
+func TestCheckRouteName(t *testing.T) {
+	// test 1 -> change
+	str := "cv-traffic-training-202402090958"
```
Comment (astefanutti) [inline ray-operator/controllers/ray/utils/util_test.go:95]: Would you mind structuring the test cases following the usual convention, e.g.:

```
for name, tc := range tests {
		t.Run(name, func(t *testing.T) {
```

Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util_test.go]: Updated!

File: ray-operator/controllers/ray/utils/util.go (hunk 5 above)
Comment (neilisaur) [reply ray-operator/controllers/ray/utils/util.go:84]: Removed

**Review by astefanutti — APPROVED** [review]
Thanks!

**Comment by astefanutti** [comment]
@kevin85421 please have a look.

**Review by kevin85421 — APPROVED** [review]
Thanks! I will merge this PR after CI passes.
