### PR TITLE
[Apiserver][Refactor] Use polling in autoscaler e2e test

### LINKED ISSUE #3293: [Bug] API server cluster autoscaler test e2e test failure
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

apiserver

### What happened + What you expected to happen

I just started to learn kuberay apiserver and setup environment on ubuntu EC2 instance.
The only command I ran is `cd apiserver && make local-e2e-test`, which fails autoscaler test.

```sh
    cluster_server_autoscaler_e2e_test.go:129: 
                Error Trace:    /home/ubuntu/kuberay/apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go:129
                Error:          Not equal: 
                                expected: 1
                                actual  : 0
                Test:           TestCreateClusterAutoscaler
```

### Reproduction script

Reproduce command:
```sh
cd apiserver && make local-e2e-test
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by owenowenisme**
## Why are these changes needed?
ApiServer is e2e flaky due to the fixed sleep time waiting for worker pod, changed to polling to deal with the flakiness, and it also speedup the test.
### Before
```
=== RUN   TestCreateClusterAutoscaler
--- PASS: TestCreateClusterAutoscaler (158.10s)
PASS
coverage: 54.2% of statements
ok      github.com/ray-project/kuberay/apiserver/test/e2e  159.198s coverage: 54.2% of statements
```
### After
```
=== RUN   TestCreateClusterAutoscaler
--- PASS: TestCreateClusterAutoscaler (119.57s)
PASS
coverage: 54.2% of statements
ok      github.com/ray-project/kuberay/apiserver/test/e2e  120.662s coverage: 54.2% of state
```

## Related issue number
Closes #3293

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [ ] Unit tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by owenowenisme** [comment]
@dentiny PTAL

**Comment by dentiny** [comment]
Please attach the github issue

**Review by dentiny — APPROVED** [review]
Hero PR! :100:

**Comment by kevin85421** [comment]
cc @rueian would you mind also reviewing this PR?

**Comment by win5923** [comment]
Hi @owenowenisme, could you rebase with the master branch, and re-enable the `TestCreateClusterAutoscaler` test?
Check https://github.com/ray-project/kuberay/pull/3351#discussion_r2042882596

**Review by rueian — APPROVED** [review]

**Comment by rueian** [comment]
Nice LGTM. It's just that `err00` looks wired 😂.

**Comment by owenowenisme** [comment]
> Nice LGTM. It's just that `err00` looks wired 😂.

Haha you're right, I was too lazy to rename that, just renamed all `err00`.

**Comment by dentiny** [comment]
> Nice LGTM. It's just that `err00` looks wired 😂.

Is it because of variable shadowing? `err` has been declared above, and (implicit captured by reference)

File: apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go [hunk 1]
```diff
@@ -122,13 +123,15 @@ func TestCreateClusterAutoscaler(t *testing.T) {
 	waitForRayJob(t, tCtx, createActorRequest.Job.Name, []rayv1api.JobStatus{rayv1api.JobStatusSucceeded})
 
 	// worker pod should be created as part of job execution
-	time.Sleep(20 * time.Second)
-
-	// Get number of workers
-	rayCluster, err = tCtx.GetRayClusterByName(actualCluster.Name)
+	err = wait.PollUntilContextTimeout(tCtx.ctx, 500*time.Millisecond, 3*time.Minute, false, func(_ context.Context) (done bool, err error) {
```
Comment (kevin85421) [inline apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go:126]: What's the difference between `wait` from `apimachinery` and `Eventually` from `Gomega`? If there isn't any difference, can we use `Eventually` instead to be consistent with the tests for the `ray-operator`?

Comment (owenowenisme) [reply apiserver/test/e2e/cluster_server_autoscaler_e2e_test.go:126]: Yes, I think we could replace `wait` with `Eventually`, there's no huge difference.
But may I address that in another PR?
Because I have another PR might conflict a lot if I change all e2e to `gomega`on this one.
