### PR TITLE
[Bug][RayJob] RayJob with custom head service name

### LINKED ISSUE #1294: [Feature] Allow setting the RayClusterName in the job specification to have determinitic service head
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Currently in order to expose the service to the end user, we need to look for the service name which contains a random number.

For instance of the user has already a unique RayJob: `job-22f1d24aff9a4c7fbe5ab9707decbcb0` the cluster name would something like this `job-22f1d24aff9a4c7fbe5ab9707decbcb0-raycluster-7ct2d` and subsequently the service head would be `22ff9a4c7fbe5ab9707decbcb0-raycluster-7ct2d-head-svc`.

It would be nice to allow the user to set the value and only generate them if not specified.

### Use case

I understand the logic to prevent crashing the creation of the cluster, unfortunately this make using the operator very hard.

I think the specification should allow setting the RayClusterName similar to the JobId to allow building on top of this operator.

**Note**: I already tried to set the name of the service and head via `metadata.name` unfortunately some env vars are auto generated and the ray params and using the env var to resolve the service name.

### Related issues

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

As @mmourafiq pointed out in https://github.com/ray-project/kuberay/pull/1326#issuecomment-1678476425, some users prefer a deterministic head service name for RayJob in order to set up a reverse proxy. Although we've made the entire head service configurable, there are some issues that arise when we set the name of the head service:

* Kubernetes Jobs cannot communicate with the Ray head because of an incorrect service name.
* Ray workers fail to connect to the Ray head due to the same naming issue.

## Related issue number

Closes #1294 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

```sh
# Step 0: Build a KubeRay operator image
# Step 1: Install a KubeRay operator
helm install kuberay-operator kuberay/kuberay-operator --version 0.6.0 --set image.repository=controller,image.tag=latest

# Step 2: Create a RayJob with custom head service
# https://gist.github.com/kevin85421/b8e0259467ffdb1b000c4177159f57e9#file-ray-job-custom-head-svc-name-yaml
kubectl apply -f ray-job-custom-head-svc-name.yaml

# Step 3: Check RayJob's status
kubectl get rayjobs.ray.io rayjob-sample -o=jsonpath='{.status.jobStatus}'
# [expected output]: "SUCCEEDED"
```

### CODE REVIEW

**Comment by mmourafiq** [comment]
This looks good 👍

File: ray-operator/controllers/ray/utils/util.go [hunk 1]
```diff
@@ -129,14 +138,43 @@ func GetNamespace(metaData metav1.ObjectMeta) string {
...
-	return fmt.Sprintf("%s.%s.svc.%s", GenerateServiceName(clusterName), namespace, GetClusterDomainName())
+func GenerateFQDNServiceName(cluster rayv1alpha1.RayCluster, namespace string) string {
+	headSvcName, err := GenerateHeadServiceName(RayClusterCRD, cluster.Spec, cluster.Name)
+	if err != nil {
+		logrus.Errorf("Failed to generate head service name: %v", err)
+		return ""
+	}
+	if cluster.Spec.HeadGroupSpec.HeadService != nil && cluster.Spec.HeadGroupSpec.HeadService.Name != "" {
+		headSvcName = cluster.Spec.HeadGroupSpec.HeadService.Name
+	}
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/utils/util.go:176]: Nit: Why do we need this part, isn't it already done in `GenerateHeadServiceName`?

File: ray-operator/controllers/ray/utils/util.go [hunk 2]
```diff
@@ -145,11 +183,6 @@ func ExtractRayIPFromFQDN(fqdnRayIP string) string {
 	return strings.Split(fqdnRayIP, ".")[0]
 }
 
-// GenerateDashboardServiceName generates a ray head service name from cluster name
-func GenerateDashboardServiceName(clusterName string) string {
-	return fmt.Sprintf("%s-%s-%s", clusterName, DashboardName, "svc")
-}
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/utils/util.go:151]: Nice, it wasn't used anywhere?

**Review by architkulkarni — APPROVED** [review]
Looks good to me!

**Comment by architkulkarni** [comment]
Do you think we should add your manual test YAML to the RayJob sample YAML tests so that the e2e behavior is tested?

File: ray-operator/controllers/ray/utils/util.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/utils/util.go]: Deleted https://github.com/ray-project/kuberay/pull/1332/commits/2f6c72bb72ef2e19c4260c1daf6cb02e9d0bf50a

**Comment by kevin85421** [comment]
> Do you think we should add your manual test YAML to the RayJob sample YAML tests so that the e2e behavior is tested in CI?

This would be great. Should I wait for #1320 or #1321 to be merged or I can work on the test without these 2 PRs? Thanks!

**Comment by architkulkarni** [comment]
> > Do you think we should add your manual test YAML to the RayJob sample YAML tests so that the e2e behavior is tested in CI?
> 
> This would be great. Should I wait for #1320 or #1321 to be merged or I can work on the test without these 2 PRs? Thanks!

@kevin85421 I think it's independent and you don't need to wait, I think you would just need to add the yaml to the list of tested yamls in test_sample_rayjob_yamls.py

**Comment by kevin85421** [comment]
@architkulkarni I have already added a test `ray-job.custom-head-svc.yaml` for this PR.
