### PR TITLE
[kubectl-plugin] fix rayStartParams error when creating workgroup

### LINKED ISSUE #3250: [Bug] Use kubectl plugin to create workgroup will cause error `rayStartParams` Required value
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

```shell=
$ kubectl ray create cluster raycluster-sample
$ kubectl ray create workergroup example-group --ray-cluster raycluster-sample --worker-memory 5Gi
```

### Reproduction script

> Follow the instruction from https://docs.ray.io/en/latest/cluster/kubernetes/user-guides/kubectl-plugin.html

```shell=
$ kubectl ray create cluster raycluster-sample
$ kubectl ray create workergroup example-group --ray-cluster raycluster-sample --worker-memory 5Gi
```
> Error: error updating Ray cluster with new worker group: RayCluster.ray.io "raycluster-sample" is invalid: spec.workerGroupSpecs[1].rayStartParams: Required value

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by CheyuWu**
```shell=
$ kubectl ray create cluster raycluster-sample
$ kubectl ray create workergroup example-group --ray-cluster raycluster-sample --worker-memory 5Gi
```
> It will raise error
```
Error: error updating Ray cluster with new worker group: RayCluster.ray.io "raycluster-sample" is invalid: spec.workerGroupSpecs[1].rayStartParams: Required value
```

## Related issue number
Closes #3250 

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [x] Unit tests
  - [ ] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by CheyuWu** [comment]
Hi @MortalHappiness  PTAL

**Review by andrewsykim — APPROVED** [review]

File: kubectl-plugin/pkg/cmd/create/create_workergroup.go [hunk 1]
```diff
@@ -143,6 +143,10 @@ func (options *CreateWorkerGroupOptions) Run(ctx context.Context, factory cmduti
 }
 
 func createWorkerGroupSpec(options *CreateWorkerGroupOptions) rayv1.WorkerGroupSpec {
+	if options.rayStartParams == nil {
+		options.rayStartParams = map[string]string{}
+	}
+
```
Comment (MortalHappiness) [inline kubectl-plugin/pkg/cmd/create/create_workergroup.go:149]: I think this should be put inside the `Complete` function. You can open another PR to address this.

Comment (CheyuWu) [reply kubectl-plugin/pkg/cmd/create/create_workergroup.go:149]: OK, no problem.
