### PR TITLE
[Bug][GCS FT] Worker pods crash unexpectedly when gcs_server on head pod is killed

### LINKED ISSUE #634: [Bug] Worker pods crash unexpectedly when gcs_server on head pod is killed
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

Others

### What happened + What you expected to happen

TODO

### Reproduction script

TODO

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
### Major changes

When we kill the GCS server process (`pkill gcs_server`) on the head Pod, a Raylet (?) will exit the process if it cannot connect to the GCS server after `RAY_gcs_rpc_server_reconnect_timeout_s` ([code](https://sourcegraph.com/github.com/ray-project/ray@3aa6ede43743a098b5e0eb37ec11505f46100313/-/blob/src/ray/rpc/gcs_server/gcs_rpc_client.h?L527-L546)). By default, the value is 60s.

In #634, the `RAY_gcs_rpc_server_reconnect_timeout_s` values for both head and workers are set to 60 seconds. This means that the head and workers will crash almost simultaneously, 60 seconds after the GCS server process is terminated. Therefore, we need to ensure that the `RAY_gcs_rpc_server_reconnect_timeout_s` for the workers is greater than the time it takes for a new GCS server process to become available after the old one is terminated. That is, 

```
WORKER_RECONNECTION_TIMEOUT > HEAD_RECONNECTION_TIMEOUT + restart the head Pod + new GCS server process become ready
```

This PR injects `RAY_gcs_rpc_server_reconnect_timeout_s` env variable to workers with default value 600s if GCS FT is enabled. Hence, head will crash 60 seconds after the process is terminated, and the new GCS server process will be ready before 600 seconds. Hence, the workers will not crash.

### Minor changes
* Remove `rayCluster` label: The label has been removed by #761 from sample YAML files. This PR removes the label from unit tests.

* [compatibility-test.py](https://github.com/ray-project/kuberay/pull/1036/files#diff-db7eeddbec6895cf05cb70312b97d42f54bdd61ac34ee18d3f74d02ab349b5bf): This is just for refactoring.

* [ray-cluster.ray-ft.yaml.template](https://github.com/ray-project/kuberay/pull/1036/files#diff-62f8a48fc70b61fc917b570ad6780f87b1e506806b66914f5d1ad4c9ac0abe21): Set `RAY_gcs_rpc_server_reconnect_timeout_s` to make the compatibility test become faster.

## Related issue number
Closes #634 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

```sh
# Build the KubeRay image (controller:latest)
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0 --set image.repository=controller,image.tag=latest

# Create a RayCluster with GCS FT
kubectl apply -f ray-cluster.external-redis.yaml

# This env var should not be set on head Pod by default
kubectl describe pod $YOUR_HEAD_POD | grep RAY_gcs_rpc_server_reconnect_timeout_s

# The env should be injected to worker Pods by default.
kubectl describe pod $YOUR_WORKER_POD | grep RAY_gcs_rpc_server_reconnect_timeout_s
# RAY_gcs_rpc_server_reconnect_timeout_s:  600

# Kill the GCS server process on the head Pod
kubectl exec -it $YOUR_HEAD_POD -- pkill gcs_server

# Expected behavior: head Pod will crash after 60 seconds, and workers will not crash.
```

Screen Shot 2023-04-19 at 1 15 19 PM

Screen Shot 2023-04-19 at 1 23 27 PM

### CODE REVIEW

**Comment by architkulkarni** [comment]
@iycheng do you mind just checking the PR description and confirming that the solution makes sense from the Ray side?

File: ray-operator/controllers/ray/common/constant.go [hunk 1]
```diff
@@ -88,7 +89,8 @@ const (
 	RAYCLUSTER_DEFAULT_REQUEUE_SECONDS      = 300
 
 	// Ray core default configurations
-	DefaultRedisPassword = "5241590000000000"
+	DefaultRedisPassword                 = "5241590000000000"
+	DefaultWorkerRayGcsReconnectTimeoutS = "600"
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/common/constant.go:93]: Here, or somewhere else in the code, can we add a brief comment explaining why we picked this value? It's explained well in the PR description but it's helpful to have it in a code comment

File: tests/config/ray-cluster.ray-ft.yaml.template [hunk 2]
```diff
@@ -92,6 +92,8 @@ spec:
               # RAY_REDIS_ADDRESS can force ray to use external redis
               - name: RAY_REDIS_ADDRESS
                 value: redis:6379
+              - name: RAY_gcs_rpc_server_reconnect_timeout_s
+                value: "20"
```
Comment (architkulkarni) [inline tests/config/ray-cluster.ray-ft.yaml.template:96]: Do we intend to check this value somewhere? I didn't see it in the test

**Review by architkulkarni — APPROVED** [review]
Looks good to me

File: tests/config/ray-cluster.ray-ft.yaml.template (hunk 2 above)
Comment (kevin85421) [reply tests/config/ray-cluster.ray-ft.yaml.template:96]: This is used to accelerate the test. Some tests in `compatibility-test.py` will kill the GCS server process on the head Pod and wait until the new one is available. By default, the head will crash after 60 seconds. With this configuration, it will crash after 20 seconds.

Comment (architkulkarni) [reply tests/config/ray-cluster.ray-ft.yaml.template:96]: Oh right. This is another place where a code comment would be helpful

File: ray-operator/controllers/ray/common/pod.go [hunk 3]
```diff
@@ -646,13 +646,17 @@ func setContainerEnvVars(pod *v1.Pod, rayContainerIndex int, rayNodeType rayiov1
...
+		}
+	}
 }
 
 func envVarExists(envName string, envVars []v1.EnvVar) bool {
-	if len(envVars) == 0 {
-		return false
-	}
-
 	for _, env := range envVars {
```
Comment (gvspraveen) [inline ray-operator/controllers/ray/common/pod.go:660]: doesnt this break if envVars slice is nil? Previously `len(envVars) == 0` protected from that if i am not wrong.

Comment (kevin85421) [reply ray-operator/controllers/ray/common/pod.go:660]: If the slice is empty, it will not enter the for loop. 

```go
// You can edit this code!
// Click here and start typing.
package main

import "fmt"

func envVarExists(fruitName string, fruits []string) bool {
	for _, fruit := range fruits {
                fmt.Println("Enter the loop")
		if fruitName == fruit {
			return true
		}
	}
	return false
}

func main() {
	fruits := []string{"apple", "banana", "cherry", "date"}
	fmt.Println(envVarExists("banana", fruits))     // true
	fmt.Println(envVarExists("aaaaaa", fruits))     // false
	fmt.Println(envVarExists("aaaaaa", []string{})) // false
}

# STDOUT
Enter the loop
Enter the loop
true
Enter the loop
Enter the loop
Enter the loop
Enter the loop
false
false
```

Comment (kevin85421) [reply ray-operator/controllers/ray/common/pod.go:660]: You can try this on https://go.dev/play/

File: ray-operator/controllers/ray/common/constant.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/common/constant.go:93]: Added comment in https://github.com/ray-project/kuberay/pull/1036/commits/d0991ff50ac8437ed24517c4fa9c797add3349ca

File: tests/config/ray-cluster.ray-ft.yaml.template (hunk 2 above)
Comment (kevin85421) [reply tests/config/ray-cluster.ray-ft.yaml.template:96]: Added comment in https://github.com/ray-project/kuberay/pull/1036/commits/d0991ff50ac8437ed24517c4fa9c797add3349ca

**Comment by kevin85421** [comment]
@architkulkarni would you mind taking a look at this Ci failure (https://github.com/ray-project/kuberay/actions/runs/4758810193/jobs/8457448052?pr=1036)? Thanks! This seems to be my second time to see the error message. Thanks!

**Comment by kevin85421** [comment]
@wilsonwang371 @iycheng would you mind taking a look at this PR? You only need to take a look at `pod.go` and `pod_test.go`. It may take 10 mins to review. Thanks!

File: ray-operator/controllers/ray/common/pod.go [hunk 4]
```diff
@@ -646,13 +646,20 @@ func setContainerEnvVars(pod *v1.Pod, rayContainerIndex int, rayNodeType rayiov1
 			}
 		}
 	}
+	if !envVarExists(RAY_GCS_RPC_SERVER_RECONNECT_TIMEOUT_S, container.Env) && rayNodeType == rayiov1alpha1.WorkerNode {
+		// If GCS FT is enabled and RAY_GCS_RPC_SERVER_RECONNECT_TIMEOUT_S is not set, set the worker's
+		// RAY_GCS_RPC_SERVER_RECONNECT_TIMEOUT_S to 600s. If the worker cannot reconnect to GCS within
+		// 600s, the Raylet will exit the process. By default, the value is 60s, so the head node will
+		// crash if the GCS server is down for more than 60s. Typically, the new GCS server will be available
+		// in 120 seconds, so we set the timeout to 600s to avoid the worker nodes crashing.
```
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/common/pod.go:654]: 120 seconds works in my local Kind cluster, but it may not work in a production Kubernetes cluster. Users can easily change the value by setting an environment variable. In addition, it is possible for some Pods on public cloud to experience network disconnections for several minutes. That's why I decided to select a higher timeout.

[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/common/pod.go:654]: Gentle ping @wilsonwang371 

Does this make sense to you?
