### PR TITLE
[RayService] Directly fail CR if is invalid

### LINKED ISSUE #4045: [Bug]  RayService not failed when metadata is invalid
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Similar to #3980. We should update the RayService controller to mark the CR as Failed when `ValidateRayServiceMetadata` fails, rather than continuously requeueing.
https://github.com/ray-project/kuberay/blob/d59cbd8901c498b17bac728be54189214fea3f30/ray-operator/controllers/ray/rayservice_controller.go#L112-L116

### Reproduction script

Apply https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray-service.sample.yaml with a name longer than 47 characters.

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by win5923**
## Why are these changes needed?
Similar to https://github.com/ray-project/kuberay/issues/3980. We should directly fail the RayService CR when validation fails, rather than continuously requeueing.

https://github.com/ray-project/kuberay/blob/d59cbd8901c498b17bac728be54189214fea3f30/ray-operator/controllers/ray/rayservice_controller.go#L112-L116

Also add new RayServiceConditionReason called `RayServiceValidationFailed`.
```
Status:
  Conditions:
    Last Transition Time:  2025-11-24T15:48:50Z
    Message:               The RayService metadata is invalid: RayService name should be no more than 47 characters
    Reason:                ValidationFailed
    Status:                False
    Type:                  Ready
  Last Update Time:        2025-11-24T15:48:50Z
```

## Related issue number
Closes #4045

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [x] Unit tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 1]
```diff
@@ -115,15 +115,21 @@ func (r *RayServiceReconciler) Reconcile(ctx context.Context, request ctrl.Reque
...
-	if err := utils.ValidateRayServiceSpec(rayServiceInstance); err != nil {
-		r.Recorder.Eventf(rayServiceInstance, corev1.EventTypeWarning, string(utils.InvalidRayServiceSpec),
-			"The RayService spec is invalid %s/%s: %v", rayServiceInstance.Namespace, rayServiceInstance.Name, err)
-		return ctrl.Result{RequeueAfter: ServiceDefaultRequeueDuration}, err
+	// Perform all validations and directly fail the RayService if any of the validation fails
+	errType, err := validateRayService(ctx, rayServiceInstance)
+	// Immediately update the status after validation
+	if err != nil {
+		r.Recorder.Eventf(rayServiceInstance, corev1.EventTypeWarning, string(errType),
+			"%s/%s: %v", rayServiceInstance.Namespace, rayServiceInstance.Name, err)
```
Comment (win5923) [inline ray-operator/controllers/ray/rayservice_controller.go:123]: Follow RayJob pattern:
https://github.com/ray-project/kuberay/blob/32c1d1b4d1b257be6245aa620a5594ba6dc167d8/ray-operator/controllers/ray/rayjob_controller.go#L147-L149

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 2]
```diff
@@ -115,15 +115,21 @@ func (r *RayServiceReconciler) Reconcile(ctx context.Context, request ctrl.Reque
...
+
+		setCondition(rayServiceInstance, rayv1.RayServiceReady, metav1.ConditionFalse, rayv1.RayServiceValidationFailed, err.Error())
```
Comment (AndySung320) [inline ray-operator/controllers/ray/rayservice_controller.go:125]: The validation code updates `Conditions`, but `kubectl get rayservice` displays the deprecated `ServiceStatus` field: `// +kubebuilder:printcolumn:name="service status",type=string,JSONPath=".status.serviceStatus"` (In `ray-operator/apis/ray/v1/rayservice_types.go` around line 216)

Will users see validation failures when they run `kubectl get rayservice`? Or will the "service status" column show stale/empty data since we're not updating that field?

I'm a bit new to this codebase, so please let me know if I'm misunderstanding how this works!

Comment (win5923) [reply ray-operator/controllers/ray/rayservice_controller.go:125]: User need to use `kubectl describe rayservice` to see the `RayServiceConditionReason`.


By the way, I'm not sure why we didn't use `printcolumn` to display the `RayServiceConditionType` for `kubectl get rayservice`. maybe it's is ongoing.

https://github.com/ray-project/kuberay/issues/2851
https://github.com/ray-project/kuberay/issues/2299

File: ray-operator/test/e2erayservice/rayservice_validation_test.go [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+	. "github.com/ray-project/kuberay/ray-operator/test/support"
+)
+
+func TestRayServiceValidation(t *testing.T) {
+	test := With(t)
+	g := NewWithT(t)
+
+	// Create a namespace
+	namespace := test.NewTestNamespace()
+	rayServiceName := "rayservice-sample-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```
Comment (machichima) [inline ray-operator/test/e2erayservice/rayservice_validation_test.go]: nit: Can we set the name with `strings.Repeat("a", 48)` to make it obvious that it exceed 48 characters?

Comment (win5923) [reply ray-operator/test/e2erayservice/rayservice_validation_test.go]: Thanks, fix in https://github.com/ray-project/kuberay/pull/4228/commits/49c3b45d64342634c454462e6f2b01988f34d18d.

**Review by AndySung320 — APPROVED** [review]
