### PR TITLE
[RayCluster][Fix] leave .Status.State untouched when there is a reconcile error

### LINKED ISSUE #2357: [Regression from v1.1] RayCluster Condition should surface resource quota issue correctly
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

In v1.1, when a RayCluster cannot spin up worker nodes due to a resource quota issue, it would have the following status
```
status:
  ...
  reason: 'pods "rayjob-test2-raycluster-bsh5z-worker-small-wg-mh9v2" is forbidden:
    exceeded quota: low-resource-quota, requested: limits.cpu=200m,limits.memory=256Mi,
    used: limits.cpu=0,limits.memory=0, limited: limits.cpu=100m,limits.memory=107374182400m'
  state: failed
```
However, in v1.2, it simply says
```
status:
  ...
  lastUpdateTime: "2024-09-05T23:43:05Z"
  maxWorkerReplicas: 1
  minWorkerReplicas: 1
  observedGeneration: 1
  state: ready
  stateTransitionTimes:
    ready: "2024-09-05T23:43:05Z"
```

First, the state should not be ready. According to [the doc](https://docs.google.com/document/d/1bRL0cZa87eCX6SI7gqthN68CgmHaB6l3-vJuIse-BrY/edit), 

> When all Pods in the RayCluster are running for the first time, the RayCluster CR’s Status.State will transition to ready.

But not all pods in the RayCluster are running. 

Second, the resource quota error should be added as a condition. The design doc alludes to emulating ReplicaSet conditions, which includes [a type for resource quota error](https://pkg.go.dev/k8s.io/api/apps/v1#ReplicaSetConditionType). Right now, the only place to find this error is in the operator logs: 
```
..."error":"FailedCreateWorkerPod pods \"rayjob-test2-raycluster-x7242-small-wg-worker-rbkqx\" is forbidden: exceeded quota: low-resource-quota, requested: limits.cpu=200m,limits.memory=256Mi, ...
```
This makes it impossible for users to self-serve and debug this error. 

As mentioned in https://github.com/ray-project/kuberay/issues/2182, our current way of surfacing this error to the user when deploying a Ray Job is using a separate query to the Ray Cluster for the error: 
```go
rayCluster, err := r.rayClient.RayClusters(namespace).
         Get(ctx, clusterName, metav1.GetOptions{})
if rayCluster.Status.State == rayv1api.Failed {
         return rayCluster.Status.Reason, nil
}
```
However, the 1.2 update breaks the logic, so we cannot upgrade to 1.2 yet. 

### Reproduction script

Create a resource quota: 
```
resourceQuota := corev1.ResourceQuota{
	ObjectMeta: metav1.ObjectMeta{
		Name:      "low-resource-quota",
		Namespace: tCtx.namespace,
	},
	Spec: corev1.ResourceQuotaSpec{
		Hard: corev1.ResourceList{
			corev1.ResourceLimitsCPU:    resource.MustParse(".1"),
			corev1.ResourceLimitsMemory: resource.MustParse(".1Gi"),
		},
	},
}

_, err := tCtx.k8sClient.CoreV1().
	ResourceQuotas(tCtx.namespace).
	Create(tCtx.ctx, &resourceQuota, metav1.CreateOptions{})
```

Deploy a Ray job: 
```
const sampleJobResponseJSON = `{"name":"rayjob-test2", "namespace":"kubeflow-ml", "user":"3cp0", "entrypoint":"python -V", "clusterSpec":{"headGroupSpec":{"computeTemplate":"default-template", "image":"rayproject/ray:2.9.0", "serviceType":"NodePort", "rayStartParams":{"dashboard-host":"0.0.0.0"}, "environment":{}, "labels":{"sidecar.istio.io/inject":"false"}}, "workerGroupSpec":[{"groupName":"small-wg", "computeTemplate":"default-template", "image":"rayproject/ray:2.9.0", "replicas":1, "minReplicas":1, "maxReplicas":1, "rayStartParams":{"metrics-export-port":"8080"}, "environment":{}, "labels":{"sidecar.istio.io/inject":"false"}}]}, "createdAt":"2024-05-20T21:33:03Z"}`
```

Where the compute template is defined as 
```
configMap := corev1.ConfigMap{
	ObjectMeta: metav1.ObjectMeta{
		Name:      tCtx.computeTemplate,
		Namespace: tCtx.namespace,
		Labels: map[string]string{
			"ray.io/compute-template": tCtx.computeTemplate,
			"ray.io/config-type":      "compute-template",
		},
	},
	Data: map[string]string{
		"cpu":             ".1",
		"gpu":             "0",
		"gpu_accelerator": "",
		"memory":          ".2",
		"name":            tCtx.computeTemplate,
		"namespace":       tCtx.namespace,
	},
}
_, err := tCtx.k8sClient.CoreV1().
	ConfigMaps(tCtx.namespace).
	Create(tCtx.ctx, &configMap, metav1.CreateOptions{})
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by rueian**
## Why are these changes needed?

We accidentally set the `.State` of RayCluster CR to `rayv1.Ready` even if there was a reconcile error in PR #2258 where we removed `rayv1.Failed`. This made users unable to deal with `false ready` RayClusters with no pod actually created, see #2357.

But since #2258 has been released and the `rayv1.Failed` has gone, I think we can't bring back `rayv1.Failed` either now. This PR fixes the issue by leaving the `.State` field untouched when there is a reconcile error but setting the error message in the `.Reason` field. That means the initial `.State` for case #2357 will be `blank` and the pod creation error will be in the `.Reason` field. The new unit test case in this PR also tests this behavior.

Example result:

```sh
▶ kubectl describe raycluster raycluster-mini
Name:         raycluster-mini
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  ray.io/v1
Kind:         RayCluster
Metadata:
  Creation Timestamp:  2024-12-06T22:53:44Z
  Generation:          1
  Resource Version:    1393
  UID:                 da4d6b0d-c3a3-4f00-9b9b-e4c411e2d6be
Spec:
  Head Group Spec:
    ...
  Ray Version:       2.9.0
  Suspend:           false
  Worker Group Specs:
    ...
Status:
  Desired CPU:              2
  Desired GPU:              0
  Desired Memory:           2G
  Desired TPU:              0
  Desired Worker Replicas:  1
  Endpoints:
    Client:     10001
    Dashboard:  8265
    Metrics:    8080
    Redis:      6379
  Head:
    Service Name:       raycluster-mini-head-svc
  Last Update Time:     2024-12-06T22:53:46Z
  Max Worker Replicas:  1
  Min Worker Replicas:  1
  Observed Generation:  1
  Reason:               FailedCreateHeadPod
pods "raycluster-mini-head-v6zqb" is forbidden: exceeded quota: demoquota, requested: cpu=1,memory=1G, used: cpu=100m,memory=512Mi, limited: cpu=1,memory=1G
Events:
  Type     Reason                 Age   From                   Message
  ----     ------                 ----  ----                   -------
  Normal   CreatedService         3s    raycluster-controller  Created service default/raycluster-mini-head-svc
  Warning  FailedToCreateHeadPod  3s    raycluster-controller  Failed to create head Pod default/, pods "raycluster-mini-head-tqljd" is forbidden: exceeded quota: demoquota, requested: cpu=1,memory=1G, used: cpu=100m,memory=512Mi, limited: cpu=1,memory=1G
  Warning  FailedToCreateHeadPod  3s    raycluster-controller  Failed to create head Pod default/, pods "raycluster-mini-head-gt52b" is forbidden: exceeded quota: demoquota, requested: cpu=1,memory=1G, used: cpu=100m,memory=512Mi, limited: cpu=1,memory=1G
```

## Related issue number

Closes #2357

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests

### CODE REVIEW

**Comment by kevin85421** [comment]
do we still need this in case https://github.com/ray-project/kuberay/issues/2357#issuecomment-2522234634?

**Comment by rueian** [comment]
I think we still need this. Currently, we mark the RayCluster CR as `Ready` when no Pods are created due to the k8s quota limit. That doesn't look correct in any way.

This PR will make `.State` left blank in this case since we don't introduce the `Failed` state back.

**Comment by kevin85421** [comment]
maybe we need to check the number of Pods before passing to the function `CheckAllPodsRunning`?

**Comment by rueian** [comment]
> maybe we need to check the number of Pods before passing to the function `CheckAllPodsRunning`?

Yeap, checking `len(runtimePods) > 0` before invoking `CheckAllPodsRunning()` works as well. Is there any reason we ignore the `reconcileErr` here?

**Comment by kevin85421** [comment]
> Is there any reason we ignore the reconcileErr here?

does it include in `conditions`?

**Comment by rueian** [comment]
Yes, it is included in the `ReplicaFailure` condition, but if the feature gate is disable, then users can only find the error from logs.

And I think it is not very good to call `CheckAllPodsRunning` while the `reconcileErr` is not nil. That can cause we turn a CR to `Ready` state early. Shouldn't we turn the CR to `Ready` only when the `reconcileErr` is nil?

**Comment by kevin85421** [comment]
> And I think it is not very good to call CheckAllPodsRunning while the reconcileErr is not nil. That can cause we turn a CR to Ready state early. Shouldn't we turn the CR to Ready only when the reconcileErr is nil?

This is a bug. We should not call `CheckAllPodsRunning` when the number of running Pods is not equal to the expected number of Pods.

**Comment by kevin85421** [comment]
Discussed offline:

1. we will not set `Reason`
2. only call `CheckAllPodsRunning` when reconcile error is nil and the number of Pods is as expected.

**Comment by rueian** [comment]
> Discussed offline:
> 
> 1. we will not set `Reason`
> 2. only call `CheckAllPodsRunning` when reconcile error is nil and the number of Pods is as expected.

Updated. Test cases related to `calculateStatus` are also modified to make sure we don't change mark the CR as Ready when there are not enough Pods.

File: ray-operator/controllers/ray/raycluster_controller_unit_test.go [hunk 1]
```diff
@@ -1784,6 +1801,147 @@ func TestCalculateStatus(t *testing.T) {
 	assert.True(t, meta.IsStatusConditionPresentAndEqual(newInstance.Status.Conditions, string(rayv1.RayClusterReplicaFailure), metav1.ConditionTrue))
 }
 
+func TestCalculateStatusWithoutDesiredReplicas(t *testing.T) {
+	setupTest(t)
+
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller_unit_test.go:1806]: 1. Add comments to explain this test.
2. Add assertions to ensure that `testRayCluster` fulfills the assumptions made by this test (i.e., the worker group's replicas should not be 0).

File: ray-operator/controllers/ray/raycluster_controller_unit_test.go [hunk 2]
```diff
@@ -1784,6 +1801,147 @@ func TestCalculateStatus(t *testing.T) {
...
+	newInstance, err := r.calculateStatus(ctx, testRayCluster, nil)
+	assert.Nil(t, err)
+	assert.Equal(t, newInstance.Status.State, rayv1.ClusterState("")) //nolint:staticcheck // https://github.com/ray-project/kuberay/pull/2288
+	assert.Equal(t, newInstance.Status.Reason, "")
+	assert.Nil(t, newInstance.Status.StateTransitionTimes)
+}
+
+func TestCalculateStatusWithReconcileErrorBackAndForth(t *testing.T) {
+	setupTest(t)
+
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller_unit_test.go:1859]: same

File: ray-operator/controllers/ray/raycluster_controller_unit_test.go (hunk 1 above)
Comment (rueian) [reply ray-operator/controllers/ray/raycluster_controller_unit_test.go:1808]: Done.

File: ray-operator/controllers/ray/raycluster_controller_unit_test.go (hunk 2 above)
Comment (rueian) [reply ray-operator/controllers/ray/raycluster_controller_unit_test.go:1865]: Done.

**Review by kevin85421 — APPROVED** [review]

**Comment by andrewsykim** [comment]
sorry for the late reply, LGTM
