### PR TITLE
[Bug] Re-enable flaky kubectl plugin e2e test in kubectl_ray_job_submit_test.go

### LINKED ISSUE #2801: [Bug] Re-enable flaky kubectl plugin e2e test in `kubectl_ray_job_submit_test.go`
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

https://github.com/ray-project/kuberay/pull/2800 temporarily disabled this flaky test. Try to fix it and re-enable it.

https://github.com/ray-project/kuberay/blob/4bb1226ce442f6a03241de91e496adb3f5adef37/kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go#L34

https://github.com/ray-project/kuberay/blob/4bb1226ce442f6a03241de91e496adb3f5adef37/kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go#L70

Possibly related to https://github.com/ray-project/kuberay/issues/2758

### Reproduction script

N/A

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by owenowenisme**
## Why are these changes needed?

There are 2 reason make the test fail.
- There are some kubectl process occupied the 8265 port that is required by the kubectl job submit. But for the independence of tests, we should not expect the test cause this problem to kill the process properly every time, so added the pkill kubectl before running kubectl job submit test.
- The ray is not installed on build kite env, so modified the setup-env.sh to install. 

## Related issue number
Closes #2801 

## Checks

- [ ] I've made sure the tests are passing.
- Testing Strategy
  - [ ] Unit tests
  - [ ] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by owenowenisme** [comment]
@MortalHappiness 
PTAL🙏

File: .buildkite/setup-env.sh [hunk 1]
```diff
@@ -27,5 +27,12 @@ mv linux-amd64/helm /usr/local/bin/helm
 helm repo add kuberay https://ray-project.github.io/kuberay-helm/
 helm repo update
 
+# Install python 3.11 and pip
+apt-get update
+apt-get install -y python3.11 python3-pip
+
+# Install requirements
+pip install --break-system-packages ray==2.41.0 ray\[default\]==2.41.0
```
Comment (MortalHappiness) [inline .buildkite/setup-env.sh:35]:
```suggestion
pip install --break-system-packages ray[default]==2.41.0
```

File: kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go [hunk 2]
```diff
@@ -31,7 +31,8 @@ var _ = Describe("Calling ray plugin `job submit` command on Ray Job", func() {
 	})
 
 	It("succeed in submitting RayJob", func() {
-		Skip("Skip this test as it is failing on CI")
+		killKubectlCmd := exec.Command("pkill", "-9", "kubectl")
+		_ = killKubectlCmd.Run()
```
Comment (MortalHappiness) [inline kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go:35]: Why?

**Comment by MortalHappiness** [comment]
Could you also create another "[DO NOT MERGE]" draft PR and run it more than 5 times and make sure all tests pass? Just like what I did in https://github.com/ray-project/kuberay/pull/3116#pullrequestreview-2646276133

File: kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go (hunk 2 above)
Comment (owenowenisme) [reply kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go:35]: > ## Why are these changes needed?
> There are 2 reason make the test fail.
> 
> * There are some kubectl process occupied the 8265 port that is required by the kubectl job submit. But for the independence of tests, we should not expect the test cause this problem to kill the process properly every time, so added the pkill kubectl before running kubectl job submit test.
> * The ray is not installed on build kite env, so modified the setup-env.sh to install.

Comment (MortalHappiness) [reply kubectl-plugin/test/e2e/kubectl_ray_job_submit_test.go:35]: We should also example which tests occupies this port. This can be done in follow-up PRs.

File: .buildkite/setup-env.sh [hunk 3]
```diff
@@ -32,7 +32,7 @@ apt-get update
 apt-get install -y python3.11 python3-pip
 
 # Install requirements
-pip install --break-system-packages ray==2.41.0 ray\[default\]==2.41.0
+pip install --break-system-packages ray[default]==2.41.0
```
Comment (MortalHappiness) [inline .buildkite/setup-env.sh:35]: Is it possible not to use the `--break-system-packages` flag?

Comment (owenowenisme) [reply .buildkite/setup-env.sh:35]: We could. But we will have to use venv.

**Comment by owenowenisme** [comment]
https://buildkite.com/ray-project/ray-ecosystem-ci-kuberay-ci/builds?branch=owenowenisme%3Apr%2F3124%2Fci-test
Run 5 tests. Please ignore the oldest one, it is not related to this.

**Review by MortalHappiness — APPROVED** [review]

**Review by kevin85421 — APPROVED** [review]
