### PR TITLE
[Bug] Modification of nameOverride will cause label selector mismatch for head node

### LINKED ISSUE #571: [Bug] Modification of nameOverride will cause label selector mismatch for head node
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

As mentioned in #495 and #530, the value of [nameOverride](https://github.com/ray-project/kuberay/blob/master/helm-chart/ray-cluster/values.yaml#L10) needs to be hardcoded with the value "kuberay" to avoid the mismatch between head pod and head service.

### Reproduction script

See #495.

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

As mentioned in https://github.com/ray-project/kuberay/issues/495 and https://github.com/ray-project/kuberay/pull/530, the value of [nameOverride](https://github.com/ray-project/kuberay/blob/master/helm-chart/ray-cluster/values.yaml#L10) needs to be hardcoded with the value "kuberay" to avoid the mismatch between head pod and head service.

The value of `app.kubernetes.io/name` in the head pod's labels is same as `app.kubernetes.io/name` specified in `RayCluster.Spec.HeadGroupSpec.Template.ObjectMeta.Labels` of RayCluster custom resource YAML file. See the function `labelPod` in [pod.go](https://github.com/ray-project/kuberay/blob/38ac168e1112379fef7022a97fd78a644e3072f3/ray-operator/controllers/ray/common/pod.go#L486) for more details.

`RayCluster.Spec.HeadGroupSpec.Template.ObjectMeta.Labels["app.kubernetes.io/name"]` is controlled by the value of `nameOverride` in helm chart.

However, the value of `app.kubernetes.io/name` in the head pod service's selector is hardcoded with the constant variable `ApplicationName` (= "kuberay")

## Related issue number
closes #571 
#495 
#530

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

```bash
# Step1: Clone my repo and checkout to `nameOverride` branch
# Step2: Build Docker image
# Step3: Update image of kuberay-operator chart
# Step4: Update `nameOverride` in ray-cluster chart from "kuberay" to "aaaaaaaaaa"
# Step5: Install kuberay-operator
cd helm-chart/kuberay-operator
helm install kuberay-operator .

# Step6: Install raycluster custom resource
cd helm-chart/ray-cluster
helm install ray-cluster .

# Step7: Set up port-forwarding
kubectl port-forward svc/ray-cluster-aaaaaaaaaa-head-svc 8265:8265

# Step8: Submit a simple job
ray job submit --address http://localhost:8265 -- python -c "import ray; ray.init(); print(ray.cluster_resources())"
```

### Check head node service
* `kubectl describe svc/ray-cluster-aaaaaaaaaa-head-svc`

* Without this PR: 
```
Selector: app.kubernetes.io/created-by=kuberay-operator,app.kubernetes.io/name=kuberay,ray.io/cluster=ray-cluster-aaaaaaaaaa,ray.io/identifier=ray-cluster-aaaaaaaaaa-head,ray.io/node-type=head
```
  * With this PR:
```
Selector: app.kubernetes.io/created-by=kuberay-operator,app.kubernetes.io/name=aaaaaaaaaa,ray.io/cluster=ray-cluster-aaaaaaaaaa,ray.io/identifier=ray-cluster-aaaaaaaaaa-head,ray.io/node-type=head
```

### CODE REVIEW

File: ray-operator/controllers/ray/common/service_test.go [hunk 1]
```diff
@@ -78,4 +78,29 @@ func TestBuildServiceForHeadPod(t *testing.T) {
...
 	}
+
+	actualResult = svc.Spec.Selector[KubernetesApplicationNameLabelKey]
+	expectedResult = ApplicationName
+	if !reflect.DeepEqual(expectedResult, actualResult) {
+		t.Fatalf("Expected `%v` but got `%v`", expectedResult, actualResult)
+	}
+}
+
+func TestBuildServiceForHeadPodWithDefaultLabel(t *testing.T) {
```
Comment (DmitriGekhtman) [inline ray-operator/controllers/ray/common/service_test.go:89]: Maybe something like `TestBuildServiceForHeadPodWithAppNameLabel`, since it's testing using a non-default ApplicationName Label?

File: ray-operator/controllers/ray/common/service_test.go [hunk 2]
```diff
@@ -78,4 +78,29 @@ func TestBuildServiceForHeadPod(t *testing.T) {
...
+	svc, err := BuildServiceForHeadPod(*instanceWithWrongSvc, labels)
+	assert.Nil(t, err)
+
+	actualResult := svc.Spec.Selector[KubernetesApplicationNameLabelKey]
+	expectedResult := "testname"
+	if !reflect.DeepEqual(expectedResult, actualResult) {
+		t.Fatalf("Expected `%v` but got `%v`", expectedResult, actualResult)
+	}
+
+	actualLength := len(svc.Spec.Selector)
```
Comment (DmitriGekhtman) [inline ray-operator/controllers/ray/common/service_test.go:101]: Could you add a brief comment explaining this branch of test logic?
(for example, mention that 5 is the number of default labels, and that we're checking that we've correctly modified the app name label without adding any extra labels)

**Review by DmitriGekhtman — COMMENTED** [review]
This makes sense to me -- I left some minor nits about test documentation.

If you haven't yet, could you test this out manually? You could do that by building an operator image with the changes, deploying with a non-default label, and making sure the worker pod connects to the cluster successfully.

**Comment by DmitriGekhtman** [comment]
> This makes sense to me -- I left some minor nits about test documentation.
> 
> If you haven't yet, could you test this out manually? You could do that by building an operator image with the changes, deploying with a non-default label, and making sure the worker pod connects to the cluster successfully.

Sorry, I see you've already done that.

**Review by DmitriGekhtman — APPROVED** [review]

File: ray-operator/controllers/ray/common/service_test.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/common/service_test.go]: Updated.

File: ray-operator/controllers/ray/common/service_test.go (hunk 2 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/common/service_test.go:101]: Updated.
