### PR TITLE
fix: only filter RayCluster events for reconciliation

### LINKED ISSUE #872: [Bug] Pod updates should trigger RayCluster reconciliation
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

See https://github.com/ray-project/kuberay/pull/850#issuecomment-1368534811 and related comments on that PR.

Currently, pod state changes don't trigger cluster reconciliation. This is due to an event filter: https://github.com/ray-project/kuberay/blob/633ff6375099b2737db4c74a51c31028d2e54bc3/ray-operator/controllers/ray/raycluster_controller.go#L803

We should not filter out pod status changes, but continue to filter out RayCluster status changes. We should take care to avoid reconciling in a tight loop, because `instance.Status.LastUpdateTime` is updated at each reconciliation.

### Reproduction script

Same reproduction as in https://github.com/ray-project/kuberay/issues/845.  That issue will soon be closed by https://github.com/ray-project/kuberay/pull/850 using a separate fix (always reconciling every 60 seconds), but the present issue is still valid. This issue will fix the up to 60s delay between the cluster being ready and the Ray Job being submitted (this is triggered by the next periodic reconcile).

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by davidxia**
#639 accidentally applied event filters for child resources Pods and Services. This change does not filter Pod or Service related events. This means Pod updates will trigger RayCluster reconciliation.

closes #872

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -799,8 +800,12 @@ func (r *RayClusterReconciler) buildWorkerPod(instance rayiov1alpha1.RayCluster,
 // SetupWithManager builds the reconciler.
 func (r *RayClusterReconciler) SetupWithManager(mgr ctrl.Manager, reconcileConcurrency int) error {
 	b := ctrl.NewControllerManagedBy(mgr).
-		For(&rayiov1alpha1.RayCluster{}).Named("raycluster-controller").
-		WithEventFilter(predicate.Or(predicate.GenerationChangedPredicate{}, predicate.LabelChangedPredicate{}, predicate.AnnotationChangedPredicate{})).
+		Named("raycluster-controller").
+		For(&rayiov1alpha1.RayCluster{}, builder.WithPredicates(predicate.Or(
```
Comment (davidxia) [inline ray-operator/controllers/ray/raycluster_controller.go:804]: Based on [this code snippet](https://stackoverflow.com/a/71649836/553994). I couldn't find a way to test this since I don't know how to force a change to a Pod's status.

Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go:804]: There may be a better way, but one manual test would be the script at the bottom of the PR description here https://github.com/ray-project/kuberay/pull/850:
The head pod naturally changes from PENDING -> RUNNING.  Without that PR, the cluster doesn't reconcile upon this status change, so the job never gets submitted.  (With that PR, it would reconcile every 60 seconds.)

With your PR, job would get submitted as soon as the cluster was ready.

```
      # This script is used to rebuild the KubeRay operator image and load it into the Kind cluster. 
# Step 0: Delete the existing Kind cluster
kind delete cluster 

# Step 1: Create a Kind cluster
kind create cluster --image=kindest/node:v1.24.0

# Step 2: Modify KubeRay source code
# For example, add a log "Hello KubeRay" in the function `Reconcile` in `raycluster_controller.go`.

# Step 3: Build a Docker image
#         This command will copy the source code directory into the image, and build it.
# Command: IMG={IMG_REPO}:{IMG_TAG} make docker-build
IMG=kuberay/operator:nightly make docker-build

# Step 4: Load the custom KubeRay image into the Kind cluster.
# Command: kind load docker-image {IMG_REPO}:{IMG_TAG}
kind load docker-image kuberay/operator:nightly

# Step 5: Keep consistency
# If you update RBAC or CRD, you need to synchronize them.
# See the section "Consistency check" for more information.

# Step 6: Install KubeRay operator with the custom image via local Helm chart
# (Path: helm-chart/kuberay-operator)
# Command: helm install kuberay-operator --set image.repository={IMG_REPO} --set image.tag={IMG_TAG} .
helm install kuberay-operator --set image.repository=kuberay/operator --set image.tag=nightly ~/kuberay/helm-chart/kuberay-operator

# Step 7: Submit a RayJob
kubectl apply -f config/samples/ray_v1alpha1_rayjob.yaml   

# Step 8: Check the status of the pods
watch kubectl get pods

# When the pods are ready, check `kubectl logs` to see that the job has status SUCCEEDED
```

**Comment by architkulkarni** [comment]
Nice catch, it sounds like this was a pretty subtle issue. I didn't quite understand how the code change works, any chance you could add more detail here? Somehow `WithPredicates` doesn't apply the filters to child resources, but `EventFilter` does?

**Comment by architkulkarni** [comment]
Also, I heard that one reason the filter was added originally was to prevent reconciling in a tight loop, because `instance.Status.LastUpdateTime` is updated at each reconcile (@brucez-anyscale may have more context here): https://github.com/ray-project/kuberay/blob/9d50cbd5d39e118114f2b3f2d0a7a9dcf560b8e1/ray-operator/controllers/ray/raycluster_controller.go#L885

Would that issue be reintroduced with this PR?

**Comment by davidxia** [comment]
This change only applies the predicates to the RayCluster resources and not all watched resources like Pods and Services. The original bug won't be introduced. @architkulkarni would you be able to test out this change?

**Comment by architkulkarni** [comment]
Sure, I'll run a manual test.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:804]: I agree the best way to test this is by verifying that it fixes the RayJob issue!

Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:804]: cc @sihanwang41 we probably want to make the same adjustment to the RayService controller --
I remember you asked if there was a difference between the "event filter" and "predicate" arrangement -- we figured there wasn't a difference and went with "event filter"

Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:804]: Also, ideally we should add a unit test for this (should be possible to follow the pattern of one of the existing tests)

Comment (davidxia) [reply ray-operator/controllers/ray/raycluster_controller.go:804]: @DmitriGekhtman should the unit test be added to [raycluster_controller_test.go](https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/raycluster_controller_test.go)? There's a test there check that the [controller recreates a deleted worker Pod](https://github.com/ray-project/kuberay/blob/2600854c61673f2b7da9fe2b54c8220468c1a013/ray-operator/controllers/ray/raycluster_controller_test.go#L193-L208). This test currently passes on master without this change. Is this expected? I guess globalPredicates don't filter out deletion events of owned resources?

If so, I'm thinking we can write a test that creates an event on a child resource that's currently filtered out by the globalPredicates like a Pod status change. Then we check if the RayCluster's `.status.lastUpdateTime` is updated? If this sounds good, any ideas on the test code to write to force a Pod status change that will currently fail when run against master branch?

I also updated `rayservice_controller.go`.

**Comment by architkulkarni** [comment]
The manual test passed (confirmed that the job didn't hang.) Also I checked the logs and confirmed that reconciling wasn't happening in a tight loop.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:804]: It's expected that the test passes -- the current problem is that pod status changes are ignored.
I think it should be possible to use the machinery of that test to verify that RayCluster status.state transitions to Ready within half a second of all managed pods transitioning to Running.

Comment (davidxia) [reply ray-operator/controllers/ray/raycluster_controller.go:804]: Thanks, added a test. Lmk how it looks

Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/raycluster_controller.go:816]: looks good

**Review by DmitriGekhtman — APPROVED** [review]
Looks good -- could you push an empty commit to re-trigger the CI?

**Review by kevin85421 — APPROVED** [review]
Good catch! LGTM.

**Comment by kevin85421** [comment]
@davidxia would you mind checking the error message of CI? The new unit test fails.

**Comment by davidxia** [comment]
Thanks

```
• Failure [0.000 seconds]
Inside the default namespace
/home/runner/work/kuberay/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:46
  When creating a raycluster
  /home/runner/work/kuberay/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:[131](https://github.com/ray-project/kuberay/actions/runs/4006247114/jobs/6881074875#step:9:132)
    cluster's .status.state should be updated to 'ready' [It]
    /home/runner/work/kuberay/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:160

    Expected
        <v1alpha1.ClusterState>: unhealthy
    to equal
        <v1alpha1.ClusterState>: ready

    /home/runner/work/kuberay/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:164
```

I added debug logs to see why the start params are invalid.

**Comment by davidxia** [comment]
@kevin85421 The debug logs I added in last commit don't show up in the failing test logs. Do you know how I can debug further? I think it's because the ray start params are invalid.

**Comment by DmitriGekhtman** [comment]
> @kevin85421 The debug logs I added in last commit don't show up in the failing test logs. Do you know how I can debug further? I think it's because the ray start params are invalid.

Seems we need to access the logs of the operator in the context of the test.
Or try copying rayStartParams from an example cr.

**Comment by kevin85421** [comment]
> @kevin85421 The debug logs I added in last commit don't show up in the failing test logs. Do you know how I can debug further? I think it's because the ray start params are invalid.

I can reproduce this bug on my laptop by:

```sh
# path: kuberay/ray-operator
make test
```

There are three reasons to make this test fail.

### Reason 1
https://github.com/ray-project/kuberay/blob/db0ee96eb3fff8a38734fdcbffc1a02cb0a6c4d2/ray-operator/controllers/ray/raycluster_controller_test.go#L65
`object-store-memory` is defined, but the `RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE` (i.e. `AllowSlowStorageEnvVar`) environment variable does not exist. Hence, the function `ValidateHeadRayStartParams` will return false. We can either removing `object-store-memory` or adding `RAY_OBJECT_STORE_ALLOW_SLOW_STORAGE` to solve this bug.

### Reason 2

https://github.com/ray-project/kuberay/blob/db0ee96eb3fff8a38734fdcbffc1a02cb0a6c4d2/ray-operator/controllers/ray/raycluster_controller_test.go#L151-L158

The new test is just after the test "should create 3 workers". However, the worker Pods are highly possible to be in pending rather than running. Hence, the function `CheckAllPodsRunnning` will return false. You can print the Pods' states by the following code:

```go
It("cluster's .status.state should be updated to 'ready'", func() {
	listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"})
	for _, aPod := range workerPods.Items {
		fmt.Printf("Pod Phase: %v\n", aPod.Status.Phase)
	}
	Eventually(
		getResourceFunc(ctx, client.ObjectKey{Name: myRayCluster.Name, Namespace: "default"}, myRayCluster),
		time.Second*60, time.Millisecond*500).Should(BeNil(), "My myRayCluster  = %v", myRayCluster.Name)
	Expect(myRayCluster.Status.State).Should(Equal(rayiov1alpha1.Ready))
})
```

Maybe the test case logic should be:

```
It("cluster's .status.state should be updated to 'ready'", func() {
  // Step 1: Wait for all Pods becoming running.
  // Step 2: Check myRayCluster.Status.State
})
```

### Reason 3
The following change may be unnecessary.
`Eventually(..., time.Millisecond*500)` -> `Eventually(...,time.Second*15, time.Millisecond*500)`

File: ray-operator/controllers/ray/raycluster_controller_test.go [hunk 2]
```diff
@@ -62,7 +63,6 @@ var _ = Context("Inside the default namespace", func() {
 					"port":                "6379",
 					"object-manager-port": "12345",
 					"node-manager-port":   "12346",
-					"object-store-memory": "100000000",
```
Comment (davidxia) [inline ray-operator/controllers/ray/raycluster_controller_test.go:65]: need to remove for controller to think ray start params are valid

File: ray-operator/controllers/ray/raycluster_controller_test.go [hunk 3]
```diff
@@ -190,9 +189,39 @@ var _ = Context("Inside the default namespace", func() {
...
+			for _, headPod := range headPods.Items {
+				Expect(headPod.Status.Phase).Should(Equal(corev1.PodRunning))
+			}
+		})
+
+		It("cluster's .status.state should be updated to 'ready' shortly after all Pods are Running", func() {
+			Eventually(
+				getClusterState(ctx, "default", myRayCluster.Name),
+				time.Second*(common.RAYCLUSTER_DEFAULT_REQUEUE_SECONDS+5), time.Millisecond*500).Should(Equal(rayiov1alpha1.Ready))
+		})
```
Comment (davidxia) [inline ray-operator/controllers/ray/raycluster_controller_test.go:220]: the important part

File: ray-operator/controllers/ray/suite_test.go [hunk 4]
```diff
@@ -79,6 +81,7 @@ var _ = BeforeSuite(func(done Done) {
 	Expect(k8sClient).ToNot(BeNil())
 
 	// Suggested way to run tests
+	os.Setenv(common.RAYCLUSTER_DEFAULT_REQUEUE_SECONDS_ENV, "10")
```
Comment (davidxia) [inline ray-operator/controllers/ray/suite_test.go:84]: decrease requeue delay to make test faster

File: ray-operator/controllers/ray/raycluster_controller_test.go [hunk 5]
```diff
@@ -190,9 +189,39 @@ var _ = Context("Inside the default namespace", func() {
...
+				headPod.Status.Phase = corev1.PodRunning
+				Expect(k8sClient.Status().Update(ctx, &headPod)).Should(BeNil())
+			}
+			Consistently(
+				listResourceFunc(ctx, &headPods, headFilterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*5, time.Millisecond*500).Should(Equal(1), fmt.Sprintf("headGroup %v", headPods.Items))
+			for _, headPod := range headPods.Items {
+				Expect(headPod.Status.Phase).Should(Equal(corev1.PodRunning))
+			}
+		})
```
Comment (davidxia) [inline ray-operator/controllers/ray/raycluster_controller_test.go:214]: Need to manually update Pod statuses otherwise they'll always be Pending. [envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/envtest) doesn't create a full K8s cluster. It's only the control plane. There's no container runtime or any other K8s controllers. So Pods are created, but no controller updates them from Pending to Running.

> setting up and starting an instance of etcd and the Kubernetes API server, without kubelet, controller-manager or other components 

https://book.kubebuilder.io/reference/envtest.html

File: ray-operator/controllers/ray/raycluster_controller_test.go [hunk 6]
```diff
@@ -190,9 +190,39 @@ var _ = Context("Inside the default namespace", func() {
 				time.Second*15, time.Millisecond*500).Should(BeNil(), "autoscaler RoleBinding = %v", rbName)
 		})
 
+		It("should be able to update all Pods to Running", func() {
+			for _, workerPod := range workerPods.Items {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller_test.go:194]: Would you mind adding comments to explain the reason for updating Pod statuses manually?

File: ray-operator/controllers/ray/raycluster_controller_test.go (hunk 5 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller_test.go:215]: Cool!

**Review by kevin85421 — APPROVED** [review]
LGTM! Thank you for this contribution!

File: ray-operator/controllers/ray/raycluster_controller_test.go (hunk 6 above)
Comment (davidxia) [reply ray-operator/controllers/ray/raycluster_controller_test.go]: done

**Comment by kevin85421** [comment]
Merge this PR. The CI failure is due to #852.
