### PR TITLE
 Inject the --block option to ray start command automatically

### LINKED ISSUE #915: [Feature] Inject the --block option to ray start command automatically
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/kuberay/pull/675#issuecomment-1302670536

With `--block`, when the ray process crashes, the KubeRay operator can detect the unhealthy condition in a short time because the container will exit immediately. Without `--block`, the unhealthy condition can still be detected by both readiness and liveness probes, but it may take more time to detect it.

### Use case

_No response_

### Related issues

#675 
#912 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Yicheng-Lu-llll**
## Why are these changes needed?
 
This PR:
1. Inject the `--block` option to the ray start command automatically if the user has not set the `-- block` option. See https://github.com/ray-project/kuberay/pull/675 and https://github.com/ray-project/kuberay/pull/912#issuecomment-1436393712
2.  According to [ray start options document](https://docs.ray.io/en/latest/cluster/cli.html#ray-start), there are many parameters that the user should be able to set in the format `'parameters': 'true'` or `'parameters': 'false'` (e.g `--block`, `--disable-usage-stats`) in `rayStartParams`. However, kuberay can not handle(will fail to run all the pods) if the user set 'parameters': 'false' in rayStartParams. This PR enables the user to set a 'false' value.

**Prove that Without --block, it may take a much longer time to detect the unhealthy condition and restart the pod:**

You can find [without_block.yaml](https://github.com/Yicheng-Lu-llll/kuberay/blob/tmp/without_block.yaml) and [with_block.yaml](https://github.com/Yicheng-Lu-llll/kuberay/blob/tmp/with_block.yaml) here.
```sh
# without block case:
# Create head and worker pod
# Note, we need to enable Fault Tolerance. readiness probe and Liveness probe will only be installed if Fault Tolerance is enabled. 
# See https://github.com/ray-project/kuberay/blob/master/docs/guidance/gcs-ft.md
kubectl apply -f /home/lyc/without_block.yaml
#  ulimit -n 65536; ray start  --num-cpus=1  --metrics-export-port=8080  --address=raycluster-external-redis-head-svc:6379  && sleep infinity
#  ulimit -n 65536; ray start --head  --num-cpus=1  --metrics-export-port=8080  --dashboard-host=0.0.0.0  && sleep infinity

# kill gcs server, the pod will continue running.
# Note, you can also do ray stop -f to kill all the ray processes.
# The pod will always continue running due to "sleep infinity" process.
date && kubectl exec -it $(kubectl get pods -o=name | grep head) --  pkill gcs_server
# list all event based on the happening time and see when the liveness probe fail
kubectl get events --sort-by='{.metadata.creationTimestamp}' -o yaml | grep -E 'message|firstTimestamp' 
# get pod's last exit time
kubectl get  $(kubectl get pods -o=name | grep head) -o yaml | grep finishedAt
# get pod's restart time
kubectl get  $(kubectl get pods -o=name | grep head) -o yaml | grep startedAt


# I have run the above three times, here is the result:

#   kill gcs server at :                   Sun Feb 26 04:59:39 UTC 2023
#   liveness probe/readness probe fail at: "2023-02-26T05:01:41Z"
#   pod finishedAt :                       "2023-02-26T05:04:04Z"
#   pod restartedAt:                       "2023-02-26T05:04:04Z"

#   kill gcs server at :                   Sun Feb 26 05:23:51 UTC 2023
#   liveness probe/readness probe fail at: "2023-02-26T05:25:54Z"
#   pod finishedAt :                       "2023-02-26T05:28:17Z"
#   pod restartedAt:                       "2023-02-26T05:28:17Z"

#   kill gcs server at :                   Sun Feb 26 05:38:52 UTC 2023
#   liveness probe/readness probe fail at: "2023-02-26T05:40:56Z"
#   pod finishedAt :                       "2023-02-26T05:43:19Z"
# pod restartedAt:                         "2023-02-26T05:43:19Z"
```

```sh
# with block case:
# Create head and worker pod
kubectl apply -f /home/lyc/with_block.yaml
# 'ulimit -n 65536; ray start  --address=raycluster-complete-head-svc:6379  --metrics-export-port=8080  --num-cpus=1  --memory=1000000000  --block '
# 'ulimit -n 65536; ray start --head  --num-cpus=1  --memory=2000000000  --block  --dashboard-host=0.0.0.0  --metrics-export-port=8080 '

# kill all ray processes, the pod will exit immediately.
date && kubectl exec -it $(kubectl get pods -o=name | grep head) --  ray stop -f
# get pod's last exit time
kubectl get  $(kubectl get pods -o=name | grep head) -o yaml | grep finishedAt
# get pod's restart time
kubectl get  $(kubectl get pods -o=name | grep head) -o yaml | grep startedAt


# I have run the above three times, here is the result:

#   kill all ray processes at:   Sun Feb 26 04:44:50 UTC 2023
#   pod finishedAt :             "2023-02-26T04:44:53Z"
#   pod restartedAt:             "2023-02-26T04:44:53Z"

#   kill all ray processes at:   Sun Feb 26 04:51:07 UTC 2023
#   pod finishedAt :             "2023-02-26T04:51:09Z"
#   pod restartedAt:             "2023-02-26T04:51:10Z"

#   kill all ray processes at:   Sun Feb 26 04:55:09 UTC 2023
#   pod finishedAt :             "2023-02-26T04:55:11Z"
#   pod restartedAt:             "2023-02-26T04:55:12Z"
```

To summarize the result, In a single, healthy node environment:
 - with the -- block option, the pod will restart immediately after the ray process crash. 
 - Without -- block option, 
    - the liveness probe/readiness probe will fail **129.3 seconds** after killing the ray processes. 
    - The pod will restart **143 seconds** after the liveness probe/readiness probe fail.

**Questions:**

**Should we enforce adding the `--block` option (even if the user set `'block': 'false'`  in ` rayStartParams `)?**'

Because not every user will enable [Fault Tolerance](https://github.com/ray-project/kuberay/blob/master/docs/guidance/gcs-ft.md). But the readiness probe and Liveness probe will only be installed if Fault Tolerance is enabled. That is,  if running without Fault Tolerance and ray processes somehow crash, kuberay will never detect the failure and restart the pod for the user. 

## Related issue number
Closes #915 

## Checks

I've made sure the tests are passing in various situations:
 -  `'block' : 'false'`  in `rayStartParams`
59a160e73483e85a7812d98eeabfb1c

 - `'block' : 'true'`    in `rayStartParams`
 642bab545267313905186747f46a092

 -  `block` not set.
497221a8428c87458669903e4291249

- Test convertParamMap
```golang

func TestConvertParamMap(t *testing.T) {
	rayStartParams := map[string]string{
		"booleanOptionsTrue":  "true",
		"booleanOptionsFalse": "false",
		"ParameterOptions":    "arguments",
		"log-color":           "false",
		"include-dashboard":   "true",
	}
	s := convertParamMap(rayStartParams)
	// s will be:
       //  --booleanOptionsTrue  --ParameterOptions=arguments  --log-color=false  --include-dashboard=true 

}

```

### CODE REVIEW

File: ray-operator/controllers/ray/common/pod.go [hunk 1]
```diff
@@ -706,11 +711,16 @@ func concatenateContainerCommand(nodeType rayiov1alpha1.RayNodeType, rayStartPar
 
 func convertParamMap(rayStartParams map[string]string) (s string) {
 	flags := new(bytes.Buffer)
-	nonFlagParams := []string{"log-color", "include-dashboard"}
+	// NonFlagParams with a value of true or false.
+	specialNonFlagParams := []string{"log-color", "include-dashboard"}
 	for k, v := range rayStartParams {
-		if strings.ToLower(v) == "true" && !utils.Contains(nonFlagParams, k) {
-			fmt.Fprintf(flags, " --%s ", k)
+		if utils.Contains([]string{"true", "false"}, strings.ToLower(v)) && !utils.Contains(specialNonFlagParams, k) {
```
Comment (Yicheng-Lu-llll) [inline ray-operator/controllers/ray/common/pod.go:717]: handle the case if user sets rayStartParams["XXX"] = "false". XXX can be `block` option.

File: ray-operator/controllers/ray/common/pod.go [hunk 2]
```diff
@@ -706,11 +711,16 @@ func concatenateContainerCommand(nodeType rayiov1alpha1.RayNodeType, rayStartPar
 
 func convertParamMap(rayStartParams map[string]string) (s string) {
 	flags := new(bytes.Buffer)
-	nonFlagParams := []string{"log-color", "include-dashboard"}
+	// NonFlagParams with a value of true or false.
```
Comment (kevin85421) [inline ray-operator/controllers/ray/common/pod.go:714]: Explain the definitions of NonFlagParams and FlagParams.

**Review by kevin85421 — COMMENTED** [review]
1. Add an unit test

2. Open an issue to remove `--block` from YAML files after 0.5.0, and update https://github.com/ray-project/kuberay/issues/940.

**Review by kevin85421 — APPROVED** [review]
LGTM! 

Approve this PR without running by myself because: (1) This PR has enough unit tests (2) The screenshots in the PR description are reliable.

**Comment by kevin85421** [comment]
* Without fault tolerance
  * Case 1 (without `--block`): Pods cannot detect errors, including `pkill gcs_server` and `ray stop -f`, forever.
  * Case 2 (with `--block`): Pods will be terminated after `gcs_rpc_server_reconnect_timeout_s` seconds (default: 60s).

* With fault tolerance
  * Case 1 (without `--block`): Pods can detect errors by the healthiness probe.
  * Case 2 (with `--block`): Pods will be terminated after `gcs_rpc_server_reconnect_timeout_s` seconds (default: 60s) or detect errors by the healthiness probe.
