### PR TITLE
[Bug][RayJob] Check dashboard readiness before creating job pod (#1381)

### LINKED ISSUE #1381: [Bug] [RayJob] First job pod sometimes fails to connect to Ray cluster
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Sometimes after submitting a `RayJob`, we see that the first job submission pod has failed:

```text
NAME                                        READY   STATUS      RESTARTS   AGE
kuberay-operator-7447d85d58-89nhg           1/1     Running     0          5m44s
rayjob-sample-hwbgg                         0/1     Error       0          2m55s
rayjob-sample-raycluster-vkbxr-head-4pnd5   1/1     Running     0          5m12s
rayjob-sample-w5nvf                         0/1     Completed   0          2m48s
```

In the logs for the errored pod, we see

```
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 248, in _check_connection_and_version
    self._check_connection_and_version_with_url(min_version, version_error_message)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 278, in _check_connection_and_version_with_url
    raise ConnectionError(
ConnectionError: Failed to connect to Ray at address: http://rayjob-sample-raycluster-vkbxr-head-svc.default.svc.cluster.local:8265.
```

The pod gets retried, so the RayJob itself eventually succeeds, but this is still unexpected because the RayJob controller is supposed to wait for the cluster to be ready before submitting the job.

### Reproduction script

`kubectl apply -f config/samples/ray_v1alpha1_rayjob.yaml`

### Anything else
[logs.zip](https://github.com/ray-project/kuberay/files/12490160/logs.zip)

It only happens sometimes.  (5-20% of the time?)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by rueian**
## Why are these changes needed?

As discussed in the https://github.com/ray-project/kuberay/issues/1381#issuecomment-1720721651, I added a readiness check to the dashboard server as a workaround before the release of KubeRay 1.0.0.

I didn't add new tests for these changes because it was hard to mock the `rayDashboardClient` accordingly to simulate the target behavior. But I did make sure these changes can pass the current tests.

To further add tests for these, I would suggest adding mocking functionalities into the `FakeRayDashboardClient` first. For example:

```go
func (r *FakeRayDashboardClient) GetJobInfo(ctx context.Context, jobId string) (*RayJobInfo, error) {
	return r.GetJobInfoMock(ctx, jobId)
}

// setup mock
ts := time.Now()
r.GetJobInfoMock = func(ctx context.Context, jobId string) (*RayJobInfo, error) {
	if time.Since(ts) < time.Second*10 {
		return nil, errors.New("dashboard is not ready")
	}
	return nil, nil
}
```

## Related issue number

#1381

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 1]
```diff
@@ -200,6 +200,15 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
 	rayDashboardClient := utils.GetRayDashboardClientFunc()
 	rayDashboardClient.InitClient(clientURL)
 
+	// Check the dashboard readiness by checking the err return from rayDashboardClient.GetJobInfo.
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:203]: We do not need to send a request to check the dashboard's readiness in each reconciliation. We can only check it when no Kubernetes Job exists.

https://github.com/ray-project/kuberay/blob/6d5020fba579ca3296a20fc8ee6a6b809864690d/ray-operator/controllers/ray/rayjob_controller.go#L331

**Comment by kevin85421** [comment]
If you plan not to add tests here, would you mind doing some experiments with and without this PR to show that this PR actually relieves this situation?

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 1 above)
Comment (rueian) [reply ray-operator/controllers/ray/rayjob_controller.go]: I think line 331 is too far from the dashboard related code. Inserting readiness check there might be a little confusing. 

What about checking the readiness right before setting the `rayJobInstance.Status.DashboardURL`? And we don't check it again if `rayJobInstance.Status.DashboardURL` is set.

**Comment by rueian** [comment]
> If you plan not to add tests here, would you mind doing some experiments with and without this PR to show that this PR actually relieves this situation?

Actually, I have managed to add tests.

In order to test the situation, I have done:

1. Adding the `GetJobInfoMock` field, which is an `atomic.Pointer`, to the `FakeRayDashboardClient`
2. Introducing a new `WaitForDashboardReady` JobDeploymentStatus to test for.
3. Writing test cases to test the transition of the `WaitForDashboardReady` status and `rayJobInstance.Status.DashboardURL` before and after mocking.

In addition, the `go vet` complained about copying atomic value in `rayservice_controller_test.go` after adding the `GetJobInfoMock` mock field:

```
controllers/ray/rayservice_controller_test.go:656:9: return copies lock value: github.com/ray-project/kuberay/ray-operator/controllers/ray/utils.FakeRayDashboardClient contains sync/atomic.Pointer[func(_ context.Context, jobId string) (*github.com/ray-project/kuberay/ray-operator/controllers/ray/utils.RayJobInfo, error)] contains sync/atomic.noCopy
make: *** [vet] Error 1
```

Therefore, I have updated the `rayservice_controller_test.go` as well.

**Comment by rueian** [comment]
Hi @kevin85421,

As we discussed offline, I have added an `expected_job_pods = 1` check into the current end-to-end test to catch future bugs that are similar to those described in #1381.

In my own experience of running end-to-end tests on my laptop with and without the patch to check the readiness of the dashboard, I confirm that the `first job submission pod has failed` situation happened about ~20% of the time, like @architkulkarni said, without the patch. While with the patch, the situation never happened again.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 2]
```diff
@@ -194,12 +194,19 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
 			err = r.updateState(ctx, rayJobInstance, nil, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusWaitForDashboard, err)
 			return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
 		}
+		// Check the dashboard readiness by checking the err return from rayDashboardClient.GetJobInfo.
+		// Note that rayDashboardClient.GetJobInfo returns no error in the case of http.StatusNotFound.
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/rayjob_controller.go:198]: > Note that rayDashboardClient.GetJobInfo returns no error in the case of http.StatusNotFound.

A bit confused by this comment -- this means if we get http.StatusNotFound we'll proceed with the job submission? When does this situation happen?

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 3]
```diff
@@ -194,12 +194,19 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+		// This check is a workaround for https://github.com/ray-project/kuberay/issues/1381.
+		rayDashboardClient.InitClient(clientURL)
+		if _, err = rayDashboardClient.GetJobInfo(ctx, rayJobInstance.Status.JobId); err != nil {
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/rayjob_controller.go:201]: Out of curiosity why use getJobInfo(jobID)? The job hasn't been submitted yet, so I guess there won't be any jobInfo available yet.  Is this just an arbitrary HTTP request to make sure the server is working?

**Review by architkulkarni — APPROVED** [review]
Looks good to me, nice tests!  Will merge after @kevin85421's approval

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 3 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:201]: > Is this just an arbitrary HTTP request to make sure the server is working?

Yes. Can we conclude that the dashboard is ready for the `ray job submit` command if `GetJobInfo` succeeds?

Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:201]: Yeah, I think that's a fair conclusion

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: > When does this situation happen?

`http.StatusNotFound` is 404. We should not proceed with the job submission if the dashboard URL is 404 not found.

https://github.com/ray-project/kuberay/blob/92651545d9730904ae9cbe40c5c39e5803e6bb9d/ray-operator/controllers/ray/utils/dashboard_httpclient.go#L354-L356

Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: I see, so it sounds like the PR in its current state needs to be updated. 

Should we update the dashboard client to return an error in the case of 404, or should we check if the response is 404 on the job controller side?  

My guess is that updating it in the job controller will have fewer unexpected side effects, but it still seems a bit weird that the HTTP client returns `nil, nil` in this case.

Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: > Should we update the dashboard client to return an error in the case of 404?

This seems to be more make sense to me. What do you think?

Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: Yeah I think this makes more sense.  We should just check that it doesn't break anything for other callers, but I don't think it will

Comment (rueian) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: I think it is ok for GetJobInfo to return nil, nil since callers can check the NotFound situation by checking the first return value is nil or not, and they should always do.

With that in mind, returning NotFound as an error seems a little bit redundant.

Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: > I think it is ok for GetJobInfo to return nil, nil since callers can check the NotFound situation by checking the first return value is nil or not, and they should always do.

Yes, users can examine the first returned value, but it seems somewhat irregular not to throw an error when the retrieval of job information fails.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 3 above)
Comment (rueian) [reply ray-operator/controllers/ray/rayjob_controller.go:201]: Yes, it is just an arbitrary HTTP request to make sure the server is working.

So it is ok to go proceed with the job submission if we get 404 from the GetJobInfo here. That means the dashboard is working.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (rueian) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: Sure. Just note that some people may consider the NotFound as a successful result and I believe that is the reason why the original author chose to return nil err in the GetJobInfo.

Should I change its behavior in this PR? Or should I open another issue for it first?

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 3 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:201]: > So it is ok to go proceed with the job submission if we get 404 from the GetJobInfo here. That means the dashboard is working.

Does this imply that a 404 response will be returned if the JobID does not exist?

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: > Just note that some people may consider the NotFound as a successful result and I believe that is the reason why the original author chose to return nil err in the GetJobInfo.

If the function is `DeleteJobInfo`, it makes sense to interpret a 404 as a successful result, as the job may have been deleted by the previous reconciliation. However, I cannot conceive of any justification for deeming a 404 in GetJobInfo as success. Can you think of any specific reasons?

> Should I change its behavior in this PR? Or should I open another issue for it first?

I prefer not to include the change in this PR. We can open an issue to track the progress and discussion.

Comment (rueian) [reply ray-operator/controllers/ray/rayjob_controller.go:198]: > However, I cannot conceive of any justification for deeming a 404 in GetJobInfo as success. Can you think of any specific reasons?

It is just another standpoint of designing API behavior, regardless of API naming, saying "Hey, I have finished what you asked for successfully without any error. And the result is no result".

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 3 above)
Comment (rueian) [reply ray-operator/controllers/ray/rayjob_controller.go:201]: Maybe not. But a 404 response implies the dashboard server is up.

**Review by kevin85421 — APPROVED** [review]
LGTM! Thank you for the contribution! @rueian would you mind opening an issue for https://github.com/ray-project/kuberay/pull/1429#discussion_r1336690601?

**Comment by rueian** [comment]
> LGTM! Thank you for the contribution! @rueian would you mind opening an issue for [#1429 (comment)](https://github.com/ray-project/kuberay/pull/1429#discussion_r1336690601)?

Thanks! I opened here https://github.com/ray-project/kuberay/issues/1453
