### PR TITLE
refactor: Fix flaky tests by using RetryOnConflict

### LINKED ISSUE #902: [Bug] 409 conflict error may occur when updating cr in the test
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

If running `make test` several times, the following error may occur(409 error appears 14 times in 100 runs):
```



                Status: "Failure",
                Message: "Operation cannot be fulfilled on rayservices.ray.io \"rayservice-sample\": the object has been modified; please apply your changes to the latest version and try again",
                Reason: "Conflict",
                Details: {
                    Name: "rayservice-sample",
                    Group: "ray.io",
                    Kind: "rayservices",
                    UID: "",
                    Causes: nil,
                    RetryAfterSeconds: 0,
                },
                Code: 409,
```
From the [k8s api-conventions docuemnt](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency):

> Kubernetes leverages the concept of resource versions to achieve optimistic concurrency. All Kubernetes resources have a "resourceVersion" field as part of their metadata. This resourceVersion is a string that identifies the internal version of an object that can be used by clients to determine when objects have changed. When a record is about to be updated, its version is checked against a pre-saved value, and if it doesn't match, the update fails with a StatusConflict (HTTP status code 409).

**It is believed that this error is due to changes made by others(like another client) between the last Get and Update.** 

From  [k8s api-conventions docuemnt](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency):

> In the case of a conflict, the correct client action at this point is to GET the resource again, apply the changes afresh, and try submitting again.

It suggests using the retry strategy(though it emphasizes more on first reading and then writing.
**While it is doubtful to apply this strategy in the operator(may be better to just fail the update operation and let the decision be made in the next reconciliation), In my own view, it is good to use it in the test.**

**So, a possible solution(need to discuss) is to use RetryOnConflict for every update operation in the test.**

### How do others deal with Update?
1. client-go already has [a helper function: RetryOnConflict](https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict) and an[ example ](https://github.com/kubernetes/client-go/blob/master/examples/dynamic-create-update-delete-deployment/main.go#L118-L129) that use the above strategy.  RetryOnConflict will retry until the timeout or the error code is not 409.

2. [azure-databricks-operator](https://github.com/Azure/azure-databricks-operator/blob/265a0a8546293a5d52cdb8a98bac507ce0750cae/controllers/dbfsblock_controller_test.go#L106)(also [link](https://github.com/Azure/azure-databricks-operator/blob/0f722a710fea06b86ecdccd9455336ca712bf775/controllers/secretscope_controller_test.go#L216)) does in a normal way(no retry just call update and see if success).

### Reproduction script

 running `make test `several times.

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Yicheng-Lu-llll**
## Why are these changes needed?

In a previous [experiment](https://github.com/ray-project/kuberay/issues/894#issuecomment-1416892144), it was shown that 86 runs succeed, and 14 runs failed with the following errors：

```
[Fail] Inside the default namespace When creating a raycluster [It] should update a raycluster object 
/home/lyc/Desktop/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:279

[Fail] Inside the default namespace When creating a raycluster [It] should have only 1 running worker 
/home/lyc/Desktop/kuberay/ray-operator/controllers/ray/raycluster_controller_test.go:286

[Fail] Inside the default namespace When creating a rayservice [It] should perform a zero-downtime update after a code change. 
/home/lyc/Desktop/kuberay/ray-operator/controllers/ray/rayservice_controller_test.go:354

```
The above errors are all due to [409 conflict](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency):

- In previous PR #73, retryOnOldRevision is used in certain places to retry updat call if facing a 409 conflict error. According to the previous experiment, it is necessary to apply the retry strategy to more k8sClient.Update calls especially those causing the above errors.
- Compare retryOnOldRevision with [RetryOnConflict ](https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict), RetryOnConflict gives more advantages. It provides exponential backoff to avoid exhausting the apiserver.

So, two changes are made in this PR:
-   Replace retryOnOldRevision with [RetryOnConflict](https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict)
-   Apply [RetryOnConflict](https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict) to more k8sClient.Update calls.

If you have concerns about using RetryOnConflict to handle 409 conflict errors in testing or need some background information, see the below links :
- [k8s api-conventions document](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency) describe the client action in the case of a conflict
- The [ [link](https://github.com/kubernetes/client-go/blob/master/examples/dynamic-create-update-delete-deployment/main.go#L118-L129) [link ](https://github.com/kubernetes-sigs/kubebuilder/blob/master/testdata/project-v4-with-deploy-image/internal/controller/busybox_controller.go#L245-L248) ] show how they implement the retry strategy.
-  [Don’t Retry on Conflict section in this article ](https://medium.com/@timebertt/kubernetes-controllers-at-scale-clients-caches-conflicts-patches-explained-aa0f7a8b4332) and [comment ](https://github.com/kubernetes-sigs/kubebuilder/issues/3212#issuecomment-1426794273 ) suggests not to use retry strategy in controllers and explain why. (Note, there are concerns and shortages to using the retry strategy in controllers as described above, but they are not for testing)

## Related issue number

Closes #902

## Checks
In a 2-core CPU, 7 GB RAM VM (to simulate the github's standard Linux runner), I ran the test 100 times:

```sh
rootPath="/home/lyc/Desktop/lessFlasky/kuberay"
cd $rootPath/ray-operator
for i in {1..100};
        do echo "iteration ${i}";
        make test | tee /home/lyc/Desktop/tmp/log${i}
done
```

_**All pass with no error. The test is stable now.**_

### CODE REVIEW

File: ray-operator/controllers/ray/raycluster_controller_test.go [hunk 1]
```diff
@@ -266,17 +261,18 @@ var _ = Context("Inside the default namespace", func() {
...
-			*rep = 1
-			myRayCluster.Spec.WorkerGroupSpecs[0].Replicas = rep
-			myRayCluster.Spec.WorkerGroupSpecs[0].ScaleStrategy.WorkersToDelete = []string{podToDelete1.Name}
-
-			Expect(k8sClient.Update(ctx, myRayCluster)).Should(Succeed(), "failed to update test RayCluster resource")
+			err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
+				Eventually(
+					getResourceFunc(ctx, client.ObjectKey{Name: myRayCluster.Name, Namespace: "default"}, myRayCluster),
+					time.Second*9, time.Millisecond*500).Should(BeNil(), "My raycluster = %v", myRayCluster)
+				podToDelete1 := workerPods.Items[0]
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller_test.go:268]:
```suggestion
				podToDelete := workerPods.Items[0]
```

I will expect to see `podToDelete2` below if the variable name is `podToDelete1` here.

File: ray-operator/controllers/ray/raycluster_controller_test.go [hunk 2]
```diff
@@ -266,17 +261,18 @@ var _ = Context("Inside the default namespace", func() {
...
+				rep := new(int32)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller_test.go:269]: Is this temporary variable necessary?

File: ray-operator/controllers/ray/rayservice_controller_test.go [hunk 3]
```diff
@@ -299,17 +300,21 @@ var _ = Context("Inside the default namespace", func() {
...
 			// adding a scale strategy
-			Eventually(
-				getResourceFunc(ctx, client.ObjectKey{Name: myRayService.Name, Namespace: "default"}, myRayService),
-				time.Second*3, time.Millisecond*500).Should(BeNil(), "My myRayService  = %v", myRayService.Name)
+			err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
+				Eventually(
+					getResourceFunc(ctx, client.ObjectKey{Name: myRayService.Name, Namespace: "default"}, myRayService),
+					time.Second*3, time.Millisecond*500).Should(BeNil(), "My myRayService  = %v", myRayService.Name)
+
+				podToDelete1 := workerPods.Items[0]
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller_test.go:308]:
```suggestion
				podToDelete := workerPods.Items[0]
```

File: ray-operator/controllers/ray/rayservice_controller_test.go [hunk 4]
```diff
@@ -299,17 +300,21 @@ var _ = Context("Inside the default namespace", func() {
...
+				rep := new(int32)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller_test.go:309]: Same

File: ray-operator/controllers/ray/rayservice_controller_test.go [hunk 5]
```diff
@@ -348,10 +353,16 @@ var _ = Context("Inside the default namespace", func() {
 
 			// The cluster shouldn't switch until deployments are finished updating
 			fakeRayDashboardClient.SetServeStatus(generateServeStatus(metav1.NewTime(time.Now().Add(time.Duration(-5)*time.Minute)), "UPDATING"))
-			myRayService.Spec.RayClusterSpec.HeadGroupSpec.Template.Spec.Containers[0].Env[1].Value = "UPDATED_VALUE"
-			myRayService.Spec.RayClusterSpec.WorkerGroupSpecs[0].Template.Spec.Containers[0].Env[1].Value = "UPDATED_VALUE"
 
-			Expect(k8sClient.Update(ctx, myRayService)).Should(Succeed(), "failed to update test RayService resource")
+			err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
+				Eventually(
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller_test.go:358]: Can you explain why we need to `getResourceFunc` here?

Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayservice_controller_test.go:356]: Without getResourceFunc , if a 409 conflict happens, the resourceVersion we pass to API server during retry updating will never be updated and thus will never match the resourceVersion in the API server.

**Comment by Yicheng-Lu-llll** [comment]
Also update the usage of k8s.io/utils/pointer pkg. Some functions are deprecated and have new names. See [here](https://pkg.go.dev/k8s.io/utils/pointer#pkg-variables).

**Review by kevin85421 — APPROVED** [review]
LGTM. Thank you for the fix!
