### PR TITLE
RayJob Volcano Integration 

### LINKED ISSUE #1580: [Bug] RayJob Volcano integration
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When label RayJob with volcano scheduler and queue，ray operator crashes. Raycluster object would be created with no status. None of relevant cluster pod would be created. Rayjob is the sample job provided in[ examples](https://github.com/ray-project/kuberay/blob/master/ray-operator/config/samples/ray_v1alpha1_rayjob.yaml).  This happens in both v.0.6.0 and v.1.0.0
Tried same setup for RayCluster, everything works as expected.

The log from ray operator is the following:
```
INFO    controllers.RayCluster  reconcileHeadService    {"1 head service found": "rayjob-sample-raycluster-klhw9-head-svc"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ad868]

goroutine 786 [running]:
github.com/ray-project/kuberay/ray-operator/controllers/ray/batchscheduler/volcano.(*VolcanoBatchScheduler).DoBatchSchedulingOnSubmission(0xc001758368?, 0xc008176500)
        /workspace/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:55 +0xe8
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).reconcilePods(0xc0003054f0, {0x194d558, 0xc008536ed0}, 0xc008176500)
        /workspace/controllers/ray/raycluster_controller.go:550 +0x23f
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).rayClusterReconcile(0xc0003054f0, {0x194d558, 0xc008536ed0}, {{{0xc00812ee68, 0x8}, {0xc00814ab00, 0x1e}}}, 0xc008176500)
        /workspace/controllers/ray/raycluster_controller.go:340 +0xea8
github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayClusterReconciler).Reconcile(0xc0003054f0, {0x194d558, 0xc008536ed0}, {{{0xc00812ee68, 0x8}, {0xc00814ab00, 0x1e}}})
        /workspace/controllers/ray/raycluster_controller.go:158 +0x21e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00025edc0, {0x194d558, 0xc008536e10}, {{{0xc00812ee68?, 0x163d900?}, {0xc00814ab00?, 0x4045d4?}}})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x28b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00025edc0, {0x194d4b0, 0xc000d2f040}, {0x158c6a0?, 0xc006dccf00?})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x352
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00025edc0, {0x194d4b0, 0xc000d2f040})
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x31c
Reproduced steadily. Volcano works fine with RayCluster, it’s only problematic with RayJob.  (both v.6.0.0 and V.1.0.0) 
```

### Reproduction script

apiVersion: ray.io/v1alpha1
kind: RayJob
metadata:
  name: rayjob-sample
  labels:
    ray.io/scheduler-name: volcano
    volcano.sh/queue-name: kuberay-test-queue
...

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by win5923**
## Why are these changes needed?

- `RayJob Volcano support`: Adds Volcano scheduler support for RayJob CRD.
- `Gang scheduling`: Ensures Ray pods and submitter pod are scheduled together as a unit, preventing partial scheduling issues.

### E2E

1. Deploy the KubeRay operator with the batch-scheduler `volcano`:
```
./ray-operator/bin/manager -leader-election-namespace default -use-kubernetes-proxy -batch-scheduler=volcano
```
2. Create a RayJob with a head node (1 CPU + 2Gi of RAM), two workers (1 CPU + 1Gi of RAM each) and one submitter pod (0.5 CPU + 200Mi of RAM), for a total of 3500m CPU and 4296Mi of RAM
```
kubectl apply -f ray-operator/config/samples/ray-job.volcano-scheduler-queue.yaml
```

3. Add an additional RayJob with the same configuration but with a different name
```
sed 's/rayjob-sample-0/rayjob-sample-1/' ray-operator/config/samples/ray-job.volcano-scheduler-queue.yaml | kubectl apply -f-
```
4. All the pods stuck on pending for new RayJob
image

### PodGroup
- ray-rayjob-sample-0-pg:
```
$ k get podgroup ray-rayjob-sample-0-pg  -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2025-09-25T15:16:14Z"
  generation: 3
  name: ray-rayjob-sample-0-pg
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayJob
    name: rayjob-sample-0
    uid: e7652cc7-7593-4bd1-8ab1-bc043e62d7e5
  resourceVersion: "8779"
  uid: 84247ace-fcb5-4bce-9e18-b33e3769b941
spec:
  minMember: 3
  minResources:
    cpu: 3500m
    memory: 4296Mi
  queue: kuberay-test-queue
status:
  conditions:
  - lastTransitionTime: "2025-09-25T15:16:15Z"
    reason: tasks in gang are ready to be scheduled
    status: "True"
    transitionID: 6ccaf1db-e4f6-4cfa-ad71-f3abf039e03c
    type: Scheduled
  phase: Running
  running: 1
```
- ray-rayjob-sample-1-pg:
```
$ k get podgroup ray-rayjob-sample-1-pg  -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2025-09-25T15:17:54Z"
  generation: 2
  name: ray-rayjob-sample-1-pg
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayJob
    name: rayjob-sample-1
    uid: 3a98a4fe-19a5-4f36-9ba3-ebd252c5a267
  resourceVersion: "9080"
  uid: 0dde7617-6fa7-4867-97f6-2deb965170a1
spec:
  minMember: 3
  minResources:
    cpu: 3500m
    memory: 4296Mi
  queue: kuberay-test-queue
status:
  conditions:
  - lastTransitionTime: "2025-09-25T15:17:55Z"
    message: '3/3 tasks in gang unschedulable: pod group is not ready, 3 Pending,
      3 minAvailable; Pending: 3 Unschedulable'
    reason: NotEnoughResources
    status: "True"
    transitionID: cfb01bbc-c53b-42e4-9b02-8e56c46b8e6c
    type: Unschedulable
  phase: Pending
```

### Queue
```
$ k get queue kuberay-test-queue -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: Queue
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"scheduling.volcano.sh/v1beta1","kind":"Queue","metadata":{"annotations":{},"name":"kuberay-test-queue"},"spec":{"capability":{"cpu":4,"memory":"6Gi"},"weight":1}}
  creationTimestamp: "2025-09-25T15:17:54Z"
  generation: 2
  name: kuberay-test-queue
  resourceVersion: "9089"
  uid: 2690f4ca-aa29-4812-aa21-3d0228dfa271
spec:
  capability:
    cpu: 4
    memory: 6Gi
  parent: root
  reclaimable: true
  weight: 1
status:
  allocated:
    cpu: "3"
    memory: 4Gi
    pods: "3"
  reservation: {}
  state: Open
```

### Testing RayJob HTTPMode

```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sample-2
  labels:
    ray.io/scheduler-name: volcano
    volcano.sh/queue-name: kuberay-test-queue
spec:
  submissionMode: HTTPMode
```

```
$ k get podgroup ray-rayjob-sample-2-pg -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2025-09-25T15:20:15Z"
  generation: 2
  name: ray-rayjob-sample-2-pg
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayJob
    name: rayjob-sample-2
    uid: cc971b5a-347f-4e12-bc24-e6a65710f8d8
  resourceVersion: "9342"
  uid: e87b6399-74fa-4b42-9d88-3413c5b84865
spec:
  minMember: 3
  minResources:
    cpu: "3"
    memory: 4Gi
  queue: kuberay-test-queue
status:
  conditions:
  - lastTransitionTime: "2025-09-25T15:20:16Z"
    message: '3/3 tasks in gang unschedulable: pod group is not ready, 3 Pending,
      3 minAvailable; Pending: 3 Unschedulable'
    reason: NotEnoughResources
    status: "True"
    transitionID: c5c9e5c2-1bd4-4b0e-b405-78331ea6caf1
    type: Unschedulable
  phase: Pending
```

## Related issue number
Closes #1580

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [x] Unit tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 1]
```diff
@@ -25,6 +25,7 @@ import (
 
 const (
 	PodGroupName      = "podgroups.scheduling.volcano.sh"
```
Comment (win5923) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:28]: This variable is unused and can be removed i think.

**Review by troychiu — COMMENTED** [review]
I am wondering if we should separate this PR into two. One for interface migration and one for RayJob Volcano Integration. This makes both review and rollback easier IMO.

**Comment by win5923** [comment]
> I am wondering if we should separate this PR into two. One for interface migration and one for RayJob Volcano Integration. This makes both review and rollback easier IMO.

Got it! I will change this PR to focus on the RayJob Volcano integration, and will create a separate PR for the interface migration.
Thanks.

**Comment by win5923** [comment]
Created a issue for interface migration.
https://github.com/ray-project/kuberay/issues/4097

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 2]
```diff
@@ -34,106 +35,188 @@ type VolcanoBatchScheduler struct {
...
+		return nil
+	}
+
+	minMember, totalResource := v.calculatePodGroupParams(ctx, &raycluster.Spec)
+
+	return v.syncPodGroup(ctx, raycluster, minMember, totalResource)
+}
+
+// handleRayJob calculates the PodGroup MinMember and MinResources for a RayJob
+// The submitter pod is intentionally excluded from MinMember calculation.
```
Comment (troychiu) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: Do you mind elaborating on why we want to exclude the submitter pod? Also, if we exclude the submitter pod from resource calculation, what is the main goal of this RayJob integration?

Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: The submitter pod needs to wait until all RayCluster pods are ready before it is created. However, this leads to a minMember mismatch in the PodGroup, causing the RayCluster to remain in a Pending state.
As a temporary workaround, I’ve configured the RayJob to use the same PodGroup settings as the RayCluster.

Comment (owenowenisme) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: So, currently gang scheduling does not consider submitter pod? ( If I am right it doesn't consider submitter pod resource according to the pod group spec below. )
```
k describe podgroup ray-rayjob-sample-1-pg
Name:         ray-rayjob-sample-1-pg
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  scheduling.volcano.sh/v1beta1
Kind:         PodGroup
Spec:
  Min Member:  3
  Min Resources:
    Cpu:     3
    Memory:  4Gi
  Queue:     kuberay-test-queue

```
I think even though the min member mismatch we could still calculate the correct min resource so that the gang scheduling can consider submitter's resource requirement.

In other word, can minMember = worker num+ 1 (head ) and minResource = worker resource + head resource + submitter resource solve the problem?

Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: > I think even though the min member mismatch we could still calculate the correct min resource so that the gang scheduling can consider submitter's resource requirement.
> 
> In other word, can minMember = worker num+ 1 (head ) and minResource = worker resource + head resource + submitter resource solve the problem?

Sure, Thanks your suggestion! Updated in https://github.com/ray-project/kuberay/pull/3972/commits/a96d3a4058b2bcd0c26f110e8437d514c7484fd1


```
$ k get podgroup ray-rayjob-sample-0-pg  -o yaml
apiVersion: scheduling.volcano.sh/v1beta1
kind: PodGroup
metadata:
  creationTimestamp: "2025-09-25T15:16:14Z"
  generation: 3
  name: ray-rayjob-sample-0-pg
  namespace: default
  ownerReferences:
  - apiVersion: ray.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: RayJob
    name: rayjob-sample-0
    uid: e7652cc7-7593-4bd1-8ab1-bc043e62d7e5
  resourceVersion: "8779"
  uid: 84247ace-fcb5-4bce-9e18-b33e3769b941
spec:
  minMember: 3
  minResources:
    cpu: 3500m
    memory: 4296Mi
  queue: kuberay-test-queue
status:
  conditions:
  - lastTransitionTime: "2025-09-25T15:16:15Z"
    reason: tasks in gang are ready to be scheduled
    status: "True"
    transitionID: 6ccaf1db-e4f6-4cfa-ad71-f3abf039e03c
    type: Scheduled
  phase: Running
  running: 1
```

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 3]
```diff
@@ -34,106 +36,196 @@ type VolcanoBatchScheduler struct {
...
+}
+
+// handleRayJob calculates the PodGroup MinMember and MinResources for a RayJob
+func (v *VolcanoBatchScheduler) handleRayJob(ctx context.Context, rayJob *rayv1.RayJob) error {
+	if rayJob.Spec.RayClusterSpec == nil {
+		return fmt.Errorf("gang scheduling does not support RayJob %s/%s referencing an existing RayCluster", rayJob.Namespace, rayJob.Name)
 	}
 
-	return v.syncPodGroup(ctx, app, minMember, totalResource)
+	totalResourceList := []corev1.ResourceList{{}}
```
Comment (fscnick) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: For curiosity, why is there an empty `ResourceList`?

Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: To passed to [sumResourceList(list []corev1.ResourceList) corev1.ResourceList](https://github.com/ray-project/kuberay/blob/eb66a26b78b7a4fc92c0e1f3d412e15b75b6c0ea/ray-operator/controllers/ray/utils/util.go#L506-L519) for calculating the total required resources.

Comment (fscnick) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: However, there is no `name` and `quantity` in an empty `ResourceList`. It just skip the inner loop and further to the next element in the slice.

Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: Oh, you are right! I was just following the code from [util.go](https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/utils/util.go) https://github.com/ray-project/kuberay/blob/eb66a26b78b7a4fc92c0e1f3d412e15b75b6c0ea/ray-operator/controllers/ray/utils/util.go#L429-L458

I think we can open a follow-up PR to clean up these redundant empty ResourceList initializations.

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 4]
```diff
@@ -34,106 +36,195 @@ type VolcanoBatchScheduler struct {
...
+	minMember, totalResource := v.calculatePodGroupParams(ctx, rayJob.Spec.RayClusterSpec)
+	totalResourceList = append(totalResourceList, totalResource)
+
+	// MinMember intentionally excludes the submitter pod to avoid a startup deadlock
+	// (submitter waits for cluster; gang would wait for submitter). We still add the
+	// submitter's resource requests into MinResources so capacity is reserved.
+	if rayJob.Spec.SubmissionMode == rayv1.K8sJobMode {
+		submitterTemplate := common.GetSubmitterTemplate(&rayJob.Spec, rayJob.Spec.RayClusterSpec)
+		submitResource := utils.CalculatePodResource(submitterTemplate.Spec)
+		totalResourceList = append(totalResourceList, submitResource)
```
Comment (owenowenisme) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]:
```suggestion
		submitterResource := utils.CalculatePodResource(submitterTemplate.Spec)
		totalResourceList = append(totalResourceList, submitterResource)
```

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 5]
```diff
@@ -34,106 +36,195 @@ type VolcanoBatchScheduler struct {
...
+		submitterTemplate := common.GetSubmitterTemplate(&rayJob.Spec, rayJob.Spec.RayClusterSpec)
+		submitterResource := utils.CalculatePodResource(submitterTemplate.Spec)
+		totalResourceList = append(totalResourceList, submitterResource)
+	}
+
+	return v.syncPodGroup(ctx, rayJob, minMember, utils.SumResourceList(totalResourceList))
+}
+
+func getAppPodGroupName(object metav1.Object) string {
+	// Prefer the RayJob name if this object originated from a RayJob
```
Comment (troychiu) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:104]: why do we need this? IIUC, if the object is a rayCluster, it won't be originated from a rayjob since we early return in line 60 right?

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 6]
```diff
@@ -34,106 +36,195 @@ type VolcanoBatchScheduler struct {
...
+// syncPodGroup ensures a Volcano PodGroup exists/updated for the given object
+// with the provided size (MinMember) and total resources.
+func (v *VolcanoBatchScheduler) syncPodGroup(ctx context.Context, owner metav1.Object, size int32, totalResource corev1.ResourceList) error {
+	logger := ctrl.LoggerFrom(ctx).WithName(pluginName)
+
+	podGroupName := getAppPodGroupName(owner)
+	podGroup := volcanoschedulingv1beta1.PodGroup{}
+	if err := v.cli.Get(ctx, types.NamespacedName{Namespace: owner.GetNamespace(), Name: podGroupName}, &podGroup); err != nil {
 		if !errors.IsNotFound(err) {
+			logger.Error(err, "failed to get PodGroup", "name", podGroupName)
```
Comment (troychiu) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: maybe also include the CRD type and name in the log?

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 7]
```diff
@@ -34,106 +36,195 @@ type VolcanoBatchScheduler struct {
...
+	annotations[volcanoschedulingv1beta1.KubeGroupNameAnnotationKey] = getAppPodGroupName(parent)
 
-	podGroupName := getAppPodGroupName(app)
-	podGroup := volcanov1beta1.PodGroup{}
-	if err := v.cli.Get(ctx, types.NamespacedName{Namespace: app.Namespace, Name: podGroupName}, &podGroup); err != nil {
+	switch child.(type) {
+	case *corev1.Pod:
+		annotations[volcanobatchv1alpha1.TaskSpecKey] = groupName
+	case *corev1.PodTemplateSpec:
+		annotations[volcanobatchv1alpha1.TaskSpecKey] = utils.RayNodeSubmitterGroupLabelValue
```
Comment (troychiu) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: why isn't it using the groupName passed in?

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 1 above)
Comment (troychiu) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:28]: I think we can just remove it

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 5 above)
Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:104]: If the RayCluster is originated from a RayJob, and at line 226 (Same as `populateAnnotations`), it tries to retrieve the name of the RayCluster during execution. However, the PodGroup is created using the name of the RayJob.

That’s why `getAppPodGroupName` needs to check whether the RayCluster is originated from a RayJob.

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 6 above)
Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: Thanks! updated in https://github.com/ray-project/kuberay/pull/3972/commits/597e57d6ddf2e2f74ee9bdd8105c62286a376e1c.

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 7 above)
Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: Nice catch! Updated in https://github.com/ray-project/kuberay/pull/3972/commits/597e57d6ddf2e2f74ee9bdd8105c62286a376e1c.

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 5 above)
Comment (troychiu) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:104]: I see! Thank you for the explanation.

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 8]
```diff
@@ -34,106 +36,189 @@ type VolcanoBatchScheduler struct {
...
+		podGroup := createPodGroup(owner, podGroupName, size, totalResource)
 		if err := v.cli.Create(ctx, &podGroup); err != nil {
 			if errors.IsAlreadyExists(err) {
-				logger.Info("pod group already exists, no need to create")
+				logger.Info("podGroup already exists, no need to create", "name", podGroupName)
 				return nil
 			}
 
-			logger.Error(err, "Pod group CREATE error!", "PodGroup.Error", err)
+			logger.Error(err, "failed to create PodGroup", "name", podGroupName)
```
Comment (troychiu) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: nit: also log more information

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 9]
```diff
@@ -34,106 +36,189 @@ type VolcanoBatchScheduler struct {
...
 			return err
 		}
 	} else {
-		if podGroup.Spec.MinMember != size || !quotav1.Equals(*podGroup.Spec.MinResources, totalResource) {
+		if podGroup.Spec.MinMember != size || podGroup.Spec.MinResources == nil || !quotav1.Equals(*podGroup.Spec.MinResources, totalResource) {
 			podGroup.Spec.MinMember = size
 			podGroup.Spec.MinResources = &totalResource
 			if err := v.cli.Update(ctx, &podGroup); err != nil {
-				logger.Error(err, "Pod group UPDATE error!", "podGroup", podGroupName)
+				logger.Error(err, "failed to update PodGroup", "name", podGroupName)
```
Comment (troychiu) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: same

**Review by troychiu — APPROVED** [review]

**Comment by troychiu** [comment]
cc @Future-Outlier @rueian

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 10]
```diff
@@ -34,106 +36,189 @@ type VolcanoBatchScheduler struct {
...
+	}
+
+	var totalResourceList []corev1.ResourceList
+	minMember, totalResource := v.calculatePodGroupParams(ctx, rayJob.Spec.RayClusterSpec)
+	totalResourceList = append(totalResourceList, totalResource)
+
+	// MinMember intentionally excludes the submitter pod to avoid a startup deadlock
+	// (submitter waits for cluster; gang would wait for submitter). We still add the
+	// submitter's resource requests into MinResources so capacity is reserved.
+	if rayJob.Spec.SubmissionMode == rayv1.K8sJobMode {
```
Comment (rueian) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:87]: Do we need to do this for SidecarMode?

Comment (Future-Outlier) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:87]: I think in SidecarMode, when calculating the head pod's resource, we will call the function `CalculatePodResource`, and this func will iterate all containers in the head pod spec like this`for _, container := range podSpec.Containers`.
so I think sidecar mode will work, but if we can get a screenshot about a test for sidecar mode I will appreciate it.


cc @win5923

File: ray-operator/config/samples/ray-job.volcano-scheduler-queue.yaml [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+    cpu: 4
+    memory: 6Gi
+---
+apiVersion: ray.io/v1
+kind: RayJob
+metadata:
+  name: rayjob-sample-0
+  labels:
+    ray.io/scheduler-name: volcano
+    volcano.sh/queue-name: kuberay-test-queue
```
Comment (Future-Outlier) [inline ray-operator/config/samples/ray-job.volcano-scheduler-queue.yaml:17]: Hi, @win5923 
can we add `ray.io/gang-scheduling-enabled: "true"` in the example and test them?

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 10 above)
Comment (Future-Outlier) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:87]: wait, @rueian is right.
when using sidecar mode, the `Min Resources`'s `CPU` shoulde be `3.5`, but this is not correct here.

Image

**Review by Future-Outlier — CHANGES_REQUESTED** [review]
will request changes until all comments are resolved

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 10 above)
Comment (win5923) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go:87]: Thanks @rueian!
I’ve already added the check for SidecarMode. https://github.com/ray-project/kuberay/pull/3972/commits/ae2941f752ffa0fd54e4eddfbe094f587ba2856c

image

File: ray-operator/config/samples/ray-job.volcano-scheduler-queue.yaml (hunk 11 above)
Comment (win5923) [reply ray-operator/config/samples/ray-job.volcano-scheduler-queue.yaml:17]: Currently, adding `ray.io/gang-scheduling-enabled: "true"` does not have any effect. This only works with `YuniKorn` or the `Scheduler plugin`.

https://github.com/ray-project/kuberay/blob/c6bafa350ce2c80baf478ffcd88a82a594b29d2f/ray-operator/controllers/ray/batchscheduler/yunikorn/yunikorn_scheduler.go#L120-L123

https://github.com/ray-project/kuberay/blob/c6bafa350ce2c80baf478ffcd88a82a594b29d2f/ray-operator/controllers/ray/batchscheduler/scheduler-plugins/scheduler_plugins.go#L109-L112

And I think this is a breaking change if we add this check. We should also update the doc to mention that starting from version 1.5.0, users need to add `ray.io/gang-scheduling-enabled: "true"` to enable gang scheduling for Volcano. https://docs.ray.io/en/latest/cluster/kubernetes/k8s-ecosystem/volcano.html

Comment (Future-Outlier) [reply ray-operator/config/samples/ray-job.volcano-scheduler-queue.yaml:17]: I found that volcano's default scheduler configmap is gang scheduling enabled!
so in the future, if the user want to disable it, we might need to tell them to edit the configmap or figure out some way to control it by adding more information in our CR.

thank you!!
```yaml
apiVersion: v1
data:
  volcano-scheduler.conf: |
    actions: "enqueue, allocate, backfill"
    tiers:
    - plugins:
      - name: priority
      - name: gang
        enablePreemptable: false
      - name: conformance
    - plugins:
      - name: overcommit
      - name: drf
        enablePreemptable: false
      - name: predicates
      - name: proportion
      - name: nodeorder
      - name: binpack
```

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 12]
```diff
@@ -34,106 +36,189 @@ type VolcanoBatchScheduler struct {
...
+	totalResourceList = append(totalResourceList, totalResource)
+
+	// MinMember intentionally excludes the submitter pod to avoid a startup deadlock
+	// (submitter waits for cluster; gang would wait for submitter). We still add the
+	// submitter's resource requests into MinResources so capacity is reserved.
+	if rayJob.Spec.SubmissionMode == rayv1.K8sJobMode || rayJob.Spec.SubmissionMode == rayv1.SidecarMode {
+		submitterTemplate := common.GetSubmitterTemplate(&rayJob.Spec, rayJob.Spec.RayClusterSpec)
+		submitterResource := utils.CalculatePodResource(submitterTemplate.Spec)
+		totalResourceList = append(totalResourceList, submitterResource)
+	}
```
Comment (Future-Outlier) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: I think the result for this code is correct, but the behavior is not.
for k8s mode, we should get submitter's information from `submitterTemplate`
for sidecar mode, we should get submitter's information from `GetDefaultSubmitterContainer`, since we use this function currently.

update:
I've discussed offline with @win5923 
I am writing a commit to fix this!

Comment (rueian) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: Younikorn also uses GetSubmitterTemplate for sidecar mode. Would you like to update the Younikorn part as well (newTaskGroupsFromRayJobSpec)?

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go [hunk 13]
```diff
@@ -78,13 +78,23 @@ func (v *VolcanoBatchScheduler) handleRayJob(ctx context.Context, rayJob *rayv1.
...
+	if rayJob.Spec.SubmissionMode == rayv1.K8sJobMode {
 		submitterTemplate := common.GetSubmitterTemplate(&rayJob.Spec, rayJob.Spec.RayClusterSpec)
-		submitterResource := utils.CalculatePodResource(submitterTemplate.Spec)
-		totalResourceList = append(totalResourceList, submitterResource)
+		return utils.CalculatePodResource(submitterTemplate.Spec)
+	} else if rayJob.Spec.SubmissionMode == rayv1.SidecarMode {
+		submitterContainer := common.GetDefaultSubmitterContainer(rayJob.Spec.RayClusterSpec)
+		return corev1.ResourceList{
+			corev1.ResourceCPU:    submitterContainer.Resources.Requests[corev1.ResourceCPU],
+			corev1.ResourceMemory: submitterContainer.Resources.Requests[corev1.ResourceMemory],
```
Comment (rueian) [inline ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: Can we take all the resource types into account here? We'd better not assume there are only CPU and memory.

Comment (Future-Outlier) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: just fix it here, thank you!
https://github.com/ray-project/kuberay/pull/3972/commits/cf6b48bb361aae7decfe7309e66a28495031a3f5

File: ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go (hunk 12 above)
Comment (Future-Outlier) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: yes I can do it now

Comment (Future-Outlier) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: ## sidecar mode (only 2 items in task-groups) (the head pod resource = head container + submitter container)
image


image

## k8s mode (3 items in task-groups (head pod, worker pod, and submmiter pod))
image

Comment (Future-Outlier) [reply ray-operator/controllers/ray/batchscheduler/volcano/volcano_scheduler.go]: Hi, @rueian 
I have tested the Yunikorn integration in both Kubernetes job mode and sidecar mode and can confirm that no code changes are required. The existing logic correctly handles both scenarios.

### Kubernetes Job Mode
The function `newTaskGroupsFromRayJobSpec` is ultimately called by `AddMetadataToChildResource`. **Within the RayJob controller, `AddMetadataToChildResource` is only invoked when the RayJob is configured for Kubernetes job mode, as seen in these two locations:**

1st place: https://github.com/ray-project/kuberay/blob/c6bafa350ce2c80baf478ffcd88a82a594b29d2f/ray-operator/controllers/ray/rayjob_controller.go#L582-L606
2nd place: https://github.com/ray-project/kuberay/blob/c6bafa350ce2c80baf478ffcd88a82a594b29d2f/ray-operator/controllers/ray/rayjob_controller.go#L949-L956
That's why it behaves correctly.

Because of this, the Yunikorn-specific logic is correctly applied only when the RayJob creates a Kubernetes Job, and it behaves as expected.

### Sidecar Mode
In sidecar mode, the submitter container is added to the Ray head pod, which is part of the RayCluster specification. When the RayCluster controller reconciles the RayCluster custom resource, it calculates the task groups for the head and worker pods. At that point, the head pod correctly contains both the Ray head container and the submitter sidecar container, ensuring their resources are accounted for in the task group calculation, as handled by the logic here:

https://github.com/ray-project/kuberay/blob/c6bafa350ce2c80baf478ffcd88a82a594b29d2f/ray-operator/controllers/ray/rayjob_controller.go#L978-L1016
