### PR TITLE
fix: `.status.availableWorkerReplicas`

### LINKED ISSUE #885: [Bug] `.status.availableWorkerReplicas` incorrectly counts head Pods
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

`kubectl get raycluster my-cluster -o yaml` shows `.status.availableWorkerReplicas` as always one more than `.status.desiredWorkerReplicas`. I think the operator is incorrectly including head Pods in `availableWorkerReplicas`.

[see previous comment](https://github.com/ray-project/kuberay/pull/878#issuecomment-1400405806)

### Reproduction script

Create a RayCluster with workers. Run `kubectl get raycluster my-cluster -o yaml` and look at `.status`.

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by davidxia**
to not count head Pods. closes #885

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: ray-operator/controllers/ray/utils/util.go [hunk 1]
```diff
@@ -201,10 +201,13 @@ func CalculateMaxReplicas(cluster *rayiov1alpha1.RayCluster) int32 {
 	return count
 }
 
-// CalculateDesiredReplicas calculate desired worker replicas at the cluster level
+// CalculateAvailableReplicas calculates available worker replicas at the cluster level
 func CalculateAvailableReplicas(pods corev1.PodList) int32 {
 	count := int32(0)
 	for _, pod := range pods.Items {
+		if val, ok := pod.Annotations["ray.io/node-type"]; !ok || val != string(rayiov1alpha1.WorkerNode) {
```
Comment (davidxia) [inline ray-operator/controllers/ray/utils/util.go:208]: I had to use `ray.io/node-type` because importing `common.RayNodeTypeLabelKey` caused import cycle.

```
-: import cycle not allowed: import stack: [
  github.com/ray-project/kuberay/ray-operator
  github.com/ray-project/kuberay/ray-operator/controllers/ray
  github.com/ray-project/kuberay/ray-operator/controllers/ray/batchscheduler
  github.com/ray-project/kuberay/ray-operator/controllers/ray/batchscheduler/volcano
  github.com/ray-project/kuberay/ray-operator/controllers/ray/common
  github.com/ray-project/kuberay/ray-operator/controllers/ray/utils
  github.com/ray-project/kuberay/ray-operator/controllers/ray/common
]
```

**Comment by davidxia** [comment]
@kevin85421

File: ray-operator/controllers/ray/utils/util_test.go [hunk 2]
```diff
@@ -312,3 +312,34 @@ func TestReconcile_CheckNeedRemoveOldPod(t *testing.T) {
 
 	assert.Equal(t, PodNotMatchingTemplate(pod, workerTemplate), true, "expect template & pod not matching")
 }
+
+func TestCalculateAvailableReplicas(t *testing.T) {
+	podList := corev1.PodList{
```
Comment (kevin85421) [inline ray-operator/controllers/ray/utils/util_test.go:317]: Would you mind adding comments for the definition of available replicas?

File: ray-operator/controllers/ray/utils/util.go (hunk 1 above)
Comment (kevin85421) [inline ray-operator/controllers/ray/utils/util.go:208]: `ray.io/node-type` is a label rather than an annotation.

Screen Shot 2023-01-29 at 7 33 14 AM

**Review by kevin85421 — COMMENTED** [review]
Thank you for your contribution! Would you mind adding a screenshot of `kubectl get raycluster`?

File: ray-operator/controllers/ray/utils/util.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/utils/util.go:208]: Cool. Maybe we need to separate `constant.go` into a separate module in the future. cc @DmitriGekhtman @Jeffwan @architkulkarni

Comment (DmitriGekhtman) [reply ray-operator/controllers/ray/utils/util.go:208]: Yeah, we should track solving that.
It would be better if we could eliminate common and utils by refactoring the package structure -- https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

Comment (davidxia) [reply ray-operator/controllers/ray/utils/util.go:208]: yes thanks

**Comment by davidxia** [comment]
tested manually

```
kubectl get rayclusters
NAME        DESIRED WORKERS   AVAILABLE WORKERS   STATUS   AGE
dxia-test   3                 3                   ready    6d17h

kubectl get rayclusters dxia-test -o yaml

...
status:
  availableWorkerReplicas: 3
  desiredWorkerReplicas: 3
...
```

File: ray-operator/controllers/ray/utils/util_test.go (hunk 2 above)
Comment (davidxia) [reply ray-operator/controllers/ray/utils/util_test.go:317]: I added a comment to `controllers/ray/utils/util.go`. Lmk if this it's good.

> A worker is available if its Pod is running or pending.

Is it correct to count pending Pods or only running?

Comment (kevin85421) [reply ray-operator/controllers/ray/utils/util_test.go:317]: For me, the straightforward definition of "available replicas" is the number of worker Pods that are ready to serve actors and tasks. Also, we can refer to the definition of `AvailableReplicas` in ReplicaSet. 

[1] [Kubernetes source code: How to calculate `AvailableReplicas`?](https://github.com/kubernetes/kubernetes/blob/7b243cef1a81f4a0ac1619f7b9238fcd2bac2b9c/pkg/controller/replicaset/replica_set_utils.go#L86-L128)
[2] [Understanding the Available condition of a Kubernetes deployment](https://maelvls.dev/deployment-available-condition/): I did not have a chance to read this article, but this may be helpful.

Do you have any thoughts about the definition of "available"?

Comment (kevin85421) [reply ray-operator/controllers/ray/utils/util_test.go:317]: cc @DmitriGekhtman

Comment (davidxia) [reply ray-operator/controllers/ray/utils/util_test.go:317]: > straightforward definition of "available replicas" is the number of worker Pods that are ready to serve actors and tasks

This makes sense. We shouldn't count pending Pods [here](https://github.com/ray-project/kuberay/pull/887/files#diff-cc9abb27aaceca3f10193e2ab35fb00dca44b8858709c5c0f4df751c1387291aR212) then, right?

Comment (kevin85421) [reply ray-operator/controllers/ray/utils/util_test.go:317]: > This makes sense. We shouldn't count pending Pods [here](https://github.com/ray-project/kuberay/pull/887/files#diff-cc9abb27aaceca3f10193e2ab35fb00dca44b8858709c5c0f4df751c1387291aR212) then, right?

Yes. If referring to the definition of AvailableReplicas in ReplicaSet makes sense to you, we shouldn't count pending Pods.

Comment (davidxia) [reply ray-operator/controllers/ray/utils/util_test.go:317]: Great! Updated. Ready for another view

**Review by kevin85421 — APPROVED** [review]
LGTM! Test this PR manually.

Screen Shot 2023-02-04 at 8 55 59 PM

**Comment by kevin85421** [comment]
CI failure is due to #852.
