### PR TITLE
[Bug] autoscaler not working properly in rayjob 

### LINKED ISSUE #532: [Bug] autoscaler not working properly in rayjob
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I submit a rayjob into k8s with autoscaler, the autoscaler not work properly. New pod did created but another pod terminated suddenly, and the number of pods equals replica in raycluster spec.
I think there has conflicts between rayjob controller and kuberay autoscaler.
The autoscaler did modified replicas in raycluster workergroup but then rayjob controller do a diff check on raycluster spec between  k8s and rayjob spec and roll it back.
There are some messages can help.
pic1 : autoscaler log
image
pic2 : the object has been modified error in operator
image
pic3 : operator update raycluster spec
image

### Reproduction script

[hp-pi-autoscale-job.txt](https://github.com/ray-project/kuberay/files/9495509/hp-pi-autoscale-job.txt)
[code-pi-cm.txt](https://github.com/ray-project/kuberay/files/9495510/code-pi-cm.txt)

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by Yicheng-Lu-llll**
## In short:
When submitting a Ray job to Kubernetes with the autoscaler, the following behaviors can be observed:

1. A new worker pod is created as the autoscaler increases the number of replicas.
2. An existing worker is terminated simultaneously.
3. The total number of worker pods remains equal to the original replica count.

The root cause is that both the autoscaler and the RayJob controller are trying to update the replicas, causing worker pods to be repeatedly created and terminated.

So, This PR:

1. Preventing Ray job controllers from updating the RayCluster when the autoscaler is enabled.
2.  Even when the autoscaler is not enabled, Ray job controller only modifies the replica, rather than the entire RayClusterSpec.

## Reproduce
The reproduction file can be found here: [ray_v1alpha1_rayjob.yaml](https://github.com/Yicheng-Lu-llll/kuberay/blob/tmp/ray_v1alpha1_rayjob.yaml).

I believe the root cause of the problem lies in this section of the code:

https://github.com/ray-project/kuberay/blob/3571d52d723de7135338b6d5f9a41fb9b2e972f0/ray-operator/controllers/ray/rayjob_controller.go#L379-L382

##  The sequence of events is as follows:
After `kubectl apply -f ray_v1alpha1_rayjob.yaml`:
1. RayJob operator creates a Ray cluster with 1 head pod and 1 worker pod.

2. Based on the workload (placement group in this case), the autoscaler adjusts the RayCluster replica count to 2.
3. The RayCluster operator creates a new worker pod.
4. During the reconciliation of the RayJob operator, it executes the above-mentioned code, overwriting `RayClusterInstance.Spec` with `RayJobInstance.Spec.RayClusterSpec`（The goal here is to reflect the user's update to the ray job yaml file）. As a result, the replica count reverts to its original value of 1(Replicas's type is *int32).
5. The RayCluster operator deletes an existing worker pod based on the updated replica count.
6. So, we can see "New pod did created but another pod terminated suddenly."

## Fix

From my understanding, the need to overwrite `RayClusterInstance.Spec` with` RayJobInstance.Spec.RayClusterSpec` (when a RayCluster is found) arises when users update the replicas in the Ray job YAML file, prompting the Ray job controller to adjust the replica count on their behalf.

So, the root cause stems from both the autoscaler (based on the workload) and Ray job controllers (based on the Ray job YAML file) attempting to update the replica count simultaneously. Consider these points:

1. RayCluster currently only permits replica updates; modifying other specs may cause errors.
2. When the autoscaler is enabled, users are less likely to manually adjust the replica count, as the autoscaler should adapt the replica based on workload.

So, a potential solution to address this issue is:

1. Preventing Ray job controllers from updating the RayCluster when the autoscaler is enabled.
2.  Even when the autoscaler is not enabled, Ray job controllers should only modify the replica, rather than the entire RayClusterSpec.

## Related issue number
Closes #532

## Checks
Most tests are incorporated in the CI. Additionally, I've conducted manual testing for the following cases.

**_I can confirm all the below cases will work._**

- [x] Case1: With in-tree autoscaling is disabled, user(RayJob controller) should be able to update the replica.

- [x] Case2: With in-tree autoscaling disabled, if users update specs other than the replica, The following log message should be displayed:

```log
2023-05-19T01:05:10.326Z        INFO    controllers.RayJob      RayJob supports replica changes only. Adjustments made to other specs will be disregarded as they may cause unexpected behavior
```

- [x] Case3: With in-tree autoscaling is enabled, the autoscaler should be able to adjust the number of workers based on the workload. The RayJob controller should not be able to change RayJob and  propagate to the RayCluster. The following log message should be displayed:

```log
2023-05-19T01:08:28.652Z        INFO    controllers.RayJob      Since in-tree autoscaling is enabled, any adjustments made to the RayJob will be disregarded and will not be propagated to the RayCluster.
```

- [x] Case4: With RayClusterSpec empty and ClusterSelector set, an existing Ray cluster should be used. The following log message should be displayed:

```log
2023-05-19T01:14:23.429Z        INFO    controllers.RayJob      ClusterSelector is being used to select an existing RayCluster. RayClusterSpec will be disregarded      {"raycluster": "default/raycluster-autoscaler"}
```

- [x] Case5: With both RayClusterSpec and ClusterSelector are set, an existing Ray cluster should be used RayClusterSpec should be ignored. The RayJob controller should not be able to change RayJob and  propagate to the **existing** RayCluster.  The following log message should be displayed:

```log
2023-05-19T01:19:05.363Z        INFO    controllers.RayJob      ClusterSelector is being used to select an existing RayCluster. RayClusterSpec will be disregarded      {"raycluster": "default/raycluster-autoscaler"}
```

- [x] Case6: With both RayClusterSpec and ClusterSelector are unset, The following error message should be displayed:

```log
2023-05-19T01:22:12.162Z        ERROR   controllers.RayJob      Failed to configure RayCluster instance due to missing configuration    {"error": "Both ClusterSelector and RayClusterSpec are undefined"}
```

### CODE REVIEW

**Comment by Yicheng-Lu-llll** [comment]
@architkulkarni @kevin85421, Would you mind reviewing this PR and letting me know if it looks good to you? Thank you!

The issue we're facing is that both the autoscaler and the RayJob controller are trying to update the replicas, causing worker pods to be repeatedly created and terminated.

The proposed solution is to prevent the RayJob controller from updating the replicas if the autoscaler is enabled.

The rationale behind this is:

1. When the autoscaler is in use, users are less likely to manually modify the replicas in the RayJob YAML, as the autoscaler will dynamically adjust the replicas based on the workload.

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 1]
```diff
@@ -33,45 +33,112 @@ import (
...
 
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/client-go/util/retry"
 	"sigs.k8s.io/controller-runtime/pkg/client"
 	// +kubebuilder:scaffold:imports
 )
 
-var _ = Context("Inside the default namespace", func() {
-	ctx := context.TODO()
-	myRayJob := &rayiov1alpha1.RayJob{
```
Comment (Yicheng-Lu-llll) [inline ray-operator/controllers/ray/rayjob_controller_test.go:42]: I've simply moved myRayJob outside of the function to turn it into a global variable, thereby preventing the need to rewrite this spec multiple times. There is no change to the spec itself.

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 2]
```diff
@@ -33,45 +33,112 @@ import (
...
+			},
+			WorkerGroupSpecs: []rayiov1alpha1.WorkerGroupSpec{
+				{
+					Replicas:    pointer.Int32(3),
+					MinReplicas: pointer.Int32(0),
+					MaxReplicas: pointer.Int32(10000),
+					GroupName:   "small-group",
 					RayStartParams: map[string]string{
 						"port":                        "6379",
-						"object-store-memory":         "100000000",
```
Comment (Yicheng-Lu-llll) [inline ray-operator/controllers/ray/rayjob_controller_test.go:55]: Again, there is no change to the spec actually. This holds true for all subsequent code as well.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 3]
```diff
@@ -368,22 +368,43 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
...
 	if err == nil {
 		r.Log.Info("RayJob associated rayCluster found", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
-		// just return the rayClusterInstance if cluster spec is nil
+
+		// Case1: We are submitting a job to an existing ray cluster, just return the rayClusterInstance
 		if rayJobInstance.Spec.RayClusterSpec == nil {
 			return rayClusterInstance, nil
 		}
 
+		// Note, Unlike the Ray service, which creates new Ray clusters if any spec is changed,
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:377]:
```suggestion
		// Note, unlike the RayService, which creates new Ray clusters if any spec is changed,
```

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 4]
```diff
@@ -197,7 +201,37 @@ var _ = Context("Inside the default namespace", func() {
 			workerPods := corev1.PodList{}
 			Eventually(
 				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
-				time.Second*15, time.Millisecond*500).Should(Equal(3), fmt.Sprintf("workerGroup %v", workerPods.Items))
+				time.Second*15, time.Millisecond*500).Should(Equal(int(*myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas)), fmt.Sprintf("workerGroup %v", workerPods.Items))
+			if len(workerPods.Items) > 0 {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:205]: Why do we only check `Items[0]` instead of all Pods?

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 5]
```diff
@@ -197,7 +201,37 @@ var _ = Context("Inside the default namespace", func() {
...
+				return k8sClient.Update(ctx, myRayJob)
+			})
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayJob")
+
+			// confirm the number of worker pods is not changed
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: "small-group"}
+			workerPods := corev1.PodList{}
+			Eventually(
+				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*15, time.Millisecond*500).Should(Equal(int(newReplicas)), fmt.Sprintf("workerGroup %v", workerPods.Items))
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:234]: Why does the number of workers equal newReplicas when the number of worker Pods hasn't changed?

```
// confirm the number of worker pods is not changed
```

The comment seems to be wrong.

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 6]
```diff
@@ -235,6 +269,95 @@ var _ = Context("Inside the default namespace", func() {
...
+			})
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayCluster replica")
+
+			// Confirm a new worker pod is created
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: "small-group"}
+			workerPods := corev1.PodList{}
+			Eventually(
+				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*15, time.Millisecond*500).Should(Equal(int(*myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas)+1), fmt.Sprintf("workerGroup %v", workerPods.Items))
+			if len(workerPods.Items) > 0 {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:324]: Why do we only check `Items[0]` instead of all Pods?

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 7]
```diff
@@ -235,6 +269,95 @@ var _ = Context("Inside the default namespace", func() {
...
+			})
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayJob")
+
+			// confirm the number of worker pods is not changed
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: "small-group"}
+			workerPods := corev1.PodList{}
+			Eventually(
+				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*15, time.Millisecond*500).Should(Equal(int(oldReplicas)), fmt.Sprintf("workerGroup %v", workerPods.Items))
+			if len(workerPods.Items) > 0 {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:354]: Same

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 8]
```diff
@@ -235,6 +269,95 @@ var _ = Context("Inside the default namespace", func() {
...
+
+			// simulate updating the RayJob directly.
+			err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
+				*myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas = *myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas + 100
+				return k8sClient.Update(ctx, myRayJob)
+			})
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayJob")
+
+			// confirm the number of worker pods is not changed
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: "small-group"}
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:349]: Use variable instead of hard-coded into `smaill-group`.

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 9]
```diff
@@ -235,6 +269,95 @@ var _ = Context("Inside the default namespace", func() {
...
+				return k8sClient.Update(ctx, myRayCluster)
+			})
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayCluster replica")
+
+			// Confirm a new worker pod is created
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: "small-group"}
+			workerPods := corev1.PodList{}
+			Eventually(
+				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*15, time.Millisecond*500).Should(Equal(int(*myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas)+1), fmt.Sprintf("workerGroup %v", workerPods.Items))
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:323]: Use `Consistently` to ensure that the worker is not terminated by the RayJob described in the PR description.

File: ray-operator/controllers/ray/rayjob_controller_test.go (hunk 5 above)
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller_test.go:234]: Thank you for pointing out!

**Review by architkulkarni — APPROVED** [review]
Looks good pending @kevin85421 's comments. Some minor questions:
- Should we add a log in each of the 4 cases, or will it be too spammy? This is to prevent a future user complaining about changes being "silently ignored"
- Is there a convenient way to parametrize the tests (similar to `pytest.mark.parametrize` in python) to avoid repeated code, to isolate the part of the test that's different when the autoscaler is on vs off? A quick search turned up something about "table-driven tests" but I'm not sure if that's applicable here.

**Comment by Yicheng-Lu-llll** [comment]
> * Should we add a log in each of the 4 cases, or will it be too spammy? This is to prevent a future user complaining about changes being "silently ignored"

Thank you for pointing out! I have changed according. I use `areSpecsIdentical` , `areReplicasIdentical` to ensure we only log when necessary.

> Is there a convenient way to parametrize the tests (similar to pytest.mark.parametrize in python) to avoid repeated code, to isolate the part of the test that's different when the autoscaler is on vs off? A quick search turned up something about "table-driven tests" but I'm not sure if that's applicable here.

The diffculty is we need to create two different RayJobs, one with autoscaler, one without. Ans the test logic/behavior will be slighly different.  It might be challenging to abstract into common test logic.

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 10]
```diff
@@ -192,14 +196,46 @@ var _ = Context("Inside the default namespace", func() {
...
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].GroupName}
 			workerPods := corev1.PodList{}
 			Eventually(
 				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
-				time.Second*15, time.Millisecond*500).Should(Equal(3), fmt.Sprintf("workerGroup %v", workerPods.Items))
-			if len(workerPods.Items) > 0 {
-				Expect(workerPods.Items[0].Status.Phase).Should(Or(Equal(corev1.PodRunning), Equal(corev1.PodPending)))
+				time.Second*15, time.Millisecond*500).Should(Equal(int(*myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas)), fmt.Sprintf("workerGroup %v", workerPods.Items))
+			for _, workerPod := range workerPods.Items {
+				Expect(workerPod.Status.Phase).Should(Or(Equal(corev1.PodRunning), Equal(corev1.PodPending)))
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:206]: The document [envtest](https://book.kubebuilder.io/reference/envtest.html) indicates that envtest will start a Kubernetes cluster with etcd and the Kubernetes API server, without kubelet, controller-manager or other components. Hence, there is no built-in Kubernetes Pod controller in the fake cluster. In my understanding, the status will not be updated to `corev1.PodRunning` forever. Can you check this?

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 11]
```diff
@@ -192,14 +196,46 @@ var _ = Context("Inside the default namespace", func() {
...
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayJob")
+
+			// confirm the number of worker pods increased.
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].GroupName}
+			workerPods := corev1.PodList{}
+			Eventually(
+				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*15, time.Millisecond*500).Should(Equal(int(newReplicas)), fmt.Sprintf("workerGroup %v", workerPods.Items))
+			for _, workerPod := range workerPods.Items {
+				Expect(workerPod.Status.Phase).Should(Or(Equal(corev1.PodRunning), Equal(corev1.PodPending)))
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:238]: Same. Is it possible to be `corev1.PodRunning`?

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 12]
```diff
@@ -235,6 +271,107 @@ var _ = Context("Inside the default namespace", func() {
...
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayCluster replica")
+
+			// confirm a new worker pod is created.
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].GroupName}
+			workerPods := corev1.PodList{}
+			Eventually(
+				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*15, time.Millisecond*500).Should(Equal(int(*myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].Replicas)+1), fmt.Sprintf("workerGroup %v", workerPods.Items))
+			for _, workerPod := range workerPods.Items {
+				Expect(workerPod.Status.Phase).Should(Or(Equal(corev1.PodRunning), Equal(corev1.PodPending)))
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:329]: Same

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 13]
```diff
@@ -235,6 +271,107 @@ var _ = Context("Inside the default namespace", func() {
...
+			Expect(err).NotTo(HaveOccurred(), "failed to update RayJob")
+
+			// confirm the number of worker pods is not changed.
+			filterLabels := client.MatchingLabels{common.RayClusterLabelKey: myRayJob.Status.RayClusterName, common.RayNodeGroupLabelKey: myRayJob.Spec.RayClusterSpec.WorkerGroupSpecs[0].GroupName}
+			workerPods := corev1.PodList{}
+			Consistently(
+				listResourceFunc(ctx, &workerPods, filterLabels, &client.ListOptions{Namespace: "default"}),
+				time.Second*5, time.Millisecond*500).Should(Equal(int(oldReplicas)), fmt.Sprintf("workerGroup %v", workerPods.Items))
+			for _, workerPod := range workerPods.Items {
+				Expect(workerPod.Status.Phase).Should(Or(Equal(corev1.PodRunning), Equal(corev1.PodPending)))
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:369]: Same

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 14]
```diff
@@ -367,23 +367,58 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
 	rayClusterInstance := &rayv1alpha1.RayCluster{}
 	err := r.Get(ctx, rayClusterNamespacedName, rayClusterInstance)
 	if err == nil {
-		r.Log.Info("RayJob associated rayCluster found", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
-		// just return the rayClusterInstance if cluster spec is nil
+		r.Log.Info("Found associated RayCluster for RayJob", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
+
+		// Case1: The job is submitted to an existing ray cluster, simply return the rayClusterInstance.
 		if rayJobInstance.Spec.RayClusterSpec == nil {
```
[the remark this answers is not in the document]
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller.go:435]: With the current logic:

1. `RayClusterSpec` empty, `clusterSelector` set: Existing RayCluster is used.
2. `RayClusterSpec` empty, `clusterSelector` unset: Triggers an error for RayCluster creation.
3. `RayClusterSpec` set, `clusterSelector` set: Existing RayCluster is used, RayClusterSpec is ignored. However, this could result in a conflict as both the RayJob controller and the autoscaler in the existing RayCluster might try to update replicas simultaneously.
4. `RayClusterSpec` set, `clusterSelector` unset: A new RayCluster is created based on `RayClusterSpec`.

In summary, if `clusterSelector` is set, `RayClusterSpec` is ignored under the current logic. But this might result in scenario 3.

To address scenario 3 and simplifies the logic, How about change the logic to be::

1. `clusterSelector` set: The existing RayCluster is used. Modifications to the existing RayCluster by the RayJob controller would not be permitted (this would avoid scenario 3).
2. `clusterSelector` unset: A new RayCluster is created based on `RayClusterSpec` (obviously, this will trigger an error for RayCluster creation if `RayClusterSpec` is nil).

This change maintains backward compatibility.

File: ray-operator/controllers/ray/rayjob_controller_test.go (hunk 10 above)
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller_test.go:206]: Thank you for pointing out! The status will not be updated to `corev1.PodRunning` forever. Let me change the logic here.

Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller_test.go:206]: I will remove this test logic here as the status will always be `pending` unless manually updated.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 15]
```diff
@@ -429,24 +429,70 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
...
-		r.Log.Info("RayJob associated rayCluster found", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
-		// just return the rayClusterInstance if cluster spec is nil
+		r.Log.Info("Found associated RayCluster for RayJob", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
+
+		// Case1: The job is submitted to an existing ray cluster, simply return the rayClusterInstance.
+		// We do not use rayJobInstance.Spec.RayClusterSpec == nil to check if the cluster selector mode is activated.
+		// This is because a user might set both RayClusterSpec and ClusterSelector. with rayJobInstance.Spec.RayClusterSpec == nil,
+		// though the RayJob controller will still use ClusterSelector, but it's now able to update the replica.
+		// this could result in a conflict as both the RayJob controller and the autoscaler in the existing RayCluster might try to update replicas simultaneously.
+		// if len(rayJobInstance.Spec.ClusterSelector) != 0 {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:439]:
```suggestion

```

remove this?

Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller.go:439]: Thank you for pointing out! I used for testing and forgot to remove it.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 16]
```diff
@@ -429,24 +429,69 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
...
-		if rayJobInstance.Spec.RayClusterSpec == nil {
+		r.Log.Info("Found associated RayCluster for RayJob", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
+
+		// Case1: The job is submitted to an existing ray cluster, simply return the rayClusterInstance.
+		// We do not use rayJobInstance.Spec.RayClusterSpec == nil to check if the cluster selector mode is activated.
+		// This is because a user might set both RayClusterSpec and ClusterSelector. with rayJobInstance.Spec.RayClusterSpec == nil,
+		// though the RayJob controller will still use ClusterSelector, but it's now able to update the replica.
+		// this could result in a conflict as both the RayJob controller and the autoscaler in the existing RayCluster might try to update replicas simultaneously.
+		if len(rayJobInstance.Spec.ClusterSelector) != 0 {
+			r.Log.Info("ClusterSelector is being used to select an existing RayCluster", "raycluster", rayClusterNamespacedName)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:440]: Add a sentence "ignore the rayJobInstance.Spec.RayClusterSpec"

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 17]
```diff
@@ -429,24 +429,69 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
...
+		r.Log.Info("Update ray cluster replica", "raycluster", rayClusterNamespacedName)
 		if err := r.Update(ctx, rayClusterInstance); err != nil {
-			r.Log.Error(err, "Fail to update ray cluster instance!", "rayCluster", rayClusterNamespacedName)
+			r.Log.Error(err, "Fail to update ray cluster replica!", "rayCluster", rayClusterNamespacedName)
 			// Error updating the RayCluster object.
 			return nil, client.IgnoreNotFound(err)
 		}
+
 	} else if errors.IsNotFound(err) {
+		if len(rayJobInstance.Spec.ClusterSelector) == 0 && rayJobInstance.Spec.RayClusterSpec == nil {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:489]: This is not good. We should not try to `GET` RayCluster if both `ClusterSelector` and `RayClusterSpec` are not set. Please add a comment "TODO" and a new issue to track the progress.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 18]
```diff
@@ -429,24 +429,71 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
 	rayClusterInstance := &rayv1alpha1.RayCluster{}
 	err := r.Get(ctx, rayClusterNamespacedName, rayClusterInstance)
 	if err == nil {
-		r.Log.Info("RayJob associated rayCluster found", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
-		// just return the rayClusterInstance if cluster spec is nil
-		if rayJobInstance.Spec.RayClusterSpec == nil {
+		r.Log.Info("Found associated RayCluster for RayJob", "rayjob", rayJobInstance.Name, "raycluster", rayClusterNamespacedName)
+
+		// Case1: The job is submitted to an existing ray cluster, simply return the rayClusterInstance.
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:434]:
```		
// Case1: The job is submitted to an existing RayCluster. Return the existing RayCluster instance and ignore all updates from RayClusterSpec.
```

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 19]
```diff
@@ -235,6 +265,101 @@ var _ = Context("Inside the default namespace", func() {
 	})
 })
 
+var _ = Context("Inside the default namespace with autoscaler", func() {
+	ctx := context.TODO()
+	myRayJob := myRayJob.DeepCopy()
+	myRayJob.Name = "rayjob-test-with-autoscaler"
+	upscalingMode := rayiov1alpha1.UpscalingMode("Default")
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:272]: This seems to be only used by L276. Maybe we do not need this variable.

File: ray-operator/controllers/ray/rayjob_controller_test.go [hunk 20]
```diff
@@ -235,6 +265,101 @@ var _ = Context("Inside the default namespace", func() {
...
+	imagePullPolicy := corev1.PullPolicy("IfNotPresent")
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller_test.go:273]: Same as `upscalingMode`

**Review by kevin85421 — APPROVED** [review]
LGTM. There are still a few minor things that can be improved, but it is fine to resolve them in another PR.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 18 above)
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller.go:434]: This is becasue in golang, we can't take the address of a constant(Constants don't have a specific memory location). We need to define a variable, assign the constant value to the variable, and then take the address of that variable.

File: ray-operator/controllers/ray/rayjob_controller_test.go (hunk 19 above)
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller_test.go:272]: This is becasue in golang, we can't take the address of a constant(Constants don't have a specific memory location). We need to define a variable, assign the constant value to the variable, and then take the address of that variable.

Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/rayjob_controller_test.go:272]: This is becasue in golang, we can't take the address of a constant(Constants don't have a specific memory location). We need to define a variable, assign the constant value to the variable, and then take the address of that variable.
