### PR TITLE
[RayJob] Submit job using K8s job instead of checking Status and using DashboardHTTPClient

### LINKED ISSUE #756: [Bug] 409 conflicts cause two jobs creations
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

I submitted a RayJob to an existing RayCluster with `clusterSelector` and then deleted it. I repeated the process 6 times, and 2 (11:13:54 & 11:32:05) of them created two jobs rather than one job.

Screen Shot 2022-11-22 at 11 32 23 AM

I checked the log and found 409 conflicts occurred at both 11:13:54 & 11:32:05. The root cause is that `SubmitJob()` ([Link](https://github.com/ray-project/kuberay/blob/792af2a6e8411ba10f9fe5962142cc6385ee549e/ray-operator/controllers/ray/rayjob_controller.go#L166)) succeeded but `r.Status().Update(ctx, rayJob)` ([Link](https://github.com/ray-project/kuberay/blob/792af2a6e8411ba10f9fe5962142cc6385ee549e/ray-operator/controllers/ray/rayjob_controller.go#L359)) failed. So, the job submit again in the next iteration of reconciliation.

```
2022-11-22T19:13:54.262Z        ERROR   controller.rayjob       Reconciler error        {"reconciler group": "ray.io", "reconciler kind": "RayJob", "name": "rayjob-sample-2", "namespace": "default", "error": "combined error: <nil> Operation cannot be fulfilled on rayjobs.ray.io \"rayjob-sample-2\": the object has been modified; please apply your changes to the latest version and try again", "errorVerbose": "combined error: <nil> Operation cannot be fulfilled on rayjobs.ray.io \"rayjob-sample-2\": the object has been modified; please apply your changes to the latest version and try again\ngithub.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayJobReconciler).updateState\n\t/workspace/controllers/ray/rayjob_controller.go:350\ngithub.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayJobReconciler).Reconcile\n\t/workspace/controllers/ray/rayjob_controller.go:202\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
.
.
.
2022-11-22T19:32:05.487Z        ERROR   controller.rayjob       Reconciler error        {"reconciler group": "ray.io", "reconciler kind": "RayJob", "name": "rayjob-sample-2", "namespace": "default", "error": "combined error: <nil> Operation cannot be fulfilled on rayjobs.ray.io \"rayjob-sample-2\": the object has been modified; please apply your changes to the latest version and try again", "errorVerbose": "combined error: <nil> Operation cannot be fulfilled on rayjobs.ray.io \"rayjob-sample-2\": the object has been modified; please apply your changes to the latest version and try again\ngithub.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayJobReconciler).updateState\n\t/workspace/controllers/ray/rayjob_controller.go:350\ngithub.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayJobReconciler).Reconcile\n\t/workspace/controllers/ray/rayjob_controller.go:202\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227
```

### Reproduction script

Follow the section "Manual tests" in #735. You need to try multiple times to reproduce the bug.

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
This PR changes the way job submission is handled.  Prior to this PR, the job controller reconciliation loop would check the `Status` of the job, and based on that, decide whether to submit the job or not.  This design had a bug that would sometimes result in duplicate job submissions; see #756 for a full description of the root cause (in a nutshell, the `Status` might not be updated to "Running" immediately.)

This PR fixes the issue because it no longer uses the `Status` field of the job to determine whether to submit the job upon each reconciliation.  Instead, it creates a K8s job to submit the Ray job.  A k8s job will not duplicated even if it's created multiple times.

The PR also exposes the pod template for the k8s job pod that submits the job so that the user can supply it in their RayJob manifest as needed.  In the typical case, the user should not need to specify this, the default should be sufficient.

This is the first PR in a larger refactor of RayJob; this PR just contains a localized change in the submission path.   See https://docs.google.com/document/d/1G--fKMCqp-M3T0qDPQy5eOQJQKRmubr7SyZQ_ms6Py4/edit for more details about the design.

## Related issue number
Closes #756 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
I will review this PR after I bump the version of RayJob at https://github.com/ray-project/kuberay/pull/1132. I will try to get it done this week.

**Comment by architkulkarni** [comment]
@kevin85421 could you please give this a preliminary review? If the overall approach makes sense, I'll clean up the code and add some unit tests.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 1]
```diff
@@ -192,37 +200,43 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
-	// Check the current status of ray jobs before submitting.
-	jobInfo, err := rayDashboardClient.GetJobInfo(ctx, rayJobInstance.Status.JobId)
+	// Ensure k8s job has been created
+	jobName, err := r.CreateK8sJob(ctx, rayJobInstance)
 	if err != nil {
-		err = r.updateState(ctx, rayJobInstance, jobInfo, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusFailedToGetJobStatus, err)
-		// Dashboard service in head pod takes time to start, it's possible we get connection refused error.
-		// Requeue after few seconds to avoid continuous connection errors.
+		r.Log.Error(err, "failed to create k8s job")
+		err = r.updateState(ctx, rayJobInstance, nil, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusFailedJobDeploy, err)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:207]: Calling `updateState` multiple times does not make sense to me. We can refer to the implementation of [ReplicaSet](https://sourcegraph.com/github.com/kubernetes/kubernetes@9e622d23648f4af4a12835de97484dc0e4859269/-/blob/pkg/controller/replicaset/replica_set.go?L710).

Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:207]: Gotcha, I remember you made a similar improvement for RayService. 

I think we can implement your suggestion in a separate PR to keep the current PR smaller and self-contained, but let me know if you think otherwise.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 2]
```diff
@@ -287,12 +305,143 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+		}
+		metadata := string(metadataBytes)
+
+		k8s_job_command = append(k8s_job_command, "--metadata-json", metadata)
+	}
+
+	// Add jobid to command
+	if len(rayJobInstance.Status.JobId) > 0 {
+		jobid := rayJobInstance.Status.JobId
+		k8s_job_command = append(k8s_job_command, "--job-id", jobid)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:399]: What's this option for?

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 3]
```diff
@@ -287,12 +305,143 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+	}
+
+	submitter_template.Spec.Containers[0].Command = append(k8s_job_command, commandSlice...)
+
+	jobName := rayJobInstance.Name
+	jobNamespace := rayJobInstance.Namespace
+
+	// Create a Job object with the specified name and namespace
+	job := &batchv1.Job{}
+	if err := r.Client.Get(ctx, client.ObjectKey{Namespace: jobNamespace, Name: jobName}, job); err != nil {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:415]: Maybe we should check this at first before setting up `submitter_template`?

**Review by kevin85421 — COMMENTED** [review]
I do not review it thoroughtly. Will take another pass after the version bump.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 4]
```diff
@@ -287,12 +305,143 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
 		}
 	}
 	return ctrl.Result{}, nil
 }
 
+// CreateK8sJob creates a Kubernetes Job for the Ray Job if it doesn't exist, otherwise return the existing one.
+func (r *RayJobReconciler) CreateK8sJob(ctx context.Context, rayJobInstance *rayv1alpha1.RayJob) (string, error) {
+	var submitter_template v1.PodTemplateSpec
+	// Check if SubmitterPodTemplate is not provided
+	if rayJobInstance.Spec.SubmitterPodTemplate == nil {
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:325]: I just wanted `SubmitterPodTemplate` to be optional so that it's less of a burden for users to upgrade their YAML files to the new version.  For example, the v1alpha1 sample YAML doesn't need to be modified at all.

[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:325]: I'm not confident that this is the correct way to handle optional fields though, let me know if you know a better way.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 5]
```diff
@@ -287,12 +305,143 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+		// Set the default value
+		submitter_template = v1.PodTemplateSpec{
+			Spec: v1.PodSpec{
+				Containers: []v1.Container{
+					{
+						Name:  "ray-job-submitter",
+						Image: "rayproject/ray:2.5.0",
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:332]: Oh yeah, good catch, I forgot to update this part.  We should definitely match the image.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 6]
```diff
@@ -287,12 +305,143 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+						Resources: v1.ResourceRequirements{
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:333]: Could you go into a bit more detail here? What default resources would make sense?

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:399]: This passes the Ray Job ID to Ray to define the ID for the new job.  It seems currently in KubeRay we generate a Ray job ID based on the name, plus 5 random letters.  I haven't made any change to this behavior in this PR, previously `job_id` was passed via the HTTP client.  But it's possible we don't need the 5 random letters anymore and we can consider removing it in a future PR.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Fixed

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 3 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Fixed 4b6f489

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Do you mean that for the submitter pod, we should mimic what is done here?

https://github.com/ray-project/kuberay/blob/ecd15399772883c0fcb10ce599ca8fa0e07b85b2/ray-operator/controllers/ray/common/pod.go#L222C2-L222C2

And should we also do the same for `Env`, `VolumeMounts`, and `SecurityContext`?

**Comment by architkulkarni** [comment]
I will create followup issues to track the following future enhancements:
- Use `initContainer` in the k8s job submitter pod to allow the k8s job to be submitted immediately instead of after the RayCluster is ready.  The initContainer will wait for the dashboard to be ready before calling `ray job submit`.  The benefit is that (1) the latency will be cut by up to half, because without this approach we have to wait for the Ray image to load in the ray cluster, and then wait for the Ray image to load again in the job submitter pod.
- Allow waiting for a configurable number of workers to be ready before calling `ray job submit`.  Currently it just waits for the RayCluster to be ready, which means that all pods should be running.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 7]
```diff
@@ -251,6 +259,10 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
 			if err != nil && !errors.IsNotFound(err) {
 				return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, nil
 			}
+			_, err = r.deleteK8sJob(ctx, rayJobInstance)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:262]: Why do we need to delete the Kubernetes Job here if we have set the controller reference (RayCluster is the owner and Job is the dependent)? See https://kubernetes.io/docs/concepts/architecture/garbage-collection/ for more details.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 8]
```diff
@@ -287,10 +299,90 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
 			}
 			r.Log.Info("shutdownAfterJobFinishes set to true, we will delete cluster",
 				"RayJob", rayJobInstance.Name, "clusterName", fmt.Sprintf("%s/%s", rayJobInstance.Namespace, rayJobInstance.Status.RayClusterName))
-			return r.deleteCluster(ctx, rayJobInstance)
+			_, err = r.deleteCluster(ctx, rayJobInstance)
+			if err != nil && !errors.IsNotFound(err) {
+				return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, nil
+			}
+			_, err = r.deleteK8sJob(ctx, rayJobInstance)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:306]: Same

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 9]
```diff
@@ -287,10 +299,90 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+		return "", err
+	}
+
+	// Job already exists, instead of returning an error we return a "success"
+	return jobName, nil
+}
+
+// getSubmitterTemplate builds the submitter pod template for the Ray job.
+func (r *RayJobReconciler) getSubmitterTemplate(rayJobInstance *rayv1alpha1.RayJob) (v1.PodTemplateSpec, error) {
+	var submitter_template v1.PodTemplateSpec
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:341]: This does not appear to follow the coding style. `submitterTemplate`?

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 10]
```diff
@@ -287,10 +299,90 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+
+	// Set the default value for the optional field SubmitterPodTemplate if not provided.
+	if rayJobInstance.Spec.SubmitterPodTemplate == nil {
+		submitter_template = common.GetDefaultSubmitterTemplate(rayJobInstance)
+	} else {
+		submitter_template = *rayJobInstance.Spec.SubmitterPodTemplate.DeepCopy()
+	}
+
+	// Set the command in the submitter pod template.
+	k8s_job_command, err := common.GetK8sJobCommand(rayJobInstance)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:351]: coding style

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 11]
```diff
@@ -287,10 +299,90 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+	if err != nil {
+		return v1.PodTemplateSpec{}, err
+	}
+
+	submitter_template.Spec.Containers[0].Command = k8s_job_command
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:356]: 1. If the command is specified, we should honor it.
2. If we want to hardcode `Containers[0]` as the submitter, we should make users know it (maybe add a log?).

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 12]
```diff
@@ -287,10 +299,90 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+			Name:      rayJobInstance.Name,
+			Namespace: rayJobInstance.Namespace,
+		},
+		Spec: batchv1.JobSpec{
+			Template: submitterTemplate,
+		},
+	}
+
+	// Set the ownership in order to do the garbage collection by k8s.
+	if err := ctrl.SetControllerReference(rayJobInstance, job, r.Scheme); err != nil {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:375]: IIRC, the conclusion of our discussion is that the owner of the Kubernetes Job is RayCluster, not RayJob.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 13]
```diff
@@ -287,10 +299,90 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+		return "", err
+	}
+
+	// Create the Kubernetes Job
+	if err := r.Client.Create(ctx, job); err != nil {
+		return "", err
+	}
+
+	// Return the Job's name
+	return job.Name, nil
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:385]: The `job.name` is not utilized anywhere. Should we return it?

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 14]
```diff
@@ -75,7 +77,7 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
 	var err error
 	var rayJobInstance *rayv1alpha1.RayJob
 	if rayJobInstance, err = r.getRayJobInstance(ctx, request); err != nil {
-		return ctrl.Result{}, client.IgnoreNotFound(err)
+		return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, client.IgnoreNotFound(err)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:80]: In this case, if we delete a RayJob, will it be reconciled indefinitely?

File: ray-operator/controllers/ray/common/job.go [hunk 15]
```diff
@@ -0,0 +1,119 @@
...
+		}
+		k8sJobCommand = append(k8sJobCommand, "--runtime-env-json", runtimeEnvDecoded)
+	}
+
+	if len(metadata) > 0 {
+		metadataJson, err := GetMetadataJson(metadata, rayJobInstance.Spec.RayClusterSpec.RayVersion)
+		if err != nil {
+			return nil, err
+		}
+		k8sJobCommand = append(k8sJobCommand, "--metadata-json", metadataJson)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/common/job.go:78]: What is the purpose of `--metadata-json`?

File: ray-operator/controllers/ray/common/job.go [hunk 16]
```diff
@@ -0,0 +1,119 @@
...
+	}
+	return []string{"ray", "job", "submit", "--address", address}
+}
+
+// GetMetadataJson returns the JSON string of the metadata for the Ray job.
+func GetMetadataJson(metadata map[string]string, rayVersion string) (string, error) {
+	// Check that the Ray version is at least 2.6.0.
+	// If it is, we can use the --metadata-json flag.
+	// Otherwise, we need to raise an error.
+	constraint, _ := semver.NewConstraint(">= 2.6.0")
```
Comment (kevin85421) [inline ray-operator/controllers/ray/common/job.go:39]: Why are we restricted to using `Ray >= 2.6.0`?

**Review by kevin85421 — COMMENTED** [review]
1. What is your strategy for `ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}`? It appears that we are requeueing the custom resource everywhere. I guess the following condition is highly possible to happen:

```go
func a():
   ...
   return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err

func b():
   _, err = a()
   if err != nil
     return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
```

The CR seems to be queued twice.


2. Would you mind adding some tests like: https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/rayservice_controller_unit_test.go

3. Could you test the stability of `test_sample_rayjob_yamls.py`?

File: ray-operator/controllers/ray/common/job.go (hunk 15 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/common/job.go:78]: metadata is an option exposed by the Ray Job API for attaching arbitrary metadata to a Ray job.  `metadata--json` is the API for passing it via the CLI.

File: ray-operator/controllers/ray/common/job.go (hunk 16 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/common/job.go:39]: The `metadata-json` CLI argument was only introduced in Ray 2.6.0.  Prior to Ray 2.6.0, `metadata` could only be passed via the Ray Jobs REST API or Python SDK.  So this could be a breaking change for KubeRay users who use `metadata` and upgrade kuberay to v0.6.0 but don't upgrade Ray to 2.6.0.  I think it's okay because RayJob is still alpha and `metadata` is not a commonly used field. I don't see an easy workaround unfortunately.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 14 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:80]: Yes, based on the discussion on this PR https://github.com/ray-project/kuberay/pull/850#issuecomment-1368094367 it sounds like we are always supposed to requeue, but let me know if the situation for RayJob is different for some reason.  I noticed that without this requeueing, there was a delay of a few minutes before a completed job status was reflected correctly.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 7 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:262]: Yeah, I got the ownership wrong.  RayCluster should be the owner like you said; I'll fix this and remove the deletion

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 17]
```diff
@@ -192,40 +194,46 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
 			return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
 		}
-		return ctrl.Result{}, nil
+		r.Log.Error(err, "failed to get k8s job")
+		err = r.updateState(ctx, rayJobInstance, nil, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusFailedToGetJobStatus, err)
+		return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
+	}
+
+	// Check the current status of ray jobs
+	jobInfo, err := rayDashboardClient.GetJobInfo(ctx, rayJobInstance.Status.JobId)
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:224]: The Kubernetes job status only shows details of the following form: `Pods Statuses:  0 Running / 1 Succeeded / 0 Failed`

The Ray job statuses are similar, but not quite the same: 
https://docs.ray.io/en/latest/cluster/running-applications/job-submission/doc/ray.job_submission.JobStatus.html#ray.job_submission.JobStatus

Plus the Ray JobInfo status message field includes useful information such as the traceback for a failed job.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 18]
```diff
@@ -192,40 +194,46 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
 
-		r.Log.Info("Job successfully submitted", "RayJob", rayJobInstance.Name, "jobId", jobId)
-		r.Recorder.Eventf(rayJobInstance, corev1.EventTypeNormal, "Submitted", "Submit Job %s", jobId)
-		// Here, we directly update to PENDING and emit an event to trigger a new reconcile loop
-		err = r.updateState(ctx, rayJobInstance, jobInfo, rayv1alpha1.JobStatusPending, rayv1alpha1.JobDeploymentStatusRunning, nil)
-		if err != nil {
+	// Check the status of the k8s job and update the RayJobInstance status accordingly.
+	// Get the k8s job
+	k8sJob := &batchv1.Job{}
+	err = r.Client.Get(ctx, types.NamespacedName{Name: jobName, Namespace: rayJobInstance.Namespace}, k8sJob)
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:211]: Good point, I will optimize this

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 19]
```diff
@@ -62,6 +63,7 @@ func NewRayJobReconciler(mgr manager.Manager) *RayJobReconciler {
 // +kubebuilder:rbac:groups=core,resources=serviceaccounts,verbs=get;list;watch;create;delete
 // +kubebuilder:rbac:groups="rbac.authorization.k8s.io",resources=roles,verbs=get;list;watch;create;delete;update
 // +kubebuilder:rbac:groups="rbac.authorization.k8s.io",resources=rolebindings,verbs=get;list;watch;create;delete
+// +kubebuilder:rbac:groups=batch,resources=jobs,verbs=get;list;watch;create;update;patch;delete
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:66]: Good question, I didn't try to optimize this list.  Maybe we only need `get`, `create`, and `delete`, I'll double check on this.

**Comment by architkulkarni** [comment]
> 1. What is your strategy for `ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}`? It appears that we are requeueing the custom resource everywhere. I guess the following condition is highly possible to happen:
> 
> ```go
> func a():
>    ...
>    return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
> 
> func b():
>    _, err = a()
>    if err != nil
>      return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
> ```
> 
> The CR seems to be queued twice.

@kevin85421 I think in this example, the CR is only requeued once, right? The return value from `a` is not actually used.  In general, I think there will only ever be at most one requeue; the top-level function will only ever see at most one `ctrl.Result` value.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 14 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:80]: Do you recommend that the RayJobController watch the k8s job somehow so that a reconciliation is automatically triggered when the k8s job completes? Is this something we need to add or would it happen automatically?

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 9 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Thanks, fixed 6287936

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 11 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Good points, added here 6287936

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 13 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:391]: Actually, we do use it in a few logs.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 7 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Fixed 471f979

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 20]
```diff
@@ -192,40 +194,46 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
-	if jobInfo == nil {
-		// Submit the job if no id set
-		jobId, err := rayDashboardClient.SubmitJob(ctx, rayJobInstance, &r.Log)
-		if err != nil {
-			r.Log.Error(err, "failed to submit job")
-			err = r.updateState(ctx, rayJobInstance, jobInfo, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusFailedJobDeploy, err)
-			return ctrl.Result{}, err
-		}
+	r.Log.Info("K8s job successfully created", "RayJob", rayJobInstance.Name, "jobId", jobName)
+	r.Recorder.Eventf(rayJobInstance, corev1.EventTypeNormal, "Created", "Created k8s job %s", jobName)
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:206]: You're right:
```
Events:
  Type    Reason   Age                    From               Message
  ----    ------   ----                   ----               -------
  Normal  Created  4m34s                  rayjob-controller  Created cluster rayjob-sample-raycluster-p2jt6
  Normal  Created  106s (x24 over 2m35s)  rayjob-controller  Created k8s job rayjob-sample```
```
Let me think about how to fix this.

[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Fixed 874237a

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 21]
```diff
@@ -192,40 +194,46 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
-	r.Log.V(1).Info("RayJob information", "RayJob", rayJobInstance.Name, "jobInfo", jobInfo, "rayJobInstance", rayJobInstance.Status.JobStatus)
-	if jobInfo == nil {
-		// Submit the job if no id set
-		jobId, err := rayDashboardClient.SubmitJob(ctx, rayJobInstance, &r.Log)
-		if err != nil {
-			r.Log.Error(err, "failed to submit job")
-			err = r.updateState(ctx, rayJobInstance, jobInfo, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusFailedJobDeploy, err)
-			return ctrl.Result{}, err
-		}
+	r.Log.Info("K8s job successfully created", "RayJob", rayJobInstance.Name, "jobId", jobName)
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Yup, agree.  Fixed https://github.com/ray-project/kuberay/commit/874237a0e189dff3020bd58b9daf46326d7fe18d

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 22]
```diff
@@ -192,40 +194,46 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
 
-	// Check the current status of ray jobs before submitting.
-	jobInfo, err := rayDashboardClient.GetJobInfo(ctx, rayJobInstance.Status.JobId)
+	// Ensure k8s job has been created
+	jobName, err := r.getOrCreateK8sJob(ctx, rayJobInstance)
 	if err != nil {
-		err = r.updateState(ctx, rayJobInstance, jobInfo, rayJobInstance.Status.JobStatus, rayv1alpha1.JobDeploymentStatusFailedToGetJobStatus, err)
-		// Dashboard service in head pod takes time to start, it's possible we get connection refused error.
-		// Requeue after few seconds to avoid continuous connection errors.
+		r.Log.Error(err, "failed to create k8s job")
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Yup, fixed https://github.com/ray-project/kuberay/commit/874237a0e189dff3020bd58b9daf46326d7fe18d

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:214]: Is it safer to call `Get()` again to get the latest status, or does it not matter because the time in between the two "Get" operations is short enough? I'm not sure of the performance overhead of calling `Get()` twice and if it's worth optimizing.

**Comment by architkulkarni** [comment]
@kevin85421 I will add tests similar to https://github.com/ray-project/kuberay/blob/master/ray-operator/controllers/ray/rayservice_controller_unit_test.go.

I've fixed or responded to all other comments.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: @kevin85421 oh I think this got buried, I'm still unclear on this point. Let me know your thoughts

File: ray-operator/controllers/ray/common/job.go [hunk 23]
```diff
@@ -0,0 +1,119 @@
...
+
+// getDefaultSubmitterTemplate creates a default submitter template for the Ray job.
+func GetDefaultSubmitterTemplate(rayJobInstance *rayv1alpha1.RayJob) v1.PodTemplateSpec {
+	// Use the image of the Ray head to be defensive against version mismatch issues
+	return v1.PodTemplateSpec{
+		Spec: v1.PodSpec{
+			Containers: []v1.Container{
+				{
+					Name:  "ray-job-submitter",
+					Image: rayJobInstance.Spec.RayClusterSpec.HeadGroupSpec.Template.Spec.Containers[0].Image,
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/common/job.go:105]: @kevin85421 is this safe? Is this field guaranteed to be set, or do we need to handle the case where it isn't set somehow?

Comment (architkulkarni) [reply ray-operator/controllers/ray/common/job.go]: Added the ray latest image as a fallaback in case this is missing for some reason.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 18 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:214]: We cannot guarantee that both Get() operations will have the same results, but the inconsistency should be handled by the Kubernetes concurrency model rather than the operator in my understanding.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 17 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:227]: Got it.

**Comment by kevin85421** [comment]
> > 1. What is your strategy for `ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}`? It appears that we are requeueing the custom resource everywhere. I guess the following condition is highly possible to happen:
> > 
> > ```go
> > func a():
> >    ...
> >    return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
> > 
> > func b():
> >    _, err = a()
> >    if err != nil
> >      return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The CR seems to be queued twice.
> 
> @kevin85421 I think in this example, the CR is only requeued once, right? The return value from `a` is not actually used. In general, I think there will only ever be at most one requeue; the top-level function will only ever see at most one `ctrl.Result` value.

Yes, you are correct. According to [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/a784ee78d04bdf216006adfbc313328a0aded88a/pkg/internal/controller/controller.go#L314-L341), only the return value of `Reconcile` can control the WorkQueue behavior.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 14 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:80]: > In this case, if we delete a RayJob, will it be reconciled indefinitely?

I conducted an experiment in #1196. The RayJob resource event will continue to be reconciled indefinitely, even if the RayJob custom resource is deleted.

Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go:80]: @kevin85421 Thanks for running the test!  In this case, is the fix to change this line to `ctrl.Result{}`? Do we need to change back any of the other occurrences as well?

File: ray-operator/controllers/ray/common/job.go [hunk 24]
```diff
@@ -0,0 +1,128 @@
...
+func GetDefaultSubmitterTemplate(rayJobInstance *rayv1alpha1.RayJob) v1.PodTemplateSpec {
+	// Use the image of the Ray head to be defensive against version mismatch issues
+	var image string
+	if rayJobInstance.Spec.RayClusterSpec != nil &&
+		len(rayJobInstance.Spec.RayClusterSpec.HeadGroupSpec.Template.Spec.Containers) > 0 {
+		image = rayJobInstance.Spec.RayClusterSpec.HeadGroupSpec.Template.Spec.Containers[0].Image
+	}
+
+	if len(image) == 0 {
+		image = "rayproject/ray:latest"
```
Comment (kevin85421) [inline ray-operator/controllers/ray/common/job.go:107]: Does `latest` point to the latest stable release?

File: ray-operator/controllers/ray/common/job.go [hunk 25]
```diff
@@ -0,0 +1,128 @@
...
+	}
+	return v1.PodTemplateSpec{
+		Spec: v1.PodSpec{
+			Containers: []v1.Container{
+				{
+					Name:  "ray-job-submitter",
+					Image: image,
+					Resources: v1.ResourceRequirements{
+						Limits: v1.ResourceList{
```
Comment (kevin85421) [inline ray-operator/controllers/ray/common/job.go:116]: It is better to set the same values for `Limits` and `Requests` for stability reasons. Additionally, we should include default memory configurations here.

File: ray-operator/controllers/ray/common/job.go (hunk 24 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/common/job.go:107]: Yes, that's right.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 26]
```diff
@@ -287,10 +298,96 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+func (r *RayJobReconciler) getSubmitterTemplate(rayJobInstance *rayv1alpha1.RayJob) (v1.PodTemplateSpec, error) {
+	var submitterTemplate v1.PodTemplateSpec
+
+	// Set the default value for the optional field SubmitterPodTemplate if not provided.
+	if rayJobInstance.Spec.SubmitterPodTemplate == nil {
+		submitterTemplate = common.GetDefaultSubmitterTemplate(rayJobInstance)
+		r.Log.Info("default submitter template is used")
+	} else {
+		submitterTemplate = *rayJobInstance.Spec.SubmitterPodTemplate.DeepCopy()
+		r.Log.Info("user-provided submitter template is used")
```
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Fixed

File: ray-operator/controllers/ray/common/job.go (hunk 25 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/common/job.go:116]: Fixed.  I used a 1Gi memory configuration, but I'm not too confident about it.  Let me know if you have a better guess for the default.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 14 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:80]: We can refer to the following example provided by the operator-framework.

* https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/
* https://github.com/operator-framework/operator-sdk/blob/b794fe909abc1affa1f28cfb75ceaf3bf79187e6/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L88-L100

Comment (architkulkarni) [reply ray-operator/controllers/ray/rayjob_controller.go]: Thanks for the suggestion! Fixed 2bac395

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go]: We can add memory and CPU at this moment. I believe we have already included them.

File: ray-operator/controllers/ray/common/job.go (hunk 25 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/common/job.go:117]: Which factors influence the memory usage of `ray job submit`?

Comment (architkulkarni) [reply ray-operator/controllers/ray/common/job.go:117]: `ray job submit` just submits an HTTP POST request, and then streams the output logs from the HTTP job server to the terminal using websockets.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 14 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go]: Oh, I guess that on line 99 of `memcached_controller.go`, ctrl.Result{RequeueAfter: ...} should be used instead. The documentation may be outdated, so the changes made in https://github.com/ray-project/kuberay/commit/2bac395595d89ac53caa9e8fb2d1090be20e8537 may not make sense.

https://github.com/operator-framework/operator-sdk/commit/1ad6ff3db60d696bb0dd07553c90947d9bdc828d#diff-50e545e0f0125576d93a2a8f95fafcae3cc3aed35a6c8ad93c723834b809d940

File: ray-operator/controllers/ray/common/job.go (hunk 25 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/common/job.go:117]: Got it. We can benchmark the memory usage with a real-world workload later. Would you mind opening an issue to track the progress?

Comment (architkulkarni) [reply ray-operator/controllers/ray/common/job.go:117]: https://github.com/ray-project/kuberay/issues/1197

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 27]
```diff
@@ -95,14 +105,18 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
 			}
 		}
 
 		r.Log.Info("Remove the finalizer no matter StopJob() succeeds or not.", "finalizer", common.RayJobStopJobFinalizer)
 		controllerutil.RemoveFinalizer(rayJobInstance, common.RayJobStopJobFinalizer)
 		err := r.Update(ctx, rayJobInstance)
-		return ctrl.Result{}, err
+		if err != nil {
+			r.Log.Error(err, "Failed to remove finalizer for RayJob")
+			return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:117]: This line seems to be redundant.

**Review by kevin85421 — APPROVED** [review]
LGTM. Other comments are not that urgent. We can address them later. Would you mind running the configuration test to check the stability? Thanks!

**Comment by architkulkarni** [comment]
Thanks, I ran it a few commits ago and it passed 10/10, and I am in the process of running it again on the most recent commit.

**Comment by kevin85421** [comment]
The CI failure is related to RayJob (https://github.com/ray-project/kuberay/actions/runs/5395187640/jobs/9798627342?pr=1177).

**Comment by architkulkarni** [comment]
The sample YAML test passed 8/10 times on my laptop: https://gist.github.com/architkulkarni/c29c2cbfda6ea89ff0695d430b36184a

The first failure was a failure of `kind delete cluster`, unrelated to this PR.
The second failure was a failure in the number of head pods and worker pods to match.  the expected.  Something weird happenened where it detected 2 head pods and 0 worker pods, instead of 1 head pod and 1 worker pod.  The RayJob itself succeeded though, so this is likely an issue with the test.

However, it seems to be very flaky in CI, so merging this PR would harm productivity. Some investigation:
- In this PR, the six commits prior to 0914a5c all passed the sample YAML test in CI.
- Starting with 0914a5c all commits failed the sample YAML test, and the last commit has failed the test 4+ times.

The commit 0914a5c is almost certainly unrelated, so I think it is more likely the subsequent commit a38a22a.  

If we reduce the memory and CPU limit of the submitter pod, it think it will make the CI test less flaky, but it might be worse for users.  Thoughts?

**Comment by kevin85421** [comment]
> If we reduce the memory and CPU limit of the submitter pod, I think it will make the CI test less flaky, but it might be worse for users. Thoughts?

https://github.com/ray-project/kuberay/commit/a38a22a01c7207b56eaafa21297aa5d3deb1d5c8  => Oh, the GitHub Actions free plan runner only has 2 CPUs, and these 2 CPUs are not fully dedicated to Kubernetes. When we set the CPU resource request to 1 CPU, it makes sense for the test to fail. 

Workaround solution: 

(1) Remove CPU request and limit from this PR 
(2) Open issues to make sure: (a) add CPU configs back before v0.6.0 (b) move the RayJob tests to Buildkite before v0.6.0

> where it detected 2 head pods and 0 worker pods, instead of 1 head pod and 1 worker pod

Does the Pod managed by the Kubernetes Job have labels similar to the head Pod?

**Comment by architkulkarni** [comment]
Great suggestion, I've created the issues.

> Does the Pod managed by the Kubernetes Job have labels similar to the head Pod?

I don't think so. We don't specify any labels in `GetDefaultSubmitterTemplate`.  Is this something we want?

**Comment by architkulkarni** [comment]
Screenshot 2023-06-28 at 9 09 27 AM
The sample YAML test passed 10/10 locally on the latest commit.

The sample YAML test passed in CI on the first try.

The 2.5.0 compatibility test is flaky in general, will restart until it passes.

**Comment by architkulkarni** [comment]
The 2.5.0 test is failing on `test_ray_serve_2`, which is unrelated to this PR.  Plus, the 2.5.0 test passed on the prior commit, where the only difference is the resources specified for the RayJob submitter pod.  

Since the test failure is unrelated, I'll merge this PR.

**Comment by yishangru** [comment]
There is no resource limit specified for the created job. In case of namespaces having resource quota, associated pods cannot be created.

**Comment by kevin85421** [comment]
> There is no resource limit specified for the created job. In case of namespaces having resource quota, associated pods cannot be created.

We are aware of that. Users can set resource limits using `SubmitterPodTemplate` or opt for the nightly KubeRay, which includes #1319.
