### PR TITLE
[Test] Fixing SubmittedFinsihedTimeout e2e test for K8s v1.33+ clusters by setting JobSuccessCriteriaMet in addition to JobComplete

### LINKED ISSUE #4324: [Test] The RayJob test case might fail in k8s 1.33 above
Starting from 1.33, [SuccessPolicy](https://kubernetes.io/blog/2025/05/15/kubernetes-1-33-jobs-success-policy-goes-ga/) is GA.

The test code directly update the job status with completed is forbidden. It prompts the following error message.
```
Unexpected error:
            <*errors.StatusError | 0x1400036b5e0>: 
            Job.batch "submitter-timeout" is invalid: [status.conditions: Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition, status.active: Invalid value: 1: active>0 is invalid for finished job]
            {
                ErrStatus: {
                    TypeMeta: {Kind: "", APIVersion: ""},
                    ListMeta: {
                        SelfLink: "",
                        ResourceVersion: "",
                        Continue: "",
                        RemainingItemCount: nil,
                    },
                    Status: "Failure",
                    Message: "Job.batch \"submitter-timeout\" is invalid: [status.conditions: Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition, status.active: Invalid value: 1: active>0 is invalid for finished job]",
                    Reason: "Invalid",
                    Details: {
                        Name: "submitter-timeout",
                        Group: "batch",
                        Kind: "Job",
                        UID: "",
                        Causes: [
                            {
                                Type: "FieldValueInvalid",
                                Message: "Invalid value: cannot set Complete=True condition without the SuccessCriteriaMet=true condition",
                                Field: "status.conditions",
                            },
                            {
                                Type: "FieldValueInvalid",
                                Message: "Invalid value: 1: active>0 is invalid for finished job",
                                Field: "status.active",
                            },
                        ],
                        RetryAfterSeconds: 0,
                    },
                    Code: 422,
                },
            }
```

The corresponding snippet is
https://github.com/ray-project/kuberay/blob/c3643f7d1f6353950a9b48bbe78f610ba20d7eeb/ray-operator/test/e2erayjob/rayjob_test.go#L398-L410

### Reproduce:

1. Create k8s cluster with version 1.33 above.
2. Setup  the kuberay-operator on this cluster.
3. `go test -timeout 40m -v -run='^TestRayJob$/^RayJob_has_exceed_SubmitterFinishedTimeout$' ./test/e2erayjob `

### PR DESCRIPTION
**Pull request by marosset**
## Why are these changes needed?

Fixes #4324 

SubmitterFinishedTimeout test case fails on K8s v1.33+ clusters because of requirements where setting JobCondition.Complete=True now requires Also setting JobCondition.SuccessCriteriaMet

## Checks

The test case now passes on  on both K8s v1.32.9 and v1.33.3 clusters

```cmd
go test -timeout 40m -v -run='^TestRayJob$/^RayJob_has_exceed_SubmitterFinishedTimeout$' ./test/e2erayjob
=== RUN   TestRayJob
    rayjob_test.go:34: [2026-01-20T16:08:30-08:00] Created ConfigMap test-ns-mzrpb/jobs successfully
=== RUN   TestRayJob/RayJob_has_exceed_SubmitterFinishedTimeout
=== NAME  TestRayJob
    rayjob_test.go:384: [2026-01-20T16:08:30-08:00] Created RayJob test-ns-mzrpb/submitter-timeout successfully
    rayjob_test.go:387: [2026-01-20T16:08:30-08:00] Waiting for RayJob test-ns-mzrpb/submitter-timeout deployment status to be 'Running'
    rayjob_test.go:390: [2026-01-20T16:08:58-08:00] Waiting for Ray job test-ns-mzrpb/submitter-timeout to be actually running in Ray cluster
    rayjob_test.go:395: [2026-01-20T16:09:10-08:00] Waiting for submitter job to be created
    rayjob_test.go:400: [2026-01-20T16:09:10-08:00] Updating submitter job status to complete
    rayjob_test.go:429: [2026-01-20T16:09:10-08:00] Successfully marked submitter job as completed at 2026-01-20 16:09:10.73002736 -0800 PST m=+40.648650692
    rayjob_test.go:435: [2026-01-20T16:09:10-08:00] Waiting for RayJob test-ns-mzrpb/submitter-timeout to exceed SubmitterFinishedTimeout
    test.go:114: [2026-01-20T16:09:43-08:00] Retrieving Pod Container test-ns-mzrpb/submitter-timeout-8mqxq/ray-job-submitter logs
    test.go:94: [2026-01-20T16:09:43-08:00] Creating output directory in parent directory: /home/marosset/src/github.com/marosset/kuberay/ray-operator/_output
    test.go:105: [2026-01-20T16:09:43-08:00] Output directory has been created at: /home/marosset/src/github.com/marosset/kuberay/ray-operator/_output/TestRayJob671593480
    test.go:114: [2026-01-20T16:09:43-08:00] Retrieving Pod Container test-ns-mzrpb/submitter-timeout-vppcc-head-f8xmg/ray-head logs
    test.go:114: [2026-01-20T16:09:43-08:00] Retrieving Pod Container test-ns-mzrpb/submitter-timeout-vppcc-small-group-worker-k7r59/ray-worker logs
--- PASS: TestRayJob (73.89s)
    --- PASS: TestRayJob/RayJob_has_exceed_SubmitterFinishedTimeout (72.85s)
PASS
ok      github.com/ray-project/kuberay/ray-operator/test/e2erayjob      73.909s
```

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [x] Unit tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Review by Future-Outlier — APPROVED** [review]

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 1]
```diff
@@ -401,14 +401,26 @@ env_vars:
...
+				Message:            "Job success criteria met for timeout test",
+			},
+			batchv1.JobCondition{
+				Type:               batchv1.JobComplete,
+				Status:             corev1.ConditionTrue,
+				LastProbeTime:      now,
+				LastTransitionTime: now,
+				Reason:             "Completed",
+				Message:            "Job completed successfully for timeouttest",
+			},
```
Comment (Future-Outlier) [inline ray-operator/test/e2erayjob/rayjob_test.go]:
```suggestion
				Message:            "Job completed successfully for timeout test",
			},
```

**Comment by marosset** [comment]
> Should we also change the code in `rayjob_controller_test.go` and `raycluster_controller_unit_test.go` ?

Let me double check and I can update

**Comment by marosset** [comment]
@Future-Outlier I'll update all the tests in those files to also add the new status.
I noticed that `/bin/setup-envtest list` command only shows support for K8s versions up to v1.30

```bash
./bin/setup-envtest list
(available)  v1.30.0  linux/amd64
(available)  v1.29.3  linux/amd64
(available)  v1.29.1  linux/amd64
(available)  v1.29.0  linux/amd64
(available)  v1.28.3  linux/amd64
(available)  v1.28.0  linux/amd64
(available)  v1.27.1  linux/amd64
(available)  v1.26.1  linux/amd64
(available)  v1.26.0  linux/amd64
(available)  v1.25.0  linux/amd64
(available)  v1.24.2  linux/amd64
(available)  v1.24.1  linux/amd64
(available)  v1.23.5  linux/amd64
(available)  v1.23.3  linux/amd64
(available)  v1.23.1  linux/amd64
(available)  v1.22.1  linux/amd64
(available)  v1.22.0  linux/amd64
(available)  v1.21.4  linux/amd64
(available)  v1.21.2  linux/amd64
(available)  v1.20.2  linux/amd64
(available)  v1.19.2  linux/amd64
(available)  v1.19.0  linux/amd64
(available)  v1.17.9  linux/amd64
(available)  v1.16.4  linux/amd64
(available)  v1.15.5  linux/amd64
(available)  v1.14.1  linux/amd64
(available)  v1.13.1  linux/amd64
(available)  v1.12.3  linux/amd64
(available)  v1.11.0  linux/amd64
(available)  v1.10.1  linux/amd64
```

I can try and add support for newer versions too but think that should be done outside of this PR.
Thoughts?

**Comment by Future-Outlier** [comment]
> @Future-Outlier I'll update all the tests in those files to also add the new status. I noticed that `/bin/setup-envtest list` command only shows support for K8s versions up to v1.30
> 
> ```shell
> ./bin/setup-envtest list
> (available)  v1.30.0  linux/amd64
> (available)  v1.29.3  linux/amd64
> (available)  v1.29.1  linux/amd64
> (available)  v1.29.0  linux/amd64
> (available)  v1.28.3  linux/amd64
> (available)  v1.28.0  linux/amd64
> (available)  v1.27.1  linux/amd64
> (available)  v1.26.1  linux/amd64
> (available)  v1.26.0  linux/amd64
> (available)  v1.25.0  linux/amd64
> (available)  v1.24.2  linux/amd64
> (available)  v1.24.1  linux/amd64
> (available)  v1.23.5  linux/amd64
> (available)  v1.23.3  linux/amd64
> (available)  v1.23.1  linux/amd64
> (available)  v1.22.1  linux/amd64
> (available)  v1.22.0  linux/amd64
> (available)  v1.21.4  linux/amd64
> (available)  v1.21.2  linux/amd64
> (available)  v1.20.2  linux/amd64
> (available)  v1.19.2  linux/amd64
> (available)  v1.19.0  linux/amd64
> (available)  v1.17.9  linux/amd64
> (available)  v1.16.4  linux/amd64
> (available)  v1.15.5  linux/amd64
> (available)  v1.14.1  linux/amd64
> (available)  v1.13.1  linux/amd64
> (available)  v1.12.3  linux/amd64
> (available)  v1.11.0  linux/amd64
> (available)  v1.10.1  linux/amd64
> ```
> 
> I can try and add support for newer versions too but think that should be done outside of this PR. Thoughts?

make sense

**Comment by Future-Outlier** [comment]
cc @rueian to merge

**Comment by marosset** [comment]
I tested the unit tests with a new version of setup-envtest and K8s v1.34.1 and found we also need to set `job.status.StartTime` and `job.status.CompletionTime`.
Both changes are backwards compatible so testing with K8s v1.24 will still work.

After this merges I'll submit a PR to update setup-envtest and bump the default K8s version.
