### PR TITLE
[RayJob] Fix RayJob status reconciliation

### LINKED ISSUE #1478: [Bug]  Job CRD status not updated upon job completion
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When submitting a KubeRay job (ray job CRD) to be executed on a previously provisioned cluster, the ray job status is not set to [v1alpha1.JobStatusSucceeded](https://github.com/z103cb/kuberay/blob/a4e36c63a2d32ea3efeb9a56d5b65cdae2401a92/ray-operator/apis/ray/v1alpha1/rayjob_types.go#L19).

The underlying `batchv1.Job` status is completed.

### Reproduction script

To reproduce the issue:
1. Create k8s cluster
2. Deploy operator (v1.0.0-rc.0+) in default namespace
3. Create `ray-system` namespace: `kubectl create namespace ray-system`
4. Create a KubeRay cluster: kubectl apply -f [cluster.yaml.txt](https://github.com/ray-project/kuberay/files/12866019/cluster.yaml.txt)
5. Wait for cluster to be up an running
6. Create a KubeRay Job: kubectl apply -f [job.yaml.txt](https://github.com/ray-project/kuberay/files/12866095/job.yaml.txt)
7. Watch the job which doesn't have its status updated.

The job `batchv1.Job` has a status of 
```yaml
status:
  completionTime: "2023-10-11T06:56:19Z"
  conditions:
  - lastProbeTime: "2023-10-11T06:56:19Z"
    lastTransitionTime: "2023-10-11T06:56:19Z"
    status: "True"
    type: Complete
  startTime: "2023-10-11T06:55:46Z"
  succeeded: 1
```

Also, deleting the ray job doesn't delete the associated `batchv1.Job`
```sh
kubectl delete rayjob -n ray-system sample-job
# rayjob.ray.io "sample-job" deleted
kubectl get job -n ray-system sample-job

# NAME         COMPLETIONS   DURATION   AGE
# sample-job   1/1           33s        28m
```

### Anything else

Fairly consistent.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### LINKED ISSUE #1480: [Bug]  KubeRay Job CRD doesn't get it's status updated to "Failure"
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When submitting a Kuberay Job (ray job CRD) that is guaranteed to fail, the ray job status is updated to a [JobStatusFailed](https://github.com/z103cb/kuberay/blob/a4e36c63a2d32ea3efeb9a56d5b65cdae2401a92/ray-operator/apis/ray/v1alpha1/rayjob_types.go#L20) with the Status object not being created.

The spawned `batchv1.Job` has its `BackoffLimit` set to the default value of 6, which would cause it to be rerun 6 more times, with the subsequent runs failing with this error message:

```text
2023-10-11 01:08:19,318    INFO cli.py:36 -- Job submission server address: http://sample-cluster-head-svc.ray-system.svc.cluster.local:8265
Traceback (most recent call last):
  File "/home/ray/anaconda3/bin/ray", line 8, in <module>
    sys.exit(main())
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/scripts/scripts.py", line 2498, in main
    return cli()
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/job/cli_utils.py", line 54, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/autoscaler/_private/cli_logger.py", line 856, in wrapper
    return f(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/job/cli.py", line 262, in submit
    job_id = client.submit_job(
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/job/sdk.py", line 231, in submit_job
    self._raise_error(r)
  File "/home/ray/anaconda3/lib/python3.8/site-packages/ray/dashboard/modules/dashboard_sdk.py", line 283, in _raise_error
    raise RuntimeError(
RuntimeError: Request failed with status code 500: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/job/job_head.py", line 287, in submit_job
    resp = await job_agent_client.submit_job_internal(submit_request)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/job/job_head.py", line 80, in submit_job_internal
    await self._raise_error(resp)
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/job/job_head.py", line 68, in _raise_error
    raise RuntimeError(f"Request failed with status code {status}: {error_text}.")
RuntimeError: Request failed with status code 400: Traceback (most recent call last):
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/job/job_agent.py", line 45, in submit_job
    submission_id = await self.get_job_manager().submit_job(
  File "/home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/modules/job/job_manager.py", line 903, in submit_job
    raise ValueError(
ValueError: Job with submission_id failing-sample-job-g5fkm already exists. Please use a different submission_id.
```

The expected behaviour is:
1. The RayJob would have a failed status
2. Only one batchv1.Job would be submitted and not retried.

### Reproduction script

1. Create kind cluster
2. Deploy KubeRay operator
3. Create namespace `ray-system`: `kubectl create namespace ray-system`
4. Create ray cluster using the attached sample: kubectl apply -f
[cluster.yaml.txt](https://github.com/ray-project/kuberay/files/12866682/cluster.yaml.txt)
5. Submit ray job using the attached sample ray job: kubectl apply -f 
[fail_fast_job.yaml.txt](https://github.com/ray-project/kuberay/files/12866705/fail_fast_job.yaml.txt)

After 20 minutes or so the `batchv1.Job` status looks like this:

```yaml
status:
  conditions:
  - lastProbeTime: "2023-10-11T08:27:32Z"
    lastTransitionTime: "2023-10-11T08:27:32Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
  failed: 7
  startTime: "2023-10-11T08:07:29Z"
```

The ray job status is not update. 

Deleting the ray job does not delete the batchv1 job. An odd thing I noticed while looking at the batchv1 job yaml is the owner labels, I suspect they should point to the RayJob instance.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2023-10-11T08:07:29Z"
  generation: 1
  labels:
    controller-uid: 1d40a907-916f-426c-aa60-9c867ac1e389
    job-name: failing-sample-job
  name: failing-sample-job
  namespace: ray-system
  ownerReferences:
  - apiVersion: ray.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: RayCluster
    name: sample-cluster
    uid: 9e997f94-8574-40a1-b12d-b44a15dfaef3
  resourceVersion: "69390"
  uid: 1d40a907-916f-426c-aa60-9c867ac1e389
```

### Anything else

This might related to #1478 and #1233.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by astefanutti**
## Why are these changes needed?

This PR fixes a number of issues related to the reconciliation of the RayJob status.

It also sets RayJob resources as owners of the Kubernetes Jobs that submit Ray jobs via the CLI.

It also addresses the issue of systematic failure upon retry of the job submission reported in #1480, by disabling submission retry altogether,  until a proper solution is found. 
The simplest solution would be to expose the job override option to the CLI, though this requires more thoughts and can be addressed in a separate PR:
https://github.com/ray-project/ray/blob/56affb7e4b5af8b1da7a322fdc6ecc7e2258d522/dashboard/modules/job/job_manager.py#L919

## Related issue numbers

Fixes #1478.
Fixes #1480.

## Checks

- [x] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by astefanutti** [comment]
@z103cb @kevin85421 could you please review?

For the submission id issue upon retry, pointed out in #1480, I suggest we create a separate issue so we can take it from there.

**Comment by astefanutti** [comment]
@z103cb I've added a RayJob with cluster selector sample in 2a56347f8fce7b1b02607d05ad8c100290372499 as you suggested, and that covers the use cases related to your issues.

**Review by z103cb — APPROVED** [review]
@astefanutti thank you for adding the example. This PR is `LGTM`. I have valided that this PR fixes the underlying  issues.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 1]
```diff
@@ -393,19 +403,25 @@ func (r *RayJobReconciler) getSubmitterTemplate(rayJobInstance *rayv1.RayJob) (v
...
+			// The `ray job submit` command fails when submission is retried with the same job ID.
+			// Let's disable backoff retry, until job submission retry effectively works.
+			BackoffLimit: pointer.Int32(0),
+			Template:     submitterTemplate,
 		},
 	}
 
 	// Set the ownership in order to do the garbage collection by k8s.
-	if err := ctrl.SetControllerReference(rayClusterInstance, job, r.Scheme); err != nil {
+	if err := ctrl.SetControllerReference(rayJobInstance, job, r.Scheme); err != nil {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:424]: We might implement retry logic for RayJob in the future. If RayJob retries, it will spawn a new RayCluster and a new K8s Job. Therefore, the controller for the K8s Job should be the RayCluster.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 2]
```diff
@@ -393,19 +403,25 @@ func (r *RayJobReconciler) getSubmitterTemplate(rayJobInstance *rayv1.RayJob) (v
...
 			Namespace: rayJobInstance.Namespace,
+			Labels: map[string]string{
+				common.KubernetesCreatedByLabelKey: common.ComponentName,
+			},
 		},
 		Spec: batchv1.JobSpec{
-			Template: submitterTemplate,
+			// The `ray job submit` command fails when submission is retried with the same job ID.
+			// Let's disable backoff retry, until job submission retry effectively works.
+			BackoffLimit: pointer.Int32(0),
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:418]: We can reduce it, but there will still be cases where the RayCluster doesn't receive the request from the K8s Job.

File: ray-operator/config/samples/ray-job.cluster-selector.yaml [hunk 3]
```diff
@@ -0,0 +1,149 @@
...
+    sys.exit(1)
+---
+# The RayJob, that references the RayCluster into which the Ray job is to be submitted.
+# You can change the entrypoint to fail_fast.py for testing the case where the job fails.
+apiVersion: ray.io/v1
+kind: RayJob
+metadata:
+  name: rayjob-cluster-selector
+spec:
+  clusterSelector:
```
Comment (kevin85421) [inline ray-operator/config/samples/ray-job.cluster-selector.yaml:126]: We do not encourage users to use `clusterSelector`. The better option is to use `ray job submit` to submit a ray job to a RayCluster.

**Review by kevin85421 — COMMENTED** [review]
Thank you for the contribution! Would you mind adding some tests once we achieve the consensus for the code change? Thanks!

File: ray-operator/main.go [hunk 4]
```diff
@@ -39,7 +43,8 @@ var (
 func init() {
 	utilruntime.Must(clientgoscheme.AddToScheme(scheme))
 	utilruntime.Must(rayv1.AddToScheme(scheme))
-	utilruntime.Must(routev1.AddToScheme(scheme))
+	utilruntime.Must(routev1.Install(scheme))
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply ray-operator/main.go:46]: There is no technical difference, but the `AddToScheme` method has been documented as deprecated in this package.

File: ray-operator/main.go [hunk 5]
```diff
@@ -126,15 +131,25 @@ func main() {
 		LeaderElectionID:       "ray-operator-leader",
 	}
 
+	selectorsByObject, err := cacheSelectors()
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply ray-operator/main.go:134]: Currently the informer for batch Jobs resources watches all the Jobs, cluster-wide most of the time. This is not needed, as KubeRay is only interested in the Jobs it creates, and it can raise scalability concerns both for KubeRay (size of the informer cache) and the API server / etcd (watch events).

controller-runtime provide that mechanism to narrow the scope of the informer caches.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 1 above)
Comment (astefanutti) [reply ray-operator/controllers/ray/rayjob_controller.go:424]: I think this will require more thought, depending on the evolution of the retry mechanism, and the RayCluster reuse case. Yet at the moment, as a user, I find it surprising that the Job is not cascade-deleted when I delete the RayJob.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (astefanutti) [reply ray-operator/controllers/ray/rayjob_controller.go:418]: This may depending on the evolution of the retry mechanism longer term, but pragmatically, in the short term, I guess it depends on how likely pre-submission failures are compared to (recoverable) post-submission ones. If the former are more likely, then it'd probably be useful to keep retrying. So maybe a middle ground is to reduce the number of retries from the default, six, to something like two or three. Still it feels like it should be possible to re-submit a job, leveraging the override option from the Ray job manager.

File: ray-operator/main.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/main.go:46]: Would you mind sharing the link of the doc?

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:424]: > Yet at the moment, as a user, I find it surprising that the Job is not cascade-deleted when I delete the RayJob.

Really? It should be deleted. If not, it is a bug. RayJob is the controller reference of the RayCluster, and the RayCluster is the controller reference of the Kubernetes Job. Hence, I expected that the K8s Job should be removed if RayJob is deleted.

Comment (astefanutti) [reply ray-operator/controllers/ray/rayjob_controller.go:424]: Not in the case the RayJob does not own the RayCluster, that is when it's created with a `clusterSelector` field.

Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:424]: Screen Shot 2023-10-19 at 9 53 36 AM

I conducted an experiment, and I do not observe the behavior.

Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:424]: > Not in the case the RayJob does not own the RayCluster, that is when it's created with a clusterSelector field.

Got it. We do not encourage users to use that.

Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:424]: You can ignore the comment at https://github.com/ray-project/kuberay/pull/1539/files#r1365854531. I hadn't seen your reply when I wrote mine.

File: ray-operator/main.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/main.go:134]: What's the difference between 

```go
cache.MultiNamespacedCacheBuilder(watchNamespaces)
```

and 

```go
cache.MultiNamespacedCacheBuilder(watchNamespaces)(config, opts)
```
?

File: ray-operator/main.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/main.go:46]: Is the deprecation only for `route`, or is all of `AddToScheme` deprecated?

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:418]: > So maybe a middle ground is to reduce the number of retries from the default, six, to something like two or three.

Makes sense.

> Still it feels like it should be possible to re-submit a job, leveraging the override option from the Ray job manager.

I cannot get the point. Would you mind explaining it?

**Comment by z103cb** [comment]
> OK, so I guess this sample, updated without `clusterSelector`, would not add much value compared to the existing ones, and should be removed. @z103cb you OK with that? 

I think for as long the option exists in the operator (i.e is not officially deprecated), we should keep this there. Perhaps adding adding a comment in the sample to the effect "Please don't use this, we will deperecate it in the future" would be OK.

@kevin85421 is the encouragement documented somewhere in the operator? I am wondering if I have missed it.

**Comment by z103cb** [comment]
> Screen Shot 2023-10-19 at 9 53 36 AM

I conducted an experiment, and I do not observe the behavior. 

The issue is not related to the "submit job with cluster". In my own experiments that works fine. The issue is around submitting a ray job against a running cluster using the "cluster selector" option.  I have documeted the ways to reproduce the bug(s) this PR addresses in the linked issues. I think is best to address the bug, so things work as expected for the user.

The usefullness of the "job with cluster selector" is debatable, but until is officially deprecated the feature should work.

File: ray-operator/main.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (astefanutti) [reply ray-operator/main.go:46]: It's only for Routes. It doubt the `AddToScheme` method in the `github.com/openshift/api/route/v1` package will be removed anytime soon, yet, that change avoids the warning from IDE / tooling.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (astefanutti) [reply ray-operator/controllers/ray/rayjob_controller.go:418]: >> Still it feels like it should be possible to re-submit a job, leveraging the override option from the Ray job manager.

> I cannot get the point. Would you mind explaining it?

If the submitter job fails "post-submission", i.e., after the first successful `ray job submit` command attempt, any subsequent retry will fail with the `Job with submission_id [...] already exists.` error. If the command could be changed to `ray job submit --overwrite=true`, then it'll fix the issue.

It seems the Ray Job manager has an `overwrite` option: https://github.com/ray-project/ray/blob/56affb7e4b5af8b1da7a322fdc6ecc7e2258d522/dashboard/modules/job/job_manager.py#L919, though it's not currently exposed in the API and CLI.

File: ray-operator/main.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/main.go:46]: Thanks!

**Review by kevin85421 — COMMENTED** [review]
Reply https://github.com/ray-project/kuberay/pull/1539/files#r1366631875:

We specify the submission ID to prevent the same job from being submitted twice in certain edge cases. Any job submission with a duplicate ID will be rejected.

The Kubernetes Job backoff limit aims to ensure that each Ray job is submitted to the RayCluster exactly once. KubeRay has very limited information about the failure: is the failure related to the accessibility of the Ray head?

* Case 1: If the failure is not related to the accessibility of the Ray head, the possible causes may be:
  * **Case 1-1 application-level:** Users' Ray scripts have some bugs. In this case, we should not submit a new job with different submission ID or overwrite it.
  * **Case 1-2 system-level:** For example, a job fails due to the crash of a Ray worker Pod. Users should handle the retry from the application-level logic.

Your sentences are mostly clear. Here's a slightly refined version:

* **Case 2: The Ray head is inaccessible.**
  * **Case 2-1: Ray head becomes inaccessible before receiving the job submission request**: This situation might arise from a network issue between the K8s Job and the Ray head. The K8s Job's `backoffLimit` is designed to handle such cases.
  * **Case 2-2: Ray head crashes after receiving the job submission**: Since GCS fault tolerance only supports Ray Serve, the job's information will be lost if the Ray head crashes. Consequently, using the same submission ID will not lead to a rejection. This can be relieved by the `backoffLimit` or we may implement a retry to delete RayCluster + Job and restart a new RayCluster + Job.
  * **Case 2-3: The network between Ray head and K8s Job is disconnected after the Ray head begins executing the job**: Job submissions with the same submission ID will be rejected to ensure that only one job runs in the cluster at any given time.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:418]: I replied here: https://github.com/ray-project/kuberay/pull/1539#pullrequestreview-1690746497

**Review by kevin85421 — COMMENTED** [review]
Hi @astefanutti @z103cb,

Could you please 

(1) Remove the sample YAML: This encourages users to use `clusterSelector`, which we discourage and may deprecate in the future. Including it in the YAML could complicate potential deprecation.

(2) Set the `BackoffLimit` to non-zero.

I don't want to introduce any new changes related to clusterSelector, such as changing the controller reference or checking the length of ClusterSelector, but the points from you guys also make sense. I am fine with the related code changes, but please remove the sample YAML before the community has a consensus of RayJob in the future.

I will start working on RayJob next week. I hope to begin once this PR is merged to avoid any potential conflicts you might have to resolve. Thanks!

File: ray-operator/main.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/main.go:134]: I need to take a look at what is `SelectorsByObject` before I resolve this thread.

**Review by architkulkarni — COMMENTED** [review]
Thanks for the fix! My main question is about the decision to only reconcile if the job is pending or running.

Also, could you say more about the cause of https://github.com/ray-project/kuberay/issues/1478  "When submitting a KubeRay job (ray job CRD) to be executed on a previously provisioned cluster, the ray job status is not set to [v1alpha1.JobStatusSucceeded](https://github.com/z103cb/kuberay/blob/a4e36c63a2d32ea3efeb9a56d5b65cdae2401a92/ray-operator/apis/ray/v1alpha1/rayjob_types.go#L19)." and how this PR fixes it?

**Review by z103cb — APPROVED** [review]
LGTM

File: ray-operator/main.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (astefanutti) [reply ray-operator/main.go:141]: Inlined as code comment. PTAL.

**Comment by astefanutti** [comment]
@kevin85421 @z103cb 

> (1) Remove the sample YAML: This encourages users to use `clusterSelector`, which we discourage and may deprecate in the future. Including it in the YAML could complicate potential deprecation.

The sample has been removed.

> (2) Set the `BackoffLimit` to non-zero.

The `BackoffLimit` is set to 2, so a same job submission is attempted 3 times at the maximum.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 2 above)
Comment (astefanutti) [reply ray-operator/controllers/ray/rayjob_controller.go]: > The default submitter pod template has RestartPolicyNever, do you happen to know why it was still getting retried before this PR?

@architkulkarni `RestartPolicy` controls the kubelet behaviour when a container exits within a Pod. With  `RestartPolicyNever` the Pod is failed, while with `RestartPolicyAlways` for example, the container is restarted in-place. `BackoffLimit` on the hand controls the Job controller behaviour on Pod failure, specifically the maximum number of time a Job Pod should be recreated before failing the Job. So you can have `RestartPolicyNever` and  still have the ray job submission retried when `BackoffLimit` is not zero.

**Comment by astefanutti** [comment]
> We specify the submission ID to prevent the same job from being submitted twice in certain edge cases. Any job submission with a duplicate ID will be rejected.

> The Kubernetes Job backoff limit aims to ensure that each Ray job is submitted to the RayCluster exactly once. KubeRay has very limited information about the failure: is the failure related to the accessibility of the Ray head?

@kevin85421 if the `ray job submit` command would return a specific code upon execution with an already submitted id (like already exists), one solution would be to set a [Pod failure policy](https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-failure-policy) in the submitter Job, .e.g.:

```yaml
apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: ray-job-submitter
        command:
        - ray
        - job
        - submit
  podFailurePolicy:
    rules:
    - action: FailJob
      onExitCodes:
        containerName:
        operator: In
        values: [<already exists code>]
```

So the Job would not be retry at all in that case we know it's unrecoverable.

I can check what are the Ray job CLI return codes if you think that's worth exploring.

**Comment by astefanutti** [comment]
> Also, could you say more about the cause of #1478 "When submitting a KubeRay job (ray job CRD) to be executed on a previously provisioned cluster, the ray job status is not set to [v1alpha1.JobStatusSucceeded](https://github.com/z103cb/kuberay/blob/a4e36c63a2d32ea3efeb9a56d5b65cdae2401a92/ray-operator/apis/ray/v1alpha1/rayjob_types.go#L19)." and how this PR fixes it?

@architkulkarni the cause was that early return statement, removed with 383aaf13d7b1e18577831d77b463e3d2bfa1e2c3, that was preventing the status update from happening, so the Id in the Job status, which is relied on in the remaining logic, was never persisted.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 6]
```diff
@@ -324,11 +327,18 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
 	}
-	return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, nil
+
+	if isJobPendingOrRunning(rayJobInstance.Status.JobStatus) {
+		// Requeue the RayJob to poll its status from the running Ray job
+		return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, nil
+	}
+	// Otherwise only reconcile the RayJob upon new events for watched resources
+	// to avoid infinite reconciliation.
+	return ctrl.Result{}, nil
```
[the remark this answers is not in the document]
Comment (astefanutti) [reply ray-operator/controllers/ray/rayjob_controller.go:337]: This only changes the behaviour for RayJobs in terminal state. To be on the safe side, this keeps the requeueing / polling logic for RayJobs in "RayCluster deployment" phase, as well as for RayJobs in running state.  

Generally, it's a desired property from the performance / scalability standpoint to have controllers converging into a stationary state, that reacts to events, rather than entering an infinite loop, with a polling rate as small as `RayJobDefaultRequeueDuration`, which defaults to 3s.

For terminal states, I think it's safe to assume that no events are going to be missed, otherwise it's a bug that can be fixed. And to mitigate any discrepancy, the `SyncPeriod` manager option could be changed from the default, 10 hours, to something of an order of magnitude lower, even down to a few 10s of minutes.

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 7]
```diff
@@ -324,7 +327,14 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
 			}
 		}
 	}
-	return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, nil
+
+	if isJobPendingOrRunning(rayJobInstance.Status.JobStatus) {
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayjob_controller.go:331]: Is there a possibility that `JobStatus` is empty at this point, causing it to `return ctrl.Result{}, nil`?

File: ray-operator/main.go [hunk 8]
```diff
@@ -126,50 +131,66 @@ func main() {
...
+	// Manager Cache
+	// Set the informers label selectors to narrow the scope of the resources being watched and cached.
+	// This improves the scalability of the system, both for KubeRay itself by reducing the size of the
+	// informers cache, and for the API server / etcd, by reducing the number of watch events.
+	// For example, KubeRay is only interested in the batch Jobs it creates when reconciling RayJobs,
+	// so the controller sets the app.kubernetes.io/created-by=kuberay-operator label on any Job it creates,
+	// and that label is provided to the manager cache as a selector for Job resources.
+	selectorsByObject, err := cacheSelectors()
+	exitOnError(err, "unable to create cache selectors")
+	if watchNamespaces := strings.Split(watchNamespace, ","); len(watchNamespaces) == 1 { // It is not possible for len(watchNamespaces) == 0 to be true. The length of `strings.Split("", ",")`` is still 1.
```
Comment (kevin85421) [inline ray-operator/main.go:143]:
```suggestion
	if watchNamespaces := strings.Split(watchNamespace, ","); len(watchNamespaces) == 1 { // It is not possible for len(watchNamespaces) == 0 to be true. The length of `strings.Split("", ",")` is still 1.
```

**Comment by architkulkarni** [comment]
> > if the ray job submit command would return a specific code upon execution with an already submitted id (like already exists), one solution would be to set a [Pod failure policy](https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-failure-policy) in the submitter Job, .e.g.:
> 
> @astefanutti Thank you for this recommendation! This feature was first introduced in K8s 1.25 as an alpha feature, so this would be a breaking change for KubeRay. We may consider to revisit this after 3 K8s major releases.

I agree. Right now the Ray job CLI doesn't return any special error codes (the CLI code just raises a Python exception, which I believe is return code 1), but I think we can update Ray to return a special error code here and the change should be relatively uncontroversial

**Review by architkulkarni — APPROVED** [review]
Looks good to me! (pending Kai-Hsun's last question about JobStatus being empty)

**Comment by kevin85421** [comment]
>  I agree. Right now the Ray job CLI doesn't return any special error codes (the CLI code just raises a Python exception, which I believe is return code 1), but I think we can update Ray to return a special error code here and the change should be relatively uncontroversial

Ideally, this should be the case, but I believe there's a significant challenge for Ray to return a meaningful exit code at this moment. For example, if the Ray C++ binary exits the process with a non-zero exit code, not all code paths in Ray's Python code catch that exit code.

**Comment by architkulkarni** [comment]
That's true for propagating error codes in general, but here we're talking about just returning an error for the specific case of submitting a job_id which has already been submitted ([which we already have a check for](https://github.com/ray-project/ray/blob/56affb7e4b5af8b1da7a322fdc6ecc7e2258d522/dashboard/modules/job/job_manager.py#L923)).  We could have the job manager raise a special exception here instead of `ValueError`, and make the HTTP job server could check for that exception and return a special HTTP response code, and the CLI could check for that and exit with a special error code.

**Comment by kevin85421** [comment]
> That's true for propagating error codes in general, but here we're talking about just returning an error for the specific case of submitting a job_id which has already been submitted ([which we already have a check for](https://github.com/ray-project/ray/blob/56affb7e4b5af8b1da7a322fdc6ecc7e2258d522/dashboard/modules/job/job_manager.py#L923)). We could have the job manager raise a special exception here instead of `ValueError`, and make the HTTP job server could check for that exception and return a special HTTP response code, and the CLI could check for that and exit with a special error code.

Understood. I hadn't noticed that. I thought that we wanted to use exit codes to categorize all cases as mentioned in https://github.com/ray-project/kuberay/pull/1539#pullrequestreview-1690746497.

File: ray-operator/main.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/main.go:141]: > Currently the informer for batch Jobs resources watches all the Jobs, cluster-wide most of the time.

I want to double-check this statement. Are you saying that the informer still watches K8s Jobs from all namespaces even if we specify only one namespace in `watchNamespaces`?

[the remark this answers is not in the document]
Comment (astefanutti) [reply ray-operator/main.go:141]: I meant that when the `watch-namespace` CLI option is not provided, which I assumed is the most general case, then the informer watches all the Kubernetes Jobs for all namespaces.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 7 above)
Comment (astefanutti) [reply ray-operator/controllers/ray/rayjob_controller.go:332]: The only path, other than when the RayJob is in a terminal state, is the reconciliation cycle where the Kubernetes Job is created. However, now that this Job is watched, further reconciliation is guaranteed.

That being said, I've added an extra change in f7b639bf8bda205f739c6331d6b02fa0a093870c that initialises the Job status, instead of eventually have it updated once the ray job has started. This is generally a best practice, and it'll make sure periodic reconciliation will be triggered when `isJobPendingOrRunning` is true.

File: ray-operator/main.go (hunk 8 above)
Comment (astefanutti) [reply ray-operator/main.go]: Done.

File: ray-operator/controllers/ray/rayjob_controller.go (hunk 7 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayjob_controller.go:332]: Great!

**Review by kevin85421 — APPROVED** [review]
LGTM. Thank @astefanutti for this contribution! I will merge this PR. Would you mind opening a follow-up PR to add tests for this PR?

**Comment by blublinsky** [comment]
LGTM

**Comment by astefanutti** [comment]
> LGTM. Thank @astefanutti for this contribution! I will merge this PR. Would you mind opening a follow-up PR to add tests for this PR?

@kevin85421 Thanks. Sure, I'll work on the tests ASAP.
