### PR TITLE
Fix file matching in Aliyun OSS GetContent

### LINKED ISSUE #4690: [Bug][History Server] OSS GetContent failed to get object due to key not found
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

historyserver

### What happened + What you expected to happen

The History Server fails to retrieve Ray events files from Alibaba Cloud OSS storage. When attempting to get log files (e.g., `event_RAYLET.log`, `event_AUTOSCALER.log`), the following errors occur:

```
time="2026-04-10T08:09:40Z" level=error msg="Failed to get object session_2026-04-09_06-41-42_754637_1/logs/ad7c5ae15a841446b2417b2d0b2a4c1c1b3093dbb70c6140604dcbd8/events/event_RAYLET.log: oss: service returned error: StatusCode=404, ErrorCode=NoSuchKey, ErrorMessage=\"The specified key does not exist.\", RequestId=69D8B044C4CCB13734EA5xxx, Ec=0026-00000001"
time="2026-04-10T08:09:40Z" level=error msg="Failed to get object by list all files session_2026-04-09_06-41-42_754637_1/logs/ad7c5ae15a841446b2417b2d0b2a4c1c1b3093dbb70c6140604dcbd8/events/event_RAYLET.log"
time="2026-04-10T08:09:40Z" level=error msg="Failed to get object session_2026-04-09_06-41-42_754637_1/logs/c8115debd2e5e64828da9697b78ed96fc6bea228b625fe90b39e00bb/events/event_RAYLET.log: oss: service returned error: StatusCode=404, ErrorCode=NoSuchKey, ErrorMessage=\"The specified key does not exist.\", RequestId=69D8B044C4CCB137345D6xxx, Ec=0026-00000001"
time="2026-04-10T08:09:40Z" level=error msg="Failed to get object by list all files session_2026-04-09_06-41-42_754637_1/logs/c8115debd2e5e64828da9697b78ed96fc6bea228b625fe90b39e00bb/events/event_RAYLET.log"
time="2026-04-10T08:09:40Z" level=error msg="Failed to get object session_2026-04-09_06-36-04_133938_1/logs/34a3db93a0fec0166ea2abc7970ec4b1318d685aef7b722c570f3f66/events/event_AUTOSCALER.log: oss: service returned error: StatusCode=404, ErrorCode=NoSuchKey, ErrorMessage=\"The specified key does not exist.\", RequestId=69D8B044C4CCB137345D6xxx, Ec=0026-00000001"
```

The `GetContent` method should successfully retrieve log files from OSS storage. When the initial `GetObject` request fails with a 404 error (due to path mismatch), the fallback logic should correctly find and retrieve the file by listing all files in the directory.

### Reproduction script

1. Deploy History Server with Alibaba Cloud OSS as the storage backend
2. Create a Ray cluster that generates logs to OSS storage
3. Observe the error logs showing `Failed to get object`

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by utafrali**
## Why are these changes needed?

The issue was in the file matching logic. GetContent was comparing path.Base(f) against the full fileName path, so it would never match. Fixed by comparing basenames on both sides. Also added the found flag and break to exit early once we find the right file.

## Related issue number

Fixes #4690

## Checks
- [x] I've made sure the tests are passing.
- Testing Strategy
  - [x] Unit tests
  - [ ] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Review by Future-Outlier — COMMENTED** [review]
cc @ChenYi015 to take a look

**Comment by ChenYi015** [comment]
LGTM.

**Review by Future-Outlier — APPROVED** [review]
since @ChenYi015 is the maintainer of the Aliyun storage module, I approve this PR

File: historyserver/pkg/storage/aliyunoss/ray/ray.go [hunk 1]
```diff
@@ -193,13 +193,15 @@ func (r *RayLogsHandler) GetContent(clusterId string, fileName string) io.Reader
 		allFiles := r._listFiles(clusterId+"/"+path.Dir(fileName), "", false)
 		found := false
 		for _, f := range allFiles {
-			if path.Base(f) == fileName {
+			if path.Base(f) == path.Base(fileName) {
 				logrus.Infof("Get object %s info success", f)
 				body, err = r.OssBucket.GetObject(f, options...)
 				if err != nil {
 					logrus.Errorf("Failed to get object %s: %v", f, err)
 					return nil
```
Comment (andrewsykim) [inline historyserver/pkg/storage/aliyunoss/ray/ray.go:201]: why return nil when err is not nil?

**Comment by utafrali** [comment]
Right, fixing that
