### PR TITLE
[Autoscaler][Test] Fix flaky idleTimeoutSeconds test

### LINKED ISSUE #2858: [Autoscaler] Follow up of #2725
### Search before asking

- [x] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/kuberay/pull/2725#pullrequestreview-2580154224

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ryanaoleary**
## Why are these changes needed?

This PR reconfigures the `TestRayClusterAutoscalerV2IdleTimeout` test based on the comments in https://github.com/ray-project/kuberay/pull/2725#pullrequestreview-2580154224. Additionally, this PR fixes the test flakiness by adding a `timeoutBuffer` of 20 seconds when checking for replica scale down.

Viewing the test logs confirms that the autoscaler is correctly using the custom `idleTimeoutSeconds` and marking the nodes as idle, but for whatever reason `RayClusterDesiredWorkerReplicas` takes an additional ~10-15 seconds to update and scale down the replica.

Autoscaler container logs:
```
2025-01-29 14:21:03,820 INFO event_logger.py:76 -- Removing 1 nodes of type short-idle-timeout-group (idle).
2025-01-29 14:21:03,821 - INFO - Update instance RAY_RUNNING->RAY_STOP_REQUESTED (id=d71be9f4-3f7e-4aa8-9f1e-d8f1515addf3, type=short-idle-timeout-group, cloud_instance_id=ray-cluster-short-idle-timeout-group-worker-b8gb4, ray_id=425712ae84330c7076dc229d23e4f7ec3faa236a811105bc78d938e2): draining ray: idle for 10.112 secs > timeout=10.0 secs
2025-01-29 14:21:03,821 INFO instance_manager.py:262 -- Update instance RAY_RUNNING->RAY_STOP_REQUESTED (id=d71be9f4-3f7e-4aa8-9f1e-d8f1515addf3, type=short-idle-timeout-group, cloud_instance_id=ray-cluster-short-idle-timeout-group-worker-b8gb4, ray_id=425712ae84330c7076dc229d23e4f7ec3faa236a811105bc78d938e2): draining ray: idle for 10.112 secs > timeout=10.0 secs
...
2025-01-29 14:21:44,390 - INFO - Removing 1 nodes of type long-idle-timeout-group (idle).
2025-01-29 14:21:44,390 INFO event_logger.py:76 -- Removing 1 nodes of type long-idle-timeout-group (idle).
2025-01-29 14:21:44,390 - INFO - Update instance RAY_RUNNING->RAY_STOP_REQUESTED (id=80d7b407-37c7-4023-b782-e4bb1b83a0f5, type=long-idle-timeout-group, cloud_instance_id=ray-cluster-long-idle-timeout-group-worker-tddgr, ray_id=2534f2c1e558c801603199a886237123c2726a765df364769ba9fc01): draining ray: idle for 33.597 secs > timeout=30.0 secs
``` 

## Related issue number

https://github.com/ray-project/kuberay/issues/2561
Closes #2858

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
   - [x] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ryanaoleary** [comment]
cc: @kevin85421 @rueian

File: ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go [hunk 1]
```diff
@@ -368,57 +368,75 @@ func TestRayClusterAutoscalerV2IdleTimeout(t *testing.T) {
...
 
 		headPod, err := GetHeadPod(test, rayCluster)
 		g.Expect(err).NotTo(gomega.HaveOccurred())
 		test.T().Logf("Found head pod %s/%s", headPod.Namespace, headPod.Name)
 
-		// After customIdleTimeoutSeconds, the replica in the worker group with custom idleTimeoutSeconds set should be scaled down.
-		g.Eventually(RayCluster(test, rayCluster.Namespace, rayCluster.Name), time.Duration(customIdleTimeoutSeconds)*time.Second).
+		// Deploy one detached actor on each worker group. This is guaranteed by setting `maxReplicas` and specifying respective num-cpus.
+		ExecPodCmd(test, headPod, common.RayHeadContainer, []string{"python", "/home/ray/test_scripts/create_detached_actor.py", "actor-short-timeout", "--num-cpus=1"})
+		ExecPodCmd(test, headPod, common.RayHeadContainer, []string{"python", "/home/ray/test_scripts/create_detached_actor.py", "actor-long-timeout", "--num-cpus=2"})
```
Comment (rueian) [inline ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go:426]: I think the `--num-cpus=2` actor should be deployed first; otherwise, it could be blocked by another actor for insufficient cpus in group 2.

Comment (ryanaoleary) [reply ray-operator/test/e2eautoscaler/raycluster_autoscaler_test.go:425]: [507bead](https://github.com/ray-project/kuberay/pull/2862/commits/507bead25f68fbc18787604f4ceeed02d1ce1124)

**Review by rueian — APPROVED** [review]

**Review by kevin85421 — APPROVED** [review]
