### PR TITLE
[Bug][RayJob] Sidecar mode shouldn't restart head pod when head pod is deleted

### LINKED ISSUE #4176: [Bug][RayJob] Sidecar mode shouldn't restart head pod when head pod is deleted
In this [PR](https://github.com/ray-project/kuberay/pull/4141), we fail the RayJob if the RayCluster is provisioned. However, this is a breaking change since we shouldn’t include other modes like K8sJobMode or HTTPMode.
One possible solution is to add a label or annotation to identify whether the RayCluster is from RayJob’s sidecar mode or not, then fail the RayJob if needed.

### PR DESCRIPTION
**Pull request by 400Ping**
## Why are these changes needed?
In this [PR](https://github.com/ray-project/kuberay/pull/4141), we fail the RayJob if the RayCluster is provisioned. However, this is a breaking change since we shouldn’t include other modes like K8sJobMode or HTTPMode.

## Related issue number

Closes #4176 
## Checks

- [ ] I've made sure the tests are passing.
- Testing Strategy
  - [ ] Unit tests
  - [ ] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by 400Ping** [comment]
From my understanding the failed CI is not related to the changes in this PR?

**Comment by 400Ping** [comment]
cc @Future-Outlier @rueian PTAL

**Review by Future-Outlier — COMMENTED** [review]
Hi, @400Ping 
let us know if you need any help, plz ping us

**Comment by 400Ping** [comment]
Ok, will do thanks.

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -692,13 +691,12 @@ func (r *RayClusterReconciler) reconcilePods(ctx context.Context, instance *rayv
...
 			// In this case, the worker Pods will not be killed by the new head Pod when it is created, but the submission ID has already been
 			// used by the old Ray job, so the new Ray job will fail.
-			if meta.IsStatusConditionTrue(instance.Status.Conditions, string(rayv1.RayClusterProvisioned)) {
-				logger.Info(
-					"reconcilePods: Found 0 head Pods for a RayJob-managed RayCluster; skipping head creation to let RayJob controller handle the failure",
-					"rayCluster", instance.Name,
-				)
-				return nil
-			}
+			meta.IsStatusConditionTrue(instance.Status.Conditions, string(rayv1.RayClusterProvisioned)) {
```
Comment (rueian) [inline ray-operator/controllers/ray/raycluster_controller.go]: The if statement got split too far apart. could you reunite them?

Comment (400Ping) [reply ray-operator/controllers/ray/raycluster_controller.go]: Is this a97a3b517e39b8e5510fdf2b3066ba66c7e8d30f what you want?

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 2]
```diff
@@ -300,20 +302,28 @@ env_vars:
...
+		g.Eventually(func() int {
+			pods, listErr := test.Client().Core().CoreV1().Pods(rayCluster.Namespace).List(
+				test.Ctx(), common.RayClusterHeadPodsAssociationOptions(rayCluster).ToMetaV1ListOptions())
+			if listErr != nil {
+				return -1
+			}
+			return len(pods.Items)
+		}, TestTimeoutMedium, 2*time.Second).Should(Equal(1))
+		g.Consistently(RayJob(test, rayJob.Namespace, rayJob.Name), TestTimeoutShort).
+			ShouldNot(WithTransform(RayJobDeploymentStatus, Equal(rayv1.JobDeploymentStatusFailed)))
```
Comment (rueian) [inline ray-operator/test/e2erayjob/rayjob_test.go]: image
 CI keeps failing

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 3]
```diff
@@ -109,6 +109,18 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+		rayJobInstance.ObjectMeta.DeletionTimestamp.IsZero() &&
+		addSidecarDisableHeadRestartLabel(rayJobInstance) {
+		logger.Info("Add label to disable head Pod recreation for sidecar-mode RayJob",
+			"label", utils.RayJobDisableHeadNodeRestartLabelKey)
+		if err := r.Update(ctx, rayJobInstance); err != nil {
+			logger.Error(err, "Failed to update RayJob labels")
+			return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, err
+		}
+		return ctrl.Result{RequeueAfter: RayJobDefaultRequeueDuration}, nil
+	}
```
Comment (Future-Outlier) [inline ray-operator/controllers/ray/rayjob_controller.go]: We should delete this, we can handle this in validation.go and `getOrCreateRayClusterInstance`
```suggestion
```

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 4]
```diff
@@ -973,6 +999,28 @@ func (r *RayJobReconciler) constructRayClusterForRayJob(rayJobInstance *rayv1.Ra
...
+func ensureRayClusterHasSidecarDisableHeadRestartLabel(rayCluster *rayv1.RayCluster) bool {
+	if rayCluster.Labels == nil {
+		rayCluster.Labels = map[string]string{}
+	}
+	if _, exists := rayCluster.Labels[utils.RayJobDisableHeadNodeRestartLabelKey]; exists {
+		return false
+	}
+	rayCluster.Labels[utils.RayJobDisableHeadNodeRestartLabelKey] = "true"
+	return true
+}
```
Comment (Future-Outlier) [inline ray-operator/controllers/ray/rayjob_controller.go]: I think we can delete this and let 
https://github.com/ray-project/kuberay/pull/4234/files#diff-f10777dd022e918221782f3ea3f88c70293404f9e62ded13cbad66b68c6d19efR964-R968

handle it

**Comment by Future-Outlier** [comment]
> cc @win5923 @machichima @AndySung320 to take over the e2e test part, thank you!

also cc @seanlaii to take a look, thank you!

File: ray-operator/controllers/ray/utils/constant.go [hunk 5]
```diff
@@ -28,6 +28,9 @@ const (
 	KubeRayVersion                           = "ray.io/kuberay-version"
 	RayCronJobNameLabelKey                   = "ray.io/cronjob-name"
 	RayCronJobTimestampAnnotationKey         = "ray.io/cronjob-scheduled-timestamp"
+	RayJobSubmissionModeLabelKey             = "ray.io/job-submission-mode"
```
Comment (machichima) [inline ray-operator/controllers/ray/utils/constant.go:32]: Curious, why we need this label? Seems like we are not using it?

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 6]
```diff
@@ -289,6 +290,7 @@ env_vars:
 		rayJob, err := test.Client().Ray().RayV1().RayJobs(namespace.Name).Apply(test.Ctx(), rayJobAC, TestApplyOptions)
 		g.Expect(err).NotTo(HaveOccurred())
 		LogWithTimestamp(test.T(), "Created RayJob %s/%s successfully", rayJob.Namespace, rayJob.Name)
+		g.Expect(rayJob.Labels).To(Not(HaveKey(utils.RayJobDisableProvisionedHeadNodeRestartLabelKey)))
```
Comment (machichima) [inline ray-operator/test/e2erayjob/rayjob_test.go]: I think we do not need this? This label will only be added in RayCluster

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 7]
```diff
@@ -300,20 +302,28 @@ env_vars:
 		g.Expect(err).NotTo(HaveOccurred())
 		rayCluster, err := GetRayCluster(test, rayJob.Namespace, rayJob.Status.RayClusterName)
 		g.Expect(err).NotTo(HaveOccurred())
+		g.Expect(rayCluster.Labels).To(Not(HaveKeyWithValue(utils.RayJobDisableProvisionedHeadNodeRestartLabelKey, "true")))
```
Comment (machichima) [inline ray-operator/test/e2erayjob/rayjob_test.go]: I think we can use following as `RayJobDisableProvisionedHeadNodeRestartLabelKey ` will always be set?
```suggestion
		
g.Expect(rayCluster.Labels[utils.RayJobDisableProvisionedHeadNodeRestartLabelKey]).To(Equal("false"))
```

File: ray-operator/test/e2erayjob/rayjob_test.go (hunk 2 above)
Comment (machichima) [reply ray-operator/test/e2erayjob/rayjob_test.go]: I think when the head pod is deleted in default `k8sJobMode`, we will get into following block and the job deployment status will still be `Failed`. Don't know if this is the expected behavior?

https://github.com/ray-project/kuberay/blob/2464704798ae955f37378556afbe77aa66c43710/ray-operator/controllers/ray/rayjob_controller.go#L302-L307

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 8]
```diff
@@ -279,7 +280,7 @@ env_vars:
 			To(WithTransform(RayJobReason, Equal(rayv1.DeadlineExceeded)))
 	})
 
-	test.T().Run("RayJob fails when head Pod is deleted when job is running", func(_ *testing.T) {
+	test.T().Run("RayJob recreates head Pod when deleted while running", func(_ *testing.T) {
```
Comment (AndySung320) [inline ray-operator/test/e2erayjob/rayjob_test.go]: Minor suggestion on wording:
Instead of `"RayJob recreates head Pod when deleted while running"`,
consider `"RayJob controller recreates the head Pod if it is deleted while the job is running"`, since the reconciliation is handled by the controller.

File: ray-operator/controllers/ray/utils/constant.go (hunk 5 above)
Comment (Future-Outlier) [reply ray-operator/controllers/ray/utils/constant.go:32]: because we want to let user know only sidecar mode will not provision head pod twice

**Comment by Future-Outlier** [comment]
Hi, @400Ping 
plz ping @win5923 and @fscnick when you finish the test, thank you!

**Comment by 400Ping** [comment]
Ok, thanks

File: ray-operator/test/e2erayjob/rayjob_test.go (hunk 2 above)
Comment (win5923) [reply ray-operator/test/e2erayjob/rayjob_test.go]: I think I now understand why this logic is written this way, we currently have two scenarios:

1. The RayJob loses its head pod before the ray job is submitted.
2. The RayJob loses its head pod after the ray job has already been submitted. 

For scenario 1:

When the head Pod is deleted while the submitter Pod is attempting to submit the ray job, the submitter encounters a WebSocket connection failure and exits with a non-zero exit code. The K8s Job then creates a new submitter Pod to retry (the `submitterBackoffLimit` default is 2).

https://github.com/ray-project/kuberay/blob/dea5baa8a0a009c80d8e274eff1201b97554e9e2/ray-operator/controllers/ray/rayjob_controller.go#L663-L665

Meanwhile, the RayCluster controller recreates the head Pod and worker Pods (only sidecar mode skips head Pod restart). 

If the new head Pod becomes ready before the K8s Job reaches backoffLimit, the new submitter Pod could successfully submit the ray job, and the RayJob could eventually transition to `JobDeploymentStatusComplete` with `JobStatus` = `JobStatusSucceeded`.  But this is need a good luck.

For Scenario 2: 
When the head Pod is deleted after the ray job has already been submitted, the K8s Job is marked as Completed because the Pod exits with exit code 0, even though the ray job itself has not completed.

And then, when the controller tries to query the ray job status via GetJobInfo, it returns BadRequest (job not found). The RayJob will transition `JobDeploymentStatusFailed` with `JobStatus` = `JobStatusFailed`. (This is fix by https://github.com/ray-project/kuberay/issues/3860)

https://github.com/ray-project/kuberay/blob/dea5baa8a0a009c80d8e274eff1201b97554e9e2/ray-operator/controllers/ray/rayjob_controller.go#L289-L306

If not returns BadRequest then goes to `JobDeploymentStatusTransitionGracePeriodExceeded`. 

https://github.com/ray-project/kuberay/blob/dea5baa8a0a009c80d8e274eff1201b97554e9e2/ray-operator/controllers/ray/rayjob_controller.go#L1138-L1161

Comment (win5923) [reply ray-operator/test/e2erayjob/rayjob_test.go]: As Kai-Hsun mentioned in slack, I think we can simply remove this line, since the behavior in Scenario 1 is not reliable.

> I think it is pretty rare, and typically it will hit backoffLimit before the new Pod is ready and the whole cluster needs to restart. A lot of potential unexpected behavior here. Users should not rely on it.

https://ray.slack.com/archives/C07M825T94Z/p1762216441714309?thread_ts=1761694399.867989&cid=C07M825T94Z

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 9]
```diff
@@ -300,20 +302,28 @@ env_vars:
...
+		g.Consistently(RayJob(test, rayJob.Namespace, rayJob.Name), TestTimeoutShort).
+			ShouldNot(WithTransform(RayJobDeploymentStatus, Equal(rayv1.JobDeploymentStatusFailed)))
 		g.Eventually(RayJob(test, rayJob.Namespace, rayJob.Name), TestTimeoutMedium).
-			Should(WithTransform(RayJobReason, Or(
-				Equal(rayv1.JobDeploymentStatusTransitionGracePeriodExceeded),
-				Equal(rayv1.SubmissionFailed),
-			)))
+			Should(WithTransform(func(job *rayv1.RayJob) rayv1.JobDeploymentStatus {
+				return job.Status.JobDeploymentStatus
+			}, Or(Equal(rayv1.JobDeploymentStatusRunning), Equal(rayv1.JobDeploymentStatusComplete))))
```
Comment (win5923) [inline ray-operator/test/e2erayjob/rayjob_test.go]:
```suggestion
			Should(WithTransform(RayJobReason, Or(
				Equal(rayv1.JobDeploymentStatusTransitionGracePeriodExceeded),
				Equal(rayv1.SubmissionFailed),
			)))
```

File: ray-operator/test/e2erayjob/rayjob_test.go (hunk 8 above)
Comment (400Ping) [reply ray-operator/test/e2erayjob/rayjob_test.go]: done

File: ray-operator/test/e2erayjob/rayjob_test.go (hunk 6 above)
Comment (400Ping) [reply ray-operator/test/e2erayjob/rayjob_test.go]: done

File: ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go [hunk 10]
```diff
@@ -179,12 +181,30 @@ env_vars:
...
+			return len(pods.Items)
+		}, TestTimeoutMedium, 2*time.Second).Should(Equal(0))
+		g.Consistently(func() int {
+			pods, listErr := test.Client().Core().CoreV1().Pods(rayCluster.Namespace).List(
+				test.Ctx(), common.RayClusterHeadPodsAssociationOptions(rayCluster).ToMetaV1ListOptions())
+			if listErr != nil {
+				return -1
+			}
+			return len(pods.Items)
+		}, TestTimeoutShort, 2*time.Second).Should(Equal(0))
```
Comment (fscnick) [inline ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go]: nit: Could it be better for readability ?
```suggestion
		getNumOfHeadPods := func() (int, error) {
			pods, err := test.Client().Core().CoreV1().Pods(rayCluster.Namespace).List(
				test.Ctx(), common.RayClusterHeadPodsAssociationOptions(rayCluster).ToMetaV1ListOptions())
			return len(pods.Items), err
		}
		g.Eventually(getNumOfHeadPods, TestTimeoutMedium, 2*time.Second).Should(BeZero())
		g.Consistently(getNumOfHeadPods, TestTimeoutShort, 2*time.Second).Should(BeZero())
```

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 11]
```diff
@@ -300,20 +301,24 @@ env_vars:
...
+			}
+			return len(pods.Items)
+		}, TestTimeoutMedium, 2*time.Second).Should(Equal(1))
 		g.Eventually(RayJob(test, rayJob.Namespace, rayJob.Name), TestTimeoutMedium).
 			Should(WithTransform(RayJobDeploymentStatus, Equal(rayv1.JobDeploymentStatusFailed)))
-		g.Eventually(RayJob(test, rayJob.Namespace, rayJob.Name), TestTimeoutMedium).
-			Should(WithTransform(RayJobReason, Or(
-				Equal(rayv1.JobDeploymentStatusTransitionGracePeriodExceeded),
-				Equal(rayv1.SubmissionFailed),
-			)))
```
Comment (Future-Outlier) [inline ray-operator/test/e2erayjob/rayjob_test.go:316]: Hi, @400Ping why did you delete these lines?
otherwise all looks good, thank you

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 12]
```diff
@@ -300,20 +301,24 @@ env_vars:
...
-		// After head pod deletion, controller should mark RayJob as Failed with a specific message
+		// Head pod should be recreated for non-sidecar modes.
+		g.Eventually(func() int {
+			pods, listErr := test.Client().Core().CoreV1().Pods(rayCluster.Namespace).List(
+				test.Ctx(), common.RayClusterHeadPodsAssociationOptions(rayCluster).ToMetaV1ListOptions())
+			if listErr != nil {
+				return -1
+			}
+			return len(pods.Items)
+		}, TestTimeoutMedium, 2*time.Second).Should(Equal(1))
```
Comment (Future-Outlier) [inline ray-operator/test/e2erayjob/rayjob_test.go]: can we use something like 
```zsh
g.Eventually(HeadPod(test, rayCluster), TestTimeoutMedium, 2*time.Second).
			ShouldNot(BeNil())
```

File: ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go [hunk 13]
```diff
@@ -179,12 +181,21 @@ env_vars:
...
 		err = test.Client().Core().CoreV1().Pods(headPod.Namespace).Delete(test.Ctx(), headPod.Name, metav1.DeleteOptions{})
 		g.Expect(err).NotTo(HaveOccurred())
 
+		getNumOfHeadPods := func() (int, error) {
+			pods, err := test.Client().Core().CoreV1().Pods(rayCluster.Namespace).List(
+				test.Ctx(), common.RayClusterHeadPodsAssociationOptions(rayCluster).ToMetaV1ListOptions())
+			return len(pods.Items), err
+		}
+		g.Eventually(getNumOfHeadPods, TestTimeoutMedium, 2*time.Second).Should(BeZero())
+		g.Consistently(getNumOfHeadPods, TestTimeoutShort, 2*time.Second).Should(BeZero())
```
Comment (Future-Outlier) [inline ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go]: can we use something like

```zsh
g.Eventually(HeadPod(test, rayCluster), TestTimeoutMedium, 2*time.Second).
			Should(BeNil())
```

File: ray-operator/test/e2erayjob/rayjob_test.go (hunk 11 above)
Comment (400Ping) [reply ray-operator/test/e2erayjob/rayjob_test.go:316]: I removed the `Reason` assertion because, when the head pod is deleted, the controller can take different paths depending on timing, so the `Reason` is not stable. Should I put these back?

Comment (Future-Outlier) [reply ray-operator/test/e2erayjob/rayjob_test.go:316]: yes, you can use 'or' to assert the output.

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 14]
```diff
@@ -300,17 +300,20 @@ env_vars:
...
+		g.Expect(rayCluster.Labels).To(HaveKeyWithValue(utils.RayJobDisableProvisionedHeadNodeRestartLabelKey, "false"))
 		headPod, err := GetHeadPod(test, rayCluster)
 		g.Expect(err).NotTo(HaveOccurred())
 		LogWithTimestamp(test.T(), "Deleting head Pod %s/%s for RayCluster %s", headPod.Namespace, headPod.Name, rayCluster.Name)
 		err = test.Client().Core().CoreV1().Pods(headPod.Namespace).Delete(test.Ctx(), headPod.Name, metav1.DeleteOptions{})
 		g.Expect(err).NotTo(HaveOccurred())
 
-		// After head pod deletion, controller should mark RayJob as Failed with a specific message
+		// Head pod should be recreated for non-sidecar modes.
+		g.Eventually(HeadPod(test, rayCluster), TestTimeoutMedium, 2*time.Second).ShouldNot(BeNil())
```
Comment (Future-Outlier) [inline ray-operator/test/e2erayjob/rayjob_test.go]: Hi, @400Ping 
I mean you can use this function `GetHeadPod`

Comment (Future-Outlier) [reply ray-operator/test/e2erayjob/rayjob_test.go]: maybe write a new helper function is too much

Comment (400Ping) [reply ray-operator/test/e2erayjob/rayjob_test.go]: Ok noted, but the `HeadPod` is not written by me, it was written by Chi-Sheng.

Comment (400Ping) [reply ray-operator/test/e2erayjob/rayjob_test.go]: Updated in [1f9dbe8](https://github.com/ray-project/kuberay/pull/4234/commits/1f9dbe88f91f324ccbf0e90d84c5d0f43195c1cf)

Comment (JiangJiaWei1103) [reply ray-operator/test/e2erayjob/rayjob_test.go]: Hi, I think `HeadPod` is the more appropriate choice here, since it returns a function that `g.Eventually` can invoke repeatedly until the condition is satisfied.

For example:
https://github.com/ray-project/kuberay/blob/563afc89768559fdaa8a7db4b02d4853c8771a9a/ray-operator/test/support/support.go#L257-L263

https://github.com/ray-project/kuberay/blob/563afc89768559fdaa8a7db4b02d4853c8771a9a/ray-operator/test/sampleyaml/raycluster_test.go#L104

Comment (400Ping) [reply ray-operator/test/e2erayjob/rayjob_test.go]: Should I revert [1f9dbe8](https://github.com/ray-project/kuberay/pull/4234/commits/1f9dbe88f91f324ccbf0e90d84c5d0f43195c1cf)?

Comment (Future-Outlier) [reply ray-operator/test/e2erayjob/rayjob_test.go]: it's good now, thank you for the work.

File: ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go [hunk 15]
```diff
@@ -179,12 +180,24 @@ env_vars:
...
 
+		// Head pod should NOT be recreated for sidecar modes.
+		// 1. use GetHeadPod function, I want to delete GetHeadPodOrNil function, and check the
+
+		g.Eventually(func() (*corev1.Pod, error) {
+			return GetHeadPodOrNil(test, rayCluster)
+		}, TestTimeoutMedium, 2*time.Second).Should(BeNil())
+		g.Consistently(func() (*corev1.Pod, error) {
+			return GetHeadPodOrNil(test, rayCluster)
+		}, TestTimeoutShort, 2*time.Second).Should(BeNil())
```
Comment (win5923) [inline ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go]:
```suggestion
		g.Eventually(HeadPodOrNil(test, rayCluster), TestTimeoutShort).ShouldNot(BeNil())
```

File: ray-operator/controllers/ray/utils/constant.go [hunk 16]
```diff
@@ -29,6 +29,9 @@ const (
...
+	// RayJobDisableProvisionedHeadNodeRestartLabelKey marks RayClusters created for sidecar-mode RayJobs to skip head Pod recreation after provisioning.
+	RayJobDisableProvisionedHeadNodeRestartLabelKey = "ray.io/disable-provisioned-head-restart"
```
Comment (rueian) [inline ray-operator/controllers/ray/utils/constant.go]:
```suggestion
	DisableProvisionedHeadRestartAnnotationKey = "ray.io/disable-provisioned-head-restart"
```

Can we use an annotation instead? I think we can also allow users to use this annotation on their own.

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 17]
```diff
@@ -720,13 +720,11 @@ func (r *RayClusterReconciler) reconcilePods(ctx context.Context, instance *rayv
...
 			// used by the old Ray job, so the new Ray job will fail.
-			if meta.IsStatusConditionTrue(instance.Status.Conditions, string(rayv1.RayClusterProvisioned)) {
-				logger.Info(
-					"reconcilePods: Found 0 head Pods for a RayJob-managed RayCluster; skipping head creation to let RayJob controller handle the failure",
-					"rayCluster", instance.Name,
-				)
-				return nil
-			}
+			logger.Info(
+				"reconcilePods: Found 0 head Pods for a sidecar-mode RayJob-managed RayCluster; skipping head creation to let RayJob controller handle the failure",
```
Comment (rueian) [inline ray-operator/controllers/ray/raycluster_controller.go]:
```suggestion
				"reconcilePods: Found 0 head Pods for the RayCluster; Skipped head recreation due to ray.io/disable-provisioned-head-restart",
```

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 18]
```diff
@@ -1122,6 +1120,10 @@ func (r *RayClusterReconciler) reconcileMultiHostWorkerGroup(ctx context.Context
 	return nil
 }
 
+func shouldSkipHeadPodRestart(instance *rayv1.RayCluster) bool {
+	return getCreatorCRDType(*instance) == utils.RayJobCRD && instance.Labels[utils.RayJobDisableProvisionedHeadNodeRestartLabelKey] == "true"
```
Comment (rueian) [inline ray-operator/controllers/ray/raycluster_controller.go]:
```suggestion
	return instance.Annotations[utils.DisableProvisionedHeadRestartAnnotationKey] == "true"
```

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 19]
```diff
@@ -939,6 +940,14 @@ func (r *RayJobReconciler) constructRayClusterForRayJob(rayJobInstance *rayv1.Ra
 	maps.Copy(labels, rayJobInstance.Labels)
 	labels[utils.RayOriginatedFromCRNameLabelKey] = rayJobInstance.Name
 	labels[utils.RayOriginatedFromCRDLabelKey] = utils.RayOriginatedFromCRDLabelValue(utils.RayJobCRD)
+	labels[utils.RayJobSubmissionModeLabelKey] = string(rayJobInstance.Spec.SubmissionMode)
+
+	if rayJobInstance.Spec.SubmissionMode == rayv1.SidecarMode {
+		labels[utils.RayJobDisableProvisionedHeadNodeRestartLabelKey] = "true"
+	} else {
+		labels[utils.RayJobDisableProvisionedHeadNodeRestartLabelKey] = "false"
+	}
```
Comment (rueian) [inline ray-operator/controllers/ray/rayjob_controller.go:949]:
```suggestion
	if rayJobInstance.Spec.SubmissionMode == rayv1.SidecarMode {
		annotations[utils.DisableProvisionedHeadRestartAnnotationKey] = "true"
	}
```

File: ray-operator/controllers/ray/utils/constant.go [hunk 20]
```diff
@@ -29,6 +29,9 @@ const (
 	KubeRayVersion                           = "ray.io/kuberay-version"
 	RayCronJobNameLabelKey                   = "ray.io/cronjob-name"
 	RayCronJobTimestampAnnotationKey         = "ray.io/cronjob-scheduled-timestamp"
+	RayJobSubmissionModeLabelKey             = "ray.io/job-submission-mode"
+	// RayJobDisableProvisionedHeadNodeRestartLabelKey marks RayClusters created for sidecar-mode RayJobs to skip head Pod recreation after provisioning.
```
Comment (machichima) [inline ray-operator/controllers/ray/utils/constant.go]:
```suggestion
	// DisableProvisionedHeadRestartAnnotationKey marks RayClusters created for sidecar-mode RayJobs to skip head Pod recreation after provisioning.
```
nit

File: ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go [hunk 21]
```diff
@@ -179,12 +180,24 @@ env_vars:
...
+		g.Expect(rayCluster.Labels[utils.RayJobSubmissionModeLabelKey]).To(Equal(string(rayv1.SidecarMode)))
+		g.Expect(rayCluster.Labels[utils.RayJobDisableProvisionedHeadNodeRestartLabelKey]).To(Equal("true"))
 		headPod, err := GetHeadPod(test, rayCluster)
 		g.Expect(err).NotTo(HaveOccurred())
 		LogWithTimestamp(test.T(), "Deleting head Pod %s/%s for RayCluster %s", headPod.Namespace, headPod.Name, rayCluster.Name)
 		err = test.Client().Core().CoreV1().Pods(headPod.Namespace).Delete(test.Ctx(), headPod.Name, metav1.DeleteOptions{})
 		g.Expect(err).NotTo(HaveOccurred())
 
+		// Head pod should NOT be recreated for sidecar modes.
+		// 1. use GetHeadPod function, I want to delete GetHeadPodOrNil function, and check the
```
Comment (machichima) [inline ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go]: Is this comment unfinished?

File: ray-operator/test/support/ray.go [hunk 22]
```diff
@@ -135,6 +135,12 @@ func HeadPod(t Test, rayCluster *rayv1.RayCluster) func() (*corev1.Pod, error) {
 	}
 }
 
+func HeadPodOrNil(t Test, rayCluster *rayv1.RayCluster) func() (*corev1.Pod, error) {
+	return func() (*corev1.Pod, error) {
+		return GetHeadPodOrNil(t, rayCluster)
+	}
+}
+
```
Comment (machichima) [inline ray-operator/test/support/ray.go]: Is this function being used anywhere?

File: ray-operator/test/support/ray.go [hunk 23]
```diff
@@ -149,6 +155,23 @@ func GetHeadPod(t Test, rayCluster *rayv1.RayCluster) (*corev1.Pod, error) {
 	return &pods.Items[0], nil
 }
 
+func GetHeadPodOrNil(t Test, rayCluster *rayv1.RayCluster) (*corev1.Pod, error) {
```
Comment (machichima) [inline ray-operator/test/support/ray.go]: Can we directly use `GetHeadPod` above? I think that matches our needs?

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 24]
```diff
@@ -939,6 +940,12 @@ func (r *RayJobReconciler) constructRayClusterForRayJob(rayJobInstance *rayv1.Ra
 	maps.Copy(labels, rayJobInstance.Labels)
 	labels[utils.RayOriginatedFromCRNameLabelKey] = rayJobInstance.Name
 	labels[utils.RayOriginatedFromCRDLabelKey] = utils.RayOriginatedFromCRDLabelValue(utils.RayJobCRD)
+	labels[utils.RayJobSubmissionModeLabelKey] = string(rayJobInstance.Spec.SubmissionMode)
+
+	if rayJobInstance.Spec.SubmissionMode == rayv1.SidecarMode {
+		annotations[utils.DisableProvisionedHeadRestartAnnotationKey] = "true"
```
Comment (machichima) [inline ray-operator/controllers/ray/rayjob_controller.go:948]: `annotations` here is not defined (see CI error). We need to define this above 
```go
annotations := make(map[string]string, len(rayJobInstance.Annotations))
maps.Copy(annotations, rayJobInstance.Annotations)
```
and pass it to `RayCluster` below

**Comment by 400Ping** [comment]
> Hi, @400Ping do you mind solve the comments?

Done, PTAL

File: ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go [hunk 25]
```diff
@@ -179,12 +180,24 @@ env_vars:
...
 
+		// Head pod should NOT be recreated for sidecar modes.
+		g.Eventually(func() error {
+			_, err := GetHeadPod(test, rayCluster)
+			return err
+		}, TestTimeoutMedium, 2*time.Second).Should(HaveOccurred())
+		g.Consistently(func() error {
+			_, err := GetHeadPod(test, rayCluster)
+			return err
+		}, TestTimeoutShort, 2*time.Second).Should(HaveOccurred())
```
Comment (win5923) [inline ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go:199]:
```suggestion
		g.Consistently(HeadPod(test, rayCluster), TestTimeoutShort, 2*time.Second).
      Should(BeNil())
```
Nit: we can simply use HeadPod?

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 26]
```diff
@@ -300,17 +300,23 @@ env_vars:
...
 		g.Expect(err).NotTo(HaveOccurred())
 		LogWithTimestamp(test.T(), "Deleting head Pod %s/%s for RayCluster %s", headPod.Namespace, headPod.Name, rayCluster.Name)
 		err = test.Client().Core().CoreV1().Pods(headPod.Namespace).Delete(test.Ctx(), headPod.Name, metav1.DeleteOptions{})
 		g.Expect(err).NotTo(HaveOccurred())
 
-		// After head pod deletion, controller should mark RayJob as Failed with a specific message
+		// Head pod should be recreated for non-sidecar modes.
+		g.Eventually(func() (*corev1.Pod, error) {
+			return GetHeadPod(test, rayCluster)
+		}, TestTimeoutMedium, 2*time.Second).ShouldNot(BeNil())
```
Comment (win5923) [inline ray-operator/test/e2erayjob/rayjob_test.go:314]:
```suggestion
		g.Eventually(HeadPod(test, rayCluster), TestTimeoutMedium, 2*time.Second).
      ShouldNot(BeNil())
```

Nit: we can simply use HeadPod?

File: ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go [hunk 27]
```diff
@@ -179,12 +180,24 @@ env_vars:
...
 		g.Expect(err).NotTo(HaveOccurred())
 		LogWithTimestamp(test.T(), "Deleting head Pod %s/%s for RayCluster %s", headPod.Namespace, headPod.Name, rayCluster.Name)
 		err = test.Client().Core().CoreV1().Pods(headPod.Namespace).Delete(test.Ctx(), headPod.Name, metav1.DeleteOptions{})
 		g.Expect(err).NotTo(HaveOccurred())
 
+		// Head pod should NOT be recreated for sidecar modes.
+		g.Eventually(func() error {
+			_, err := GetHeadPod(test, rayCluster)
+			return err
+		}, TestTimeoutMedium, 2*time.Second).Should(HaveOccurred())
```
Comment (win5923) [inline ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go:195]:
```suggestion
		g.Eventually(HeadPod(test, rayCluster), TestTimeoutMedium, 2*time.Second).
      Should(BeNil())
```
Nit: we can simply use HeadPod?

File: ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go (hunk 25 above)
Comment (win5923) [reply ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go:199]: NVM, your implement is good!

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 28]
```diff
@@ -935,14 +936,22 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
 }
 
 func (r *RayJobReconciler) constructRayClusterForRayJob(rayJobInstance *rayv1.RayJob, rayClusterName string) (*rayv1.RayCluster, error) {
-	labels := make(map[string]string, len(rayJobInstance.Labels))
+	labels := make(map[string]string, len(rayJobInstance.Labels)+3)
```
Comment (machichima) [inline ray-operator/controllers/ray/rayjob_controller.go]: I think the size we set here is the initial size for the map, and we can extend when adding more object into the map without it throwing errors. 
In this case I think we do not need `+3`? As if we add more label here in the future, we will need to update here, which is not ideal

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 29]
```diff
@@ -935,14 +936,22 @@ func (r *RayJobReconciler) getOrCreateRayClusterInstance(ctx context.Context, ra
...
 	maps.Copy(labels, rayJobInstance.Labels)
 	labels[utils.RayOriginatedFromCRNameLabelKey] = rayJobInstance.Name
 	labels[utils.RayOriginatedFromCRDLabelKey] = utils.RayOriginatedFromCRDLabelValue(utils.RayJobCRD)
+	labels[utils.RayJobSubmissionModeLabelKey] = string(rayJobInstance.Spec.SubmissionMode)
+
+	annotations := make(map[string]string, len(rayJobInstance.Annotations)+1)
```
Comment (machichima) [inline ray-operator/controllers/ray/rayjob_controller.go]: ditto

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 30]
```diff
@@ -300,17 +300,23 @@ env_vars:
 		g.Expect(err).NotTo(HaveOccurred())
 		rayCluster, err := GetRayCluster(test, rayJob.Namespace, rayJob.Status.RayClusterName)
 		g.Expect(err).NotTo(HaveOccurred())
+		g.Expect(rayCluster.Labels).To(HaveKeyWithValue(utils.RayJobSubmissionModeLabelKey, string(rayv1.K8sJobMode)))
```
Comment (machichima) [inline ray-operator/test/e2erayjob/rayjob_test.go]:
```go
g.Expect(rayCluster.Labels[utils.RayJobSubmissionModeLabelKey]).To(Equal(string(rayv1.SidecarMode)))
```
Can we use this as what we had in `ray-operator/test/e2erayjob/rayjob_sidecar_mode_test.go`?
