### PR TITLE
[RayService][Observability] Add more logging for RayService troubleshooting

### LINKED ISSUE #903: [Discussion][Feature] Add more logging to `RayService` deployments
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

There are no logs to debug / track progress of `RayService` deployments. If the Ray Cluster head pod fails, I cannot see what went wrong in the logs.

### Use case

It is practically impossible to know what's wrong with a deployment if it does not start up. All I get is a generic message saying 
```
Put "http://rayservice-poc-raycluster-v7d4g-dashboard-svc.kuberay.svc.cluster.local:52365/api/serve/deployments/": dial tcp 10.96.153.56:52365: connect: connection refused
```
when running the `kubectl describe` command.

The KubeRay pod logs also say a similar thing. It gets very difficult to debug issues in these scenarios.

### Related issues

When applying a `RayService` with a `serveConfig` embedded in it, I can see the ray cluster head pod running, but the worker group is still pending. On running the `kubectl describe` command, I see
```
rayservice-controller  Controller sent API request to update Serve deployments on cluster rayservice-poc-raycluster-v7d4g
```

My `serveConfig` had a working directory pointing to an S3 bucket, and to access that I provided the AWS environment variables in `serveConfig.runtimeEnv.env_vars`. On moving those env variables to the head and worker containers, the serve application started running.

I would love for some more logs to be added to make sure these bugs can be found and fixed easily.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

1. Add logs and update the troubleshooting guide for the failure of getting serve status. (Issue 7)
2. Add logs and update the troubleshooting guide for the unexpected blue-green upgrades. (Issue 8) 

```go
if !isHealthy || (prevStatus.HealthLastUpdateTime != nil && time.Since(prevStatus.HealthLastUpdateTime.Time).Seconds() > serviceUnhealthySecondThreshold) {
	// TODO (kevin85421): Without `!isHealthy`, this `if` statement is almost impossible to be reached because the `HealthLastUpdateTime` of a serve deployment
	// is always later than the `HealthLastUpdateTime` of the serve application. Hence, the restart is always triggered by the serve application. If we
	// can confirm that `isHealthy = false` is always set by the serve application check, we can remove the `time.Since` check here.
	r.Log.Info("Restart RayCluster", "deploymentName", deploymentName, "appName", appName, "restart reason",
		fmt.Sprintf(
			"The status of the serve deployment %s or the serve application %s has not been HEALTHY/RUNNING for more than %f seconds. "+
				"Hence, KubeRay operator labels the RayCluster unhealthy and will prepare a new RayCluster. "+
				"The message of the serve deployment is: %s", deploymentName, appName, serviceUnhealthySecondThreshold, deploymentStatus.Message))
	isHealthy = false
}
```

In my observation, if the `HealthLastUpdateTime` of the serve application is **t**, the `HealthLastUpdateTime` of the serve deployment is **t+x**, where **x >= 0**. Hence, `isHealthy = false` is always set by the serve application.

## Related issue number

Closes #903 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

The details for manual testing are explained in Issue 7 and Issue 8 in the **rayservice-troubleshooting.md** file.

### CODE REVIEW

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 1]
```diff
@@ -718,33 +718,40 @@ func (r *RayServiceReconciler) updateServeDeployment(ctx context.Context, raySer
...
+	// TODO (kevin85421): Separate the logic for retrieving Serve application statuses from checking Serve application statuses into two separate functions.
+	// Currently, the handling logic for `isHealthy` and `isReady` between these two behaviors is inconsistent. This can cause potential issues in the future.
 	var serveAppStatuses map[string]*utils.ServeApplicationStatus
 	var err error
 	if serveConfigType == utils.SINGLE_APP {
 		var singleApplicationStatus *utils.ServeApplicationStatus
 		if singleApplicationStatus, err = dashboardClient.GetSingleApplicationStatus(ctx); err != nil {
-			r.Log.Error(err, "Failed to get Serve deployment statuses from dashboard!")
+			err = fmt.Errorf(
+				"Failed to get Serve deployment statuses from the dashboard agent (port: 52365). "+
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/rayservice_controller.go:743]:
```suggestion
				"Failed to get Serve deployment statuses from the dashboard agent (port: 52365). "+
```
Is the port configurable? If it's easy to include the actual port here, we should, instead of hardcoding it.

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 2]
```diff
@@ -1099,8 +1118,19 @@ func (r *RayServiceReconciler) reconcileServe(ctx context.Context, rayServiceIns
...
+			"Restart RayCluster", "AvailableWorkerReplicas", availableWorkerReplicas, "DesiredWorkerReplicas", desiredWorkerReplicas,
+			"restart reason",
+			"The serve application is unhealthy, restarting the cluster. If the AvailableWorkerReplicas is not equal to DesiredWorkerReplicas, "+
+				"this may imply that the Autoscaler does not have enough resources to scale up the cluster. Hence, the serve application does not "+
+				"have enough resources to run. Please check https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayservice-troubleshooting.md for more details.",
+			"RayCluster", rayClusterInstance)
+		r.Recorder.Eventf(
+			rayServiceInstance, "Normal", "Restarting",
+			"Please check https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayservice-troubleshooting.md for more details. The cluster will restart after %s", ServiceRestartRequeueDuration,
+			"AvailableWorkerReplicas", availableWorkerReplicas, "DesiredWorkerReplicas", desiredWorkerReplicas)
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/rayservice_controller.go:1133]: Nit: we can check in the code whether available=desired and only print the last part if necessary, right? Could be less spammy that way

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 3]
```diff
@@ -718,33 +718,40 @@ func (r *RayServiceReconciler) updateServeDeployment(ctx context.Context, raySer
...
-	// This is used for testing purposes.
+	// If the `unhealthySecondThreshold` value is non-nil, then we will use that value. Otherwise, we will use the value ServiceUnhealthySecondThreshold
+	// which can be set in a test. This is used for testing purposes.
 	serviceUnhealthySecondThreshold := ServiceUnhealthySecondThreshold
 	if unhealthySecondThreshold != nil {
 		serviceUnhealthySecondThreshold = float64(*unhealthySecondThreshold)
 	}
 
+	// TODO (kevin85421): Separate the logic for retrieving Serve application statuses from checking Serve application statuses into two separate functions.
+	// Currently, the handling logic for `isHealthy` and `isReady` between these two behaviors is inconsistent. This can cause potential issues in the future.
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/rayservice_controller.go:736]: Agree the logic is confusing, should we file a tracking issue on github?

**Review by architkulkarni — APPROVED** [review]
Looks good to me, comments non-blocking

File: ray-operator/controllers/ray/rayservice_controller.go (hunk 3 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayservice_controller.go:736]: Track the progress https://github.com/ray-project/kuberay/issues/1234.

File: ray-operator/controllers/ray/rayservice_controller.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/rayservice_controller.go:743]: Good idea. Would it be better if I update the error message to "Failed to retrieve Serve deployment statuses from the dashboard agent port of the head service (`dashboard-agent`)"? The actual port will be shown in `err`. In Issue 7, the error message is `Get \"http://rayservice-sample-raycluster-rqlsl-head-svc.default.svc.cluster.local:52365/api/serve/applications/\": dial tcp 10.96.7.154:52365: connect: connection refused`.

Comment (kevin85421) [reply ray-operator/controllers/ray/rayservice_controller.go]: Updated https://github.com/ray-project/kuberay/pull/1230/commits/107edd327906cf5868bdd3cfa6ba560c98c7ba1c

File: ray-operator/controllers/ray/rayservice_controller.go (hunk 2 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayservice_controller.go:1133]: Sure, I don't have a strong opinion.

File: ray-operator/controllers/ray/rayservice_controller.go (hunk 1 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/rayservice_controller.go]: Sounds good!
