### PR TITLE
[Enhancement] GPU RayCluster doesn't work on GKE Autopilot

### LINKED ISSUE #1349: [Enhancement] GPU RayCluster doesn't work on GKE Autopilot
[GKE Autopilot](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview) is a streamlined, user-friendly way to set up a cluster.  

However, trying to use KubeRay with a GPU results in the `RayCluster` showing its status as `failed`, with the following error message:

```
GPU-using init containers are not supported in Autopilot.
```

The workaround is to not use Autopilot, and instead manually create the GKE cluster with a GPU node pool, manually installing the nvidia drivers, setting up taints and tolerations, etc.  If we can fix the issue in KubeRay, the user won't have to think about any of this.

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

GKE's Autopilot does not support GPU-using init containers, so we explicitly specify the resources for the init container instead of reusing the resources of the Ray container. The resource consumption of the init container should be constant. Hence, it is OK to hard-code the resources.

## Related issue number

Closes #1349 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] This PR is not tested :(

```sh
# Step 1: Create a GKE Autopilot cluster
gcloud container clusters create-auto kuberay-gpu-cluster --region=us-west1

# Step 2: Install a KubeRay operator with this PR
# Step 3: Install a RayCluster https://gist.github.com/kevin85421/ef4c3a0c7493e76edd3d2cab5cea33e4
# (Note that you need to add nodeSelector)

```

### CODE REVIEW

**Review by architkulkarni — APPROVED** [review]
Nice fix! Once this makes it into the kuberay release, we can probably simplify some of the GKE instructions in our doc and just recommend users to use GKE autopilot going forward. (Depending of how stable we believe GKE Autopilot is)

File: ray-operator/controllers/ray/common/pod.go [hunk 1]
```diff
@@ -185,8 +185,19 @@ func DefaultWorkerPodTemplate(instance rayv1alpha1.RayCluster, workerSpec rayv1a
...
+			// GKE's Autopilot does not support GPU-using init containers, so we explicitly specify the resources for the
+			// init container instead of reusing the resources of the Ray container.
+			Resources: v1.ResourceRequirements{
+				Limits: v1.ResourceList{
+					v1.ResourceCPU:    resource.MustParse("200m"),
+					v1.ResourceMemory: resource.MustParse("256Mi"),
+				},
+				Requests: v1.ResourceList{
+					v1.ResourceCPU:    resource.MustParse("200m"),
+					v1.ResourceMemory: resource.MustParse("256Mi"),
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/common/pod.go:198]: A comment here with some indication of why these numbers were chosen would be useful, perhaps a brief reminder of what the init container does

Comment (kevin85421) [reply ray-operator/controllers/ray/common/pod.go:200]: Updated https://github.com/ray-project/kuberay/pull/1470/commits/9039f24866f504f7cdfd82be7f277933fdb68602
