### PR TITLE
Fix: Move replica validation logic to right place.

### LINKED ISSUE #4101: Move Replica validation to `validation.go`
https://github.com/ray-project/kuberay/blob/eb66a26b78b7a4fc92c0e1f3d412e15b75b6c0ea/ray-operator/controllers/ray/utils/util.go#L345-L352

Validation logic like this should be added to `controllers/ray/utils/validation.go` and be checked before the rayCluster pods creation.

### PR DESCRIPTION
**Pull request by kash2104**
## Why are these changes needed?
These changes are done to check the validation logic before rayCluster pod creation. It moves the replica validation logic as well as removes the redundant tests. Along with this, unit test are added since we moved the logic from `utils.go` to `validation.go`.

## Related issue number
Closes #4101 

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [ ] Unit tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by JiangJiaWei1103** [comment]
Thanks for your effort.

cc @Future-Outlier 
This PR duplicates with https://github.com/ray-project/kuberay/pull/4116, which seemed inactive now. Should we close https://github.com/ray-project/kuberay/pull/4116 and work on this one?

**Comment by kash2104** [comment]
I have gone through #4116 but it was inactive and no changes were being made after the merging of volcano pr. Many changes are required since volcano pr's merging, that's why I opened up this PR.

**Comment by JiangJiaWei1103** [comment]
Gotcha. Let's wait for maintainers' reply. I'll help review, thank you.

**Comment by kash2104** [comment]
@Future-Outlier  Just wanted to follow up - do you prefer closing #4116 and continuing the work in this PR?

**Comment by Future-Outlier** [comment]
> @Future-Outlier Just wanted to follow up - do you prefer closing #4116 and continuing the work in this PR?

Hi, @kash2104 I just left a comment to #4116 and ask her if she have time to finish the work.
if after 2 weeks she haven't replied, you can take over it

**Comment by Future-Outlier** [comment]
cursor review

File: ray-operator/controllers/ray/utils/validation.go [hunk 1]
```diff
@@ -111,11 +111,30 @@ func ValidateRayClusterSpec(spec *rayv1.RayClusterSpec, annotations map[string]s
...
 	for _, workerGroup := range spec.WorkerGroupSpecs {
 		if len(workerGroup.Template.Spec.Containers) == 0 {
 			return fmt.Errorf("workerGroupSpec should have at least one container")
 		}
 
+		// When autoscaling is enabled, MinReplicas and MaxReplicas are optional
+		// as users can manually update them and the autoscaler will handle the adjustment.
+		if !isAutoscalingEnabled && (workerGroup.MinReplicas == nil || workerGroup.MaxReplicas == nil) {
+			return fmt.Errorf("worker group %s must set both minReplicas and maxReplicas when autoscaling is disabled", workerGroup.GroupName)
+		}
```
[the remark this answers is not in the document]
Comment (400Ping) [reply ray-operator/controllers/ray/utils/validation.go:126]: Agree

File: ray-operator/controllers/ray/utils/validation.go [hunk 2]
```diff
@@ -111,11 +111,30 @@ func ValidateRayClusterSpec(spec *rayv1.RayClusterSpec, annotations map[string]s
...
+			return fmt.Errorf("worker group %s has negative minReplicas %d", workerGroup.GroupName, *workerGroup.MinReplicas)
+		}
+		if workerGroup.MaxReplicas != nil && *workerGroup.MaxReplicas < 0 {
+			return fmt.Errorf("worker group %s has negative maxReplicas %d", workerGroup.GroupName, *workerGroup.MaxReplicas)
+		}
+		if workerGroup.MinReplicas != nil && workerGroup.MaxReplicas != nil {
+			if *workerGroup.MinReplicas > *workerGroup.MaxReplicas {
+				return fmt.Errorf("worker group %s has minReplicas %d greater than maxReplicas %d", workerGroup.GroupName, *workerGroup.MinReplicas, *workerGroup.MaxReplicas)
+			}
+		}
```
Comment (machichima) [inline ray-operator/controllers/ray/utils/validation.go:137]: Should we also check if `workerGroup.Replicas` lies within the `workerGroup.MinReplicas` and workerGroup.MaxReplicas`?

File: ray-operator/controllers/ray/utils/util.go [hunk 3]
```diff
@@ -424,7 +427,11 @@ func CalculateMinReplicas(cluster *rayv1.RayCluster) int32 {
 		if nodeGroup.Suspend != nil && *nodeGroup.Suspend {
 			continue
 		}
-		count += (*nodeGroup.MinReplicas * nodeGroup.NumOfHosts)
+		minReplicas := int32(0)
+		if nodeGroup.MinReplicas != nil {
+			minReplicas = *nodeGroup.MinReplicas
+		}
```
Comment (machichima) [inline ray-operator/controllers/ray/utils/util.go]: Maybe we can use `ptr.Deref`, which is used in other places as well

https://github.com/ray-project/kuberay/blob/270a143937be35614ae84de03a35870f603f779e/ray-operator/controllers/ray/utils/util.go#L830-L831

File: ray-operator/controllers/ray/utils/validation.go (hunk 2 above)
Comment (kash2104) [reply ray-operator/controllers/ray/utils/validation.go:137]: @machichima Here in the`validation.go`, we are just checking whether the values for min and max replicas aren't incorrect or impossible before pod creation happens but the actual logic of number of replicas is moved to `util.go`

So I think that here in `validation.go`, we won't be needing this check.

File: ray-operator/controllers/ray/utils/util.go [hunk 4]
```diff
@@ -384,34 +384,31 @@ func GenerateIdentifier(clusterName string, nodeType rayv1.RayNodeType) string {
 	return fmt.Sprintf("%s-%s", clusterName, nodeType)
 }
 
-func GetWorkerGroupDesiredReplicas(ctx context.Context, workerGroupSpec rayv1.WorkerGroupSpec) int32 {
-	log := ctrl.LoggerFrom(ctx)
+func GetWorkerGroupDesiredReplicas(workerGroupSpec rayv1.WorkerGroupSpec) int32 {
 	// Always adhere to min/max replicas constraints.
 	var workerReplicas int32
+	minReplicas := ptr.Deref(workerGroupSpec.MinReplicas, int32(0))
+	maxReplicas := ptr.Deref(workerGroupSpec.MaxReplicas, int32(math.MaxInt32))
```
Comment (machichima) [inline ray-operator/controllers/ray/utils/util.go:391]: Just to confirm, is the `math.MaxInt32` also the default value for max replicas we set in the CRD?

File: ray-operator/controllers/ray/utils/util_test.go [hunk 5]
```diff
@@ -565,37 +564,21 @@ func TestGetWorkerGroupDesiredReplicas(t *testing.T) {
...
 
-	// Test 3: `WorkerGroupSpec.Replicas` is not nil but is more than maxReplicas.
-	replicas = int32(6)
-	workerGroupSpec.Replicas = &replicas
-	assert.Equal(t, GetWorkerGroupDesiredReplicas(ctx, workerGroupSpec), maxReplicas)
-
-	// Test 4: `WorkerGroupSpec.Replicas` is not nil but is less than minReplicas.
-	replicas = int32(0)
-	workerGroupSpec.Replicas = &replicas
-	assert.Equal(t, GetWorkerGroupDesiredReplicas(ctx, workerGroupSpec), minReplicas)
```
Comment (machichima) [inline ray-operator/controllers/ray/utils/util_test.go:583]: Should we keep those checks? I think this part is not moved to validation

File: ray-operator/controllers/ray/utils/validation_test.go [hunk 6]
```diff
@@ -2473,3 +2481,83 @@ func TestValidateRayClusterUpgradeOptions(t *testing.T) {
...
+						Template:    podTemplateSpec(nil, nil),
+						Replicas:    ptr.To(int32(1)),
+						MinReplicas: ptr.To(int32(2)),
+						MaxReplicas: ptr.To(int32(5)),
+					},
+				}
+				return s
+			}(),
+			expectError: false,
+		},
```
Comment (machichima) [inline ray-operator/controllers/ray/utils/validation_test.go:2535]: I think this will not raise error because we did the clamp it to `minReplicas` in `util.go`? Could we please add comment or update the test name to briefly explain why this will not raise error? As usually we would expect error being raised in this case

File: ray-operator/controllers/ray/utils/util.go (hunk 4 above)
Comment (kash2104) [reply ray-operator/controllers/ray/utils/util.go:391]: Yes https://github.com/ray-project/kuberay/blob/b8451500d4276e5c27a1025c732c562eaac04a37/ray-operator/apis/ray/v1alpha1/raycluster_types.go#L56

File: ray-operator/controllers/ray/utils/util_test.go (hunk 5 above)
Comment (kash2104) [reply ray-operator/controllers/ray/utils/util_test.go:583]: The part that we have moved to the validation keeps in check that the desired state of the replicas are within the correct bounds or not after the pods have been created. So these tests were checking that logic by using the `GetWorkerGroupDesiredReplicas` and we have moved this logic to `validation.go` and thus have added the tests for them in `validation_test.go` as well.

Thus these checks have removed from `util_test.go`.

Comment (machichima) [reply ray-operator/controllers/ray/utils/util_test.go:583]: Please correct me if I'm wrong, I think in validation we only check if maxReplicas and minReplicas are set correctly (comment: https://github.com/ray-project/kuberay/pull/4307#discussion_r2702167074). The test here is for checking if the replicas will be clamped to max or min replica, so I think we should include them?

Comment (kash2104) [reply ray-operator/controllers/ray/utils/util_test.go:583]: I agree on including them back.

File: ray-operator/controllers/ray/utils/validation_test.go (hunk 6 above)
Comment (kash2104) [reply ray-operator/controllers/ray/utils/validation_test.go:2535]: @machichima Should I add the comment for this test case or something else is recommended?

Comment (machichima) [reply ray-operator/controllers/ray/utils/validation_test.go:2535]: Adding a comment here sounds good to me!

**Comment by machichima** [comment]
For the failed rayjob e2e test in CI, please try to merge master. The error should go away

**Comment by kash2104** [comment]
@machichima Have fixed the tests.

**Comment by machichima** [comment]
cc @JiangJiaWei1103 to also take a look

File: ray-operator/controllers/ray/utils/validation.go (hunk 2 above)
Comment (JiangJiaWei1103) [reply ray-operator/controllers/ray/utils/validation.go:137]: Just to confirm: `validation.go` is strictly for ensuring the min and max replica configurations are valid, while the actual clipping logic resides in `util.go`. Therefore, we don't need to re-verify if the replicas fall within the [min, max] range here. Please let me know if I've misunderstood anything. Thanks!

**Comment by kash2104** [comment]
@JiangJiaWei1103 You have understood it correctly.

**Comment by machichima** [comment]
cc @Future-Outlier for final round

**Comment by kash2104** [comment]
@Future-Outlier Have added the test cases.

**Review by Future-Outlier — APPROVED** [review]
LGTM, cc @rueian @andrewsykim to merge.
