### PR TITLE
[Fix] Resolve int32 overflow by having the calculation in int64 and c…

### LINKED ISSUE #4153: [Bug] `Status.MaxWorkerReplicas` overflow when numOfHosts > 1
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Applying the following YAML will cause an overflow in `Status.MaxWorkerReplicas`:
```
workerGroupSpecs:
  - replicas: 1
    minReplicas: 3
    numOfHosts: 4
```

By default, `maxReplicas` is set to 2147483647. 
https://github.com/ray-project/kuberay/blob/3471f99e23084d722734369f102b9965674bde47/ray-operator/apis/ray/v1/raycluster_types.go#L112-L114
However, in `CalculateMaxReplicas`, there’s no check to prevent overflow when multiplying by `numOfHosts`, which can result in an incorrect value for `Status.MaxWorkerReplicas`.

https://github.com/ray-project/kuberay/blob/3471f99e23084d722734369f102b9965674bde47/ray-operator/controllers/ray/utils/util.go#L394-L405

### Reproduction script

Applying the following YAML
```
# For examples with more realistic resource configuration, see
# ray-cluster.complete.large.yaml and
# ray-cluster.autoscaler.large.yaml.
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: raycluster-kuberay
spec:
  rayVersion: '2.46.0' # should match the Ray version in the image of the containers
  # Ray head pod template
  headGroupSpec:
    # rayStartParams is optional with RayCluster CRD from KubeRay 1.4.0 or later but required in earlier versions.
    rayStartParams: {}
    template:
      spec:
        schedulerName: default-scheduler
        containers:
        - name: ray-head
          image: rayproject/ray:2.46.0
          resources:
            limits:
              cpu: 1
              memory: 2G
            requests:
              cpu: 1
              memory: 2G
          ports:
          - containerPort: 6379
            name: gcs-server
          - containerPort: 8265 # Ray dashboard
            name: dashboard
          - containerPort: 10001
            name: client
  workerGroupSpecs:
  # the pod replicas in this group typed worker
  - replicas: 1
    minReplicas: 3
    numOfHosts: 4
    # logical group name, for this called small-group, also can be functional
    groupName: workergroup
    # rayStartParams is optional with RayCluster CRD from KubeRay 1.4.0 or later but required in earlier versions.
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
          image: rayproject/ray:2.46.0
          resources:
            limits:
              cpu: 1
              memory: 1G
            requests:
              cpu: 1
              memory: 1G
```

```
$ kubectl get raycluster raycluster-kuberay -o yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ray.io/v1","kind":"RayCluster","metadata":{"annotations":{},"name":"raycluster-kuberay","namespace":"default"},"spec":{"headGroupSpec":{"rayStartParams":{},"template":{"spec":{"containers":[{"image":"rayproject/ray:2.46.0","name":"ray-head","ports":[{"containerPort":6379,"name":"gcs-server"},{"containerPort":8265,"name":"dashboard"},{"containerPort":10001,"name":"client"}],"resources":{"limits":{"cpu":1,"memory":"2G"},"requests":{"cpu":1,"memory":"2G"}}}],"schedulerName":"default-scheduler"}}},"rayVersion":"2.46.0","workerGroupSpecs":[{"groupName":"workergroup","minReplicas":3,"numOfHosts":4,"rayStartParams":{},"replicas":1,"template":{"spec":{"containers":[{"image":"rayproject/ray:2.46.0","name":"ray-worker","resources":{"limits":{"cpu":1,"memory":"1G"},"requests":{"cpu":1,"memory":"1G"}}}]}}}]}}
  creationTimestamp: "2025-10-28T16:05:15Z"
  generation: 1
  name: raycluster-kuberay
  namespace: default
  resourceVersion: "13168"
  uid: c83e5bd6-c5ee-4a22-b615-341fee75725a
....
status:
  availableWorkerReplicas: 12
  conditions:
  - lastTransitionTime: "2025-10-28T16:05:36Z"
    message: ""
    reason: HeadPodRunningAndReady
    status: "True"
    type: HeadPodReady
  - lastTransitionTime: "2025-10-28T16:06:43Z"
    message: All Ray Pods are ready for the first time
    reason: AllPodRunningAndReadyFirstTime
    status: "True"
    type: RayClusterProvisioned
  - lastTransitionTime: "2025-10-28T16:05:36Z"
    message: ""
    reason: RayClusterSuspended
    status: "False"
    type: RayClusterSuspended
  - lastTransitionTime: "2025-10-28T16:05:36Z"
    message: ""
    reason: RayClusterSuspending
    status: "False"
    type: RayClusterSuspending
  desiredCPU: "5"
  desiredGPU: "0"
  desiredMemory: 6G
  desiredTPU: "0"
  desiredWorkerReplicas: 12
  endpoints:
    client: "10001"
    dashboard: "8265"
    gcs-server: "6379"
    metrics: "8080"
  head:
    podIP: 10.244.0.34
    podName: raycluster-kuberay-head-g5wzm
    serviceIP: 10.244.0.34
    serviceName: raycluster-kuberay-head-svc
  lastUpdateTime: "2025-10-28T16:06:43Z"
  maxWorkerReplicas: -4                <---- overflowed
  minWorkerReplicas: 12
  observedGeneration: 1
  readyWorkerReplicas: 12
  state: ready
  stateTransitionTimes:
    ready: "2025-10-28T16:06:43Z"
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by justinyeh1995**
…ap it if the count is over math.MaxInt32

## Why are these changes needed?

The `CalculateMaxReplicas` function did not guard against integer overflow, which could result in an incorrect value for Status.MaxWorkerReplicas, as reported in #4153.

```yaml
$ kubectl get raycluster raycluster-kuberay -o yaml
apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ray.io/v1","kind":"RayCluster","metadata":{"annotations":{},"name":"raycluster-kuberay","namespace":"default"},"spec":{"headGroupSpec":{"rayStartParams":{},"template":{"spec":{"containers":[{"image":"rayproject/ray:2.46.0","name":"ray-head","ports":[{"containerPort":6379,"name":"gcs-server"},{"containerPort":8265,"name":"dashboard"},{"containerPort":10001,"name":"client"}],"resources":{"limits":{"cpu":1,"memory":"2G"},"requests":{"cpu":1,"memory":"2G"}}}],"schedulerName":"default-scheduler"}}},"rayVersion":"2.46.0","workerGroupSpecs":[{"groupName":"workergroup","minReplicas":3,"numOfHosts":4,"rayStartParams":{},"replicas":1,"template":{"spec":{"containers":[{"image":"rayproject/ray:2.46.0","name":"ray-worker","resources":{"limits":{"cpu":1,"memory":"1G"},"requests":{"cpu":1,"memory":"1G"}}}]}}}]}}
  creationTimestamp: "2025-10-28T16:05:15Z"
  generation: 1
  name: raycluster-kuberay
  namespace: default
  resourceVersion: "13168"
  uid: c83e5bd6-c5ee-4a22-b615-341fee75725a
....
status:
  availableWorkerReplicas: 12
  conditions:
  - lastTransitionTime: "2025-10-28T16:05:36Z"
    message: ""
    reason: HeadPodRunningAndReady
    status: "True"
    type: HeadPodReady
  - lastTransitionTime: "2025-10-28T16:06:43Z"
    message: All Ray Pods are ready for the first time
    reason: AllPodRunningAndReadyFirstTime
    status: "True"
    type: RayClusterProvisioned
  - lastTransitionTime: "2025-10-28T16:05:36Z"
    message: ""
    reason: RayClusterSuspended
    status: "False"
    type: RayClusterSuspended
  - lastTransitionTime: "2025-10-28T16:05:36Z"
    message: ""
    reason: RayClusterSuspending
    status: "False"
    type: RayClusterSuspending
  desiredCPU: "5"
  desiredGPU: "0"
  desiredMemory: 6G
  desiredTPU: "0"
  desiredWorkerReplicas: 12
  endpoints:
    client: "10001"
    dashboard: "8265"
    gcs-server: "6379"
    metrics: "8080"
  head:
    podIP: 10.244.0.34
    podName: raycluster-kuberay-head-g5wzm
    serviceIP: 10.244.0.34
    serviceName: raycluster-kuberay-head-svc
  lastUpdateTime: "2025-10-28T16:06:43Z"
  maxWorkerReplicas: -4                <---- overflowed
  minWorkerReplicas: 12
  observedGeneration: 1
  readyWorkerReplicas: 12
  state: ready
  stateTransitionTimes:
    ready: "2025-10-28T16:06:43Z"
```

After the fix, the maximum replicas now caps at 2,147,483,647.

```yaml
$kubectl get raycluster raycluster-kuberay -o yaml

apiVersion: ray.io/v1
kind: RayCluster
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"ray.io/v1","kind":"RayCluster","metadata":{"annotations":{},"name":"raycluster-kuberay","namespace":"default"},"spec":{"headGroupSpec":{"rayStartParams":{},"template":{"spec":{"containers":[{"image":"rayproject/ray:2.46.0","name":"ray-head","ports":[{"containerPort":6379,"name":"gcs-server"},{"containerPort":8265,"name":"dashboard"},{"containerPort":10001,"name":"client"}],"resources":{"limits":{"cpu":1,"memory":"2G"},"requests":{"cpu":1,"memory":"2G"}}}],"schedulerName":"default-scheduler"}}},"rayVersion":"2.46.0","workerGroupSpecs":[{"groupName":"workergroup","minReplicas":3,"numOfHosts":4,"rayStartParams":{},"replicas":1,"template":{"spec":{"containers":[{"image":"rayproject/ray:2.46.0","name":"ray-worker","resources":{"limits":{"cpu":1,"memory":"1G"},"requests":{"cpu":1,"memory":"1G"}}}]}}}]}}
  creationTimestamp: "2025-10-30T10:53:15Z"
  generation: 1
  name: raycluster-kuberay
  namespace: default
  resourceVersion: "2885229"
  uid: 1be0d901-2c48-45e1-a3ef-fbfc6f4f6d45
spec:
  headGroupSpec:
    rayStartParams: {}
    template:
      spec:
        containers:
        - image: rayproject/ray:2.46.0
          name: ray-head
          ports:
          - containerPort: 6379
            name: gcs-server
            protocol: TCP
          - containerPort: 8265
            name: dashboard
            protocol: TCP
          - containerPort: 10001
            name: client
            protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 2G
            requests:
              cpu: 1
              memory: 2G
        schedulerName: default-scheduler
  rayVersion: 2.46.0
  workerGroupSpecs:
  - groupName: workergroup
    maxReplicas: 2147483647.               <---- caps at 2147483647
    minReplicas: 3
    numOfHosts: 4
    rayStartParams: {}
    replicas: 1
    template:
      spec:
        containers:
        - image: rayproject/ray:2.46.0
          name: ray-worker
          resources:
            limits:
              cpu: 1
              memory: 1G
            requests:
              cpu: 1
              memory: 1G

```

## Related issue number

Closes #4153

## Checks

- [ ] I've made sure the tests are passing.
- Testing Strategy
  - [x] Unit tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by justinyeh1995** [comment]
@win5923 @Future-Outlier I somehow could not add you as reviewers, so I will ping you here instead. Please take a look. Thanks!

File: ray-operator/controllers/ray/utils/util.go [hunk 1]
```diff
@@ -393,15 +393,21 @@ func CalculateMinReplicas(cluster *rayv1.RayCluster) int32 {
 
 // CalculateMaxReplicas calculates max worker replicas at the cluster level
 func CalculateMaxReplicas(cluster *rayv1.RayCluster) int32 {
-	count := int32(0)
+	count := int64(0)
```
Comment (justinyeh1995) [inline ray-operator/controllers/ray/utils/util.go]: int64 maximum value is approximately 9 × 10^18

Worst case scenario would be
maxReplicas (int32): maximum value = 2,147,483,647
numOfHosts (int32): maximum value = 2,147,483,647
Maximum product: 2,147,483,647 × 2,147,483,647 is approximately 4 × 10^18

It is well within int64 range.

**Comment by justinyeh1995** [comment]
> Can we do sth like
> 
> https://github.com/ray-project/kuberay/blob/2acc21964d6ff8df1009b837d24e1f372859f89b/ray-operator/controllers/ray/utils/util.go#L249
> 
> to avoid `nosec`?

I think we can.

Say we have another function
```go
func SafeInt64ToInt32(n int64) int32 
```
we can change the logic into something like this 
```go
func CalculateMaxReplicas(cluster *rayv1.RayCluster) int32 {
	count := int64(0)
	for _, nodeGroup := range cluster.Spec.WorkerGroupSpecs {
		if nodeGroup.Suspend != nil && *nodeGroup.Suspend {
			continue
		}
		count += int64(*nodeGroup.MaxReplicas) * int64(nodeGroup.NumOfHosts)

		// stop the calculation if an overflow happens
		if count > math.MaxInt32 {
			break
		}
	}

	return SafeInt64ToInt32(count)
```
Do you think it will be a reasonable way of approaching it?

**Comment by troychiu** [comment]
yeah IMO that's better

**Review by 400Ping — APPROVED** [review]
LGTM

**Comment by justinyeh1995** [comment]
> yeah IMO that's better

Sounds good. I will update this section accordingly.

File: ray-operator/controllers/ray/utils/util.go [hunk 2]
```diff
@@ -253,6 +253,14 @@ func SafeUint64ToInt64(n uint64) int64 {
 	return int64(n)
 }
 
+// CapInt64ToInt32 converts int64 to int32, capping at math.MaxInt32 if the value exceeds it.
+func CapInt64ToInt32(n int64) int32 {
+	if n > math.MaxInt32 {
+		return math.MaxInt32
+	}
```
Comment (troychiu) [inline ray-operator/controllers/ray/utils/util.go:261]: You may need a minimum check to avoid lint error. Also, could you follow the naming convention for the function?

File: ray-operator/controllers/ray/utils/util.go [hunk 3]
```diff
@@ -393,15 +401,20 @@ func CalculateMinReplicas(cluster *rayv1.RayCluster) int32 {
...
-	count := int32(0)
+	count := int64(0)
 	for _, nodeGroup := range cluster.Spec.WorkerGroupSpecs {
 		if nodeGroup.Suspend != nil && *nodeGroup.Suspend {
 			continue
 		}
-		count += (*nodeGroup.MaxReplicas * nodeGroup.NumOfHosts)
+		count += int64(*nodeGroup.MaxReplicas) * int64(nodeGroup.NumOfHosts)
+
+		// early return if an overflow happens
```
Comment (troychiu) [inline ray-operator/controllers/ray/utils/util.go]: Do we still need this early return if we will do a safe type casting?

File: ray-operator/controllers/ray/utils/util.go (hunk 2 above)
Comment (justinyeh1995) [reply ray-operator/controllers/ray/utils/util.go:261]: Thanks for the feedback! I'll add the minimum check and see if it resolves the lint error, and rename the function to SafeInt64ToInt32 as well.

File: ray-operator/controllers/ray/utils/util.go (hunk 3 above)
Comment (justinyeh1995) [reply ray-operator/controllers/ray/utils/util.go]: I think that's a decision to be made. The early return is a non-critical optimization 
but not as clean as Option 1. I'm happy to go with either way.

Option 1
```go
func CalculateMaxReplicas(cluster *rayv1.RayCluster) int32 {
	count := int64(0)
	for _, nodeGroup := range cluster.Spec.WorkerGroupSpecs {
		if nodeGroup.Suspend != nil && *nodeGroup.Suspend {
			continue
		}
		count += int64(*nodeGroup.MaxReplicas) * int64(nodeGroup.NumOfHosts)
	}
	return SafeInt64ToInt32(count)
```
Option 2
```go
func CalculateMaxReplicas(cluster *rayv1.RayCluster) int32 {
	count := int64(0)
	for _, nodeGroup := range cluster.Spec.WorkerGroupSpecs {
		if nodeGroup.Suspend != nil && *nodeGroup.Suspend {
			continue
		}
		count += int64(*nodeGroup.MaxReplicas) * int64(nodeGroup.NumOfHosts)

		// early return if an overflow happens
		if count > math.MaxInt32 {
			return math.MaxInt32
		}
	}
	return SafeInt64ToInt32(count)
}
```

Comment (troychiu) [reply ray-operator/controllers/ray/utils/util.go]: I'll go for option 1 but if others think option 2 is better then I am fine with it.

Comment (justinyeh1995) [reply ray-operator/controllers/ray/utils/util.go]: I see. Now with the SafeInt64ToInt32 doing the overflow/underflow prevention. I think Option 1 is much cleaner.

**Review by troychiu — APPROVED** [review]
Thank you!
