### PR TITLE
[RayService] Trim Redis Cleanup job less than 63 chars

### LINKED ISSUE #2845: [Bug] Fix long job names and labels exceeding 63 characters in Redis cleanup jobs
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

**What happened**

When the RayCluster name is long, the Redis cleanup job name and its associated labels exceed Kubernetes' 63-character limit. This results in the cleanup job failing to be created.

**Error Message:**
```yaml
spec.template.labels: Invalid value: "text-translation-model-rayservice-raycluster-g9gps-redis-cleanup": must be no more than 63 characters
```

**Expected Behavior**

The job name and labels should be truncated to comply with the Kubernetes 63-character limit while ensuring uniqueness. This would allow the Redis cleanup job to be created successfully even when the RayCluster name is long.

### Reproduction script

Create a rayservice with a long name, then delete it's raycluster, and execute `kubectl get events` to see cleanup job not getting created because of this issue.

### Anything else

_No response_

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by aviadshimoni**
## Why are these changes needed?

When the RayCluster name is too long, the Redis cleanup job name and associated labels exceed Kubernetes' 63-character limit. This causes the cleanup job to fail during creation with the following error:
```
Warning  FailedToCreateRedisCleanupJob  raycluster/text-translation-model-rayservice-raycluster-g9gps        Failed to create Redis cleanup Job text-translation-model/text-translation-model-rayservice-raycluster-g9gps-redis-cleanup, Job.batch "text-translation-model-rayservice-raycluster-g9gps-redis-cleanup" is invalid: spec.template.labels: Invalid value: "text-translation-model-rayservice-raycluster-g9gps-redis-cleanup": must be no more than 63 characters
```
## Related issue number

Closes #2845

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(
image

Update: Tested ✅ , great development doc! 🥇

### CODE REVIEW

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -1143,14 +1143,20 @@ func (r *RayClusterReconciler) buildWorkerPod(ctx context.Context, instance rayv
 func (r *RayClusterReconciler) buildRedisCleanupJob(ctx context.Context, instance rayv1.RayCluster) batchv1.Job {
 	logger := ctrl.LoggerFrom(ctx)
 
+	// Build the head pod
 	pod := r.buildHeadPod(ctx, instance)
 	pod.Labels[utils.RayNodeTypeLabelKey] = string(rayv1.RedisCleanupNode)
 
+	// Trim all labels to ensure they are within the 63-character limit
+	for key, value := range pod.Labels {
+		pod.Labels[key] = utils.CheckLabel(value)
```
Comment (andrewsykim) [inline ray-operator/controllers/ray/raycluster_controller.go:1152]: What's the reason for truncating all pod labels too?

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 2]
```diff
@@ -1196,9 +1202,12 @@ func (r *RayClusterReconciler) buildRedisCleanupJob(ctx context.Context, instanc
 	// For Kubernetes Job, the valid values for Pod's `RestartPolicy` are `Never` and `OnFailure`.
 	pod.Spec.RestartPolicy = corev1.RestartPolicyNever
 
+	// Trim the job name to ensure it is within the 63-character limit.
+	jobName := utils.CheckLabel(fmt.Sprintf("%s-%s", instance.Name, "redis-cleanup"))
```
Comment (andrewsykim) [inline ray-operator/controllers/ray/raycluster_controller.go:1206]: I think we can preserve. compatibility as long as we only truncate when fmt.Sprintf("%s-%s", instance.Name, "redis-cleanup") is greater than 63 chars.

Comment (andrewsykim) [reply ray-operator/controllers/ray/raycluster_controller.go:1206]: And it seems like CheckLabel already does this

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (aviadshimoni) [reply ray-operator/controllers/ray/raycluster_controller.go:1152]: because currently the error i get is on the label value:
```bash
ated worker Pod text-translation-model/text-translation-model-rayservice-raycluster-2xqx8-worker-q5x5w
9m28s       Warning   FailedToCreateRedisCleanupJob   raycluster/text-translation-model-rayservice-raycluster-g9gps         Failed to create Redis cleanup Job text-translation-model/text-translation-model-rayservice-raycluster-g9gps-redis-cleanup, Job.batch "text-translation-model-rayservice-raycluster-g9gps-redis-cleanup" is invalid: spec.template.labels: Invalid value: "text-translation-model-rayservice-raycluster-g9gps-redis-cleanup": must be no more than 63 characters
```

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 2 above)
Comment (aviadshimoni) [reply ray-operator/controllers/ray/raycluster_controller.go:1206]: excactly @andrewsykim, I could create another function just for clarity but it will do the same thing

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (DanielChern) [reply ray-operator/controllers/ray/raycluster_controller.go:1152]: I have reasons to believe that this is not required , those are the labels for Job metadata , but error indicates that the issue is with label inside spec.template. The trim of the Job name should to be enough.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 2 above)
Comment (DanielChern) [reply ray-operator/controllers/ray/raycluster_controller.go:1206]: Maybe it will be better to create a function to trim the function , this usage may confuse future reviewers

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (rueian) [reply ray-operator/controllers/ray/raycluster_controller.go:1152]: @aviadshimoni If those labels need to be trimmed, that means the Head Pod can't be created either. Did you see your Head Pod have the same issue?

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 3]
```diff
@@ -1143,14 +1143,20 @@ func (r *RayClusterReconciler) buildWorkerPod(ctx context.Context, instance rayv
...
 	logger := ctrl.LoggerFrom(ctx)
 
+	// Build the head pod
 	pod := r.buildHeadPod(ctx, instance)
 	pod.Labels[utils.RayNodeTypeLabelKey] = string(rayv1.RedisCleanupNode)
 
+	// Trim labels to meet Kubernetes naming constraints
+	for key, value := range pod.Labels {
+		pod.Labels[key] = utils.CheckLabel(value)
+	}
```
Comment (rueian) [inline ray-operator/controllers/ray/raycluster_controller.go:1153]:
```suggestion
```

I tried the test without these lines and the test still passed. I think we just don't need these lines.

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 4]
```diff
@@ -1209,8 +1218,10 @@ func (r *RayClusterReconciler) buildRedisCleanupJob(ctx context.Context, instanc
 				ObjectMeta: pod.ObjectMeta,
 				Spec:       pod.Spec,
 			},
-			// make this job be best-effort only for 5 minutes.
+			// Make this job best-effort only for 5 minutes.
 			ActiveDeadlineSeconds: ptr.To[int64](300),
+			// Keep the Job for 3 minutes after it completes for debugging
+			TTLSecondsAfterFinished: ptr.To[int32](180),
```
Comment (rueian) [inline ray-operator/controllers/ray/raycluster_controller.go:1224]:
```suggestion
```

File: ray-operator/controllers/ray/utils/util.go [hunk 5]
```diff
@@ -205,6 +205,11 @@ func CheckName(s string) string {
 	return s
 }
 
+// TrimJobName uses CheckLabel to trim Kubernetes job to constrains
+func TrimJobName(jobName string) string {
+	return CheckLabel(jobName)
```
Comment (andrewsykim) [inline ray-operator/controllers/ray/utils/util.go:210]: In a follow-up PR, I would create a private function `trimString` and then call `trimString` from both `TrimJobName` and `CheckLabels`

File: ray-operator/test/e2e/raycluster_gcsft_test.go [hunk 6]
```diff
@@ -74,6 +74,20 @@ func TestGcsFaultToleranceOptions(t *testing.T) {
 			},
 			createSecret: true,
 		},
+		{
+			name:          "Long RayCluster Name",
```
Comment (andrewsykim) [inline ray-operator/test/e2e/raycluster_gcsft_test.go:78]: @rueian @aviadshimoni  do you know if this e2e test actually exercises the clean-up job? I guess it does because at the end it waits for RayCluster deletion to succeed?

**Review by andrewsykim — COMMENTED** [review]
LGTM, just a minor question about the e2e test

File: ray-operator/test/e2e/raycluster_gcsft_test.go (hunk 6 above)
Comment (rueian) [reply ray-operator/test/e2e/raycluster_gcsft_test.go:78]: Yes, it does. `defer g.Eventually(checkRedisDBSize, time.Second*30, time.Second).Should(BeEquivalentTo("0"))` makes sure the redis is cleaned up.

Comment (andrewsykim) [reply ray-operator/test/e2e/raycluster_gcsft_test.go:78]: thanks!
