### PR TITLE
Add reminders to avoid RBAC synchronization bug

### LINKED ISSUE #164: [Bug] RBAC file can not be updated automatically
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I make some changes to kubebuilder rbac markers, after I enter `ray-operator` folder and run `make manifests`, I expect the clusterrole file can be updated automatically. However, it's not. 

https://github.com/ray-project/kuberay/blob/0ef786113439d777330a8d2067f8a6449502cc56/ray-operator/controllers/raycluster_controller.go#L62-L73

### Reproduction script

```
# 1. make kubebuilder rbac marker changes

2. `cd ray-operator`

3. `make manifests`

4. git diff -> not updates

```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

In #164, @Jeffwan mentions that RBAC files cannot be updated automatically with the command `make manifests`. The root cause is the lack of a newline after kubebuilder markers. This issue is same as https://github.com/kubernetes-sigs/controller-tools/issues/551.

In addition, the permissions of `config/rbac/role.yaml` is the union of kubebuilder markers in `raycluster_controller.go`, `rayjob_controller.go`, and `rayservice_controller.go`.

## Related issue number

closes #164 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

* Step1: Add the following marker in one of "xxxxx_controller.go"
  * `// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;list;watch;create;update;delete`
* Step2: `make manifests`
* Step3: Check `config/role.yaml`
  * There is no kubebuilder marker defining permissions of Deployment, and thus `role.yaml` will be updated.

### CODE REVIEW

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -80,6 +80,7 @@ type RayClusterReconciler struct {
 // +kubebuilder:rbac:groups="rbac.authorization.k8s.io",resources=roles,verbs=get;list;watch;create;delete;update
 // +kubebuilder:rbac:groups="rbac.authorization.k8s.io",resources=rolebindings,verbs=get;list;watch;create;delete
 
+// [WARNING]: There MUST be a newline after kubebuilder markers.
```
Comment (Jeffwan) [inline ray-operator/controllers/ray/raycluster_controller.go:83]: em. is not line 82 a new line? I may forgot the tricks here.

Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:83]: The new line is added by #577. Originally, it does not have a newline.

Comment (Jeffwan) [reply ray-operator/controllers/ray/raycluster_controller.go:83]: I mean the new line was added in https://github.com/ray-project/kuberay/pull/577 and the bug should be fixed? This PR is to add some comment to reminder developer?  But the title is the bug fix?

Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:83]: Got it. The title is confusing. I opened this PR prior to #577, but #577 was merged prior to this PR. Then, I rebased this branch with upstream. I will update the title. Thank you for pointing this out!

**Review by Jeffwan — APPROVED** [review]
