### PR TITLE
[Bug][Autoscaler] Operator does not remove workers

### LINKED ISSUE #942: [Bug] Operator does not remove workers
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The operator sometimes ends up in a bad state where it is not able to remove workers.

Logs that might be relevant:

**monitor.log**
```
2023-03-03 07:20:43,762	INFO node_provider.py:239 -- Listing pods for RayCluster ray in namespace default at pods resource version >= 4144232.
2023-03-03 07:20:43,816	INFO node_provider.py:257 -- Fetched pod data at resource version 4144232.
2023-03-03 07:20:43,820	INFO autoscaler.py:143 -- The autoscaler took 0.106 seconds to fetch the list of non-terminated nodes.
2023-03-03 07:20:43,820	WARNING node_provider.py:328 -- Waiting for operator to remove worker ray-worker-ray-n1-standard-8-ssd-0-gpu-1-9bf4k.
2023-03-03 07:20:43,820	INFO autoscaler.py:396 -- Backing off of autoscaler update. Will try again in 5 seconds.
2023-03-03 07:20:48,928	INFO node_provider.py:239 -- Listing pods for RayCluster ray in namespace default at pods resource version >= 4144304.
2023-03-03 07:20:48,983	INFO node_provider.py:257 -- Fetched pod data at resource version 4144304.
2023-03-03 07:20:48,989	INFO autoscaler.py:143 -- The autoscaler took 0.113 seconds to fetch the list of non-terminated nodes.
2023-03-03 07:20:48,989	WARNING node_provider.py:328 -- Waiting for operator to remove worker ray-worker-ray-n1-standard-8-ssd-0-gpu-1-9bf4k.
2023-03-03 07:20:48,990	INFO autoscaler.py:396 -- Backing off of autoscaler update. Will try again in 5 seconds.
```

**operator logs**
```
2023-03-03T08:11:49.945Z	INFO	controllers.RayCluster	reconciling RayCluster	{"cluster name": "ray"}
2023-03-03T08:11:49.945Z	INFO	controllers.RayCluster	reconcileServices 	{"headService service found": "ray-head-svc"}
2023-03-03T08:11:49.946Z	INFO	controllers.RayCluster	reconcilePods 	{"head pod found": "ray-head-bmgrb"}
2023-03-03T08:11:49.946Z	INFO	controllers.RayCluster	reconcilePods	{"head pod is up and running... checking workers": "ray-head-bmgrb"}
2023-03-03T08:11:49.946Z	INFO	controllers.RayCluster	reconcilePods	{"removing the pods in the scaleStrategy of": "ray-n1-standard-8-ssd-0-gpu-0"}
2023-03-03T08:11:49.946Z	INFO	controllers.RayCluster	reconcilePods	{"all workers already exist for group": "ray-n1-standard-8-ssd-0-gpu-0"}
2023-03-03T08:11:49.947Z	INFO	controllers.RayCluster	reconcilePods	{"removing the pods in the scaleStrategy of": "ray-n1-standard-8-ssd-1-gpu-0"}
2023-03-03T08:11:49.947Z	INFO	controllers.RayCluster	reconcilePods	{"all workers already exist for group": "ray-n1-standard-8-ssd-1-gpu-0"}
2023-03-03T08:11:49.947Z	INFO	controllers.RayCluster	reconcilePods	{"removing the pods in the scaleStrategy of": "ray-n1-highmem-8-ssd-1-gpu-0"}
2023-03-03T08:11:49.947Z	INFO	controllers.RayCluster	reconcilePods	{"all workers already exist for group": "ray-n1-highmem-8-ssd-1-gpu-0"}
2023-03-03T08:11:49.948Z	INFO	controllers.RayCluster	reconcilePods	{"removing the pods in the scaleStrategy of": "ray-e2-highmem-16-ssd-0-gpu-0"}
2023-03-03T08:11:49.948Z	INFO	controllers.RayCluster	reconcilePods	{"all workers already exist for group": "ray-e2-highmem-16-ssd-0-gpu-0"}
2023-03-03T08:11:49.948Z	INFO	controllers.RayCluster	reconcilePods	{"removing the pods in the scaleStrategy of": "ray-n2-highmem-32-ssd-0-gpu-0"}
2023-03-03T08:11:49.948Z	INFO	controllers.RayCluster	reconcilePods	{"all workers already exist for group": "ray-n2-highmem-32-ssd-0-gpu-0"}
2023-03-03T08:11:49.948Z	INFO	controllers.RayCluster	reconcilePods	{"removing the pods in the scaleStrategy of": "ray-n1-standard-8-ssd-0-gpu-1"}
2023-03-03T08:11:49.948Z	INFO	controllers.RayCluster	reconcilePods	{"all workers already exist for group": "ray-n1-standard-8-ssd-0-gpu-1"}
2023-03-03T08:11:49.949Z	INFO	controllers.RayCluster	reconcilePods	{"removing the pods in the scaleStrategy of": "ray-n1-standard-8-ssd-1-gpu-1"}
2023-03-03T08:11:49.949Z	INFO	controllers.RayCluster	reconcilePods	{"all workers already exist for group": "ray-n1-standard-8-ssd-1-gpu-1"}
```

### Reproduction script

No reproduction script.

### Anything else

This has happened only once, but we have only been using KubeRay for a week on our staging cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

The function `updateLocalWorkersToDelete` will update `WorkersToDelete` by filtering out Pods that are not included in `runningPods`. Hence, Pods with the status `PodFailed` are not deleted permanently.

In the autoscaler scale-down process, the autoscaler adds a failed Pod to `WorkersToDelete` and waits for all Pods in `WorkersToDelete` to be deleted before making the next decision. You can find the corresponding code [here](https://sourcegraph.com/github.com/ray-project/ray@ray-2.4.0/-/blob/python/ray/autoscaler/_private/kuberay/node_provider.py?L324-L329). However, the failed Pods will not be deleted by operator because of `updateLocalWorkersToDelete`.

* Note (optional): The definition of `non_terminated_nodes` in Autoscaler ([link](https://sourcegraph.com/github.com/ray-project/ray@cd1ba65e239360c8a7b130f991ed414eccc063ce/-/blob/python/ray/autoscaler/_private/kuberay/node_provider.py?L263))

### Case 1: Without this PR + `PodFailed` Pod + Autoscaling

* If the autoscaler adds a `PodFailed` Pod to `WorkersToDelete`, it will remain stuck there until the Pod is manually deleted by the user. This is because the function `updateLocalWorkersToDelete` ignores `PodFailed` Pods.

### Case 2: Without this PR + `PodFailed` Pod + No autoscaling

* The failed Pod will not be deleted. The KubeRay operator will attempt to maintain the cluster with the desired number of worker Pods (`Spec.WorkerGroupSpecs[*].Replicas`) that are in the `RUNNING` or `PENDING` status.

### Case 3: With this PR + `PodFailed` Pod + Autoscaling

* If the autoscaler adds a `PodFailed` Pod to `WorkersToDelete`, the KubeRay operator will delete all Pods in `WorkersToDelete`, regardless of their statuses.

### Case 4: With this PR + `PodFailed` Pod + No autoscaling

* Same as Case 2, we need to have a better approach considering the discussion in https://github.com/ray-project/kuberay/pull/1139#discussion_r1217179119.

## Related issue number
Closes #942 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

```sh
kind create cluster --image=kindest/node:v1.23.0

# path: ray-operator/
make docker-image
kind load docker-image controller:latest

# Install a KubeRay operator
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0 --set image.repository=controller,image.tag=latest

# Create an autoscaling RayCluster via a gist.
# https://gist.github.com/kevin85421/97b1241228add6ab04a30c7113479248
# Set `restartPolicy` to `Never`.
kubectl apply -f gist.yaml

# Log in to the worker Pod
kubectl exec -it ${WORKER_POD} -- bash

# Check the `ray start` process PID. In the following screenshot, the PID is 14.
ps aux
kill 14

# The worker Pod successfully become `PodFailed`.
kubectl get pods ${WORKER_POD} -o jsonpath='{.status.phase}'
# expected output: Failed

# The failed Pod should be deleted.
```

## Reproduction

```sh
kind create cluster --image=kindest/node:v1.23.0
helm install kuberay-operator kuberay/kuberay-operator --version 0.5.0

# Create an autoscaling RayCluster via a gist.
# https://gist.github.com/kevin85421/97b1241228add6ab04a30c7113479248
# Set `restartPolicy` to `Never`.
kubectl apply -f gist.yaml

# Log in to the worker Pod
kubectl exec -it ${WORKER_POD} -- bash

# Check the `ray start` process PID. In the following screenshot, the PID is 14.
ps aux
kill 14

# The worker Pod successfully become `PodFailed`.
kubectl get pods ${WORKER_POD} -o jsonpath='{.status.phase}'
# expected output: Failed

# The failed Pod will not be deleted.
```

Screen Shot 2023-06-03 at 4 17 42 PM

Screen Shot 2023-06-03 at 4 23 25 PM

### CODE REVIEW

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -532,14 +532,13 @@ func (r *RayClusterReconciler) reconcilePods(instance *rayv1alpha1.RayCluster) e
...
-		for _, aPod := range workerPods.Items {
-			if (aPod.Status.Phase == corev1.PodRunning || aPod.Status.Phase == corev1.PodPending) && aPod.ObjectMeta.DeletionTimestamp == nil {
-				runningPods.Items = append(runningPods.Items, aPod)
+		for _, pod := range workerPods.Items {
+			// TODO (kevin85421): We also need to have a clear story of all the Pod status phases, especially for PodFailed.
+			if isPodRunningOrPendingAndNotDeleting(pod) {
+				runningPods.Items = append(runningPods.Items, pod)
 			}
 		}
-		r.updateLocalWorkersToDelete(&worker, runningPods.Items)
```
Comment (kevin85421) [inline ray-operator/controllers/ray/raycluster_controller.go:540]: This function will update `WorkersToDelete` by filtering out Pods that are not included in `runningPods`.

**Comment by kevin85421** [comment]
cc @qizzzh

**Comment by kevin85421** [comment]
cc @Yicheng-Lu-llll

**Comment by qizzzh** [comment]
Does it mean that before this change is released we would need to manually delete failed pods in order to autoscaler scale-down to work? Would scale-up be affected?

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 2]
```diff
@@ -532,14 +532,13 @@ func (r *RayClusterReconciler) reconcilePods(instance *rayv1alpha1.RayCluster) e
...
 		diff := workerReplicas - int32(len(runningPods.Items))
-
 		if PrioritizeWorkersToDelete {
```
Comment (Yicheng-Lu-llll) [inline ray-operator/controllers/ray/raycluster_controller.go:542]: Just for my education,  Is there any conditions that we need set `PrioritizeWorkersToDelete` to `false`?

The reason I am asking this is because without `PrioritizeWorkersToDelete`, if  ` diff >= 0`, the kuberay operator will not respect the spec field(here `WorkersToDelete`) set by autoscaler.

Comment (Yicheng-Lu-llll) [inline ray-operator/controllers/ray/raycluster_controller.go:542]: Just for my education, Is there any conditions that we need to set `PrioritizeWorkersToDelete` to false?

The reason I am asking this is because without `PrioritizeWorkersToDelete`, if  diff >= 0, the kuberay operator will not respect the spec field(here `WorkersToDelete`) set by autoscaler.

Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/raycluster_controller.go:542]: Perhaps I'm missing something, but for now, It seems to me:

- If the autoscaler is enabled, it is necessary to set `PrioritizeWorkersToDelete` to `true` to ensure that the autoscaler functions properly.
- if autoscaler is disabled, then the user is the only one who can update the `WorkersToDelete` field. In this case, the user effectively acts as the autoscaler. 

So, I can not think a situation that we need to set `PrioritizeWorkersToDelete` to `false`.

Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/raycluster_controller.go:542]: Consider a situation with `PrioritizeWorkersToDelete` set to `false`:

1. at T0, we have 8 running workers.
2. at T1, user decides to remove worker A. So, he set replica = replica -1, and add worker A to `WorkersToDelete` in the yaml file.
3. at the same time T1, worker B and worker C fails because of OOM(let's see the restart policy is never).
4. at time T2, kuberay operator tries to collect all running workers and compare with the expected replica. it will find that the num current running pods is 8-2 = 6, the expected replica is 8 - 1 = 7. So, kuberay operator will add a new workers and never delete worker A.

**Review by DmitriGekhtman — APPROVED** [review]

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 3]
```diff
@@ -532,14 +532,13 @@ func (r *RayClusterReconciler) reconcilePods(instance *rayv1alpha1.RayCluster) e
 		}
 
 		runningPods := corev1.PodList{}
-		for _, aPod := range workerPods.Items {
-			if (aPod.Status.Phase == corev1.PodRunning || aPod.Status.Phase == corev1.PodPending) && aPod.ObjectMeta.DeletionTimestamp == nil {
-				runningPods.Items = append(runningPods.Items, aPod)
+		for _, pod := range workerPods.Items {
+			// TODO (kevin85421): We also need to have a clear story of all the Pod status phases, especially for PodFailed.
```
Comment (DmitriGekhtman) [inline ray-operator/controllers/ray/raycluster_controller.go:536]: Currently, we delete PodFailed pods if the reason is Eviction.
No particular story there -- someone complained that the evicted pods aren't deleted, so we did that.
Maybe we should just delete all failed pods?

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 2 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:542]: > Is there any conditions that we need to set PrioritizeWorkersToDelete to false?

`PrioritizeWorkersToDelete` is a feature gate (#208), and its default value is set to true. You can refer to the lessons we learned from #973. If we have a feature that allows users to enable or disable it, the cost of addressing the issue after the v0.5.0 release will not be that expensive. When the feature is stable enough, we can remove it.

>

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 4]
```diff
@@ -555,7 +554,11 @@ func (r *RayClusterReconciler) reconcilePods(instance *rayv1alpha1.RayCluster) e
 					}
 					r.Log.Info("reconcilePods", "unable to delete worker ", pod.Name)
 				} else {
-					diff++
+					// For example, the failed Pod (Status: corev1.PodFailed) is not counted in the `runningPods` variable.
+					// Therefore, we should not update `diff` when we delete a failed Pod.
+					if isPodRunningOrPendingAndNotDeleting(pod) {
```
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:559]: I cannot understand the point you are trying to make. We still need to calculate the number of Pods in `WorkersToDelete` that overlap with `runningPods`. Would you mind providing more details about the point you're trying to make? We can continue the discussion here or chat offline.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 3 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:536]: > Currently, we delete PodFailed pods if the reason is Eviction.

https://github.com/ray-project/kuberay/blob/c4201350ef13598490031f936b945565dcde9dd5/ray-operator/controllers/ray/raycluster_controller.go#L407

Based on the provided code snippet, it appears that only the head Pod with a status of `PodFailed` and reason `Evicted` will be deleted. The function `updateLocalWorkersToDelete` filters out the Pods with a status of PodFailed, so the PodFailed workers will be completely excluded from the deletion process. Do I miss anything?

> Maybe we should just delete all failed pods?

I consider to do that. Because the change could have a significant impact on stability, either positive or negative, I will create a separate PR with more careful considerations at a later time. Some points that I need to figure out:

* With GCS fault tolerance enabled, KubeRay will label certain Pods as unhealthy if their probes generate unhealthy events. Then, KubeRay will delete the Pods with the unhealthy label. This behavior may be refactored soon, and it is a bit overlapped with removing `PodFailed` Pods.

* Some users prefer to retain certain unhealthy Pods or Pods in a PodFailed state for troubleshooting purposes. (e.g. #1022)

**Review by Yicheng-Lu-llll — APPROVED** [review]

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:559]: Sync with @Yicheng-Lu-llll offline: 

[Yicheng's point]

This loop will send `Delete` requests to the Kubernetes API Server to delete Pods in `WorkersToDelete'` Afterward, we can list the worker Pods so that we do not need to maintain the `diff` within the loop.

https://github.com/ray-project/kuberay/blob/c4201350ef13598490031f936b945565dcde9dd5/ray-operator/controllers/ray/raycluster_controller.go#L472-L476

[Conclusion]

We cannot guarantee that the informer cache will be consistent with the Kubernetes API Server when listing worker Pods. Therefore, it is still necessary to calculate the `diff` within the loop.

**Review by architkulkarni — APPROVED** [review]
This looks good to me. Could you please add a bit to the PR description to describe the fix that's made in this PR?

~(Before reading the code, based on the PR description I guessed that the PR would change the behavior to delete all pods including failed pods, but actually what the PR does is to correct the value of `diff` to fix the autoscaling bug)~
Update: discussed offline, actually `diff` was correct before, but after deleting the filtering function, the PR needs to account for that in `diff` to make it correct again.

**Comment by kevin85421** [comment]
@architkulkarni I have updated the PR description. Is it clear now? Thanks!

**Comment by kevin85421** [comment]
Create a follow up issue: https://github.com/ray-project/kuberay/issues/1144
