### PR TITLE
[Fix] rayjob update raycluster status

### LINKED ISSUE #4190: [Bug] RayJob InTreeAutoscaling does not update replicas field inside RayJob
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When I test RayJob + AutoScale, I find KubeRay updates replicas field in RayCluster but not in RayJob when scaling up. This causes inconsistency between RayCluster and RayJob.

For example, I submitted a RayJob with replicas:1, min: 1, max:5, enabled InTreeAutoscaling on the RayJob. KubeRay did AutoScaling to update replicas to 5 on RayCluster, but replicas field on RayCluster was still 1.

### Reproduction script

Run RayJob like following with KubRay, wait around half minute, will see Ray autoscale kicks in and updates replicas field inside RayCluster to 5 and starts extra Ray workers. But replicas field inside RayJob will be kept as 1, not updated to 5 as expected.

```
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sample
  namespace: kuberay
spec:
  entrypoint: python /home/ray/samples/sample_code.py
  shutdownAfterJobFinishes: true
  rayClusterSpec:
    rayVersion: '2.46.0' # should match the Ray version in the image of the containers
    autoscalerOptions:
      idleTimeoutSeconds: 30
      upscalingMode: Aggressive
    enableInTreeAutoscaling: true
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.46.0
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265 # Ray dashboard
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              limits:
                cpu: "500m"
                memory: "2Gi"
              requests:
                cpu: "500m"
                memory: "2Gi"
            volumeMounts:
            - mountPath: /home/ray/samples
              name: code-sample
          volumes:
          - name: code-sample
            configMap:
              # Provide the name of the ConfigMap you want to mount.
              name: ray-job-code-sample
              # An array of keys from the ConfigMap to create as files
              items:
              - key: sample_code.py
                path: sample_code.py
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      groupName: small-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
            image: rayproject/ray:2.46.0
            resources:
              limits:
                cpu: "500m"
                memory: "2Gi"
              requests:
                cpu: "500m"
                memory: "2Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-job-code-sample
  namespace: kuberay
data:
  sample_code.py: |
    import ray
    import os
    import time

    ray.init()
    
    @ray.remote
    def my_task(x, s):
        import time
        print(f"Sleeping in worker")
        time.sleep(s)
        return x * x

    results = ([ray.get(my_task.remote(i, 1)) for i in range(30)])
    print(f"results: {results}")

    results = ray.get([my_task.remote(i, 20) for i in range(10)])
    print(f"results: {results}")

    results = ([ray.get(my_task.remote(i, 1)) for i in range(30)])
    print(f"results: {results}")
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by machichima**
## Why are these changes needed?

When the RayCluster created by RayJob has status update, it's not updated on the RayJob's RayClusterStatus field (e.g. KubeRay updates replicas field in RayCluster but not in RayJob when scaling up).

Modify the `updateRayJobStatus` function to also update rayjob status when `RayClusterStatus` field changes.

Test:
- added e2e test
- Run script provided in #4190, and check if without `jobStatus` or `jobDeploymentStatus` update, the `availableWorkerReplicas` and `desiredWorkerReplicas` are being updated.

Result screenshot:

image

## Related issue number

Closes #4190

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [ ] Unit tests
  - [x] e2e tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Review by 400Ping — APPROVED** [review]

**Review by ryankert01 — APPROVED** [review]

File: ray-operator/test/e2erayjob/rayjob_test.go [hunk 1]
```diff
@@ -433,4 +433,45 @@ env_vars:
...
+		_, err = test.Client().Ray().RayV1().RayClusters(namespace.Name).UpdateStatus(test.Ctx(), rayCluster, metav1.UpdateOptions{})
+		g.Expect(err).NotTo(HaveOccurred())
+
+		g.Eventually(func() int32 {
+			job, err := GetRayJob(test, rayJob.Namespace, rayJob.Name)
+			if err != nil {
+				return originalMaxWorkerReplica
+			}
+			return job.Status.RayClusterStatus.MaxWorkerReplicas
+		}, TestTimeoutShort).Should(Equal(newMaxWorkerReplica))
```
Comment (fscnick) [inline ray-operator/test/e2erayjob/rayjob_test.go:471]: nit: it might benefit the early failure if it gets some error.
```suggestion
g.Eventually(RayJob(test, rayJob.Namespace, rayJob.Name), TestTimeoutShort).
			Should(WithTransform(func(job *rayv1.RayJob) int32 {
				return job.Status.RayClusterStatus.MaxWorkerReplicas
			}, Equal(newMaxWorkerReplica)))
```

**Review by fscnick — APPROVED** [review]
