### PR TITLE
[GCS FT][Refactor] Redefine the behavior for deleting Pods and stop listening to Kubernetes events

### LINKED ISSUE #618: [Bug] Revisit the use of kubectl wait to avoid flakiness
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen

In KinD E2E tests, we use `kubectl wait` to block the process only when the system is not ready. However, it is not good to use `kubectl wait --for=condition=Ready` after deleting a resource.

[Example 1]
The test `test_detached_actor` kills GCS on the head pod and uses `kubectl wait` to make sure that the new head pod is ready. However, in my experiment, the head pod will need 60 seconds to crash after the GCS server is killed. The head pod is `READY:1/1, STATUS: Running` before the crash. Hence, `kubectl wait` cannot make sure the new head pod is ready.

https://github.com/ray-project/kuberay/blob/ea6e8d1e5d36690c2a3577361db124fad1389a00/tests/compatibility-test.py#L319-L327

[Example 2]
`READY: 1/1` cannot imply `STATUS: Running`. Hence, sometimes `kubectl wait --for=condition=ready` will consider a pod with `READY: 1/1, STATUS: Terminating` to meet conditions. See the post "[How can a pod have status ready and terminating?](https://stackoverflow.com/questions/55814358/how-can-a-pod-have-status-ready-and-terminating)" for more details.

* [Link](https://github.com/ray-project/kuberay/actions/runs/3184155202/jobs/5192330490#step:3:1733)
  ```
  INFO:kuberay_utils.utils:executing cmd: kubectl wait --for=condition=ready pod -l rayCluster=raycluster-compatibility-test --all --timeout=900s
  pod/raycluster-external-redis-head-xvhcg condition met
  pod/raycluster-external-redis-worker-small-group-r5s2s condition met
  INFO:kuberay_utils.utils:executing cmd: kubectl get pods -A
  NAMESPACE            NAME                                                 READY   STATUS        RESTARTS   AGE
  default              raycluster-external-redis-head-xvhcg                 1/1     Running       0          37s
  default              raycluster-external-redis-worker-small-group-jdsdd   0/1     Running       0          37s
  default              raycluster-external-redis-worker-small-group-r5s2s   1/1     Terminating   0          37s
  ```

* [Link](https://github.com/ray-project/kuberay/actions/runs/3184916517/jobs/5194247523#step:3:1752)
  ```bash
  INFO:kuberay_utils.utils:executing cmd: kubectl wait --for=condition=ready pod -l rayCluster=raycluster-compatibility-test --all --timeout=900s
  pod/raycluster-external-redis-head-x97nr condition met
  pod/raycluster-external-redis-worker-small-group-b66wg condition met
  INFO:kuberay_utils.utils:executing cmd: kubectl get pods -A
  NAMESPACE            NAME                                                 READY   STATUS        RESTARTS   AGE
  default              raycluster-external-redis-head-x97nr                 1/1     Running       0          39s
  default              raycluster-external-redis-worker-small-group-9mjgb   1/1     Running       0          39s
  default              raycluster-external-redis-worker-small-group-b66wg   1/1     Terminating   0          39s
  ```

### Reproduction script

```bash
RAY_IMAGE=rayproject/ray:2.0.0 python3 tests/compatibility-test.py RayFTTestCase.test_detached_actor 2>&1 | tee log
RAY_IMAGE=rayproject/ray:2.0.0 python3 tests/compatibility-test.py RayFTTestCase.test_kill_head 2>&1 | tee log
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### LINKED ISSUE #638: [Bug] Head pod is deleted rather than restarted when gcs_server on head pod is killed.
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ci

### What happened + What you expected to happen
* **rayproject/ray:nightly**
   * When the `gcs_server` process on the head pod is killed, the head pod will be deleted by KubeRay operator and then create a new one. ([Link1](https://github.com/ray-project/kuberay/blob/389ba0042728c3611c8596483ff442407fe08360/ray-operator/controllers/ray/raycluster_controller.go#L384), [Link2](https://github.com/ray-project/kuberay/blob/389ba0042728c3611c8596483ff442407fe08360/ray-operator/controllers/ray/raycluster_controller.go#L155))
* **rayproject/ray:2.0.0**
  * When the `gcs_server` process on the head pod is killed, the head pod will be restarted based on the pod's `restartPolicy`.

Both **restartPolicy** and **KubeRay** couple together. We need to have a further discussion about them.

### Reproduction script
This cannot be reproduced every time.
```bash
RAY_IMAGE=rayproject/ray:nightly python3 tests/compatibility-test.py RayFTTestCase.test_detached_actor 2>&1 | tee log
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### LINKED ISSUE #691: [Bug] Compatibility tests of FT features are (still) flakey
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Example:
https://github.com/ray-project/kuberay/actions/runs/3397833204/jobs/5650377940

### Reproduction script

N/A

### Anything else

Would be great to increase the total pass rate.
There aren't that many tests yet.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### LINKED ISSUE #692: Improve test quality by either improving or removing unreliable test
image

This actually looks really bad.  We don't even know it's flaky tests or test failures. 
1. Could maintainers make sure tests pass before merging the PR? 
2. Could maintainers rerun the test for post-submit commits?
3. is there a way to open rerun permission for PR author?

### LINKED ISSUE #990: [Feature] Another possible way to detect readiness failures in fault tolerance after release 0.5.0
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In the current implementation of fault tolerance, the kuberay operator watches the events to detect readiness probe failures. If detected, the pod is marked as unhealthy and will be deleted, and start a new one in later Reconciliation.

As @kevin85421 suggests https://github.com/ray-project/kuberay/issues/601#issuecomment-1458657817, watching readiness probe fail event may have downside:
> we finally need to stop watching events because operator operations should be idempotent and stateless. However, events are time-sensitive and deleting Pods based on events are not idempotent.  

A potential solution to the problem is to examine the ContainerStatus.Ready property to determine if a readiness probe has failed (refer to https://pkg.go.dev/k8s.io/api/core/v1#ContainerStatus for more information). 
```golang
// ContainerStatus contains details for the current status of this container.
type ContainerStatus struct {
	...
	// Specifies whether the container has passed its readiness probe.
	Ready bool `json:"ready" protobuf:"varint,4,opt,name=ready"`
        ...
	
}
```
And kuberay operator can watch the `ContainerStatus.Ready` (not sure watch `status` of an object is in this case is a good approach or not). Alternatively, Kuberay operator can handle readiness probe failures during the reconciliations that are triggered by other object changes.

### Use case

_No response_

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### LINKED ISSUE #1144: [Feature] How should we handle PodFailed Pods?
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

https://github.com/ray-project/kuberay/pull/1139#discussion_r1217179119

### Use case

_No response_

### Related issues

#1139 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

This PR addresses the following questions:

### 1. KubeRay is aggressive in deleting running Pods

Without this PR, the RayFTTestCase test is somewhat flaky. When GCS fault tolerance is enabled, KubeRay will inject both liveness and readiness probes into both the head and worker Pods. However, KubeRay will delete the Pod immediately if it receives an unhealthy event from the probes no matter the value of [failureThreshold](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/). Hence, it is very easy to trigger the deletion of running Pods, which is not a good idea from any perspective. In CI, the [initialDelaySeconds](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) of the probes is 30 seconds, but the GCS server may take more than 30 seconds to be ready. Hence, sometimes the probe will create an unhealthy event if the GCS server isn't ready in time. KubeRay will then delete this head Pod and create a new one in the next reconcile loop.

* [Example CI failure](https://github.com/ray-project/kuberay/actions/runs/5817013338/job/15771110726)
    Screen Shot 2023-08-18 at 2 14 17 PM

### 2. KubeRay listens to "all unhealthy events" in the Kubernetes cluster.

Without this PR, KubeRay listens to "all unhealthy events" in the Kubernetes cluster, regardless of whether they are related to KubeRay or not. This may cause OOM if there are a lot of unhealthy events in the Kubernetes cluster, and see https://github.com/ray-project/kuberay/issues/601#issuecomment-1486149187 for more details.

### 3. Undefined lifecycles of "Failed" and "Succeeded" Pods

KubeRay does not define the lifecycle of Pods in terminated states (i.e., ["Failed" or "Succeeded"](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-phase)). To be more specific, for the head Pod, KubeRay will neither delete nor create a new one when it fails. For the worker Pod, KubeRay will not delete the failed one but will create a new worker Pod.

* [Example 1](https://gist.github.com/kevin85421/71c75503f3fe72b6a9eea185873d6902): `restartPolicy: Never`, no Ray Autoscaler, delete the `ray start` process in the head Pod
   * The head Pod's status will change to "Failed" because the container's primary process is killed, and the failed Pod will remain there indefinitely. Subsequently, the worker Pod will also fail because it cannot connect to the GCS beyond a certain threshold.

* [Example 2](https://gist.github.com/kevin85421/71c75503f3fe72b6a9eea185873d6902): Same gist as example 1. In this example, we delete the `ray start` process in the worker Pod. The failed worker Pod will not be deleted, and a new worker Pod will be created.

* [Example 3](https://gist.github.com/kevin85421/e544a0c2c016278afc97774a8fa6d641): `restartPolicy: Never`, add `command: ["exit 1"]` to the worker's spec.
   * The worker Pod will fail automatically. The KubeRay operator will then create a new worker Pod, which will also fail, leading to the creation of another worker Pod, and so on. The loop will repeat forever and eat all resources in the Kubernetes cluster.

### Behavior of this PR

* If a Pod is able to restart, KubeRay will not delete it. On the other hand, KubeRay only deletes Pods which are in terminated states (i.e., "Failed" or "Succeeded") and not able to restart (i.e., `restartPolicy` is not `Always`). 
* KubeRay will not try to delete any "Running" Pods at this moment.
* KubeRay does not listen to Kubernetes events anymore.

## Follow up

* Good default values for probes
* Consider the case with sidecar containers
* Delete Pods by the value of `restartCount`

## Related issue number

I closed most issues that were used to track the progress of the flakiness of GCS FT tests.

Closes #1144 
Closes #618
Closes #990
Closes #638
Closes #691
Closes #692

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

* I used the following script to run the fault tolerance test 50 times on my devbox. It passed 50 times and failed 0 times.
  ```sh
  #!/bin/bash
  for iter in {1..50}
  do
      RAY_IMAGE=rayproject/ray:2.5.0 OPERATOR_IMAGE=controller:latest python3 tests/compatibility-test.py RayFTTestCase 2>&1 | tee logs/log_${iter} 
  done
  ```
* Verify: `for i in {1..50}; do tail -n 1 log_${i}; done | grep OK | wc -l` => 50

### CODE REVIEW

File: ray-operator/controllers/ray/raycluster_controller_fake_test.go [hunk 1]
```diff
@@ -1725,3 +1560,199 @@ func TestCalculateStatus(t *testing.T) {
...
+
+	// TODO (kevin85421): The tests in this file are not independent. As a workaround,
+	// I added the assertion to prevent the test logic from being affected by other changes.
+	// However, we should refactor the tests in the future.
+
+	// This test makes some assumptions about the testRayCluster object.
+	// (1) 1 workerGroup
+	// (2) The goal state of the workerGroup is 3 replicas.
+	// (3) Set the `WorkersToDelete` field to an empty slice.
+	// (4) Disable autoscaling.
```
Comment (architkulkarni) [inline ray-operator/controllers/ray/raycluster_controller_fake_test.go:1575]: Another basic question, it seems like even though autoscaling is disabled, we're scaling nodes up and down to meet the goal state.  So what does "autoscaling" do? (Is it the part that sets the goal state based on Ray's resource demands?)

File: tests/compatibility-test.py [hunk 2]
```diff
@@ -90,26 +90,6 @@ def setUpClass(cls):
         operator_manager.prepare_operator()
         utils.create_ray_cluster(RayFTTestCase.cluster_template, ray_version, ray_image)
 
-    @unittest.skip("Skip test_kill_head due to its flakiness.")
-    def test_kill_head(self):
```
Comment (architkulkarni) [inline tests/compatibility-test.py:94]: Why was this test flaky (and why will the new test added here https://github.com/ray-project/kuberay/pull/1341/files#diff-db7eeddbec6895cf05cb70312b97d42f54bdd61ac34ee18d3f74d02ab349b5bfR190 not be flaky? It looks similar)

File: tests/kuberay_utils/utils.py [hunk 3]
```diff
@@ -123,71 +122,77 @@ def wait_for_condition(
...
-        # the buggy behaviors of Ray HA. To elaborate, when GCS server is killed, the head pod should restart,
-        # but worker pods should not. However, currently, worker pods will also restart.
-        # See https://github.com/ray-project/kuberay/issues/634 for more details.
-        for pod in all_pods.items:
-            if pod.status.phase != 'Running':
-                logger.info(f'Pod {pod.metadata.name} is not Running.')
+        elif mode == CONST.KILL_HEAD_POD:
+            if new_head_pod_name == old_head_pod_name:
+                logger.info("The old head Pod %s is not killed.", old_head_pod_name)
+                return False
```
Comment (architkulkarni) [inline tests/kuberay_utils/utils.py:176]: Nit: do we need to include an `else` block and raise an error for unexpected mode?

**Review by architkulkarni — APPROVED** [review]
Overall looks good, no major concerns.

- In this PR the logic is to raise an error on the first reconciliation, and only bring up the new head pod on the second reconciliation.  Why not do it in the same reconciliation?

- Perhaps we should leave https://github.com/ray-project/kuberay/issues/709 open, since other tests may be flaky or may become flaky in the future.

- This PR removes the part about the RayCluster controller watching the readiness probe.  Can you please remind me which other parts of KubeRay currently use the readiness and liveness probes? Is it just for simplicity or is there some other reason?

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 4]
```diff
@@ -416,34 +335,50 @@ func (r *RayClusterReconciler) reconcilePods(ctx context.Context, instance *rayv
...
+				// However, I couldn't find any well-defined behavior in the Kubernetes documentation, so I can't guarantee that the status transition
+				// from `Running` to `Failed / Succeeded` and back to `Running` won't occur when we kill the main process (i.e., `ray start` in KubeRay)
+				// in the head Pod. Therefore, I've added this check as a safeguard.
+				message := fmt.Sprintf(
+					"The status of the head Pod %s is %s. However, KubeRay will not delete the Pod because its restartPolicy is set to 'Always' "+
+						"and it should be able to restart automatically.", headPod.Name, headPod.Status.Phase)
+				r.Log.Info(message)
+				return fmt.Errorf(message)
+			}
+			message := fmt.Sprintf("The status of the head Pod %s is %s. KubeRay will delete the Pod and recreate the head Pod in the next reconciliation.", headPod.Name, headPod.Status.Phase)
```
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go]: The status "SUCCEEDED" for a pod indicates that all of its containers have terminated with an exit code of 0. Many applications exit with a code of 0 because they possess signal handlers that gracefully shut down the applications. However, from a deployment perspective (e.g., in Kubernetes), this might still be considered a failure.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.17.10
    ports:
    - containerPort: 80
  restartPolicy: Never
```

For example, create an Nginx Pod with `restartPolicy: Never`, and then kill the process PID=1 in the Pod. The Pod status will be "SUCCEEDED".

Screen Shot 2023-08-21 at 10 56 17 AM

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 5]
```diff
@@ -416,34 +335,50 @@ func (r *RayClusterReconciler) reconcilePods(ctx context.Context, instance *rayv
...
 			if err := r.Delete(ctx, &headPod); err != nil {
 				return err
 			}
-		} else {
-			return fmt.Errorf("head pod %s is not running nor pending", headPod.Name)
+			r.Recorder.Eventf(instance, corev1.EventTypeNormal, "Deleted", "Deleted head Pod %s; status: %s", headPod.Name, headPod.Status.Phase)
+			return fmt.Errorf(message)
 		}
-	}
-	if len(headPods.Items) == 0 || headPods.Items == nil {
```
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:432]: The zero value of slice in Golang is `nil` (https://go.dev/tour/moretypes/12), and you can try this example:

```go
package main

import "fmt"

func main() {
	var s []int
	fmt.Println(s, len(s), cap(s))
	if s == nil {
		fmt.Println("nil!")
	}
	fmt.Println(len(s))
}
```

The output will be:

```
[] 0 0
nil!
0
```

File: ray-operator/controllers/ray/raycluster_controller_fake_test.go [hunk 6]
```diff
@@ -922,15 +769,6 @@ func TestReconcile_PodCrash_Diff0_WorkersToDelete_OK(t *testing.T) {
...
 
-	// Simulate 2 Pod fails. Because the workersToDelete also contains pod3 and pod4, the controller will
-	// delete these two Pods. After the deletion, the number of worker Pods should be 3.
-	podList.Items[3].Status.Phase = corev1.PodFailed
-	podList.Items[4].Status.Phase = corev1.PodFailed
-	err = fakeClient.Update(ctx, &podList.Items[3])
-	assert.Nil(t, err, "Fail to get update pod status")
-	err = fakeClient.Update(ctx, &podList.Items[4])
-	assert.Nil(t, err, "Fail to get update pod status")
-
```
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller_fake_test.go:933]: I removed this because the test is for the Autoscaler (`WorkersToDelete`). Without this PR, Pod3 and Pod4, which have the status "Failed," would be deleted by `WorkersToDelete`. However, with this PR, they will be removed, but not by `WorkersToDelete`. Maybe I need to remove "PodCrash" from the test name.

File: tests/kuberay_utils/utils.py (hunk 3 above)
Comment (kevin85421) [reply tests/kuberay_utils/utils.py:176]: Updated https://github.com/ray-project/kuberay/pull/1341/commits/ead7ca3764a8aebaafe336e4ae6ecf991e23ac61

File: tests/compatibility-test.py (hunk 2 above)
Comment (kevin85421) [reply tests/compatibility-test.py:94]: The test is very flaky without this PR. It was flaky because: 

(1) By default, Worker Pods might die if they cannot connect to GCS beyond a specific threshold, which is set to 60 seconds. Typically, the new head Pod cannot be ready in 60 seconds. #1036 fixes this problem.

(2) With GCS enabled, the head Pod sometimes cannot be ready in 30 seconds, and the readiness probe will start its first check in 30 seconds, so an unhealthy event will be created. Then, KubeRay will delete the new head Pod immediately.

> It looks similar

Yes, they are similar.

File: ray-operator/controllers/ray/raycluster_controller_fake_test.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller_fake_test.go:1575]: This test simulates disabling Autoscaler by making `WorkersToDelete` empty, so we can make sure the Pods are deleted by the terminated state checks rather than `WorkersToDelete`.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go]: Oh yeah, it makes sense to me, I was more worrying about the user who's less experienced. They might see the error message and get confused without this context

File: ray-operator/controllers/ray/raycluster_controller_fake_test.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller_fake_test.go:933]: Ah makes sense

**Comment by kevin85421** [comment]
> * In this PR the logic is to raise an error on the first reconciliation, and only bring up the new head pod on the second reconciliation.  Why not do it in the same reconciliation?  Is it just for simplicity or is there some other reason?

In my view, if a Pod keeps failing due to application logic, we should delay the recreation process so that other RayClusters' Pods can be scheduled on the k8s node. Otherwise, if we recreate it immediately, other Pods may be hard to get the resources.

> * Perhaps we should leave [[Feature] [CI] Track flakey KubeRay tests #709](https://github.com/ray-project/kuberay/issues/709) open, since other tests may be flaky or may become flaky in the future.

Done.

> * This PR removes the part about the RayCluster controller watching the readiness probe.  Can you please remind me which other parts of KubeRay currently use the readiness and liveness probes?

When GCS fault tolerance is enabled, KubeRay will inject the probes into Pods automatically.

https://github.com/ray-project/kuberay/blob/8be0a21dd1f0f4ce7298b54f4191e98a7ca9a558/ray-operator/controllers/ray/common/pod.go#L376-L409

**Comment by architkulkarni** [comment]
> In my view, if a Pod keeps failing due to application logic, we should delay the recreation process so that other RayClusters' Pods can be scheduled on the k8s node. Otherwise, if we recreate it immediately, other Pods may be hard to get the resources.

I see, thanks!

> When GCS fault tolerance is enabled, KubeRay will inject the probes into Pods automatically.

Ah, I meant to ask who *reads* the probes.  Is it some other part of KubeRay, or is it the user's application code?
