### PR TITLE
[Bug][breaking change] Unauthorized 401 error on fetching Ray Custom Resources from K8s API server

### LINKED ISSUE #1123: [Bug] Unauthorized 401 error on fetching Ray Custom Resources from K8s API server
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Ray worker nodes frequently get a 401 unauthorized error while fetching Ray custom resources from K8s API server. This repeated error leads to a CrashLoopBackOff in Ray head node making the entire Ray cluster unstable. We observed that this issue often arises during a Ray cluster blue-green deployment.

`File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/autoscaler/_private/kuberay/autoscaling_config.py", line 89, in _fetch_ray_cr_from_k8s
    result.raise_for_status()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://kubernetes.default:443/apis/ray.io/v1alpha1/namespaces/ns-team-rayservice/rayclusters/rayservice-raycluster-7ktr7`

There should never be a 401 error. The instability of a Ray cluster becomes a concern as the cluster recycles itself frequently.

### Reproduction script

Use a named service account name in head and worker pods, say `serviceAccountName: my-sa`.
Make changes to the cluster config so that it triggers a Ray cluster blue-green deployment. Observe the 401 error in a Ray worker node.

### Anything else

This problem occurs frequently though not very consistently.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

In #1123, the autoscaler container fails to GET the RayCluster from the Kubernetes API Server and receives error code 401 after a zero-downtime upgrade. If you are interested in the root cause, you can read the "debug process" section.

We have two solutions for this issue:

* Solution 1: Still create a ServiceAccount for users if the specified `ServiceAccountName` does not exist. The only difference is that we do not set the ControllerReference for the ServiceAccount to avoid it being deleted by the Kubernetes garbage collector. (Step 5 in the section **"3. Root cause of this issue"**)
  * (+) More backward-compatible
  * (-) Users need to delete the ServiceAccount themselves, which may introduce "unknown unknowns" for users.

* Solution 2 (this PR): If users specify ServiceAccountName, they need to create the ServiceAccount by themselves.
  * (-) Break the backward compatibility for users who specify the `ServiceAccountName` without creating a ServiceAccount manually.
  * (+) It can avoid "unknown unknowns" and makes it easier to identify and fix any issues. Although it breaks backward compatibility, it provides clarity and transparency in troubleshooting.
 

### 1. Understand ServiceAccount

In the head Pod, we can get three files, `ca.crt`, `namespace`, `token`, related to the ServiceAccount. You can check this [article](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-bound-service-account-tokens) for the descriptions about these 3 files.

```sh
ls /var/run/secrets/kubernetes.io/serviceaccount/
# example output: ca.crt  namespace  token
```

#### [Experiment for `ca.crt` and `token`]:

You can execute the following commands in the head Pod of an autoscaling RayCluster. The ServiceAccount should have sufficient permissions to perform a `GET` operation on the RayCluster.

```sh
# Typically, the Kubernetes APIServer will be in the default namespace, so you can use 
export APISERVER=https://kubernetes.default:443
export TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
curl -X GET $APISERVER/apis/ray.io/v1alpha1/namespaces/$RAYCLUSTER_NAMESPACE/rayclusters/$RAYCLUSTER_CR_NAME --header "Authorization: Bearer $TOKEN" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```

* [Case 1] Only use `ca.crt`: Use the anonymous ServiceAccount "system:anonymous" which does not have the permission to GET RayCluster => 403 Forbidden
* [Case 2] Only use `token`: Use the ServiceAccount that associated with this Pod which has the permission to GET RayCluster => Succeed
* [Case 3] Use `ca.crt` and `token` at the same time => Succeed (same as Case 2)

The result is same as the result in this [article](https://itnext.io/k8s-tips-accessing-the-api-server-from-a-pod-f6f72bc847de). I am not sure the purpose of ca.crt. It may only be used when some Kubernetes API Server configurations are set.

### 2. 401 Unauthorized vs 403 Forbidden

* **401 Unauthorized definition**:
  * https://kubernetes.io/docs/reference/access-authn-authz/authentication/#anonymous-requests (Kubernetes) => “For example, on a server with token authentication configured, and anonymous access enabled, a request providing an invalid bearer token would receive a 401 Unauthorized error.” => Focus on this.
  * https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html (EKS) => “Your Amazon EKS version 1.21 or later cluster’s Kubernetes API server rejects requests with tokens older than 90 days.” => This seems to be impossible in our case.

Based on this [Kubernetes link](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#anonymous-requests),

* When we did not configure `token` and Kubernetes API Server enables anonymous access (it is enabled by default after Kubernetes 1.6+, and you can check whether it is disabled or not by this [link](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#anonymous-requests).) => It will use the anonymous ServiceAccount `"system:anonymous"`. If the ServiceAccount does not have enough permissions to perform the operation. The error code will be `403 Forbidden`.

* If we specify an invalid token in the request, we will get a 401 Unauthorized error. For example, we can get 401 by changing 
  ```sh
  # Typically, the Kubernetes APIServer will be in the default namespace, so you can use 
  export APISERVER=https://kubernetes.default:443
  export TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
  curl -X GET $APISERVER/apis/ray.io/v1alpha1/namespaces/$RAYCLUSTER_NAMESPACE/rayclusters/$RAYCLUSTER_CR_NAME --header "Authorization: Bearer $TOKEN" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  ```
  
  to 

  ```sh
  # Typically, the Kubernetes APIServer will be in the default namespace, so you can use 
  export APISERVER=https://kubernetes.default:443
  export TOKEN=WRONG_TOKEN
  curl -X GET $APISERVER/apis/ray.io/v1alpha1/namespaces/$RAYCLUSTER_NAMESPACE/rayclusters/$RAYCLUSTER_CR_NAME --header "Authorization: Bearer $TOKEN" --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  ```

#### TL;DR
* `401 Unauthorized`: `token` is invalid.
* `403 Forbidden`: Kubernetes API Server can associate the ServiceAccount, but the account does not enough permission to perform the operation.

### 3. Root cause of this issue

Because we received a 401 error instead of a 403 error, our focus should be on why the `token` is invalid rather than whether the ServiceAccount has sufficient permissions or not.

* Step 1: When users specify `ServiceAccountName` (e.g., `my-sa`) for the head Pod without manually creating the ServiceAccount, KubeRay will create a ServiceAccount for them.
* Step 2: Users trigger a new RayCluster preparation by updating the RayService CR.
* Step 3: The new RayCluster will use the same `my-sa` ServiceAccount as the old RayCluster.
* Step 4: When the Serve deployments on the new RayCluster are ready and healthy, traffic will be redirected to the new RayCluster. Then, the old RayCluster will be deleted.
* Step 5: Because the old RayCluster and the `my-sa` ServiceAccount have an owner/dependent relationship, the `my-sa` ServiceAccount will be deleted when the old RayCluster is deleted.
* Step 6: Although KubeRay will create a new ServiceAccount called `my-sa` (referred to as new `my-sa` below), the new RayCluster has already mounted the old `my-sa` ServiceAccount in Step 3.
* Step 7: The autoscaler of the new RayCluster will attempt to use the token of the old my-sa ServiceAccount to make a GET request to the Kubernetes API Server for the RayCluster information. However, since the ServiceAccount has been deleted, the token is no longer valid. This is why we receive a `401 Unauthorized` error.

## Related issue number

Closes #1123 

## Checks

- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

```sh
# Step 0: Create a Kind cluster
kind create cluster --image=kindest/node:v1.23.0

# Step 1: Build docker image for this PR (path: ray-operator/) and load into the Kind cluster
make docker-image
kind load docker-image controller:latest

# Step 2: Install a KubeRay operator
# path: helm-chart/kuberay-operator
helm install kuberay-operator . --set image.repository=controller,image.tag=latest

# Step 3: Create a ServiceAccount `my-sa` with the following YAML file
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-sa
  namespace: default

# Step 3: Create a RayService
# Use this gist: https://gist.github.com/kevin85421/b2f2af680aff2562c540cef1f138b4b9
kubectl apply -f ray-service.autoscaler-with-ServiceAccountName.yaml

# Step 4: Edit `spec.rayClusterConfig.rayVersion` from 2.4.0 to 2.100.0.
kubectl edit rayservices.ray.io rayservice-sample

# Step 5: Check the log of the new RayCluster to ensure that no 401 error is present, as the expected behavior is to have no occurrences of the 401 error.
```

### CODE REVIEW

**Comment by kevin85421** [comment]
cc @anshulomar @msumitjain would you mind taking a look at this PR? You can check the section "3. Root cause of this issue" in the PR description for the root cause. Thanks!

**Comment by kevin85421** [comment]
cc @davidxia would you mind providing some feedback on this PR? Thank you!

**Comment by kevin85421** [comment]
cc @Yicheng-Lu-llll

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -1026,6 +1026,17 @@ func (r *RayClusterReconciler) reconcileAutoscalerServiceAccount(instance *rayio
 			return err
 		}
 
+		// If users specify ServiceAccountName for the head Pod, they need to create a ServiceAccount themselves.
+		// However, if KubeRay creates a ServiceAccount for users, the autoscaler may encounter permission issues during
+		// zero-downtime rolling updates when RayService is performed. See https://github.com/ray-project/kuberay/issues/1123
+		// for more details.
+		if instance.Spec.HeadGroupSpec.Template.Spec.ServiceAccountName == namespacedName.Name {
+			r.Log.Error(err, fmt.Sprintf(
+				"If users specify ServiceAccountName for the head Pod, they need to create a ServiceAccount themselves."+
```
Comment (Yicheng-Lu-llll) [inline ray-operator/controllers/ray/raycluster_controller.go:1035]: Maybe we can also remind the user to ensure at least the following permissions are granted: ["get", "list", "watch", "patch"](https://github.com/ray-project/kuberay/blob/fe29409358e911c2eecb6da6b0a530479f911567/ray-operator/controllers/ray/common/rbac.go#L29) on the pods. These permissions are necessary for the autoscaler to adjust the number of replicas based on the workload.

**Comment by Yicheng-Lu-llll** [comment]
LGTM! Thank you for the detailed explanation, I learned a lot!

leave notes for reference:

1. kuberay only automatically creates `ServiceAccount` if the user does not provide one and the autoscaler is enabled. This is necessary because the autoscaler needs permission to ["get", "list", "watch", "patch"](https://github.com/ray-project/kuberay/blob/fe29409358e911c2eecb6da6b0a530479f911567/ray-operator/controllers/ray/common/rbac.go#L29) the pods to adjust the number of replicas based on the current workload.

2. https://github.com/ray-project/kuberay/issues/1123 says it gets a 401 error for worker pods. This is because they set the same `ServiceAccountName` for the head and workers. Kuberay doesn't modify the worker's ServiceAccount.

**Comment by davidxia** [comment]
> cc @davidxia would you mind providing some feedback on this PR? Thank you!

I can try to make some time. Do you have a deadline?

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 2]
```diff
@@ -1026,6 +1026,17 @@ func (r *RayClusterReconciler) reconcileAutoscalerServiceAccount(instance *rayio
 			return err
 		}
 
+		// If users specify ServiceAccountName for the head Pod, they need to create a ServiceAccount themselves.
+		// However, if KubeRay creates a ServiceAccount for users, the autoscaler may encounter permission issues during
+		// zero-downtime rolling updates when RayService is performed. See https://github.com/ray-project/kuberay/issues/1123
+		// for more details.
+		if instance.Spec.HeadGroupSpec.Template.Spec.ServiceAccountName == namespacedName.Name {
```
[the remark this answers is not in the document]
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:1033]: I agree that using `instance.Spec.HeadGroupSpec.Template.Spec.ServiceAccountName != ""` is more straightforward for the comment "if users have specified a ServiceAccountName for the head Pod".

However, if the logic in `GetHeadGroupServiceAccountName` changes, it may be difficult for developers to be aware that they also need to update the code logic here when using `... != ""`. That's why I decide to use `... != namespacedName.Name`.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go:1035]: The permissions are defined by Role which is created by KubeRay automatically. Do we still need to add the comment?

**Comment by kevin85421** [comment]
@Yicheng-Lu-llll 

> https://github.com/ray-project/kuberay/issues/1123 says it gets a 401 error for worker pods.

I am not sure why the 401 error occurs on the worker nodes. I guess this is a typo based on the following reasons:

1. The error messages in #1123 are from Autoscaler, and the autoscaler is a sidecar container of the head Pod.

2. In my knowledge, only Autoscaler will communicate with the Kubernetes API Server (i.e. `kubernetes.default` => A special  ClusterIP Service `kubernetes` in the `default` namespace.)

> This is because they set the same ServiceAccountName for the head and workers. Kuberay does nothing to workers' ServiceAccount.

This explanation is not entirely accurate. The root cause of the issue is that the new RayCluster's head Pod is using the ServiceAccount from the old RayCluster's head Pod. When the old RayCluster is deleted, its ServiceAccount is also deleted because they have an owner/dependent relationship. As a result, the new RayCluster ends up using the token of the deleted ServiceAccount to communicate with the Kubernetes API Server, leading to the 401 error.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 1 above)
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/raycluster_controller.go:1035]: oh! I see, kuberay will automatically create `role` and `rolebinding` for the user created ServiceAccountName when `reconcileAutoscalerRole` and `reconcileAutoscalerRoleBinding`

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Yicheng-Lu-llll) [reply ray-operator/controllers/ray/raycluster_controller.go:1033]: I see, thank you!

**Comment by kevin85421** [comment]
> I can try to make some time. Do you have a deadline?

Thanks! No rush. I can also ping some folks to take a look too. This issue is blocking a user, so it would be ideal to have it merged by next Monday.

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 3]
```diff
@@ -1026,6 +1026,17 @@ func (r *RayClusterReconciler) reconcileAutoscalerServiceAccount(instance *rayio
...
+			r.Log.Error(err, fmt.Sprintf(
+				"If users specify ServiceAccountName for the head Pod, they need to create a ServiceAccount themselves."+
+					"However, ServiceAccount %s is not found. Please create one.", namespacedName.Name), "ServiceAccount", namespacedName)
```
Comment (anshulomar) [inline ray-operator/controllers/ray/raycluster_controller.go:1036]: @kevin85421 just curious, where are we checking whether the serviceaccount exists?

**Review by anshulomar — COMMENTED** [review]
@kevin85421 Thanks for taking this up! Your explanation is very thorough and meticulous.

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 3 above)
Comment (architkulkarni) [reply ray-operator/controllers/ray/raycluster_controller.go:1036]: Nit, we should make the call-to-action ("Please create one") in the error message as foolproof as possible so that users with varying levels of expertise can unblock themselves.  Is there a link to a doc we can include, or a very brief example of how to create a service account?

**Review by architkulkarni — APPROVED** [review]
Looks good to me!

File: ray-operator/controllers/ray/raycluster_controller.go (hunk 3 above)
Comment (kevin85421) [reply ray-operator/controllers/ray/raycluster_controller.go]: Updated https://github.com/ray-project/kuberay/pull/1128/commits/5a9e3e28ac3f9123a1a52a731057216f79e77c6a.

**Review by Yicheng-Lu-llll — APPROVED** [review]

**Comment by blublinsky** [comment]
@kevin85421 as @Yicheng-Lu-llll explains, what is happening is that when a new cluster is being created, it will check whether the service account exists, which it does. So service account will not be created and the existing one is going to be used. Now when the old cluster is being deleted, it will delete this service account which will lead to a 401 error. Note that exactly the same error will occur if Role/RoleBinding a deleted by the initial cluster.
In my opinion, solution 1 (removing ControllerReference) is a much better option. Additionally, controller reference in this case has to be removed from Role and RoleBinding. This will guarantee no 401 error.
The downside of this approach, as you are correctly specifying is that ServiceAccount, Role, and RoleBinding are not garbage collected, which is not that harmful, especially considering that practically the same ServiceAccount, Role and RoleBinding are going to be reused over and over.
The huge advantage of this approach is that an operator is self-contained - it creates all of the resources, that it potentially needs. In your solution, a user will need to create a lot of things - Service Account, Role, and RoleBinding upfront, which he will either forget or even worse will do it incorrectly.
Just my 2 cents on this

**Comment by blublinsky** [comment]
@kevin85421 there is also additional inconsistency in the current implementation. If ServiceAccount is specified in the head node, depending on whether autoscaling is defined, the ServiceAccount will be created (autoscaler is True) or not (autoscaler is False). So my suggestion is to make sure that ServiceAccount, that can be defined in either for the head node or some of the worker groups exists

**Comment by kevin85421** [comment]
Hi @blublinsky, thank you for sharing your thoughts!

> Note that exactly the same error will occur if Role and RoleBinding are deleted by the initial cluster.

It is true, but the names of the `Role` and `RoleBinding` are the same as the RayCluster custom resource (CR) name. Hence,  when RayService triggers a rolling upgrade, the following will happen:

[Example]

Assume: 
(1) Old RayCluster: `rayservice-sample-raycluster-4p798` 
(2) New RayCluster: `rayservice-sample-raycluster-ab123`
(3) serviceAccountName: `my-sa`

```sh
# T=0: (Only old RayCluster):
ServiceAccount1 (`my-sa`) <-- RoleBinding1 (`rayservice-sample-raycluster-4p798`) --> Role1 (`rayservice-sample-raycluster-4p798`)

# T=1: (Old RayCluster + new RayCluster)
                
`my-sa` <-- RoleBinding1 --> Role1
     ^
     |
RoleBinding2 (`rayservice-sample-raycluster-ab123`)
     |
     v
   Role2 (`rayservice-sample-raycluster-ab123`)

# T=2: The old RayCluster will be deleted after Serve deployments on the new RayCluster are ready and healthy.
# That is, RoleBinding1 and Role1 will be deleted.

`my-sa`
     ^
     |
RoleBinding2 (`rayservice-sample-raycluster-ab123`)
     |
     v
   Role2 (`rayservice-sample-raycluster-ab123`)
```

The ServiceAccount will still have enough permissions after `T=2`. I also conducted an experiment to test whether the creation or deletion of a Role/RoleBinding is possible when the associated Pods are running. To conclude the experiment, it was observed that unlike ServiceAccount, Role and RoleBinding can be updated dynamically. Hence, in my opinion, the garbage collection for Role and RoleBinding is fine.


> The downside of this approach, as you are correctly specifying is that ServiceAccount, Role, and RoleBinding are not garbage collected, which is not that harmful, especially considering that practically the same ServiceAccount, Role, and RoleBinding are going to be reused over and over.

[1] It would be beneficial if it could be reused by other custom resources managed by KubeRay. However, I am concerned about the possibility of other applications also attaching to this ServiceAccount. Typically, it is highly likely to happen because users often use simple names, such as `my-sa`, for their ServiceAccounts.

> [2] The huge advantage of this approach is that an operator is self-contained.

Agree. 


The bugs caused by [1] will be very difficult for maintainers to debug. Unlike an in-house product, KubeRay maintainers do not have access to users' Kubernetes clusters. In the case of an in-house product, I completely agree with your point because I have access to all Kubernetes logs, allowing me to focus more on user experience (e.g. self-contained [2]). However, for open-source projects, it is better to surface the issue as early as possible. It is not that painful for users to create the ServiceAccount by themselves.

**Comment by kevin85421** [comment]
Hi @blublinsky, I will merge this PR tonight because some users are blocked by it. If necessary, we can open another issue to discuss it further. Here is a possible solution for achieving a balance between user experience and "unknown unknowns":

(1) By default, we won't create a ServiceAccount for users if they specify a serviceAccountName.
(2) We can open a new PR with a feature gate (disabled by default) to create RBAC without controller references for users.

Is it OK for you?

**Comment by Yicheng-Lu-llll** [comment]
nit, We can have this breaking change in the document:

https://github.com/ray-project/kuberay/blob/4b6f1dfb00cc64a572d9861936cb7671aeb9479e/docs/guidance/autoscaler.md?plain=1#L78

**Comment by kevin85421** [comment]
> nit, We can have this breaking change in the document:
> 
> https://github.com/ray-project/kuberay/blob/4b6f1dfb00cc64a572d9861936cb7671aeb9479e/docs/guidance/autoscaler.md?plain=1#L78

Added in #1071.

**Comment by kevin85421** [comment]
Hi @blublinsky, I will merge this PR. If necessary, we can discuss the points mentioned in https://github.com/ray-project/kuberay/pull/1128#issuecomment-1577764756 in a separate issue.
