### PR TITLE
[Bug] Sidecar mode shouldn't restart head pod when head pod is deleted

### LINKED ISSUE #4130: [Bug] Sidecar mode shouldn't restart head pod when head pod is deleted
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

When using sidecar mode, the head pod should not be recreated after it is deleted. The RayJob should be marked as Failed.

### Reproduction script

```shell
go test -v -count=1 ./test/e2erayjob -run 'TestRayJobSidecarMode/RayJob_fails_when_head_Pod_is_deleted_when_job_is_running'
```
We hit a timeout while waiting for JobDeploymentStatus to become Failed, because the head pod keeps restarting indefinitely and never reaches a failed state.
```
❯ go test -v -count=1 ./test/e2erayjob -run 'TestRayJobSidecarMode/RayJob_fails_when_head_Pod_is_deleted_when_job_is_running'                                                         (base) 
=== RUN   TestRayJobSidecarMode
    rayjob_sidecar_mode_test.go:28: [2025-10-16T12:25:38Z] Created ConfigMap test-ns-9hssp/jobs successfully
=== RUN   TestRayJobSidecarMode/RayJob_fails_when_head_Pod_is_deleted_when_job_is_running
=== NAME  TestRayJobSidecarMode
    rayjob_sidecar_mode_test.go:169: [2025-10-16T12:25:38Z] Created RayJob test-ns-9hssp/delete-head-after-submit-sidecar-mode successfully
    rayjob_sidecar_mode_test.go:172: [2025-10-16T12:25:38Z] Waiting for RayJob test-ns-9hssp/delete-head-after-submit-sidecar-mode to be 'Running'
    rayjob_sidecar_mode_test.go:183: [2025-10-16T12:26:38Z] Deleting head Pod test-ns-9hssp/delete-head-after-submit-sidecar-mode-lmn8t-head-fwwlv for RayCluster delete-head-after-submit-sidecar-mode-lmn8t
    rayjob_sidecar_mode_test.go:189: 
        Timed out after 120.000s.
        Expected
            <v1.JobDeploymentStatus>: Running
        to equal
            <v1.JobDeploymentStatus>: Failed
=== NAME  TestRayJobSidecarMode/RayJob_fails_when_head_Pod_is_deleted_when_job_is_running
    testing.go:1679: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
=== NAME  TestRayJobSidecarMode
    test.go:114: [2025-10-16T12:28:38Z] Retrieving Pod Container test-ns-9hssp/delete-head-after-submit-sidecar-mode-lmn8t-head-4zv9d/ray-head logs
    test.go:102: [2025-10-16T12:28:38Z] Creating ephemeral output directory as KUBERAY_TEST_OUTPUT_DIR env variable is unset
    test.go:105: [2025-10-16T12:28:38Z] Output directory has been created at: /tmp/TestRayJobSidecarMode2305770799/001
    test.go:114: [2025-10-16T12:28:38Z] Retrieving Pod Container test-ns-9hssp/delete-head-after-submit-sidecar-mode-lmn8t-head-4zv9d/ray-job-submitter logs
    test.go:114: [2025-10-16T12:28:38Z] Retrieving Pod Container test-ns-9hssp/delete-head-after-submit-sidecar-mode-lmn8t-small--worker-8xmbn/ray-worker logs
--- FAIL: TestRayJobSidecarMode (180.52s)
    --- FAIL: TestRayJobSidecarMode/RayJob_fails_when_head_Pod_is_deleted_when_job_is_running (180.39s)
FAIL
FAIL    github.com/ray-project/kuberay/ray-operator/test/e2erayjob      180.554s
FAIL
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by 400Ping**
## Why are these changes needed?
When using sidecar mode, the head pod should not be recreated after it is deleted. The RayJob should be marked as Failed.

## Related issue number

Closes #4130 
## Checks

- [ ] I've made sure the tests are passing.
- Testing Strategy
  - [ ] Unit tests
  - [ ] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rueian** [comment]
@400Ping, the change should be made in the raycluster_controller. We need to make the raycluster_controller not recreate the head pod if the cluster belongs to a RayJob, so that we can avoid races where the raycluster_controller recreates the head before the rayjob_controller checks it.

**Comment by 400Ping** [comment]
> @400Ping, the change should be made in the raycluster_controller. We need to make the raycluster_controller not recreate the head pod if the cluster belongs to a RayJob, so that we can avoid races where the raycluster_controller recreates the head before the rayjob_controller checks it.

ok, thanks

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 1]
```diff
@@ -619,6 +619,14 @@ func (r *RayClusterReconciler) reconcilePods(ctx context.Context, instance *rayv
 			return errstd.New(reason)
 		}
 	} else if len(headPods.Items) == 0 {
+		originatedFrom := utils.GetCRDType(instance.Labels[utils.RayOriginatedFromCRDLabelKey])
+		if originatedFrom == utils.RayJobCRD {
+			logger.Info(
+				"reconcilePods: Found 0 head Pods for a RayJob-managed RayCluster; skipping head creation to let RayJob controller handle the failure",
```
Comment (rueian) [inline ray-operator/controllers/ray/raycluster_controller.go]: Won't this cause no head pod to be created at all? We still need to create the first head pod. I think you can check the RayClusterProvisioned condition to decide whether to create one or not.

**Review by Future-Outlier — COMMENTED** [review]
let's try to fix this, super important.

File: ray-operator/controllers/ray/raycluster_controller.go [hunk 2]
```diff
@@ -619,6 +619,14 @@ func (r *RayClusterReconciler) reconcilePods(ctx context.Context, instance *rayv
...
+				"rayCluster", instance.Name,
+			)
+			return nil
+		}
```
Comment (Future-Outlier) [inline ray-operator/controllers/ray/raycluster_controller.go:631]:
```suggestion
		originatedFrom := utils.GetCRDType(instance.Labels[utils.RayOriginatedFromCRDLabelKey])
		if originatedFrom == utils.RayJobCRD {
			if meta.IsStatusConditionTrue(instance.Status.Conditions, string(rayv1.RayClusterProvisioned)) {
				logger.Info(
					"reconcilePods: Found 0 head Pods for a RayJob-managed RayCluster; skipping head creation to let RayJob controller handle the failure",
					"rayCluster", instance.Name,
				)
				return nil
			}
		}
```

do you mind apply this change?

BTW, thanks @machichima for help!

File: ray-operator/controllers/ray/rayjob_controller.go [hunk 3]
```diff
@@ -276,6 +276,23 @@ func (r *RayJobReconciler) Reconcile(ctx context.Context, request ctrl.Request)
...
+			}
+			if headPod == nil {
+				rayJobInstance.Status.JobDeploymentStatus = rayv1.JobDeploymentStatusFailed
+				rayJobInstance.Status.JobStatus = rayv1.JobStatusFailed
+				rayJobInstance.Status.Reason = rayv1.AppFailed
+				rayJobInstance.Status.Message = "Submitter completed but Ray job not found in RayCluster."
+				break
+			}
+		}
+
```
Comment (Future-Outlier) [inline ray-operator/controllers/ray/rayjob_controller.go]:
```suggestion
```

I tested this in my local laptop, and find that we don't need this?
can you delete here?
or can you explain why we need this?

**Comment by 400Ping** [comment]
sorry, I am a bit busy taking midterm this week so I am a bit slow to respond

**Comment by Future-Outlier** [comment]
> sorry, I am a bit busy taking midterm this week so I am a bit slow to respond

good luck for your midterm exam, thank you!

**Review by Future-Outlier — APPROVED** [review]
I tested this in my local laptop, and @machichima did it too.

Image

Image



reproduce step
1. create a RayJob
```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: rayjob-sidecar-mode-flaky
spec:
  # In SidecarMode, the KubeRay operator injects a container into the Ray head Pod to submit the Ray job and tail logs.
  # This will avoid inter-Pod communication, which may cause network issues. For example, some users face WebSocket hangs.
  # For more details, see https://github.com/ray-project/kuberay/issues/3928#issuecomment-3187164736.
  submissionMode: "SidecarMode"
  entrypoint: python -c  "import time; time.sleep(60)"
  runtimeEnvYAML: |
    pip:
      - requests==2.26.0
      - pendulum==2.1.2
    env_vars:
      counter_name: "test_counter"

  rayClusterSpec:
    rayVersion: '2.46.0'
    headGroupSpec:
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-head
            image: rayproject/ray:2.46.0
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            resources:
              limits:
                cpu: "1"
              requests:
                cpu: "200m"
            volumeMounts:
            - mountPath: /home/ray/samples
              name: code-sample
          volumes:
          - name: code-sample
            configMap:
              name: ray-job-code-sample
              items:
              - key: sample_code.py
                path: sample_code.py
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 5
      groupName: small-group
      rayStartParams: {}
      template:
        spec:
          containers:
          - name: ray-worker
            image: rayproject/ray:2.46.0
            resources:
              limits:
                cpu: "1"
              requests:
                cpu: "200m"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ray-job-code-sample
data:
  sample_code.py: |
    import ray
    import os
    import requests

    ray.init()

    @ray.remote
    class Counter:
        def __init__(self):
            # Used to verify runtimeEnv
            self.name = os.getenv("counter_name")
            assert self.name == "test_counter"
            self.counter = 0

        def inc(self):
            self.counter += 1

        def get_counter(self):
            return "{} got {}".format(self.name, self.counter)

    counter = Counter.remote()

    for _ in range(5):
        ray.get(counter.inc.remote())
        print(ray.get(counter.get_counter.remote()))

    # Verify that the correct runtime env was used for the job.
    assert requests.__version__ == "2.26.0"
```

2. delete the head pod once the head container and submitter container are both running

3. check the rayjob CR's status (should be failure both)

4. you might wonder should we delete the worker pod? the answer is no, since we can't know if we use cluster selector from rayjob in raycluster.
but 1 thing we can do is we can use deletion policy to delete the whole raycluster if needed.

**Comment by Future-Outlier** [comment]
cc @rueian @andrewsykim for merge, thank you!

**Comment by rueian** [comment]
@400Ping, The RayJob_fails_when_head_Pod_is_deleted_when_job_is_running test is failing
