### PR TITLE
[Bug][kubectl-plugin] Wrong behavior for InteractiveMode RayJob with BackoffLimit set

### LINKED ISSUE #3525: [Bug][kubectl-plugin] Wrong behavior for InteractiveMode RayJob with BackoffLimit set
### Search before asking

- [x] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

The "deployment status" transitions from `Running` if `backoffLimit` is set to a value greater than 1 for RayJob with `InteractiveMode`. It should be `Waiting` or `Failed` and needs some discussion.

### Reproduction script

`rayjob.yaml`

```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: my-rayjob
  namespace: default
spec:
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - image: rayproject/ray:2.41.0
              name: ray-head
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
              resources:
                limits:
                  memory: 4Gi
                requests:
                  cpu: "2"
                  memory: 4Gi
    rayVersion: 2.41.0
    workerGroupSpecs:
      - groupName: default-group
        rayStartParams:
          metrics-export-port: "8080"
        replicas: 1
        template:
          spec:
            containers:
              - image: rayproject/ray:2.41.0
                name: ray-worker
                resources:
                  limits:
                    memory: 4Gi
                  requests:
                    cpu: "2"
                    memory: 4Gi
  submissionMode: InteractiveMode
  backoffLimit: 2
```

`kubectl ray job submit --working-dir . -f rayjob.yaml -- python task1.py` (note that there is no `task1.py` in the current working directory)

`kubectl get rayjob`

The "deployment status" transitions from `Initializing` to `Waiting` when the first RayCluster is created. Then it finds that `task1.py` does not exist and fails. When the second RayCluster is created, it goes back to `Initializing` again, but since `spec.JobId` is already set, it transitions to `Running` instead of `Waiting`.

### Anything else

We should discuss the behavior of `BackoffLimit` for `InteractiveMode`. We can either:

- Don't support it at all.
- Clear `spec.JobId` when the second RayCluster is created. And then wait for the user update `spec.JobId` again.
- Remember all inputs from user and then retry automatially. This might be problematic because we need to handle `workingDir` properly.

Update: After discussion, we decide to not support it at all.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by CheyuWu**
## Why are these changes needed?

Currently, when using `InteractiveMode` in a `RayJob` and setting `backoffLimit` to a value greater than 1, the job's deployment status incorrectly transitions to `Running`. According to [this discussion](https://github.com/ray-project/kuberay/issues/3525#issuecomment-2848333674), `InteractiveMode` should not be used with `backoffLimit`.

To enforce this constraint, a validation check is added during job submission.

## What does this PR do?

- Adds validation logic to prevent `backoffLimit` from being used with `InteractiveMode`.

### Code Change
In `func (options *SubmitJobOptions) Validate() error`:
Add the condition
```go
if submissionMode == rayv1.InteractiveMode && options.RayJob.Spec.BackoffLimit != nil {
  return fmt.Errorf("BackoffLimit cannot co-exist with InteractiveMode")
}
```

#### Manual Testing

`rayjob.yaml`
```yaml
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: my-rayjob
  namespace: default
spec:
  rayClusterSpec:
    headGroupSpec:
      rayStartParams:
        dashboard-host: 0.0.0.0
      template:
        spec:
          containers:
            - image: rayproject/ray:2.41.0
              name: ray-head
              ...
    rayVersion: 2.41.0
    workerGroupSpecs:
      - groupName: default-group
        ...
  submissionMode: InteractiveMode
  backoffLimit: 2
````

Run the following command:
```bash
$ kubectl ray job submit --working-dir . -f rayjob.yaml -- python task1.py
```
Given that `rayjob.yaml` contains a RayJob with both `InteractiveMode` and `BackoffLimit`, the output from console is:
```console
Error: BackoffLimit cannot co-exist with InteractiveMode
```

## Related issue number
Closes #3525 

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
  - [x] Unit tests
  - [x] Manual tests
  - [ ] This PR is not tested :(

### CODE REVIEW

File: kubectl-plugin/pkg/cmd/job/job_submit_test.go [hunk 1]
```diff
@@ -36,40 +36,50 @@ func TestRayJobSubmitValidate(t *testing.T) {
...
 
-	tests := []struct {
-		name        string
-		opts        *SubmitJobOptions
-		expectError string
-	}{
-		{
-			name: "Successful submit job validation with RayJob",
-			opts: &SubmitJobOptions{
+			opts := &SubmitJobOptions{
```
Comment (CheyuWu) [inline kubectl-plugin/pkg/cmd/job/job_submit_test.go:75]: I moved the create temp yaml step into the `t.Run`

File: kubectl-plugin/pkg/cmd/job/job_submit_test.go [hunk 2]
```diff
@@ -36,40 +36,50 @@ func TestRayJobSubmitValidate(t *testing.T) {
...
+			yamlContent: `apiVersion: ray.io/v1
+kind: RayJob
+metadata:
+  name: rayjob-sample
+spec:
+  submissionMode: 'InteractiveMode'
+  backoffLimit: 3`,
+			expectError: "BackoffLimit cannot co-exist with InteractiveMode",
+		},
+	}
```
Comment (CheyuWu) [inline kubectl-plugin/pkg/cmd/job/job_submit_test.go:64]: Add BackoffLimit co-exist with InteractiveMode testcase

**Comment by CheyuWu** [comment]
Hi @kevin85421, @MortalHappiness  PTAL

**Comment by kevin85421** [comment]
cc @davidxia for review. Thanks!

**Comment by MortalHappiness** [comment]
@CheyuWu You should also update `ray-operator/controllers/ray/rayjob_controller.go` to do validation in RayJob controller.

**Comment by CheyuWu** [comment]
> @CheyuWu You should also update `ray-operator/controllers/ray/rayjob_controller.go` to do validation in RayJob controller.

Sorry, I missed this

File: kubectl-plugin/pkg/cmd/job/job_submit.go [hunk 3]
```diff
@@ -226,6 +226,11 @@ func (options *SubmitJobOptions) Validate() error {
 		if submissionMode != rayv1.InteractiveMode {
 			return fmt.Errorf("Submission mode of the Ray Job must be set to 'InteractiveMode'")
 		}
+		// BackoffLimit cannot co-exist with InteractiveMode
+		// https://github.com/ray-project/kuberay/issues/3525
```
Comment (davidxia) [inline kubectl-plugin/pkg/cmd/job/job_submit.go:230]: Maybe instead of an issue link which will be closed when this PR is merged and requires a lot more reading to understand, it's better to summarize succinctly why the two aren't allowed together?

File: kubectl-plugin/pkg/cmd/job/job_submit.go [hunk 4]
```diff
@@ -226,6 +226,11 @@ func (options *SubmitJobOptions) Validate() error {
 		if submissionMode != rayv1.InteractiveMode {
 			return fmt.Errorf("Submission mode of the Ray Job must be set to 'InteractiveMode'")
 		}
+		// BackoffLimit cannot co-exist with InteractiveMode
```
Comment (davidxia) [inline kubectl-plugin/pkg/cmd/job/job_submit.go:229]: minor: this reads a little better, I think. Same for other instances below of co-exist.

```suggestion
		// BackoffLimit is incompatible with InteractiveMode
```

**Review by davidxia — COMMENTED** [review]
I don't have a ton of context, gave it a brief review.

**Review by kevin85421 — APPROVED** [review]
