### PR TITLE
Generate RayCluster Hash on KubeRay Version Change

### LINKED ISSUE #2315: [Bug] RayService Restarts After Upgrading KubeRay to v1.2.0-rc.0
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/kuberay/issues) and found no similar issues.

### KubeRay Component

ray-operator

### What happened + What you expected to happen

Upgrading the kuberay-operator version to the `v1.2.0-rc.0` release candidate from v1.1.0 causes a RayService to restart, reconciling the RayCluster and creating a new set of head and worker Pods. IIUC, expected behavior when installing a newer version of the Ray Operator is that running workloads should be unaffected. However, I'm observing behavior where the RayService restarts and the deployment is interrupted.

Relevant logs from the kuberay-operator after upgrading the image to `v1.2.0-rc.0`:
```
space":"default"},"reconcileID":"fc484444-80db-44d8-8652-38e4dff60878","activeClusterNumWorkerGroups":1,"goalNumWorkerGroups":1}
{"level":"info","ts":"2024-08-20T03:10:38.257Z","logger":"controllers.RayService","msg":"Active RayCluster config doesn't match goal config. RayService operator should prepare a new Ray cluster.\n* Active RayCluster config hash: D22UJ34PG57MTG9IDLDI0AAVJPLLE70D\n* Goal RayCluster config hash: OKN3DC1IOSSBST33DDOLIJR03TRSCB7A","RayService":{"name":"stable-diffusion-tpu","namespace":"default"},"reconcileID":"fc484444-80db-44d8-8652-38e4dff60878"}
{"level":"info","ts":"2024-08-20T03:10:38.257Z","logger":"controllers.RayService","msg":"Current cluster is unhealthy, prepare to restart.","RayService":{"name":"stable-diffusion-tpu","namespace":"default"},"reconcileID":"fc484444-80db-44d8-8652-38e4dff60878","Status":{"activeServiceStatus":{"applicationStatuses":{"stable_diffusion":{"status":"RUNNING","healthLastUpdateTime":"2024-08-20T03:10:08Z","serveDeploymentStatuses":{"APIIngress":{"status":"HEALTHY","healthLastUpdateTime":"2024-08-20T03:10:08Z"},"StableDiffusion":{"status":"HEALTHY","healthLastUpdateTime":"2024-08-20T03:10:08Z"}}}},"rayClusterName":"stable-diffusion-tpu-raycluster-lwbv5","rayClusterStatus":{"state":"ready","availableWorkerReplicas":1,"desiredWorkerReplicas":1,"minWorkerReplicas":1,"maxWorkerReplicas":10,"desiredCPU":"102","desiredMemory":"208G","desiredGPU":"0","desiredTPU":"4","lastUpdateTime":"2024-08-20T02:50:45Z","endpoints":{"client":"10001","dashboard":"8265","gcs":"6379","metrics":"8080","serve":"8000"},"head":{"podIP":"10.238.129.67","serviceIP":"10.238.129.67"},"observedGeneration":1}},"pendingServiceStatus":{"rayClusterStatus":{"desiredCPU":"0","desiredMemory":"0","desiredGPU":"0","desiredTPU":"0","head":{}}},"serviceStatus":"FailedToUpdateService","numServeEndpoints":2,"observedGeneration":1,"lastUpdateTime":"2024-08-20T02:35:15Z"}}
...
{"level":"error","ts":"2024-08-20T03:10:38.359Z","logger":"controllers.RayService","msg":"Fail to reconcileServe.","RayService":{"name":"stable-diffusion-tpu","namespace":"default"},"reconcileID":"9141c8e2-0804-49f5-b1d1-ff5532cf6539","error":"Found 0 head pods for RayCluster stable-diffusion-tpu-raycluster-7rxg6 in the namespace default","stacktrace":"github.com/ray-project/kuberay/ray-operator/controllers/ray.(*RayServiceReconciler).Reconcile\n\t/home/runner/work/kuberay/kuberay/ray-operator/controllers/ray/rayservice_controller.go:163\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"}
{"level":"info","ts":"2024-08-20T03:10:38.360Z","logger":"controllers.RayService","msg":"Reconciling the Serve component. Active and pending Ray clusters exist.","RayService":{"name":"stable-diffusion-tpu","namespace":"default"},"reconcileID":"2874b819-f616-4ab7-a288-d4667f35b6cf"}
{"level":"info","ts":"2024-08-20T03:10:38.360Z","logger":"controllers.RayService","msg":"FetchHeadServiceURL","RayService":{"name":"stable-diffusion-tpu","namespace":"default"},"reconcileID":"2874b819-f616-4ab7-a288-d4667f35b6cf","head service name":"stable-diffusion-tpu-raycluster-lwbv5-head-svc","namespace":"default"}
{"level":"info","ts":"2024-08-20T03:10:38.360Z","logger":"controllers.RayService","msg":"FetchHeadServiceURL","RayService":{"name":"stable-diffusion-tpu","namespace":"default"},"reconcileID":"2874b819-f616-4ab7-a288-d4667f35b6cf","head service URL":"stable-diffusion-tpu-raycluster-lwbv5-head-svc.default.svc.cluster.local:8265","port":"dashboard"}
```

### Reproduction script

Steps to reproduce:
1. Install a previous version of KubeRay
```
helm repo add kuberay https://ray-project.github.io/kuberay-helm/
helm repo update
helm install kuberay-operator kuberay/kuberay-operator --version 1.1.1
```
2. Create a RayService
```
kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes-engine-samples/main/ai-ml/gke-ray/rayserve/stable-diffusion/ray-service.yaml
```

3. Verify the RayService deploys successfully
```
kubectl get rayservices

# verify RayService is running
```

4. Install a newer version of the KubeRay operator
```
helm uninstall kuberay-operator
helm install kuberay-operator kuberay/kuberay-operator --version 1.2.0-rc.0
```
5. The RayService restarts and creates a new Ray head Pod and worker Pods
```
kubectl get rayservices
# RayService status is `restarting` and RayCluster is recreated
```

### Anything else

This occurs every time when upgrading the ray-operator image version to `v1.2.0-rc.0`, but not when installing a KubeRay operator with the same or lower version as the currently installed version

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by ryanaoleary**
## Why are these changes needed?

This PR adds a new `ray.io/kuberay-version` annotation to RayClusters created with KubeRay. This annotation is used to check for a KubeRay version change, which can cause a RayService to restart and create a new RayCluster erroneously due to a hash mismatch. If the KubeRay version annotation differs when checking `shouldPrepareNewRayCluster` and the RayCluster hashes do not match, the controller updates the `utils.HashWithoutReplicasAndWorkersToDeleteKey` annotation, KubeRay version annotation, and returns `DoNothing` to avoid restarting the RayService on version change. This unblocks the version upgrade to KubeRay `v1.2.0`.

This PR was tested by following the reproduction script in the linked issue and verifying that `Active RayCluster config doesn't match goal config. RayService operator should prepare a new Ray cluster` does not occur.

## Related issue number

Closes #2315

## Checks

- [x] I've made sure the tests are passing.
- Testing Strategy
   - [x] Unit tests
   - [x] Manual tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ryanaoleary** [comment]
cc: @andrewsykim

**Comment by ryanaoleary** [comment]
@kevin85421 is the desired behavior here to immediately start a zero-downtime upgrade (`r.markRestartAndAddPendingClusterName(ctx, rayServiceInstance`)) if the `KUBERAY_VERSION` changes? Or should we just add the updated annotations on a version change but return `DoNothing`, and leave the RayCluster as-is rather than restarting it?

**Comment by kevin85421** [comment]
> is the desired behavior here to immediately start a zero-downtime upgrade (r.markRestartAndAddPendingClusterName(ctx, rayServiceInstance)) if the KUBERAY_VERSION changes?

No, if the RayService CR's `KUBERAY_VERSION` annotation (e.g., 1.2.0) is different from (or doesn't exist) the KubeRay operator's `KUBERAY_VERSION` (e.g., 1.3.0), then we should not perform a zero downtime upgrade until:

* The `ray.io/hash-without-replicas-and-workers-to-delete` annotation is updated.
* The `KUBERAY_VERSION` annotation is updated.

After these updates, we can use the new `ray.io/hash-without-replicas-and-workers-to-delete` annotation to determine whether to trigger a zero downtime upgrade.

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 1]
```diff
@@ -576,7 +576,16 @@ func (r *RayServiceReconciler) shouldPrepareNewRayCluster(ctx context.Context, r
 			}
 		}
 
-		// Case 3: Otherwise, rollout a new cluster.
+		// Case 3: If the KubeRay version has changed and the hashes are not identical, update the RayCluster with the goalClusterHash
+		// and new KubeRay version, but do not restart the RayCluster.
+		activeKubeRayVersion := activeRayCluster.ObjectMeta.Annotations[utils.KubeRayVersion]
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller.go:581]: How about moving this check to the place between "if activeRayCluster == nil" and "Case 1"?

```go
		if activeRayCluster == nil {
			logger.Info("No active Ray cluster. RayService operator should prepare a new Ray cluster.")
			return RolloutNew
		}
                // Move the check here <--------

		// Case 1: If everything is identical except for the Replicas and WorkersToDelete of
		// each WorkerGroup, then do nothing.
```

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 2]
```diff
@@ -576,7 +576,16 @@ func (r *RayServiceReconciler) shouldPrepareNewRayCluster(ctx context.Context, r
...
+		if activeKubeRayVersion != utils.KUBERAY_VERSION {
+			activeRayCluster.ObjectMeta.Annotations[utils.HashWithoutReplicasAndWorkersToDeleteKey] = goalClusterHash
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller.go:583]: I prefer not to update the input argument (`activeRayCluster`) inside this function. How about removing the logic for updating annotations here and directly `return Update` instead?

Comment (ryanaoleary) [reply ray-operator/controllers/ray/rayservice_controller.go]: Done in [5b5fe07](https://github.com/ray-project/kuberay/pull/2320/commits/5b5fe078a11a24eabdccd74094020f60ee4510a8), we now just log and call `Update` and the cluster hash and KubeRay version are updated in `constructRayClusterForRayService`.

File: ray-operator/controllers/ray/rayservice_controller.go (hunk 1 above)
Comment (ryanaoleary) [reply ray-operator/controllers/ray/rayservice_controller.go]: Done in 5b5fe07

**Comment by kevin85421** [comment]
Thanks! I will manually test it.

File: ray-operator/controllers/ray/rayservice_controller.go [hunk 3]
```diff
@@ -531,7 +531,15 @@ func (r *RayServiceReconciler) shouldPrepareNewRayCluster(ctx context.Context, r
 			return RolloutNew
 		}
 
-		// Case 1: If everything is identical except for the Replicas and WorkersToDelete of
+		// Case 1: If the KubeRay version has changed and the hashes are not identical, update the RayCluster to get
```
Comment (andrewsykim) [inline ray-operator/controllers/ray/rayservice_controller.go:534]: This comment implies the hash needs to be checked, but we return  `Update` before checking the hash, is that expected?

Comment (ryanaoleary) [reply ray-operator/controllers/ray/rayservice_controller.go:534]: Oh I forgot to change the comment here (this check used to be after we checked that the hashes are different). Whether or not the hash is different, I think we want to just return `Update` on this iteration to get the correct KubeRay version and hash (if it has actually changed).

**Review by kevin85421 — COMMENTED** [review]
Would you mind adding a unit test in `rayservice_controller_unit_test.go`? Maybe in `TestReconcileRayCluster`, or you can add a new test if needed.

**Comment by ryanaoleary** [comment]
> Would you mind adding a unit test in `rayservice_controller_unit_test.go`? Maybe in `TestReconcileRayCluster`, or you can add a new test if needed.

Added a unit test case in f9c61e7

File: ray-operator/controllers/ray/rayservice_controller_unit_test.go [hunk 4]
```diff
@@ -779,6 +782,15 @@ func TestReconcileRayCluster(t *testing.T) {
 			enableZeroDowntime:      false,
 			shouldPrepareNewCluster: true,
 		},
+		// Test 6: If active KubeRay version doesn't match the KubeRay version annotation on the RayCluster, update the RayCluster.
+		"Active RayCluster exists. KubeRay version is mismatched. Update the RayCluster.": {
+			activeCluster:           activeCluster.DeepCopy(),
+			updateRayClusterSpec:    true,
+			enableZeroDowntime:      false,
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller_unit_test.go:789]: How about testing it with `enableZeroDowntime: true`? Zero downtime upgrade is enabled by default, so setting it to true is more close to the real situation.

File: ray-operator/controllers/ray/rayservice_controller_unit_test.go [hunk 5]
```diff
@@ -790,11 +802,16 @@ func TestReconcileRayCluster(t *testing.T) {
...
+				// Update 'ray.io/kuberay-version' to a new version if kubeRayVersion is set.
+				if tc.updateKubeRayVersion {
+					tc.activeCluster.Annotations[utils.KubeRayVersion] = tc.kubeRayVersion
+				}
 				runtimeObjects = append(runtimeObjects, tc.activeCluster.DeepCopy())
 			}
 			fakeClient := clientFake.NewClientBuilder().WithScheme(newScheme).WithRuntimeObjects(runtimeObjects...).Build()
 			r := RayServiceReconciler{
 				Client: fakeClient,
+				Scheme: newScheme,
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller_unit_test.go:814]: why do we need this?

File: ray-operator/controllers/ray/rayservice_controller_unit_test.go [hunk 6]
```diff
@@ -779,6 +782,15 @@ func TestReconcileRayCluster(t *testing.T) {
 			enableZeroDowntime:      false,
 			shouldPrepareNewCluster: true,
 		},
+		// Test 6: If active KubeRay version doesn't match the KubeRay version annotation on the RayCluster, update the RayCluster.
```
Comment (kevin85421) [inline ray-operator/controllers/ray/rayservice_controller_unit_test.go:785]: Add more comments. For example,

// Test 6: If the active KubeRay version doesn't match the KubeRay version annotation on the RayCluster, update the RayCluster's hash and KubeRay version annotations first before checking whether to trigger a zero downtime upgrade. This behavior occurs because when we upgrade the KubeRay CRD, the hash generated by different KubeRay versions may differ, which can accidentally trigger a zero downtime upgrade.

**Review by kevin85421 — COMMENTED** [review]
Others look good to me! I will manually test it after the comments are addressed.

File: ray-operator/controllers/ray/rayservice_controller_unit_test.go (hunk 5 above)
Comment (ryanaoleary) [reply ray-operator/controllers/ray/rayservice_controller_unit_test.go:814]: Without setting the Scheme the test returns a nil pointer error when creating a new RayCluster in `constructRayClusterForRayService` which gets called when updating the RayCluster.

File: ray-operator/controllers/ray/rayservice_controller_unit_test.go (hunk 6 above)
Comment (ryanaoleary) [reply ray-operator/controllers/ray/rayservice_controller_unit_test.go]: That test case description looks good to me, I added it in [3142ece](https://github.com/ray-project/kuberay/pull/2320/commits/3142eced7e35e4b5ca18b3f3c7aef586796b7b52).

File: ray-operator/controllers/ray/rayservice_controller_unit_test.go (hunk 4 above)
Comment (ryanaoleary) [reply ray-operator/controllers/ray/rayservice_controller_unit_test.go]: Done in [3142ece](https://github.com/ray-project/kuberay/pull/2320/commits/3142eced7e35e4b5ca18b3f3c7aef586796b7b52)

**Comment by MortalHappiness** [comment]
LGTM

**Comment by rueian** [comment]
LGTM

**Review by kevin85421 — APPROVED** [review]
I manually test this PR by following this issue: https://github.com/ray-project/kuberay/issues/2315#issue-2474707446.

* Zero downtime upgrade will not be triggered accidentally after upgrading.
* The annotation `ray.io/kuberay-version` is added to the RayCluster CR correctly.
* Then, I updated `rayVersion` from `2.34.0` to `2.100.0` to trigger zero downtime upgrade. It is triggered as expected.
